'use client';
import {useEffect,useMemo,useState} from 'react';
import {ArrowLeft,ArrowRight,BookOpen,Check,Download,ExternalLink,FileSearch,HelpCircle,MapPin,Milk,Newspaper,GlassWater,Anvil,Apple,Monitor,Trash2,Armchair,Recycle,Search,Share2} from 'lucide-react';
import {Button} from '@/components/ui/button';
import {Tabs,TabsList,TabsTrigger,TabsContent} from '@/components/ui/tabs';
import {Select,SelectContent,SelectItem,SelectTrigger,SelectValue} from '@/components/ui/select';
import {Dialog,DialogContent,DialogDescription,DialogTitle} from '@/components/ui/dialog';
import {Accordion,AccordionContent,AccordionItem,AccordionTrigger} from '@/components/ui/accordion';
import {Input} from '@/components/ui/input';
import {Checkbox} from '@/components/ui/checkbox';
import {journeyData} from '@/packages/overshoot-data/release7/dataset';
import {evidenceAtStage,initialJourney,journeyQuery,readJourney,stages,visibleEvidence,type JourneyEvidence,type JourneyPlace,type JourneySource,type JourneyState} from '@/packages/overshoot-data/release7/types';
import {evidenceCSV,exportHref} from '@/packages/overshoot-data/release7/export';
import './journey.css';
const datasetDownloadHref=exportHref(JSON.stringify(journeyData,null,2),'application/json');
const placeNames:Record<JourneyPlace,string>={general:'How processes work',bc:'British Columbia', 'salt-spring':'Salt Spring Island'};
const materialIcons={plastic:Milk,paper:Newspaper,glass:GlassWater,metal:Anvil,food:Apple,electronics:Monitor,garbage:Trash2,'rigid-plastic':Armchair};
export default function WasteJourney({offline=false,initialState=initialJourney}:{offline?:boolean;initialState?:JourneyState}){
 const [state,setState]=useState<JourneyState>(initialState),[mounted,setMounted]=useState(false),[sourceIds,setSourceIds]=useState<string[]|null>(null),[record,setRecord]=useState<JourneyEvidence|null>(null),[share,setShare]=useState<string|null>(null),[copied,setCopied]=useState(false);
 useEffect(()=>{const restore=()=>setState(readJourney(offline?location.hash.slice(1):location.search));restore();setMounted(true);addEventListener('popstate',restore);return()=>removeEventListener('popstate',restore)},[offline]);
 useEffect(()=>{if(mounted)history.replaceState(null,'',offline?`#${journeyQuery(state)}`:`${location.pathname}?${journeyQuery(state)}`)},[state,mounted,offline]);
 const update=(patch:Partial<JourneyState>)=>{setState(s=>({...s,...patch,query:patch.material||patch.place?'':patch.query??s.query}));setRecord(null);setSourceIds(null)};
 const material=journeyData.materials.find(m=>m.id===state.material)!,step=material.steps[state.stage],stepIndex=stages.findIndex(s=>s.id===state.stage);
 const evidence=useMemo(()=>visibleEvidence(journeyData,state),[state]);
 const currentEvidence=evidence.filter(e=>evidenceAtStage(e,state.stage)),filtered=evidence.filter(e=>`${e.title} ${e.entity} ${e.plain}`.toLowerCase().includes(state.query.toLowerCase()));
 const sources=(ids:string[])=>journeyData.sources.filter(s=>ids.includes(s.id));
 const inspect=(ids:string[],r:JourneyEvidence|null=null)=>{setSourceIds(ids);setRecord(r)};
 async function shareView(){if(offline){setShare(location.hash);return}try{await navigator.clipboard.writeText(location.href);setCopied(true);setTimeout(()=>setCopied(false),2000)}catch{setShare(location.href)}}
 return <main className="wj"><a className="wj-skip" href="#journey-result">Skip to the journey</a>{offline&&<aside className="wj-review">Working review · Not yet on the live site.</aside>}
 <header className="wj-header"><a className="wj-brand" href={offline?'https://overshoot.gaiaai.chatgpt.site':'/'}>OVERSHOOT<small>Gaia AI</small></a><nav aria-label="Primary"><a aria-current="page" href={offline?`#${journeyQuery({...state,view:'learn'})}`:'/journey'} onClick={e=>{e.preventDefault();update({view:'learn'})}}>Follow waste</a><a href={offline?'https://overshoot.gaiaai.chatgpt.site/flow?mode=explore':'/materials'}>Material flows <ExternalLink size={14}/></a></nav><Button variant="ghost" onClick={shareView} aria-label="Share this selection">{copied?<Check/>:<Share2/>}</Button></header>
 <section className="wj-intro"><p className="wj-kicker">Follow waste, one step at a time</p><h1>Where does it go<br className="wj-desktop-break"/> after the bin?</h1><p>Pick a material. Follow what changes, what comes out, and how far the evidence reaches.</p></section>
 <section className="wj-pickers" aria-label="Choose what to follow"><div className="wj-mobile-material"><label htmlFor="wj-mobile-material">Material to follow</label><Select value={state.material} onValueChange={v=>update({material:v as JourneyState['material'],stage:'collection'})}><SelectTrigger id="wj-mobile-material" aria-label="Material to follow" className="wj-select-trigger"><SelectValue/></SelectTrigger><SelectContent className="wj-select-options">{journeyData.materials.map(m=><SelectItem key={m.id} value={m.id}>{m.name}</SelectItem>)}</SelectContent></Select><small>{material.example}</small></div><div className="wj-materials" role="group" aria-label="Waste material">{journeyData.materials.map(m=>{const Icon=materialIcons[m.id];return <Button variant="ghost" key={m.id} aria-pressed={state.material===m.id} onClick={()=>update({material:m.id,stage:'collection'})}><Icon size={20} aria-hidden="true"/><span>{m.name}<small>{m.example}</small></span></Button>})}</div><div className="wj-place-row"><label><MapPin size={18}/><span>Place</span><Select value={state.place} onValueChange={v=>update({place:v as JourneyPlace})}><SelectTrigger aria-label="Place to investigate" className="wj-select-trigger"><SelectValue/></SelectTrigger><SelectContent className="wj-select-options">{Object.entries(placeNames).map(([id,name])=><SelectItem value={id} key={id}>{name}</SelectItem>)}</SelectContent></Select></label><label className="wj-detail-toggle"><Checkbox checked={state.detail} onCheckedChange={v=>update({detail:v===true})}/> Technical detail</label></div></section>
 <Tabs value={state.view} onValueChange={v=>update({view:v as JourneyState['view']})} className="wj-mode"><TabsList><TabsTrigger value="learn"><Recycle size={17}/> Follow the journey</TabsTrigger><TabsTrigger value="research"><FileSearch size={17}/> Research records</TabsTrigger></TabsList>
 <p className="wj-announcement" role="status">{material.name} · {placeNames[state.place]} · {stages[stepIndex].name}</p><TabsContent value={state.view}><div id="journey-result" className="wj-result" tabIndex={-1}>{state.view==='learn'?<>
 <div className="wj-summary"><strong>{material.name}</strong><p>{material.summary}</p></div>
 <nav className="wj-steps" aria-label="Journey stages">{stages.map((s,i)=><button key={s.id} onClick={()=>update({stage:s.id})} aria-current={state.stage===s.id?'step':undefined}><span>{String(i+1).padStart(2,'0')}</span><strong>{s.name}</strong><small>{state.place==='general'?'Process guide':evidence.some(e=>evidenceAtStage(e,s.id))?'Published evidence':'Local evidence gap'}</small></button>)}</nav>
 <div className="wj-stage-grid"><section className="wj-explanation" aria-labelledby="wj-step-title"><div className="wj-stage-label"><span>How it can work</span><span>Process explanation</span></div><p className="wj-question">{stages[stepIndex].question}</p><h2 id="wj-step-title">{step.title}</h2><p className="wj-plain">{state.detail?step.technical:step.plain}</p>{step.outputs&&<div className="wj-outputs">{step.outputs.map(o=><article key={o.name}><h3>{o.name}</h3><p>{o.explanation}</p></article>)}</div>}<p className="wj-boundary">This explains a process. It does not track your individual item.</p>{step.sources.length>0&&<Button variant="ghost" onClick={()=>inspect(step.sources)}><BookOpen size={17}/> Read the process source</Button>}</section>
 <section className="wj-local" aria-label="What is documented in this place"><div className="wj-stage-label"><span>{placeNames[state.place]}</span><span>{state.place==='general'?'No place selected':'Published local evidence'}</span></div>{state.place==='general'?<><h2>Want a real place?</h2><p>Select British Columbia or Salt Spring Island to see named programs and facilities, with gaps left visible.</p><Button onClick={()=>update({place:'bc'})}>Show British Columbia <ArrowRight size={18}/></Button></>:currentEvidence.length?<>{currentEvidence.map(r=><article className="wj-evidence-card" key={r.id}><span className="wj-evidence-label">{r.kind.replaceAll('-',' ')}{r.year?` · ${r.year}`:''}</span><h3>{r.title}</h3><p>{state.detail?r.technical:r.plain}</p>{r.quantity&&<button className="wj-quantity" onClick={()=>inspect(r.source_ids,r)}><strong>{r.quantity.value.toLocaleString()} {r.quantity.unit}</strong><span>{r.quantity.label}</span></button>}<DestinationTable record={r} onInspect={()=>inspect(r.source_ids,r)}/><p className="wj-entity"><MapPin size={15}/>{r.entity}</p><p className="wj-gap"><HelpCircle size={16}/><span>{state.detail?r.gap:r.plainGap??r.gap}</span></p><Button variant="ghost" onClick={()=>inspect(r.source_ids,r)}><BookOpen size={16}/> Inspect evidence</Button></article>)}</>:<div className="wj-gap-state"><HelpCircle size={34}/><h2>We cannot trace this step here yet.</h2><p>The acquired evidence does not identify this stage for {material.name.toLowerCase()} in {placeNames[state.place]}. That is a missing record, not proof that nothing happens.</p>{state.place==='salt-spring'&&<Button variant="outline" onClick={()=>update({place:'bc'})}>See BC evidence <ArrowRight size={18}/></Button>}<Button variant="ghost" onClick={()=>update({view:'research'})}>See what is documented</Button></div>}</section></div>
 <div className="wj-step-actions"><Button variant="outline" disabled={stepIndex===0} onClick={()=>update({stage:stages[stepIndex-1].id})}><ArrowLeft size={18}/> Previous</Button><span>{stepIndex+1} of {stages.length}</span><Button disabled={stepIndex===stages.length-1} onClick={()=>update({stage:stages[stepIndex+1].id})}>What happens next? <ArrowRight size={18}/></Button></div>
 <div className="wj-trace-note"><strong>A chain needs links.</strong><p>Two facilities appearing in a report does not prove a shipment moved between them. These stages organize the evidence; they are not an invented route from your bin.</p></div>
 </>:<section className="wj-research"><div className="wj-research-heading"><div><p className="wj-kicker">Evidence for this selection</p><h2>{material.name} · {placeNames[state.place]}</h2><p>Operator and program records. Quantities retain their own year, unit and scope.</p></div>{filtered.length?<a className="wj-download" href={exportHref(evidenceCSV(filtered,journeyData),'text/csv')} download={`overshoot-${state.place}-${state.material}-evidence.csv`}><Download size={17}/> Export CSV</a>:<Button variant="outline" disabled><Download size={17}/> Export CSV</Button>}</div><label className="wj-search"><Search size={18}/><Input aria-label="Search evidence records" placeholder="Find a facility, process or outcome…" value={state.query} onChange={e=>update({query:e.target.value.slice(0,200)})}/></label><p className="wj-meta" aria-live="polite">{filtered.length} matching records in this acquired selection.</p>{filtered.length?<div className="wj-table-wrap"><table><caption>Published evidence, including what it cannot establish</caption><thead><tr><th scope="col">Stage and record</th><th scope="col">Place / facility</th><th scope="col">What is reported</th><th scope="col">Access</th></tr></thead><tbody>{filtered.map(r=><tr key={r.id}><th scope="row"><span>{(r.supportedStages??[r.stage]).map(id=>stages.find(s=>s.id===id)?.name).join(' / ')}</span>{r.title}</th><td>{r.entity}<small>{r.year||'Web guidance; no observation year'}</small></td><td>{r.technical}<DestinationTable record={r} onInspect={()=>inspect(r.source_ids,r)}/><small>Gap: {r.gap}</small></td><td><Button variant="outline" onClick={()=>inspect(r.source_ids,r)}>Source & record</Button></td></tr>)}</tbody></table></div>:<div className="wj-gap-state"><h3>{state.query?'No records match this search.':'No local records for this selection.'}</h3><p>Choose another place or material. General process explanations remain available in the journey view.</p>{state.query&&<Button onClick={()=>update({query:''})}>Clear search</Button>}</div>}<div className="wj-research-access"><h3>Take the evidence with you</h3><p>The full review dataset includes source URLs, geographic scope, methods and unresolved links. A source in the list is not a claim of complete coverage.</p><a className="wj-download" href={datasetDownloadHref} download="overshoot-waste-journeys.json"><Download size={17}/> Download dataset + sources</a><Button variant="ghost" onClick={()=>inspect(journeyData.sources.map(s=>s.id))}><BookOpen size={17}/> Browse all sources</Button><a href="https://overshoot.gaiaai.chatgpt.site/data" target="_blank" rel="noreferrer">Open the atlas data room <ExternalLink size={15}/></a></div></section>}
 </div></TabsContent></Tabs>
 <section className="wj-understand"><h2>A few words that help</h2><Accordion type="single" collapsible>{[{id:'recycling',title:'Does “collected for recycling” mean recycled?',text:'No. Collection is an early step. A fuller account identifies sorting, the processor, useful outputs and rejected material.'},{id:'recovery',title:'Is making energy the same as recycling material?',text:'No. Energy recovery uses a material or gas as fuel. Material recycling returns matter to a material use.'},{id:'destination',title:'Why can’t you show exactly where my item went?',text:'Most public data describes a facility, program or country. Following your individual item needs connected shipment records that these sources often do not provide.'},{id:'precision',title:'How do I investigate a claim?',text:'Choose Research records or Inspect evidence. Check the geographic scope, year, method, unit and stated gap. Download the records to work with them independently.'}].map(x=><AccordionItem key={x.id} value={x.id}><AccordionTrigger>{x.title}</AccordionTrigger><AccordionContent>{x.text}</AccordionContent></AccordionItem>)}</Accordion></section>
 <footer className="wj-footer"><span>OVERSHOOT · Gaia AI</span><Button variant="ghost" onClick={()=>inspect(journeyData.sources.map(s=>s.id))}>Sources and coverage <BookOpen size={16}/></Button></footer>
 <Dialog open={sourceIds!==null} onOpenChange={v=>{if(!v){setSourceIds(null);setRecord(null)}}}><DialogContent className="wj-dialog"><DialogTitle>{record?'The record behind this claim':'Sources you can inspect'}</DialogTitle><DialogDescription>Read the scope and limitation before treating a source as an exact route.</DialogDescription>{record&&<section className="wj-record-inspection"><h3>{record.title}</h3><p>{record.technical}</p><dl><dt>Geography</dt><dd>{placeNames[record.place]} · {record.entity}</dd><dt>Evidence type</dt><dd>{record.kind.replaceAll('-',' ')}</dd><dt>What it does not establish</dt><dd>{record.gap}</dd></dl><details><summary>Original structured record</summary><pre>{JSON.stringify(record,null,2)}</pre></details></section>}{sources(sourceIds||[]).map(s=><SourceEntry key={s.id} source={s}/>)}</DialogContent></Dialog>
 <Dialog open={share!==null} onOpenChange={v=>{if(!v)setShare(null)}}><DialogContent className="wj-dialog"><DialogTitle>{offline?'Keep this selection':'Share this journey'}</DialogTitle><DialogDescription>{offline?'This selection is saved after # in the review file’s address. Share the HTML file and this selection together.':'This link preserves material, place, stage and reading mode.'}</DialogDescription><Input aria-label="Shareable selection" readOnly value={share||''} onFocus={e=>e.target.select()}/></DialogContent></Dialog>{copied&&<p className="wj-toast" role="status">Link copied</p>}
 </main>
}
function SourceEntry({source:s}:{source:JourneySource}){return <article className="wj-source"><p className="wj-kicker">{s.publisher}</p><h3>{s.title}</h3><dl><dt>Coverage</dt><dd>{s.coverage}</dd><dt>Method</dt><dd>{s.method}</dd><dt>Year</dt><dd>{s.year??'No annual observation year'}</dd><dt>Retrieved</dt><dd>{s.retrievedAt}</dd><dt>Reuse</dt><dd>{s.license}</dd></dl><a href={s.url} target="_blank" rel="noreferrer">Open primary source <ExternalLink size={16}/></a></article>}

function DestinationTable({record:r,onInspect}:{record:JourneyEvidence;onInspect:()=>void}){if(!r.destinations)return null;return <div className="wj-destinations"><table><caption>Share of reported end markets · %</caption><thead><tr><th scope="col">Destination</th><th scope="col">{r.comparisonYear}</th><th scope="col">{r.year}</th></tr></thead><tbody>{r.destinations.map(d=><tr key={d.label}><th scope="row">{d.label}<span className="wj-destination-bar" aria-hidden="true"><i style={{width:`${d.percent??0}%`}}/></span></th><td>{d.previousPercent===null?'—':d.previousPercent.toFixed(1)}</td><td>{d.percent===null?'—':d.percent.toFixed(1)}</td></tr>)}</tbody></table><small>— = source dash; not assumed zero. This describes geography, not the share of your bin recycled.</small><Button variant="ghost" onClick={onInspect}>Inspect end-market figures <BookOpen size={16}/></Button></div>}
