from pathlib import Path
import json
P=Path(__file__).resolve().parent
stats=json.loads((P/'validation.json').read_text());sources=[]
def source(id,title,publisher,dataset,edition,year,url,license,method,transform,geo,years,state='available',acquisition='acquired',download=[],notes=''):
 sources.append(dict(id=id,title=title,publisher=publisher,dataset=dataset,edition=edition,publicationYear=year,coverageYears=years,url=url,citation=f'{publisher} ({year or "n.d."}), {title}, {edition}. Retrieved 19 September 2026.',license=license,retrievedAt='2026-09-19',method=method,units='Metric tonnes for mass; percentages and tonnes/person where specified. Original values and units retained.',transformations=transform,geographicCoverage=geo,temporalCoverage=years,status=state,acquisitionStatus=acquisition,downloadUrls=download,notes=notes))
UNLICENSE='UN statistical-data terms; no explicit Creative Commons licence supplied by this API. Original agency and country attribution retained per observation. GEM report and photographs have separate, more restrictive terms.'
SDG='https://unstats.un.org/sdgapi/v1/sdg/Series/Data?seriesCode={}&pageSize=50000'
base='2026.Q2.G.02 API snapshot, 19 September 2026'
for id,title,dataset,series,method in [
 ('unsd-ewaste-2026','Electronic waste generated and recycled','SDG12.4.2 and12.5.1',['EN_EWT_GENV','EN_EWT_GENPCAP','EN_EWT_RCYV','EN_EWT_RCYR'],'UNITAR/WESR model estimates and national/Eurostat observations as identified on each row. UN SDG series is not the complete GEM country table. UNITAR values after2022 are labelled model projections; missing countries remain unavailable.'),
 ('unsd-municipal-2026','Municipal waste generation and recycling','SDG12.4.2 and12.5.1',['EN_MWT_GENV','EN_MWT_RCYR','EN_MWT_RCYV'],'National questionnaires and Eurostat/OECD figures compiled by UNSD/UNEP. National definitions and reporting years differ. Keep country footnotes and observation status. Never add these quantities to World Bank figures for the same waste stream.'),
 ('unsd-hazardous-2026','Hazardous waste generation and treatment','SDG12.4.2',['EN_HAZ_GENV','EN_HAZ_TREATV'],'National and Eurostat/UNSD observations. Treatment categories retain source taxonomy: incineration, incineration with energy recovery, landfill, recycling and other management. Imported/exported treatment can differ from domestic generation; no forced mass closure.'),
 ('unsd-food-waste-2026','Food Waste Index country and sector data','SDG12.3.1(b)',['AG_FOOD_WST','AG_FOOD_WST_PC'],'UNEP Food Waste Index2021/2024 estimates, alongside national observations. Household, retail, out-of-home and total sectors are distinct metrics. Confidence footnotes remain visible; national totals may be model estimates, not direct measurements. No addition across total and components.'),
 ('fao-food-loss-2026','Food loss percentages','SDG12.3.1(a)',['AG_FLS_PCT'],'FAO loss before retail, by food-product group. Global and regional estimates; no national numeric data in this acquired series. Food loss and retail/household food waste have different boundaries and denominators; never sum their percentages.')]:
 st=stats[id];yrs=f'{st["years"][0]}–{st["years"][1]}'
 source(id,title,'UN Statistics Division / '+('FAO' if id.startswith('fao') else 'UNEP / UNITAR / national statistical offices'),dataset,base,2026,'https://unstats.un.org/sdgs/dataportal',UNLICENSE,method,'Parse complete Series/Data JSON response; map UN M49 to ISO3; kilograms/person÷1000; tonnes and percentages unchanged. Exclude nonfinite missing observations, preserve footnotes/flags/dimensions. Keep regions in a separate artifact.',f'{st["countries"]} national/global entities in the published subset; see record-level geography.',yrs,download=[SDG.format(s) for s in series])
EURO='Eurostat reuse policy: attribution required, third-party exceptions apply. No separate licence is asserted for external-source components.'
EUAPI='https://ec.europa.eu/eurostat/api/dissemination/statistics/1.0/data/'
for id,title,code,query,method in [
 ('eurostat-circularity-2025','Circular material use rate','env_ac_cur','?lang=en','Share of circular material use in overall material use. Eurostat indicator denominator differs from the global Circularity Gap Report; do not rank both as if methodologically identical.'),
 ('eurostat-municipal-2026','Municipal waste by management operation','env_wasmun','?lang=en&unit=THS_T&sinceTimePeriod=2010','National municipal waste statistics. GEN and TRT totals overlap their child categories. DSP_I_RCV_E overlaps DSP_I and RCV_E; RCY overlaps RCY_M and RCY_C_D. Render source-selected categories without summing parents and children.'),
 ('eurostat-packaging-2026','Packaging waste by management operation','env_waspac','?lang=en&unit=T&sinceTimePeriod=2018','Packaging material and operation taxonomy preserved, including plastics, paper/cardboard, metals, wood and glass. W1501 total includes components. Recycling national/EU/nonEU destination categories overlap total recycling.'),
 ('eurostat-packaging-recycling-2026','Packaging recycling rates','cei_wm020','?lang=en','Source unit RT_TGT2025: rates under2025-and-onwards target methodology, by packaging type. Historical break flags and source precision preserved.')]:
 st=stats[id];ds=json.loads((P/'raw'/f'eurostat-{code}.json').read_text());yr=int(ds['updated'][:4]);yrs=f'{st["years"][0]}–{st["years"][1]}'
 source(id,title,'Eurostat',code,f'JSON-stat API snapshot; updated{ds["updated"]}',yr,f'https://ec.europa.eu/eurostat/databrowser/view/{code}/default/table',EURO,method,'Decode JSON-stat dimensions; preserve source flags. Thousand tonnes×1000 where applicable, tonnes and rates unchanged. EU/other aggregates stored separately from national data.',f'{st["countries"]} European countries',yrs,download=[EUAPI+code+query])
source('mat-stocks-2024','MAT_STOCKS: national material stocks and flows','Wiedenhofer et al. / BOKU University','MAT_STOCKS / MISO2 global database','v1.0, Zenodo12794253',2024,'https://doi.org/10.5281/zenodo.12794253','CC BY4.0 (dataset). Model software has a separate GPL licence.','Economy-wide dynamic, inflow-driven stock-flow model. Four end uses × four material groups. Values are model estimates; uncertainty is not supplied in this summarized CSV. Stock is accumulated mass, not annual extraction.','Kilotonnes×1000 to metric tonnes. Sum exactly16 disjoint end-use/material cells per country/process/year using compensated summation. Latest2016 totals in metrics; complete1900–2016 totals in stock-history; components retained separately.','177 countries','1900–2016',download=['https://zenodo.org/api/records/12794253/files/miso2_global_data_v1.csv/content','https://zenodo.org/api/records/12794253/files/MISO2_supp_data_v1.xlsx/content'])
source('mat-stocks-eu-2025','MAT_STOCKS detailed EU27 extract','Wiedenhofer et al. / BOKU University','MAT_STOCKS EU27','v1.0, Zenodo15090142',2025,'https://doi.org/10.5281/zenodo.15090142','CC BY4.0','Detailed stock, gross additions and end-of-life flows across12end uses and19materials. This is1990–2016, not the later EEA2022extension.','Raw CSV acquired. Retained for material-specific exploration; summarized global artifact already includes these27countries, so no duplicate import.','EU27','1990–2016',state='partial',download=['https://zenodo.org/api/records/15090142/files/MATSTOCKS_EU27_v1.csv/content'])
source('oecd-plastics-2022','Global Plastics Outlook: published global estimates','OECD','Global Plastics Outlook','Revised April2022',2022,'https://doi.org/10.1787/de747aef-en','OECD Terms and Conditions: data may be reused including commercially with attribution, subject to third-party restrictions.','ENV-Linkages model and plastics lifecycle estimates. Rounded values transcribed from the official executive summary/press release. Model mass/fate dataset is published separately under oecd-plastics-database-2022.','Million tonnes×1e6; published percentage shares unchanged. No deriving tonnes from rounded percentages.','Global','2000 and2019',state='partial',download=['https://www.oecd.org/content/dam/oecd/en/publications/reports/2022/02/global-plastics-outlook_a653d1c9/de747aef-en.pdf'])
source('oecd-plastics-database-2022','Global Plastics Outlook: use, fate, leakage and stocks','OECD','PLASTIC_WASTE_1, PLASTIC_USE_1, PLASTIC_LEAKAGE_2 andPLASTIC_LEAKAGE_3','OECD Compare Your Country embedded data snapshot',2022,'https://doi.org/10.1787/c0821f81-en','OECD Terms and Conditions, section3: attribution; permitted reuse including commercial, subject to third-party restrictions.','Historical model estimates,1990–2019. Five separate waste fates exactly sum to source total. Reported geographic model regions do not generally match countries: China includes Hong Kong. Only Canada, USA and India are mapped to national ISO3; WORLD is the native source global total. Regional model entities stay separate.','Parse publicly embedded backend JSON without executing code. Million tonnes×1e6. Preserve five source fate categories and exact native values. No post2019 scenario projections imported into factual metrics.','Global; Canada, USA, India;11regional aggregates retained separately','1990–2019',download=['https://www1.compareyourcountry.org/global-plastics-outlook/en/1/4825/datatable//IND1'])
source('unitar-gem-2024','Global E-waste Monitor2024','UNITAR / ITU','Global E-waste Monitor country/territory tableA2.4','Edition2, November2024',2024,'https://ewastemonitor.info/the-global-e-waste-monitor-2024/','CC BY-NC-SA3.0IGO, excluding third-party photographs/material. Commercial reuse may need permission.','Country/territory2022 generation and documented formal collection/recycling. The report mixes estimated generation and documented collection; missing collection is N/A, not zero.','PDF acquired for methodology/verification. Bulk country table not imported into browser due to its distinct reuse conditions; public SDG country observations used instead.','Global country/territory coverage','2022',state='partial',download=['https://ewastemonitor.info/wp-content/uploads/2024/12/GEM_2024_EN_11_NOV-web.pdf'])
# Additional primary databases deliberately registered with honest acquisition status.
source('fao-flw-database','Food Loss and Waste Database','FAO','Food Loss and Waste Database','Live2026portal',2026,'https://www.fao.org/platform-food-loss-waste/flw-data/en/','Underlying literature/databases retain their own rights; FAO warns against assuming endorsement or accuracy.','Commodity-, value-chain-stage- and study-specific observations. Source portal describes almost40,000data points from167countries and296commoditygroups. These studies are not interchangeable national annual totals.','Portal verified and snapshotted. Shiny download session not acquired; SDG food-loss country/global series acquired separately.','167countries described by source portal','Study-specific, many years',state='partial',acquisition='registered',notes='Requires study-level harmonization and confidence handling before display.')
source('eurostat-waste-generation','Waste generation by economic activity','Eurostat','env_wasgen','Live database',None,'https://ec.europa.eu/eurostat/databrowser/view/env_wasgen/default/table',EURO,'Biennial waste generation by NACEactivity, waste category and hazardous status. Includes mineral/construction waste beyond municipal scope.','Adapter pattern implemented by JSON-stat normalizer. Fullactivity/wastetype cube not acquired in this iteration.','Europe','Biennial series; coverage varies',state='partial',acquisition='registered')
source('eurostat-waste-treatment','Treatment of waste by treatment operation','Eurostat','env_wastrt','Live database',None,'https://ec.europa.eu/eurostat/databrowser/view/env_wastrt/default/table',EURO,'Waste treatment by category, hazardousness and operation, including recovery/backfilling/disposal. Geography describes treatment, not origin of waste.','Registered; must keep treatment and generation boundaries separate.','Europe','Biennial series; coverage varies',state='partial',acquisition='registered')
source('eurostat-weee','Waste electrical and electronic equipment','Eurostat','env_waseleeos','Open-scope WEEE reporting',None,'https://ec.europa.eu/eurostat/databrowser/view/env_waseleeos/default/table',EURO,'Placed-on-market, collected, recovered and recycled electrical/electronic equipment by category. Scope changes from previous10categoryseries must be handled explicitly.','Registered; SDG electronicwaste quantities already incorporate some Eurostat observations. Do not duplicate them in totals.','Europe','Open-scope seriesfrom2018',state='partial',acquisition='registered')
source('oecd-regional-plastics-2025','Regional Plastics Outlook for Southeast and East Asia','OECD','Regional Plastics Outlook','2025edition',2025,'https://www.oecd.org/en/topics/sub-issues/plastics.html','OECD publication-specific terms; most postJuly2024 written contentCCBY4.0; verify dataset third-party rights.','Regionalplastics model with historical estimates and future policy scenarios. Should complement global2019baseline, not silently replace with projected2030/2050values.','Publication existence verified on officialOECDpublicationlisting; tables not acquired.','SoutheastandEastAsia','Historicalbaselineandscenarios',state='partial',acquisition='registered')
source('eea-material-stocks-2026','Material stocks in a circular economy','European Environment Agency','Material stocks in Europe','2026report',2026,'https://www.eea.europa.eu/en/analysis/publications/material-stocks-in-a-circular-economy','EEAreuse policy; underlyingBOKUMAT_STOCKSdataCCBY4.0, figure-specificterms apply.','EEA2022stock estimates build onWiedenhoferet al.2024/2025. Different editionfrom downloadedMAT_STOCKSglobal2016.','Report verified. Updated2022countryvalues not automatically acquired; do not label2016CSVas2022.','EU27','2022',state='partial',acquisition='registered')
(P/'sources.json').write_text(json.dumps(sources,indent=2))
print(len(sources),'sources')
