'use client';
import {useMemo,useState,useRef,useEffect,useId} from 'react';
import {useOnChange} from '../useOnChange';
import {geoEqualEarth,geoMercator,geoAlbersUsa,geoPath,geoGraticule10,geoOrthographic,geoDistance} from 'd3-geo';
import type {FeatureCollection} from 'geojson';
import {Minus,Plus,RotateCcw,Globe2,Map as MapIcon} from 'lucide-react';
import {Checkbox} from '@/components/ui/checkbox';
import {useMaterialArtifact} from '../material-data';
import type {Country,Flow,SiteFeature} from './model';
import {compact,number} from './model';
import RasterTiles from './RasterTiles';
import {flowEndpoints,flowLabel,connectionBounds} from './connectionGeometry';
import {shippingTiles} from '@/packages/material-world/maritime';
import type {EnvironmentLayer} from '@/packages/material-world/environment';
export type CountryLayer={values:Map<string,number>;label:string;unit:string;year:string;thresholds:number[];loading?:boolean};
const scaleColors=[0,1,2,3,4].map(i=>`var(--map-ramp-${i})`);

export default function AtlasMap({flows,sites,countries,place,selected,onFlow,onSite,onPlace,color,siteView,countryLayer,raster,shippingDensity}:{shippingDensity?:boolean;raster?:EnvironmentLayer;countryLayer?:CountryLayer;flows:Flow[];sites:SiteFeature[];countries:Country[];place:string;selected:string;onFlow:(f:Flow)=>void;onSite:(s:SiteFeature)=>void;onPlace:(p:string)=>void;color:string;siteView:boolean}){
 const geography=useMaterialArtifact<FeatureCollection>('/data/v10/geography.json');
 const mapId=useId().replaceAll(':',''),clipId='map-clip-'+mapId,arrowId='map-arrow-'+mapId;
 const [rasterError,setRasterError]=useState(false);
 const [globe,setGlobe]=useState(false),[rotation,setRotation]=useState<[number,number]>([-15,-12]);
 const [proportional,setProportional]=useState(false);
 const [zoom,setZoom]=useState(1),[pan,setPan]=useState({x:0,y:0}),[hover,setHover]=useState('');
 const drag=useRef<{x:number;y:number;px:number;py:number;move:boolean;rotation:[number,number]}|null>(null);
 const dragFrame=useRef(0),pendingPointer=useRef({x:0,y:0,scale:1});
 useEffect(()=>()=>cancelAnimationFrame(dragFrame.current),[]);
 const [world,setWorld]=useState(false);
 useOnChange([place,siteView],()=>{setZoom(1);setPan({x:0,y:0});setWorld(false)});
 useOnChange([sites[0]?.properties.type],()=>setProportional(false));
 useOnChange([raster?.id,raster?.date,shippingDensity],()=>{if(raster||shippingDensity)setGlobe(false);setRasterError(false)});
 useOnChange([countryLayer?.values,flows,sites,place],()=>setHover(''));
 const local=place==='SSI'||place==='BC';
 const regional=!globe&&siteView&&place!=='WORLD'&&!local&&!world;
 const target=geography.data?.features.find(f=>String(f.properties?.numeric)===countries.find(c=>c.id===place)?.numeric);
 const linkBounds=connectionBounds(flows),linkKey=flows.filter(f=>f.connection).map(f=>f.id).join('|');
 useOnChange([linkKey],()=>{setZoom(1);setPan({x:0,y:0})});
 const projection=useMemo(()=>linkBounds&&!globe&&!world?geoMercator().fitExtent([[90,65],[910,435]],{type:'MultiPoint',coordinates:linkBounds}):raster||shippingDensity?(regional&&target?geoMercator().fitExtent([[70,50],[930,440]],target):geoMercator().scale(1000/(2*Math.PI)).translate([500,250])):globe?geoOrthographic().rotate(rotation).translate([500,250]).scale(224).clipAngle(90):regional&&target?(place==='USA'?geoAlbersUsa():geoMercator()).fitExtent([[70,50],[930,440]],target):geoEqualEarth().rotate([local?-145:0,0]).fitExtent([[24,24],[976,470]],{type:'Sphere'}),[regional,target,local,place,globe,rotation,raster?.id,shippingDensity,linkKey,world]);
 useOnChange([selected,linkKey],()=>{if(!selected||!siteView)return;const link=flows.find(f=>f.id===selected)?.connection;if(link&&!globe){const a=projection(link.from),b=projection(link.to);if(a&&b){const z=Math.min(64,Math.max(1,Math.min(800/Math.max(1,Math.abs(a[0]-b[0])),360/Math.max(1,Math.abs(a[1]-b[1])))));setZoom(z);setPan({x:(500-(a[0]+b[0])/2)*z,y:(250-(a[1]+b[1])/2)*z})}return}const s=sites.find(s=>s.properties.id===selected);if(!s)return;const p=projection(s.geometry.coordinates);if(p){const z=4;setZoom(z);setPan({x:(500-p[0])*z,y:(250-p[1])*z})}});
 const path=geoPath(projection);
 const coords=useMemo(()=>new Map(countries.filter(c=>c.center).map(c=>[c.id,c.center!])),[countries]);
 const countryIds=useMemo(()=>new Map(countries.map(c=>[c.numeric,c.id])),[countries]);
 const countryNames=useMemo(()=>new Map(countries.map(c=>[c.id,c.name])),[countries]);
 const located=flows.flatMap(f=>{const points=flowEndpoints(f,coords);return points?[{f,...points}]:[]});
 const comparableRoutes=located.length>0&&new Set(located.map(({f})=>[f.unit,f.basis,f.year,f.connection?'documented connection':'country report'].join('|'))).size===1;
 const drawn=(comparableRoutes?[...located].sort((a,b)=>b.f.amount-a.f.amount):located).slice(0,60);const selectedRoute=located.find(x=>x.f.id===selected);if(selectedRoute&&!drawn.includes(selectedRoute))drawn.splice(59,1,selectedRoute);
 const max=Math.max(1,...drawn.map(x=>x.f.amount));
 const comparableFlows=drawn.length>0&&new Set(drawn.map(({f})=>[f.unit,f.connection?'documented connection':'country report'].join('|'))).size===1;
 const positioned=useMemo(()=>sites.flatMap(s=>{const p=projection(s.geometry.coordinates);return p&&p.every(Number.isFinite)?[{s,p}]:[]}),[sites,projection]);
 // Aggregate all visible records in screen space; no largest-N truncation.
 const pins=useMemo(()=>{const groups=new Map<string,{s:SiteFeature;p:number[];count:number}>();for(const {s,p} of positioned){if(globe&&geoDistance(s.geometry.coordinates,[-rotation[0],-rotation[1]])>=Math.PI/2)continue;const x=500+pan.x+(p[0]-500)*zoom,y=250+pan.y+(p[1]-250)*zoom;if(x<0||x>1000||y<0||y>500)continue;const key=s.properties.id===selected?'selected':Math.floor(p[0]*zoom/25)+':'+Math.floor(p[1]*zoom/25);const g=groups.get(key);if(g){g.p=[(g.p[0]*g.count+p[0])/(g.count+1),(g.p[1]*g.count+p[1])/(g.count+1)];g.count++}else groups.set(key,{s,p:[...p],count:1})}return [...groups.values()]},[positioned,zoom,pan,globe,rotation,selected]);
 const siteMax=Math.max(1,...pins.map(({s})=>s.properties.value??0));
 const missingLocations=siteView?sites.length-positioned.length:flows.filter(f=>f.amount>0).length-located.length;
 const contextual=sites.some(s=>s.properties.stage||s.properties.transport),portCount=sites.filter(s=>s.properties.transport).length;
 const comparable=useMemo(()=>sites.some(s=>s.properties.value!==null)&&new Set(sites.map(s=>[s.properties.basis,s.properties.metric,s.properties.unit].join('|'))).size===1,[sites]);
 const radius=(s:SiteFeature)=>typeof s.properties.mapRadius==='number'?s.properties.mapRadius:proportional&&comparable&&s.properties.value!=null?Math.max(2,12*Math.sqrt(Math.max(0,s.properties.value)/siteMax)):3.5;
 const countryShapes=useMemo(()=>(regional&&place==='USA'&&target?[target]:geography.data?.features||[]).map(f=>({f,d:path(f)||''})),[geography.data,projection,regional,place,target]);
 const routes=useMemo(()=>new Set(flows.flatMap(f=>[f.origin,f.destination])),[flows]);
 const labels=(selected?drawn.filter(x=>x.f.id===selected):drawn.slice(0,4)).flatMap(({f,a,b})=>[{id:f.connection?a.join(','):f.origin,name:f.originLabel,p:a},{id:f.connection?b.join(','):f.destination,name:f.destinationLabel,p:b}]).filter((p,i,a)=>a.findIndex(q=>q.id===p.id)===i);
 return <section className="mw-map oa-atlas-map" aria-label={countryLayer?countryLayer.label+' map':siteView?'Extraction and disposal sites':'Material connections map'}>
  <div className="oa-map-controls"><div className="oa-map-projection" role="group" aria-label="Map projection"><button aria-pressed={!globe} onClick={()=>{setGlobe(false);setZoom(1);setPan({x:0,y:0})}}><MapIcon size={15}/>Flat</button><button disabled={!!raster||shippingDensity} title={raster||shippingDensity?'Raster context uses the flat map on this device':undefined} aria-pressed={globe} onClick={()=>{setGlobe(true);setZoom(1);setPan({x:0,y:0})}}><Globe2 size={15}/>Globe</button></div><span className="oa-small">{flows.some(f=>f.connection)?'Dashed links are schematic · select one for evidence':globe?'Drag to rotate the earth':siteView?'Select a point for its record':countryLayer?'Select a country for its figures':'Select a country or connection'}</span></div>
  {geography.error?<p role="alert">The map could not load. All records are available below.</p>:null}
  <a className="mw-map-skip" href={'#map-end-'+mapId}>Skip map controls</a>
  <svg viewBox={globe?'220 0 560 500':'0 0 1000 500'} role="group" aria-label="Interactive geographic map"
   onPointerDown={e=>{drag.current={x:e.clientX,y:e.clientY,px:pan.x,py:pan.y,move:false,rotation}}}
   onPointerMove={e=>{if(!drag.current)return;const d=drag.current;if(Math.abs(e.clientX-d.x)+Math.abs(e.clientY-d.y)>4)d.move=true;if(!d.move)return;pendingPointer.current={x:e.clientX,y:e.clientY,scale:1000/e.currentTarget.getBoundingClientRect().width};if(dragFrame.current)return;dragFrame.current=requestAnimationFrame(()=>{dragFrame.current=0;const d=drag.current;if(!d)return;const {x,y,scale:k}=pendingPointer.current;if(globe)setRotation([d.rotation[0]+(x-d.x)*k/4,Math.max(-80,Math.min(80,d.rotation[1]-(y-d.y)*k/4))]);else setPan({x:d.px+(x-d.x)*k,y:d.py+(y-d.y)*k})})}}
   onPointerUp={()=>{setTimeout(()=>{drag.current=null},0)}} onPointerCancel={()=>{drag.current=null}} onPointerLeave={()=>{drag.current=null}}>
   <defs><clipPath id={clipId}><rect width="1000" height="500" rx="8"/></clipPath><marker id={arrowId} viewBox="0 0 10 10" refX="8" refY="5" markerWidth="4" markerHeight="4" orient="auto-start-reverse"><path d="M 0 0 L 10 5 L 0 10 z" fill={color}/></marker></defs>
   <g clipPath={'url(#'+clipId+')'}><g transform={`translate(${500+pan.x} ${250+pan.y}) scale(${zoom}) translate(-500 -250)`}>
    {!regional&&<path d={path({type:'Sphere'})||''} fill="var(--map-water)" stroke="var(--map-line)"/>}
    {!regional&&<path d={path(geoGraticule10())||''} fill="none" stroke="var(--map-graticule)" strokeWidth={.45/zoom} pointerEvents="none"/>}
    {raster&&<RasterTiles layer={raster} projection={projection} zoom={zoom} pan={pan} onError={()=>setRasterError(true)}/>}
    {countryShapes.map(({f,d},i)=>{const id=countryIds.get(String(f.properties?.numeric)),value=id?countryLayer?.values.get(id):undefined;const name=(id?countryNames.get(id):undefined)||f.properties?.name;const label=countryLayer?name+' · '+(value===undefined?(countryLayer.loading?'Loading observation':'No observation'):number(value,1)+' '+countryLayer.unit):name;const fill=countryLayer?(value===undefined?'var(--map-no-data)':scaleColors[countryLayer.thresholds.filter(t=>value>=t).length]):id===place?'var(--map-place)':id&&routes.has(id)?'var(--map-route)':'var(--map-land)';return <path key={i} d={d} fill={fill} fillOpacity={raster&&!rasterError?(countryLayer?.65:.07):1} stroke={id===place?'var(--map-selected)':'var(--map-line)'} strokeWidth={(id===place?1.8:.65)/zoom} role={id?'button':undefined} tabIndex={id&&(countryLayer||id===place||routes.has(id))?0:-1} aria-label={'Open '+label} onKeyDown={e=>{if((e.key==='Enter'||e.key===' ')&&id){e.preventDefault();onPlace(id)}}} onClick={()=>{if(!drag.current?.move&&id)onPlace(id)}} onMouseEnter={()=>setHover(label)} onMouseLeave={()=>setHover('')} className="mw-country"><title>{label}</title></path>})}
    {shippingDensity&&<g opacity={regional ? 0.4 : 0.7}><RasterTiles urlTemplate={shippingTiles} maxZoom={4} projection={projection} zoom={zoom} pan={pan} onError={()=>{}}/></g>}
    {drawn.map(({f,a,b})=><g key={f.id} className="mw-route" role="button" tabIndex={0} aria-label={flowLabel(f,compact)} onKeyDown={e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();onFlow(f)}}} onClick={()=>{if(!drag.current?.move)onFlow(f)}} onMouseEnter={()=>setHover(flowLabel(f,compact))} onMouseLeave={()=>setHover('')}><path d={path({type:'LineString',coordinates:[a,b]})||''} fill="none" stroke="transparent" strokeWidth={14/zoom}/><path d={path({type:'LineString',coordinates:[a,b]})||''} fill="none" stroke={color} strokeWidth={(f.connection||!comparableFlows?2.5:1+3*Math.sqrt(f.amount/max))/zoom} strokeOpacity={selected&&selected!==f.id?.15:.68} strokeDasharray={f.connection?`${6/zoom} ${4/zoom}`:f.estimated?'5 5':undefined} markerEnd={'url(#'+arrowId+')'}/><title>{f.originLabel} to {f.destinationLabel}</title></g>)}
    {pins.map(({s,p,count})=><g key={s.properties.id}>{selected===s.properties.id&&<circle cx={p[0]} cy={p[1]} r={(radius(s)+3)/zoom} fill="none" stroke="var(--map-selected)" strokeWidth={1.5/zoom} pointerEvents="none"/>}<circle cx={p[0]} cy={p[1]} r={(count>1?10+Math.min(7,Math.log10(count)*3):radius(s))/zoom} fill={proportional&&s.properties.value===null?'#fffdf4':String(s.properties.stageColor||(s.properties.type==='mining-area'?'var(--map-mining)':'var(--map-site)'))} opacity={sites.some(p=>p.properties.id===selected)&&selected!==s.properties.id?.3:.9} stroke={proportional&&s.properties.value===null?'var(--map-site)':'#fff'} strokeWidth={1/zoom} role="button" tabIndex={0} aria-label={count>1?count+' nearby records; zoom in':s.properties.name+', '+(s.properties.value===null?(s.properties.metric==='Source location'?'source location':'quantity unreported'):compact(s.properties.value)+' '+s.properties.unit)} onKeyDown={e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();if(count>1){setZoom(z=>Math.min(64,z*2));setPan({x:(500-p[0])*Math.min(64,zoom*2),y:(250-p[1])*Math.min(64,zoom*2)})}else onSite(s)}}} onClick={()=>{if(!drag.current?.move){if(count>1){setZoom(z=>Math.min(64,z*2));setPan({x:(500-p[0])*Math.min(64,zoom*2),y:(250-p[1])*Math.min(64,zoom*2)})}else onSite(s)}}} onMouseEnter={()=>setHover(count>1?count+' nearby records · click to zoom':s.properties.name+' · '+(s.properties.value===null?(s.properties.metric==='Source location'?'source location':'quantity unreported'):compact(s.properties.value)+' '+s.properties.unit))} onMouseLeave={()=>setHover('')} className="mw-point"><title>{count>1?count+' nearby source records':s.properties.name}</title></circle>{count>1&&<text x={p[0]} y={p[1]} dy={3/zoom} textAnchor="middle" fontSize={9/zoom} fill="#ffffff" pointerEvents="none">{count>999?compact(count):count}</text>}</g>)}
    {(!siteView||flows.some(f=>f.connection))&&labels.map(l=>{const p=projection(l.p);if(!p||globe&&geoDistance(l.p,[-rotation[0],-rotation[1]])>=Math.PI/2)return null;return <g key={l.id} pointerEvents="none"><circle cx={p[0]} cy={p[1]} r={3/zoom} fill={color}/><text x={p[0]+7/zoom} y={p[1]-8/zoom} fontSize={(siteView?18:12)/zoom} fill="var(--map-text)" className="mw-map-label" style={{strokeWidth:3/zoom}}>{l.name}</text></g>})}
   </g></g>
  </svg>
  {hover&&<div className="mw-map-tooltip">{hover}</div>}
  <div className="mw-map-tools"><button aria-label="Zoom in" onClick={()=>setZoom(z=>Math.min(64,z*1.5))}><Plus size={18}/></button><button aria-label="Zoom out" onClick={()=>setZoom(z=>Math.max(1,z/1.5))}><Minus size={18}/></button><button aria-label="Reset map" onClick={()=>{setZoom(1);setPan({x:0,y:0});setRotation([-15,-12])}}><RotateCcw size={16}/></button>{siteView&&place!=='WORLD'&&!local&&<button aria-label={world?'Focus selected country':'Show world map'} onClick={()=>{setWorld(w=>!w);setZoom(1);setPan({x:0,y:0})}}><Globe2 size={16}/></button>}</div>
  {countryLayer?<div className="mw-country-legend" aria-label={countryLayer.label+' legend'}><strong>{countryLayer.unit}</strong>{scaleColors.map((c,i)=><span key={c}><i style={{background:c}}/>{i===0?'Under '+compact(countryLayer.thresholds[0]):i===4?compact(countryLayer.thresholds[3])+'+':compact(countryLayer.thresholds[i-1])+'–'+compact(countryLayer.thresholds[i])}</span>)}<span><i style={{background:'var(--map-no-data)'}}/>No observation</span></div>:siteView&&contextual?<div className="mw-map-options"><span>Colors show stages{portCount?' · blue ports scale with monthly calls':''}.</span><span>Nearby records are grouped; zoom for detail.</span></div>:<div className="mw-map-options">{siteView?<><label><Checkbox disabled={!comparable} checked={proportional&&comparable} onCheckedChange={v=>setProportional(v===true)}/>{comparable?'Size points by '+sites[0]?.properties.metric:'Location markers · one measure needed to scale'}</label><span>{proportional?'Circle area scales with value · minimum marker size · missing values hollow':'Equal-size location markers'}</span></>:<><span className="mw-map-key" style={{color}}><i className="mw-map-line-sample"/>{comparableFlows?'Thicker line = larger quantity in this series':'Equal-width lines · mixed measures'}</span><span>Arrow: origin → destination</span></>}</div>}
  {missingLocations>0&&<div className="mw-map-unmapped">{missingLocations} {siteView?'records cannot be projected in this view':'connections have no mapped endpoint'}. Their records remain in the list.</div>}
  {rasterError&&<p className="mw-raster-warning" role="status">Some NASA imagery could not load. Facility markers and records remain available.</p>}
  <div className="mw-map-attribution">{shippingDensity&&<span>Shipping: World Bank · CC BY 4.0 · 2015–2021 · </span>}{raster&&<span>Imagery: NASA GIBS · </span>}<a href="https://www.naturalearthdata.com/downloads/50m-cultural-vectors/" target="_blank" rel="noreferrer">Basemap: Natural Earth · 1:50m</a></div>
  <div className="mw-map-caption"><span><i style={{background:siteView?'var(--map-site)':color}}/>{countryLayer?(countryLayer.loading?'Loading material accounts…':`${countryLayer.values.size} countries / areas with data`):siteView?`${(sites.length-portCount-sites.filter(s=>s.properties.source_id==='user-coordinate').length).toLocaleString()} ${flows.some(f=>f.connection)?'mapped locations':'facility records'}${portCount?' + '+portCount.toLocaleString()+' ports':''}`:`${drawn.length} of ${located.length} located connections${located.length>60?(comparableRoutes?' · largest values prioritized':' · source order prioritized'):''}`}</span><span>{countryLayer?'Colour compares reported values · empty areas are not zero':siteView?(sites[0]?.properties.type==='mining-area'?'Representative points within mining footprints':'Site locations from the source'):'Country / region anchors, not ports or transport paths.'}</span></div>
  <span id={'map-end-'+mapId} tabIndex={-1}/>
 </section>
}
