'use client';
import {useEffect,useMemo,useState} from 'react';
import {Anchor,ArrowUpRight,Download,Pause,Play,Search,Ship,Waves} from 'lucide-react';
import {Sheet,SheetContent,SheetDescription,SheetTitle} from '@/components/ui/sheet';
import {useMaterialArtifact} from '../material-data';
import {compact,number,exportCSV} from '../atlas-next/common';
import {monthLabel,portCalls,shippingSource,vesselTypes,type MaritimeCatalog,type Port,type PortActivity,type VesselType} from '@/packages/material-world/maritime';
import type {SiteFeature} from './model';
import './maritime.css';
import {useTransportField} from './TransportState';

export function useMaritimeLayers(place:string,enabled=false){
 const [portsOn,setPortsOn]=useTransportField('mapPorts',enabled),[density,setDensity]=useTransportField('mapShipping',enabled),[period,setPeriod]=useTransportField('portMonth',''),[vessel,setVessel]=useTransportField('portVessel','all'),[selected,setSelected]=useTransportField('portId',''),[query,setQuery]=useState(''),[worldwide,setWorldwide]=useTransportField('portsWorldwide',false),[playing,setPlaying]=useState(false);
 const catalog=useMaterialArtifact<MaritimeCatalog>(portsOn?'/data/v16/maritime/catalog.json':null);
 const ports=useMaterialArtifact<Port[]>(catalog.data?.portsPath||null),activity=useMaterialArtifact<PortActivity[]>(catalog.data?.activityPath||null);
 const month=period||catalog.data?.defaultMonth||'2026-08';
 const months=catalog.data?.months||[];
 const country=['BC','SSI'].includes(place)?'CAN':place;
 const located=useMemo(()=>(ports.data||[]).filter(p=>worldwide||country==='WORLD'||p.country===country),[ports.data,country,worldwide]);
 const monthRows=useMemo(()=>new Map((activity.data||[]).filter(r=>r.month===month).map(r=>[r.port,r])),[activity.data,month]);
 const features=useMemo<SiteFeature[]>(()=>!portsOn?[]:located.map(p=>{const r=monthRows.get(p.id),calls=portCalls(r,vessel);return {type:'Feature',geometry:{type:'Point',coordinates:p.coordinates},properties:{id:'port-'+p.id,name:p.name,type:'Maritime port',country:p.country,source_id:'imf-portwatch',year:Number(month.slice(0,4)),value:calls,unit:'port calls · '+monthLabel(month),metric:'Port calls',basis:'modeled',stageColor:'#328ca1',mapRadius:calls===null?4:4+Math.min(9,Math.log1p(calls)*1.3),transport:true,portId:p.id}}}),[portsOn,located,monthRows,vessel,month]);
 const chosen=ports.data?.find(p=>p.id===selected),history=useMemo(()=>(activity.data||[]).filter(r=>r.port===selected),[activity.data,selected]);
 const search=useMemo(()=>located.filter(p=>(p.name+' '+p.countryName+' '+(p.locode||'')).normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().includes(query.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase())).sort((a,b)=>(portCalls(monthRows.get(b.id),vessel)??-1)-(portCalls(monthRows.get(a.id),vessel)??-1)),[located,query,monthRows,vessel]);
 useEffect(()=>{if(!portsOn)setPlaying(false)},[portsOn]);
 useEffect(()=>{if(!playing||!months.length)return;const timer=setInterval(()=>{if(document.hidden){setPlaying(false);return}setPeriod(p=>months[(months.indexOf(p||months.at(-1)!)+1)%months.length])},1200);return()=>clearInterval(timer)},[playing,months.join('|'),period]);
 const loading=portsOn&&(!catalog.data||!ports.data||!activity.data),error=catalog.error||ports.error||activity.error;
 function open(p:Port){setSelected(p.id);setPlaying(false)}
 const controls=<div className="mw-maritime">
  <div className="mw-maritime-bar"><span><Ship size={16}/>Transport</span><button aria-pressed={portsOn} onClick={()=>setPortsOn(v=>!v)}><Anchor size={15}/>Ports & terminals</button><button aria-pressed={density} onClick={()=>setDensity(v=>!v)}><Waves size={15}/>Shipping activity</button>{(portsOn||density)&&<span className="mw-context-label">Context layers · not product tracking</span>}</div>
  {portsOn&&<details className="mw-port-controls"><summary>Monthly port activity <span>{error?'Source unavailable':loading?'Loading source data…':number(located.length,0)+' locations'}</span></summary>{error?<p role="alert">{error}</p>:<>
   <div className="mw-port-filters"><label>Vessel type<select value={vessel} onChange={e=>setVessel(e.target.value as VesselType)}>{vesselTypes.map(([id,label])=><option key={id} value={id}>{label}</option>)}</select></label><label>Month<select value={month} disabled={!months.length} onChange={e=>{setPeriod(e.target.value);setPlaying(false)}}>{months.map(m=><option key={m} value={m}>{monthLabel(m)}</option>)}</select></label>{country!=='WORLD'&&<label className="mw-port-world"><input type="checkbox" checked={worldwide} onChange={e=>setWorldwide(e.target.checked)}/>Show ports worldwide</label>}</div>
   {!!months.length&&<div className="mw-port-time"><button onClick={()=>setPlaying(p=>!p)} aria-label={playing?'Pause port activity':'Play monthly port activity'}>{playing?<Pause size={14}/>:<Play size={14}/>}</button><input type="range" min="0" max={months.length-1} value={Math.max(0,months.indexOf(month))} aria-label="Port activity month" aria-valuetext={monthLabel(month)} onChange={e=>{setPeriod(months[Number(e.target.value)]);setPlaying(false)}}/><time>{monthLabel(month)}</time></div>}
   <details className="mw-port-directory"><summary>Find a port <Search size={13}/></summary><label className="mw-port-search"><Search size={15}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Port, country or UN/LOCODE" aria-label="Find a maritime port"/></label><div className="mw-port-results">{search.slice(0,8).map(p=><button key={p.id} onClick={()=>open(p)}><span>{p.name}<small>{p.countryName}</small></span><b>{portCalls(monthRows.get(p.id),vessel)===null?'—':number(portCalls(monthRows.get(p.id),vessel)!,0)}<small>calls</small></b></button>)}{!loading&&!search.length&&<p>No matching port in this source selection. {country!=='WORLD'?'Try worldwide ports.':'Try a broader search.'}</p>}</div>{search.length>8&&<p className="oa-small">Largest eight matching counts shown. Narrow the search to find another port.</p>}</details>
   <p className="mw-port-footnote"><i/>Blue markers: {vesselTypes.find(t=>t[0]===vessel)?.[1].toLowerCase()} · size increases with monthly calls. Calls count visits, not unique ships. <a href="https://portwatch.imf.org/pages/data-and-methodology" target="_blank" rel="noreferrer">PortWatch methods ↗</a></p>
  </>}</details>}
  {density&&<div className="mw-shipping-legend"><span className="mw-density-scale"/><span>Lower → higher commercial activity <b>2015–2021</b></span><details><summary>Read this layer</summary><p>Hourly AIS position reports from January 2015 to February 2021, including stationary ships. The World Bank raster is averaged and log-scaled for this world map. It shows historical concentrations of activity, not live ships, cargo amounts or routes for the selected material.</p><p>Generalized display; zooming in does not reveal individual ships or berths. Blank areas are not proof of no traffic.</p><a href={shippingSource} target="_blank" rel="noreferrer">World Bank source · CC BY 4.0 ↗</a></details></div>}
 </div>;
 const inspector=<Sheet open={portsOn&&!!chosen} onOpenChange={open=>{if(!open)setSelected('')}}><SheetContent className="oa-sheet mw-port-sheet"><SheetTitle>{chosen?.name||'Port'}</SheetTitle><SheetDescription>{chosen?.countryName}{chosen?.locode?' · '+chosen.locode:''} · PortWatch</SheetDescription>{chosen&&catalog.data&&<PortDetails port={chosen} rows={history} month={month} vessel={vessel} onMonth={setPeriod} catalog={catalog.data}/>}</SheetContent></Sheet>;
 return {controls,inspector,features,density,clearPort:()=>setSelected(''),selected:portsOn&&chosen?'port-'+chosen.id:'',onPort:(s:SiteFeature)=>{const p=ports.data?.find(p=>p.id===s.properties.portId);if(p)open(p)}};
}

function PortDetails({port,rows,month,vessel,onMonth,catalog}:{port:Port;rows:PortActivity[];month:string;vessel:VesselType;onMonth:(m:string)=>void;catalog:MaritimeCatalog}){
 const row=rows.find(r=>r.month===month),calls=portCalls(row,vessel),max=Math.max(1,...rows.map(r=>portCalls(r,vessel)||0));
 return <><p className="oa-big-value">{calls===null?'Not reported':number(calls,0)}<span>port calls · {vesselTypes.find(t=>t[0]===vessel)?.[1].toLowerCase()} · {monthLabel(month)}</span></p>
  <div className="mw-port-spark" aria-label="Monthly port-call history">{rows.map(r=>{const value=portCalls(r,vessel);return <button key={r.month} aria-pressed={r.month===month} aria-label={`${monthLabel(r.month)}: ${value===null?'not reported':number(value,0)+' calls'}`} title={`${monthLabel(r.month)} · ${value===null?'not reported':number(value,0)}`} onClick={()=>onMonth(r.month)}><i style={{height:(value===null?0:Math.max(2,value/max*100))+'%'}}/><span>{r.month.slice(5)}</span></button>})}</div><p className="oa-small">Sep 2025 → Aug 2026 · select a month</p>
  <dl className="oa-facts"><dt>Observation coverage</dt><dd>{row?`${row.days} of ${row.expectedDays} days${row.days<row.expectedDays?' · partial month':''}`:'No retained monthly observation'}</dd><dt>Coordinates</dt><dd>{port.coordinates[1].toFixed(5)}, {port.coordinates[0].toFixed(5)}</dd><dt>Source identifier</dt><dd>{port.id}</dd><dt>Evidence</dt><dd>AIS-derived port visits; no shipment-level commodity link</dd></dl>
  {row&&<><h3>Which vessels call here?</h3><div className="mw-vessel-mix">{vesselTypes.slice(1).map(([id,label])=><div key={id}><span>{label}</span><b>{portCalls(row,id)===null?'—':number(portCalls(row,id)!,0)}</b></div>)}</div><details className="oa-method"><summary>Modeled cargo handled</summary><p>Estimated from vessel draft and payload changes. These are source estimates, not customs weights or volumes of the material selected in OVERSHOOT.</p><dl className="oa-facts"><dt>All vessels · import</dt><dd>{row.import===null?'Not reported':compact(row.import)+' tonnes'}</dd><dt>All vessels · export</dt><dd>{row.export===null?'Not reported':compact(row.export)+' tonnes'}</dd><dt>Tankers · import</dt><dd>{row.import_tanker===null?'Not reported':compact(row.import_tanker)+' tonnes'}</dd><dt>Tankers · export</dt><dd>{row.export_tanker===null?'Not reported':compact(row.export_tanker)+' tonnes'}</dd></dl></details></>}
  <p className="oa-small">{catalog.source.attribution}</p><a className="oa-source-row" href={catalog.source.methodUrl} target="_blank" rel="noreferrer">Source & methods<ArrowUpRight size={16}/></a><a className="oa-source-row" href={port.sourceUrl} target="_blank" rel="noreferrer">Original port register<ArrowUpRight size={16}/></a><button className="oa-button outline" onClick={()=>exportCSV(rows.map(r=>({...r,portName:port.name,country:port.country,portCallsUnit:'visits',cargoUnit:'modeled tonnes',source:catalog.source.url,attribution:catalog.source.attribution,license:catalog.source.license,terms:catalog.source.licenseUrl,retrievedAt:catalog.source.retrievedAt,method:catalog.source.method})),`overshoot-port-${port.id}.csv`)}><Download size={16}/>Export monthly observations</button>
  <details className="oa-method"><summary>Coverage, source fields & reuse</summary><p>{catalog.source.method}</p><ul>{catalog.source.limitations.map(l=><li key={l}>{l}</li>)}</ul><a href={catalog.source.licenseUrl} target="_blank" rel="noreferrer">{catalog.source.license}</a><pre>{JSON.stringify({port,observation:row},null,2)}</pre><a href={catalog.queries[month]?.[0]} target="_blank" rel="noreferrer">Monthly aggregation query ↗</a></details>
 </>;
}
