"""Publish the acquisition register, with integration status separate from access."""
import json,pathlib
HERE=pathlib.Path(__file__).parent;ROOT=HERE.parents[2];OUT=ROOT/'public/data/v13'
feeds=[]
def add(id,title,topic,status,url,method,coverage,refresh,rights,limit,**extra):
 feeds.append(dict(id=id,title=title,topic=topic,status=status,url=url,method=method,coverage=coverage,refresh=refresh,rights=rights,limitations=limit,**extra))
add('eia','EIA International Energy Statistics','Oil, gas & coal','imported','https://www.eia.gov/opendata/index.php','Download the public INTL.zip bulk JSON; filter exact product/activity/unit/frequency series. Retain original country series IDs, missing markers and update dates. No API key is needed for the bulk file.','15 annual measures. Crude oil and NGL production through 2025; gas and coal through 2024. Broader oil-use coverage in 2024.','Check the bulk manifest weekly; rebuild the complete selected history when its hash changes. OVERSHOOT currently publishes reviewed snapshots.','Public-domain EIA data; all selected series declare copyright None. Acknowledge EIA and publication date.','Production, consumption, trade and reserves are different measures. The annual API does not supply observation-level estimate flags. Regional series with country-like geography fields must be excluded to prevent duplication.',downloadUrl='https://www.eia.gov/opendata/bulk/INTL.zip',metadataUrl='https://www.eia.gov/opendata/bulk/manifest.txt',termsUrl='https://www.eia.gov/about/copyrights_reuse.php',destination={'view':'materials','material':'fuels','form':'2709','layer':'production'})
add('jodi-oil','JODI Oil World Database','Oil production, refining & trade','imported','https://www.jodidata.org/oil/database/data-downloads.aspx','Download primary oil CSV files for each year. Select explicit product, flow and unit combinations. Preserve the assessment code and non-numeric source marker.','Five monthly measures, January 2025–June 2026 in the acquired files. Reporting differs by country and month.','Check after each monthly release; re-download current and previous annual files because historical months can change.','Freely downloadable; attribute IEF, Joint Organizations Data Initiative, Oil World Database and access date.','KBD is a rate, not a monthly volume. Several Gulf countries have no recent numeric submissions. Keep JODI monthly records separate from EIA annual estimates.',downloadUrl='https://www.jodidata.org/_resources/files/downloads/oil-data/annual-csv/primary/primaryyear2026.csv',metadataUrl='https://www.jodidata.org/_resources/files/downloads/oil-data/jodi-oil-wdb-item-names-ver2017.pdf',destination={'view':'materials','material':'fuels','form':'2709','layer':'production','energyMeasure':'monthly-crude-exports'})
add('jodi-gas','JODI Gas World Database','Gas & LNG','access','https://www.jodidata.org/gas/database/data-downloads.aspx','Use the publisher’s CSV export with NATGAS, INDPROD, imports/exports, LNG and pipeline dimensions. The current download page describes free CSV access but exposes no CSV link in the retrieved page.','Monthly participating-country gas records. The present app uses EIA annual gas data instead.','Monthly; acquire an official export before building an importer.','Publisher attribution required; retain the source release and its terms.','No gas CSV has been acquired in this release. Do not infer LNG tonnes from gaseous volume or combine LNG and pipeline subcategories with their totals.',metadataUrl='https://www.jodidata.org/_resources/files/downloads/gas-data/jodi-gas-wdb-short--long-names-ver2025.pdf')
add('owid-energy','Our World in Data energy data & ETL','Energy cross-checks','verified','https://github.com/owid/energy-data','Read the CSV and codebook; use the published ETL to trace each variable to EIA, Energy Institute or another original publisher. Codebook access was checked.','Useful harmonized country histories and cross-checks; not imported here as a second competing production series.','Track repository releases/commits; pin the codebook and data together.','OWID-created work is CC BY; underlying third-party source rights still apply.','Many production variables are TWh of energy content. They must not be labelled tonnes or barrels. Latest year varies by variable.',downloadUrl='https://owid-public.owid.io/data/energy/owid-energy-data.csv',repo='https://github.com/owid/etl',metadataUrl='https://github.com/owid/energy-data/blob/master/owid-energy-codebook.csv')
add('energy-institute','Energy Institute Statistical Review','Energy production, trade & reserves','access','https://www.energyinst.org/statistical-review/resources-and-data-downloads','Use the official annual spreadsheet and definitions; pin the edition and sheet/cell references. The 2026 download is behind an email-verification form. The archive lists a public 2025 workbook.','Annual country and regional tables; recent edition access has not been completed.','Annual edition; revalidate historical revisions and reuse terms.','Review the edition’s terms and any third-party reserve sources before republication.','Do not bypass the email gate. Proven reserves, resources, annual production and capacity have different definitions; regional aggregates must remain regional.')
add('usgs','USGS Mineral Commodity Summaries','Metals, industrial minerals & reserves','access','https://doi.org/10.5066/P1WKQ63T','Resolve the official DOI, acquire the ScienceBase CSV tables and their XML metadata, retain table footnotes and exact unit/basis. DOI metadata was acquired; the data host returned HTTP 403.','The 2026 data release describes over 90 nonfuel commodities, with US statistics and world production tables. Not imported.','Annual edition, with table-level checksums and revision review.','The DOI metadata identifies the data release as CC0 1.0.','A valid open licence does not solve the current download failure. Do not replace mine output with refined output, gross ore mass or a report’s regional Other subtotal.',metadataUrl='https://api.datacite.org/dois/10.5066/P1WKQ63T')
add('bgs','BGS World Mineral Statistics API','Mineral production by country','permission','https://www.bgs.ac.uk/mineralsuk/statistics/world-mineral-statistics/','Use OGC API Features with commodity, country and year filters, pagination and retained source fields. A one-record JSON request succeeded. Follow the publisher’s example notebook.','API records extend back to 1970; metadata may lag the newest yearbook. Not imported.','Annual; verify actual API years against the yearbook.','BGS terms permit specified non-commercial research uses; commercial use or supply to third parties requires checking permission with the rights owner.','An accessible API is not an unrestricted republication licence. BGS also documents flag-loss in the API representation; estimates and small/missing values need the original yearbook notes.',repo='https://github.com/BritishGeologicalSurvey/BGS-API-Documentation',downloadUrl='https://ogcapi.bgs.ac.uk/collections/world-mineral-statistics/items?f=json&limit=1',termsUrl='https://www.bgs.ac.uk/mineralsuk/statistics/world-mineral-statistics/bgs-mineral-statistics-terms-and-conditions-ipr/')
add('climate-trace','Climate TRACE data & API','Oil fields, refineries, mines & emissions','verified','https://climatetrace.org/data','Use the documented v7 API or sector download packages. The API documentation is reachable, but its schema response did not parse as JSON in this environment; validate a data payload before import. Pin each release, stable source ID, coordinates, sector, gas and reporting interval.','Worldwide emissions sources, including extraction and processing. Asset data are not yet imported into OVERSHOOT.','Monthly source releases; never treat acquisition date as observation date.','CC BY 4.0 for Climate TRACE data, with specific external-dataset exceptions listed in its terms.','These are modelled/reported emissions, not tonnes of material processed. Review external rights, coordinate precision and aggregate geometries before mapping a point.',repo='https://github.com/climatetracecoalition/climate-trace-tools',metadataUrl='https://api.climatetrace.org/v7',termsUrl='https://climatetrace.org/terms')
add('gem','Global Energy Monitor trackers','Fields, LNG terminals, pipelines & coal mines','access','https://globalenergymonitor.org/projects/global-oil-gas-extraction-tracker/','Acquire the official dated tracker export; keep unit IDs, source wiki links, operating status, production year and location-accuracy category. Review export terms before import.','The oil/gas extraction tracker describes a March 2026 release. No tracker export was acquired in this release.','Per tracker release; do not scrape wiki pages into a substitute census.','Verify and retain the licence supplied with the actual export; website availability alone is insufficient.','Size thresholds exclude smaller assets. Some locations are only country-level placeholders: these must never appear as exact field coordinates.',metadataUrl='https://www.gem.wiki/Global_Oil_and_Gas_Extraction_Tracker')
add('faostat','FAOSTAT production & forestry','Food, wood, pulp & paper','imported','https://www.fao.org/faostat/en/#data/QCL','Use the official bulk index to select a dated normalized archive. Retain item/element codes, M49 geography, unit, source flag and note. Expand to additional crops, fibres and livestock products by explicit item code.','Current maps contain eight primary crops and nine forest products for 2024. Broader crop and livestock coverage is available upstream.','Check bulk-index timestamps monthly; refresh when the selected archive changes.','CC BY 4.0 and FAO Statistical Database terms, including third-party exceptions.','Products at different processing stages overlap. Timber m³ cannot be converted to tonnes without a density basis; heads of animals cannot be treated as meat tonnage.',metadataUrl='https://bulks-faostat.fao.org/production/datasets_E.json',termsUrl='https://www.fao.org/contact-us/terms/db-terms-of-use/en/',destination={'view':'materials','material':'wood','form':'4403','layer':'production'})
add('irp','UNEP IRP Global Material Flows','Extraction, use & footprints','imported','https://www.resourcepanel.org/global-material-flows-database','Retain official country-account CSV exports and original material classifications. Keep direct-flow accounts and modelled footprints separate.','1970–2024 country material histories. Recent years are proxy estimates. Four broad extraction classes do not identify individual minerals.','Check official dataset editions; no unannounced in-place refresh.','Public export; no explicit general reuse licence identified in the reviewed source. Attribution is retained; additional redistribution should be reviewed.','All metal ores is not copper production; all non-metallic minerals is not cement. Never invent a refined-metal conversion or a balanced global trade total.',destination={'view':'places','place':'WORLD'})
add('comtrade','UN Comtrade API & official Python client','Bilateral commodity & scrap trade','imported','https://comtradeplus.un.org/','Use official availability metadata before acquisition. Partition by reporter/year/HS/flow until all pages are complete; preserve reporter versus partner, net-weight estimation flags and HS revision. Store response hashes.','Existing commodity view is a selected reporter sample, not a complete world matrix. Waste-report coverage is a separate source.','Reporting schedules differ. Reacquire revised reporter-year partitions rather than append duplicate observations.','UN Comtrade usage agreement; no blanket Creative Commons licence is asserted. Some bulk access needs a subscription.','Public preview responses can be capped. Mirror imports and exporter reports can disagree; never silently combine them. Country links are not vessel tracks or final destinations.',repo='https://github.com/uncomtrade/comtradeapicall',metadataUrl='https://comtradedeveloper.un.org/',termsUrl='https://comtradeplus.un.org/LicenseAgreement',destination={'view':'trade'})
add('baci','CEPII BACI','Annual reconciled goods trade','access','https://www.cepii.fr/DATA_DOWNLOAD/baci/doc/baci_webpage.html','Download the official HS-revision-specific release plus country and product codes. Keep the release identifier and document BACI’s reconciliation method.','A potential broader annual trade matrix. Official page returned HTTP 403 in this environment; no files acquired.','Annual; pin the release and compare revisions.','Check the actual release terms and UN Comtrade-derived reuse conditions before redistribution.','Reconciled quantities are not original exporter reports. They are not proof of final disposal or vessel movements, and must not replace observed weights without a clear label.')
add('waw','World Bank What a Waste 3.0','National & city waste systems','imported','https://datacatalog.worldbank.org/search/dataset/0039597/what-a-waste-global-database','Download the country and city workbooks with codebooks. Retain field-level original references, dates, methods and notes; validate fractions, percentages and allowed ranges.','217 countries/economies and 262 city records already imported.','Edition-based release; there is no claim of a live municipal feed.','CC BY 4.0 with attribution to the World Bank and original field sources.','City areas and observation years differ. Waste sent for recycling does not measure recovered output. Projections and modelled baselines remain separate from observations.',destination={'view':'places','placeView':'waste'})
add('sdg','UN SDG API','E-waste, food loss & hazardous waste','imported','https://unstats.un.org/sdgs/dataportal','Read Series/Data with complete pagination. Preserve series code, source, nature/estimate flags, footnotes, dimensions and reference period; map only actual country codes.','Selected source series already imported. Some e-waste data are modelled and later years can be projections.','Check source-release metadata and re-fetch complete affected series.','UN statistical-data terms and original agency attribution; no generic CC licence inferred.','Series with different denominators or scopes are not interchangeable. An aggregate region is not a country observation.',metadataUrl='https://unstats.un.org/sdgapi/swagger/',downloadUrl='https://unstats.un.org/sdgapi/v1/sdg/Series/Data?seriesCode=EN_EWT_GENV&pageSize=50000')
add('eurostat','Eurostat waste statistics','Treatment, packaging & e-waste','imported','https://ec.europa.eu/eurostat/web/waste/database','Use the official JSON-stat/SDMX API with dataset-specific dimensions and status flags. Preserve sparse cells, hazardous-waste scope and operation hierarchy.','European reporting countries; existing app includes municipal, packaging, all-sector treatment and e-waste series.','Follow dataset update timestamps; annual and biennial series differ.','Eurostat attribution policy with third-country/third-party exceptions; existing public output excludes restricted geographies.','Treatment inside a country can include imported waste. Combined categories overlap with their children. Confidential splits must remain unknown.',metadataUrl='https://ec.europa.eu/eurostat/web/user-guides/data-browser/api-data-access/api-introduction',termsUrl='https://ec.europa.eu/eurostat/web/main/help/copyright-notice')
add('oecd-plastics','OECD Global Plastics Outlook','Plastic use, waste, leakage & recycling','imported','https://doi.org/10.1787/c0821f81-en','Retain the source model tables and native geographic groups. Keep historical estimates separate from scenario projections and record the version.','Current snapshot covers 1990–2019, with only a few geographies that map directly to individual countries.','New model edition; not a monthly observational feed.','OECD terms with attribution and third-party exceptions.','Global model regions cannot be coloured as if every member country had an observed national recycling rate. No new country values have been inferred here.')
add('basel','Basel national reports','Controlled waste, destinations & treatment codes','imported','https://www.basel.int/Countries/NationalReporting/NationalReports/BC2024Reports/tabid/10394/Default.aspx','Parse national report sections by reporting country and year. Keep waste code, destination, amount, unit and recovery/disposal code together; retain a reference to the original report.','Existing source covers reporting sections, not universal shipment tracking.','Annual submissions; coverage and corrections differ by reporter.','Original reporting and convention sources must be attributed. No blanket open licence inferred.','A permitted/reported movement is not proof of delivery or successful treatment. D/R operation codes have legal versions and cannot be treated as recycling percentages.')
add('local-portals','Official regional & municipal data','Local disposal, collection & end markets','imported','https://catalogue.data.gov.bc.ca/','Use each publisher’s versioned CSV/API, area codes and definitions. BC and Statistics Canada provide the current regional examples; every additional jurisdiction needs an explicit adapter.','Detailed BC disposal areas and Canadian product trade are already retained. Other locales vary in public reporting depth.','Publisher-specific schedules; validate boundary changes, weighbridge basis and transfer/destination fields.','Dataset-specific licences; Canadian and BC open-data attribution where applicable.','No universal public feed connects every household to its final processor. Facility capacity, collected mass and recovered output must remain distinct.',metadataUrl='https://open.canada.ca/data/en/dataset/2909a648-5753-4924-878a-b069392d9cde',destination={'view':'places','place':'BC'})
add('osm','OpenStreetMap / Overpass','Location gaps','permission','https://www.openstreetmap.org/copyright','Query explicitly tagged facilities within bounded areas; retain OSM type/ID, timestamp, tags and attribution. Apply an ODbL-compatible database/reuse design before importing.','Potential location enrichment; not a throughput or operating-status census. No new OSM facility records imported here.','Incremental changes or dated regional extracts, subject to service usage policies.','Open Database Licence; derivative database and attribution obligations require deliberate handling.','A map tag or nearby point does not prove a material connection. Avoid unbounded global Overpass queries and do not label inferred coordinates as exact.',termsUrl='https://opendatacommons.org/licenses/odbl/1-0/')

data={'reviewedAt':'2026-09-22','refreshMode':'Reviewed snapshots. No scheduled refresh is currently running.','statusLabels':{'imported':'Imported snapshot','verified':'Access checked · not imported','access':'Access incomplete','permission':'Rights review needed'},'feeds':feeds}
OUT.mkdir(exist_ok=True);(OUT/'feeds.json').write_text(json.dumps(data,ensure_ascii=False,indent=2)+'\n')
registry=json.loads((ROOT/'public/data/v3/sources.json').read_text());ids={s['id'] for s in registry}
energy=json.loads((OUT/'energy/catalog.json').read_text())
for id,s in energy['sources'].items():
 entry={'id':id,'title':s['name'],'publisher':s['publisher'],'status':'available','url':s['url'],'method':s['method'],'license':s['license'],'retrievedAt':s['retrievedAt'],'limitations':[s['limitations']],'transformations':s['method'],'coverageYears':'1980–2025, measure-dependent' if id.startswith('eia') else 'January 2025–June 2026','downloadUrls':[feeds[0 if id.startswith('eia') else 1]['downloadUrl']]}
 registry=[r for r in registry if r['id']!=id]+[entry]
for r in registry:
 if r['id']=='bgs-world-minerals':r.update(status='catalogued',accessNote='OGC API access succeeded on 2026-09-22; republication rights and original source flags require review.',license=next(f['rights'] for f in feeds if f['id']=='bgs'))
(ROOT/'public/data/v3/sources.json').write_text(json.dumps(registry,ensure_ascii=False,separators=(',',':'))+'\n')

guide='''# OVERSHOOT source and acquisition register

Reviewed 22 September 2026. This is a record of tested acquisition paths, existing imports and remaining blockers. Public access, permission to redistribute, and integration into the app are separate questions. No scheduled refresh is running.

## Feed map

| Source | State | Acquisition | Scope / important limit |
| --- | --- | --- | --- |
'''
for f in feeds:
 guide+=f"| [{f['title']}]({f['url']}) | {data['statusLabels'][f['status']]} | {f['method']} | {f['coverage']} {f['limitations']} |\n"
guide+='\n## Repositories and documentation\n\n'
for f in feeds:
 if f.get('repo'):guide+=f"- [{f['title']} — repository]({f['repo']})\n"
guide+='\n## Refresh and quality method\n\n1. Acquire official machine-readable files into a candidate directory. Record the request URL, retrieval time, content hash and release identifier. Never replace a working release with an error page.\n2. Check the source licence and any third-party exceptions. Retain exact dimensions, source units, geography, flags and null markers.\n3. Normalize only explicitly defined quantities. Do not convert energy content to physical tonnes, infer metal content from ore mass, sum daily rates, or combine overlapping categories.\n4. Reject duplicate country/measure/period keys and unexpected schema or unit changes. Compare revisions, geographic coverage and maximum reporting period with the published release. Source zeros remain zeros; absent or non-numeric values remain missing.\n5. Check representative countries against their original series and cross-check only definition-compatible sources. Record unexplained disagreements instead of averaging them away.\n6. Publish a versioned, validated snapshot. Show the reporting period, acquisition date, source, unit and limits in the app. Failed imports preserve the previous release.\n\n## What is still missing\n\nMineral-specific mine/refinery output, global LNG partner routes, current field-level throughput and universal local waste destinations are not supplied by the new energy tables. USGS acquisition, BGS republication rights, JODI gas export access and GEM asset exports need further work. Climate TRACE can add emissions context, not a substitute material-flow total. The existing trade map remains a selected reporter sample.\n'
(OUT/'source-guide.md').write_text(guide)
print('Published',len(feeds),'source acquisition records.')
