"""Publish reviewed operator relationships; never join locations by proximity."""
from pathlib import Path
import json,gzip
ROOT=Path(__file__).resolve().parents[3]
R=ROOT/'public/data/v16'
reviewed='2026-09-23'
def read(p):
 b=p.read_bytes();return json.loads(gzip.decompress(b) if b[:2]==b'\x1f\x8b' else b)
pins={}
for p in (R/'journeys').glob('layer-*.json'):
 for r in read(p):pins[r['id']]=r
ports={r['id']:r for r in read(R/'maritime/ports.json')}
sources=[]
def source(id,title,publisher,url,locator,date=None):
 sources.append(dict(id=id,title=title,publisher=publisher,url=url,publishedAt=date,reviewedAt=reviewed,locator=locator,reuse='Operator facts paraphrased with attribution. No open license established for the publisher’s text.'))
source('hydro-paragominas','Paragominas','Hydro','https://www.hydro.com/en/global/about-hydro/hydro-worldwide/americas/brazil/paragominas/','Operation description: crushed bauxite, 244 km pipeline, Alunorte.')
source('hydro-alunorte','Alunorte','Hydro','https://www.hydro.com/br/global/about-hydro/a-hydro-no-mundo/americas/brasil/barcarena/alunorte/','Operation description: Paragominas supply; alumina supplied to Albras; refinery residue storage. Portuguese source.')
source('qal-products','Our products','Queensland Alumina Limited','https://qal.au/who-we-are/our-products/','Bauxite and alumina sections: Weipa feedstock shipped to Gladstone.')
source('msq-weipa','Weipa port procedures','Maritime Safety Queensland','https://www.msq.qld.gov.au/shipping/port-procedures/port-procedures-weipa','Port description: bauxite exports to Gladstone refineries.')
source('rio-boyne','Boyne Smelters Limited','Rio Tinto','https://www.riotinto.com/operations/anz/gladstone/boyne-smelters-ltd','Opening operation description: QAL supplies alumina through a conveyor.')
source('lkab-narvik','The ore trains are rolling towards Narvik again','LKAB','https://lkab.com/en/news/the-ore-trains-are-rolling-towards-narvik-again/','Kiruna departures and iron-ore pellet trains to Narvik.','2024-02-20')
source('bhp-coloso','Colossal achievement in Coloso','BHP','https://www.bhp.com/es/news/articles/2018/06/colossal-achievement-in-coloso','Copper concentrate stored and loaded onto ships at Coloso.','2018-06-27')
source('bhp-escondida-20f','BHP annual report / Form 20-F 2025','BHP','https://www.bhp.com/-/media/documents/investors/annual-reports/2025/bhpform20f2025.pdf','Printed page 186 / PDF page 199, Escondida property: concentrate pipelines to Coloso; cathode rail transport to Antofagasta and Mejillones.','2025')
source('novelis-jlr','Aluminium solutions for the Jaguar XE','Novelis','https://investors.novelis.com/news-events/press-releases/detail/220/novelis-supplies-innovative-aluminium-solutions-for-new-jaguar-xe','Paragraph beginning Since 2013: JLR aluminium manufacturing scrap recycled at Latchford.','2014-12-09')
def node(id,name,stage,trace=None,port=None,country=None):
 if trace:
  r=pins[trace];return dict(id=id,name=name,country=r['country'],stage=stage,coordinates=r['coordinates'],locationNote='Source facility point; boundary and internal production units are not resolved.',locationSource=r['source'],facility=dict(id=trace,kind=r['kind']))
 if port:
  r=ports[port];return dict(id=id,name=name,country=r['country'],stage=stage,coordinates=r['coordinates'],locationNote='PortWatch port-area anchor, not a particular berth.',locationSource='imf-portwatch',portId=port)
 return dict(id=id,name=name,country=country,stage=stage,coordinates=None,locationNote='The relationship is documented; a sufficiently specific map location has not been retained.',locationSource=None)
def edge(id,fr,to,form,mode,claim,ids,period,scope,unmapped=False):
 return dict(id=id,**{'from':fr,'to':to},materialForm=form,mode=mode,claim=claim,sourceIds=ids,evidence='operator-reported',quantity=None,period=period,geometry='unmapped' if unmapped else 'schematic',scope=scope)
networks=[
 dict(id='para-aluminium',material='aluminium',title='Bauxite to aluminium in Pará',region='Brazil',summary='A bauxite slurry pipeline feeds a refinery, which supplies a nearby smelter and stores its refining residue.',nodes=[node('paragominas','Paragominas mine','extraction',trace='trace-42233048'),node('alunorte','Alunorte refinery','refining',trace='trace-54502800'),node('albras','Albras smelter','manufacturing',trace='trace-3672954'),node('alunorte-residue','Alunorte residue deposits DRS 1 / DRS 2','disposal',country='BRA')],links=[
 edge('para-pipeline','paragominas','alunorte','Crushed bauxite slurry','pipeline','Hydro identifies a 244 km pipeline carrying bauxite from Paragominas to Alunorte.',['hydro-paragominas'],'Undated operating description; reviewed September 2026','The source establishes the connection and transport mode, not its current throughput or the precise pipe alignment.'),
 edge('para-alumina','alunorte','albras','Alumina','unspecified','Hydro identifies Albras as a recipient of part of Alunorte’s alumina output.',['hydro-alunorte'],'Undated operating description; reviewed September 2026','The receiving plant is named. The cited page does not specify the transport equipment or delivered quantity.'),
 edge('para-residue','alunorte','alunorte-residue','Washed and filtered refining residue','unspecified','Hydro describes washing and filtering refinery residue before storage in its DRS 1 and DRS 2 deposits.',['hydro-alunorte'],'Undated operating description; reviewed September 2026','Industrial residue from refining, not end-of-life aluminium. Deposit boundaries are not mapped here.',True)],gaps=['Downstream product manufacturers and end users are not identified.','No source links this metal to a particular recovered product.','Residue deposits are documented but not assigned guessed coordinates.']),
 dict(id='queensland-aluminium',material='aluminium',title='Bauxite by sea, alumina by conveyor',region='Australia',summary='Weipa’s bauxite reaches the Gladstone refinery by ship; a conveyor then supplies Boyne’s aluminium smelter.',nodes=[node('weipa','Weipa port','transport',port='port1387'),node('qal','Queensland Alumina refinery','refining',trace='trace-54502660'),node('boyne','Boyne smelter','manufacturing',trace='trace-3672944')],links=[
 edge('weipa-qal','weipa','qal','Bauxite','ship','QAL identifies Weipa as its bauxite origin and shipping to Gladstone as the transport leg. The maritime authority identifies Weipa as a bauxite export port.',['qal-products','msq-weipa'],'Undated operating descriptions; reviewed September 2026','The origin marker represents the export port, not an individual mine. The line joins endpoints and does not depict a navigable sea route.'),
 edge('qal-boyne','qal','boyne','Alumina','conveyor','Rio Tinto describes a conveyor connection supplying alumina from Queensland Alumina to Boyne Smelters.',['rio-boyne'],'Undated operating description; reviewed September 2026','The source identifies a physical connection. The diagram does not reproduce its surveyed alignment.')],gaps=['The source does not isolate the contributing Weipa mine or pit.','Specific manufactured products, customers and waste destinations are not traced.']),
 dict(id='kiruna-narvik',material='steel',title='Iron-ore pellets from Kiruna to Narvik',region='Sweden → Norway',summary='An operator-described rail connection carries processed iron ore across the border to an export port.',nodes=[node('kiruna','Kiruna mining and processing area','extraction',trace='trace-43158503'),node('narvik','Narvik port','transport',port='port796')],links=[edge('kiruna-rail','kiruna','narvik','Iron-ore pellets','rail','LKAB reports trains departing Kiruna for Narvik and describes the route carrying pellet-plant output.',['lkab-narvik'],'20 February 2024','The mapped origin is a mine-area anchor, not a particular loading siding. Historical reporting does not establish today’s service or traffic volume.')],gaps=['The source does not assign each shipment to a named steelworks.','Steelmaking, product use and scrap recovery are not traced by this record.']),
 dict(id='escondida-ports',material='copper',title='Copper leaves Escondida in two forms',region='Chile',summary='Concentrate travels to Coloso by pipeline; copper cathodes use rail connections to export ports.',nodes=[node('escondida','Escondida mining and processing area','extraction',trace='trace-45944563'),node('coloso','Coloso port','transport',country='CHL'),node('antofagasta','Antofagasta port','transport',port='port56'),node('mejillones','Mejillones port','transport',port='port728')],links=[
 edge('escondida-coloso','escondida','coloso','Copper concentrate slurry','pipeline','BHP’s property disclosure identifies Escondida-owned concentrate pipelines to Coloso. Its port description documents loading concentrate onto ships.',['bhp-escondida-20f','bhp-coloso'],'2025 property disclosure; 2018 port description','Coloso is retained as a separate endpoint. The nearby Antofagasta port marker is not substituted for it.',True),
 edge('escondida-antofagasta','escondida','antofagasta','Copper cathodes','rail','BHP’s property disclosure identifies rail transport of copper cathodes to Antofagasta.',['bhp-escondida-20f'],'2025 property disclosure','Cathodes and concentrate are separate material forms; no quantities or shares are assigned.'),
 edge('escondida-mejillones','escondida','mejillones','Copper cathodes','rail','BHP’s property disclosure also identifies Mejillones as an export port for cathodes moved by rail.',['bhp-escondida-20f'],'2025 property disclosure','This is a stated connection, not the railway alignment or a particular consignment.')],gaps=['A verified Coloso point is not retained; its pipeline is documented in the list but not drawn.','Receiving smelters, fabricators and consumers are not established.']),
 dict(id='jlr-aluminium-recovery',material='aluminium',title='Car-body scrap returns to aluminium production',region='United Kingdom',summary='Novelis describes recovering Jaguar Land Rover manufacturing scrap at Latchford for automotive sheet feedstock.',nodes=[node('jlr','Jaguar Land Rover manufacturing network','manufacturing',country='GBR'),node('latchford','Novelis Latchford recycling plant','recovery',country='GBR')],links=[edge('jlr-scrap','jlr','latchford','Aluminium manufacturing scrap','unspecified','Novelis describes a recycling arrangement operating since 2013 that converts JLR aluminium production scrap into material for automotive sheet.',['novelis-jlr'],'9 December 2014','This concerns manufacturing scrap. It does not establish recycling of vehicles after consumer use, a particular press shop or a direct delivery of finished sheet from Latchford.',True)],gaps=['The cited announcement does not name the individual originating press shops or transport mode.','No facility coordinates are guessed from a company headquarters.','A return of finished sheet to a specific plant is not mapped.'])
]
catalog=dict(release='17',reviewedAt=reviewed,method='Curated relationships explicitly described by operators or public authorities. Location records are independently matched by facility identity, not proximity. A stated relationship is not independently audited shipment tracing or evidence of current service. Missing quantities remain null. Coverage is a small set of documented networks, not a global supply-chain inventory.',geometry='Lines are schematic endpoint connections. They do not follow roads, railways, pipelines or navigable sea routes. Line width does not encode quantity.',sources=sources,networks=networks)
(ROOT/'public/data/v17/connections.json').write_text(json.dumps(catalog,ensure_ascii=False,indent=2)+'\n')
print(len(networks),'networks',sum(len(n['links']) for n in networks),'links')
