'use client';
import {ArrowRight,BookOpen,Factory,Globe2,Layers3,LocateFixed,MapPin,Route} from 'lucide-react';
import type {AtlasView} from './MaterialAtlas';
import type {AtlasState} from './atlasState';
type Destination=Partial<AtlasState>;
export default function AboutPage({onGo,onSources}:{onGo:(destination:Destination)=>void;onSources:()=>void}){
 const ways=[
  {id:'local',icon:LocateFixed,title:'Local',text:'Search for a city, enter coordinates or use your device location. See nearby source records; national totals stay separate.'},
  {id:'materials',icon:Layers3,title:'Materials',text:'Choose a material and move between its stages. Each stage shows what is measured and where the trail stops.'},
  {id:'places',icon:MapPin,title:'Places',text:'Open country accounts for extraction, imports, exports and consumption. Switch to waste observations for that place.'},
  {id:'trade',icon:Route,title:'Trade',text:'Inspect reported bilateral material and controlled-waste movements, by product, direction, unit and year.'},
  {id:'facilities',icon:Factory,title:'Facilities',text:'Find mines, factories, treatment sites and disposal records. Open any marker for its original source fields.'},
  {id:'waste',icon:BookOpen,title:'Waste',text:'Compare places and source-separated time series. Inspect definitions before comparing rates or totals.'}
 ] as const;
 return <div className="oa-about-page">
  <div className="oa-page-title"><div><span className="oa-kicker">ABOUT OVERSHOOT</span><h1>Follow the material world<br/>back to its sources.</h1><p>OVERSHOOT is a planetary atlas of material flows. It connects published evidence about extraction, making, movement, use and disposal. Pick a place or material, then follow each result to its date, measure and original source.</p></div><Globe2 size={48} className="oa-title-icon"/></div>
  <section className="oa-about-start"><h2>Three steps to an answer</h2><div className="oa-about-examples">
   <button onClick={()=>onGo({view:'local'})}><span>01 / START SOMEWHERE</span><h3>Choose a location.</h3><p>Search for your city to see nearby source records, or select a country for national accounts.</p><ArrowRight size={20}/></button>
   <button onClick={()=>onGo({view:'materials'})}><span>02 / FOLLOW SOMETHING</span><h3>Choose a material.</h3><p>Switch stages and compare extraction, trade, production and waste without mixing their units.</p><ArrowRight size={20}/></button>
   <button onClick={()=>onGo({view:'data'})}><span>03 / CHECK THE EVIDENCE</span><h3>Open the record.</h3><p>Read the source year, measurement basis and limits. Download data or query the same records through MCP.</p><ArrowRight size={20}/></button>
  </div></section>
  <section className="oa-about-section oa-about-glass"><span className="oa-kicker">A WORKED EXAMPLE · UNITED STATES · 2025</span><h2>From a named mine to a power plant.</h2><p>U.S. government fuel receipts identify the coal mines that supplied a named generating plant each month. Mine IDs join to Mine Safety and Health Administration locations; plant IDs join to Energy Information Administration locations. The delivery quantity is reported. The line on the map connects these sourced endpoints, while its physical transport path remains unknown. The plant’s coal generation is a separate measure; these records do not assign electricity to a mine or household.</p><div className="oa-about-chain-actions"><button className="oa-button" onClick={()=>onGo({view:'materials',material:'fuels',place:'USA',layer:'connections',network:'coal-6002'})}>Trace the reported deliveries<ArrowRight size={17}/></button><button className="oa-button outline" onClick={()=>onGo({view:'data'})}>Check monthly source rows<ArrowRight size={17}/></button></div></section>
  <section className="oa-about-section oa-about-chain"><span className="oa-kicker">HOW THE PIECES FIT</span><h2>One material. Several kinds of evidence.</h2><p>Start with a material and a place. Each stage answers a different question; following the arrows does not claim that the same physical object was tracked all the way through.</p><ol><li><strong>Extraction</strong><span>National material accounts measure mass taken from nature. A mine marker locates a reported operation, not its share of the national total.</span></li><li><strong>Making & movement</strong><span>Production series measure output. Customs reports connect countries by product and year; curves on the map are schematic.</span></li><li><strong>Use & accumulation</strong><span>Material footprints and stocks use different accounting methods. They cannot be summed with imports as if they were shipments.</span></li><li><strong>Discard & return</strong><span>Waste surveys and collection programs report generation, treatment or end markets. Collection and a reported end market do not prove the fate of one item.</span></li></ol><div className="oa-about-chain-actions"><button className="oa-button" onClick={()=>onGo({view:'materials',material:'copper',place:'WORLD'})}>Follow copper from the world view<ArrowRight size={17}/></button><button className="oa-button outline" onClick={()=>onGo({view:'materials',material:'fuels',place:'USA',layer:'connections',network:'coal-6002'})}>Inspect a mine-to-plant journey<ArrowRight size={17}/></button></div></section>
  <section className="oa-about-section"><h2>Choose the view for your question</h2><div className="oa-about-views">{ways.map(item=><button key={item.id} onClick={()=>onGo({view:item.id as AtlasView})}><item.icon size={23}/><div><h3>{item.title}</h3><p>{item.text}</p></div><ArrowRight size={17}/></button>)}</div></section>
  <section className="oa-about-section"><h2>Read the map honestly</h2><div className="oa-about-definitions">
   <div><h3>A point is a source location.</h3><p>A marker may be a reported facility, modeled outfall or mapped footprint. Its coordinates do not establish a supplier, output quantity or operating status.</p></div>
   <div><h3>A line is a reported link.</h3><p>Country trade curves join geographic centres. They do not show the shipping route or prove that a named facility received the material. Named operator and government links use sourced endpoints; their connecting lines are still schematic.</p></div>
   <div><h3>National and local are different scales.</h3><p>Extraction totals are country accounts. Nearby facilities are individual source records. A country total cannot be divided among markers or assigned to your chosen radius.</p></div>
   <div><h3>A gap is not a zero.</h3><p>Coverage, years and definitions vary. An empty map or table means no retained observation matches the filters unless the source explicitly reports zero. Optional estimates use linear interpolation between two nearby reported years; they carry both input rows and never fill a missing journey link.</p></div>
  </div><p className="oa-small">On a map, open a marker or line to see the source. Use the environment selector for dated imagery or biophysical context; those layers do not measure the material flow itself. Use zoom and the flat/globe switch to inspect geography.</p></section>
  <section className="oa-about-section"><h2>What is in the atlas?</h2><p>The retained snapshot includes 342,962 geolocated source records across 220 country and area codes. Material accounts cover 1970–2024; World Bank waste data covers 217 countries and economies and 262 city records. Waste research keeps 63,813 historical observations across 123 source-separated series and a separate UN collection register with 5,170 observations. FAO production histories cover 84 food, forestry and natural-fibre products. These are separate sources with different methods and reporting years, not a single inventory of everything on Earth.</p><p>Trade includes selected bilateral commodity reports, 2023–2024 controlled-waste records and partner-reported oil imports where retained export reports are absent. Port visits and historical shipping density describe transport activity; they do not identify cargo from a particular mine or waste facility. Published records are fixed snapshots, not a live feed.</p><p>For a more recent market check, consult <a href="https://comtradeapi.un.org/" target="_blank" rel="noreferrer">UN Comtrade</a> for reported international commodity trade, <a href="https://www150.statcan.gc.ca/t1/tbl1/en/tv.action?pid=1210017501" target="_blank" rel="noreferrer">Statistics Canada’s provincial trade table</a> for Canadian products and partners, and <a href="https://recyclebc.ca/about/annual-reports/" target="_blank" rel="noreferrer">Recycle BC’s annual reports</a> for packaging end markets. Their newer releases do not silently replace the dated observations shown here. Customs partners, recycling end markets and individual receiving facilities are different things.</p><button className="oa-button" onClick={onSources}>Inspect sources and coverage<ArrowRight size={17}/></button></section>
  <section className="oa-about-section oa-about-purpose"><span className="oa-kicker">AN OPEN RESEARCH PROJECT</span><h2>Bring your own question.</h2><p>Use the atlas for orientation, follow a primary source for a claim, and export the records for your analysis. The <button className="oa-text-link" onClick={()=>onGo({view:'data'})}>Material World MCP <ArrowRight size={15}/></button> makes the same retained evidence available to compatible research tools.</p></section>
 </div>;
}
