'use client';
import {useEffect,useState} from 'react';
import {ArrowUpRight,Send} from 'lucide-react';
export default function AgentDesk(){
 const [available,setAvailable]=useState(false),[checking,setChecking]=useState(true),[model,setModel]=useState('');
 const [question,setQuestion]=useState(''),[busy,setBusy]=useState(false),[answer,setAnswer]=useState(''),[error,setError]=useState(''),[dataUrl,setDataUrl]=useState(''),[used,setUsed]=useState('');
 useEffect(()=>{fetch('/api/agent',{cache:'no-store'}).then(r=>r.json() as Promise<{available?:boolean;model?:string}>).then(v=>{setAvailable(!!v.available);setModel(v.model||'')}).catch(()=>setAvailable(false)).finally(()=>setChecking(false))},[]);
 async function ask(e:React.FormEvent){e.preventDefault();setBusy(true);setError('');setAnswer('');setDataUrl('');try{const r=await fetch('/api/agent',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({question})});const v=await r.json() as {error?:string;answer:string;dataUrl:string;query:{tool:string}};if(!r.ok)throw Error(v.error||'The research agent is unavailable.');setAnswer(v.answer);setDataUrl(v.dataUrl);setUsed(v.query.tool)}catch(e){setError(e instanceof Error?e.message:'Unable to answer')}finally{setBusy(false)}}
 return <section className="od-agent"><div><span className="oa-kicker">RESEARCH ASSISTANT</span><h2>Ask the evidence a question.</h2><p>The assistant selects a read-only data tool, checks its response and answers with the year, geography and measurement basis. Open the underlying JSON to verify the result.</p><p className="od-small">{checking?'Checking model…':available?`Remote open-weight model: ${model}`:'The remote model is not connected yet. The query console below works without it.'}</p></div><div>{!checking&&!available?<div className="od-agent-alternative"><p>Start with a source-backed query now. The example follows BC glass from the known end market back to its unresolved origin.</p><a className="oa-button" href="#data-query-console">Open the BC glass query <ArrowUpRight size={16}/></a></div>:<form onSubmit={ask}><label htmlFor="od-agent-question">Your question</label><textarea id="od-agent-question" value={question} onChange={e=>setQuestion(e.target.value)} maxLength={600} rows={4} disabled={!available||busy} placeholder="Ask about a country, material, waste measure or coordinate…"/><button className="oa-button" type="submit" disabled={!available||busy||question.trim().length<5}><Send size={16}/>{busy?'Checking the records…':'Ask'}</button></form>}{error&&<p role="alert">{error}</p>}{answer&&<div className="od-agent-answer" role="status"><span>ANSWER · {used}</span><p>{answer}</p>{dataUrl&&<a href={dataUrl} target="_blank" rel="noreferrer">Open the evidence <ArrowUpRight size={15}/></a>}</div>}</div></section>
}
