'use client';
import {ArrowRight,ArrowUpRight,ExternalLink,Factory,MapPin} from 'lucide-react';
import {Sheet,SheetContent,SheetTitle,SheetDescription} from '@/components/ui/sheet';
import {Select,SelectContent,SelectItem,SelectTrigger,SelectValue} from '@/components/ui/select';
import {references,facilities,colours,endMarketLabels,type Facility} from './data';
import {number} from '../world/model';
export {number};
export function compact(n:number){const magnitude=Math.abs(n);return magnitude>=1e9?number(n/1e9,2)+'bn':magnitude>=1e6?number(n/1e6,2)+'m':magnitude>=1e3?number(n/1e3,1)+'k':number(n,2)}

export function Refs({ids}:{ids:string[]}){return <div className="oa-refs">{[...new Set(ids)].map(id=>references.find(s=>s.id===id)).filter(Boolean).map(s=><a key={s!.id} href={s!.url} target="_blank" rel="noreferrer" title={s!.title}>{s!.publisher}{s!.year?' · '+s!.year:''}<ArrowUpRight size={13}/></a>)}</div>}
export function Choice({label,value,onChange,options}:{label:string;value:string;onChange:(v:string)=>void;options:{id:string;name:string}[]}){return <label className="oa-choice"><span>{label}</span><Select value={value} onValueChange={onChange}><SelectTrigger aria-label={label}><SelectValue/></SelectTrigger><SelectContent className="oa-select">{options.map(o=><SelectItem key={o.id} value={o.id}>{o.name}</SelectItem>)}</SelectContent></Select></label>}
export function Empty({title,children}:{title:string;children:React.ReactNode}){return <div className="oa-empty"><h3>{title}</h3><p>{children}</p></div>}
export function Loading(){return <div role="status" className="oa-loading"><span/>Loading the published records…</div>}
export function ErrorState({message}:{message:string}){return <div className="oa-empty" role="alert"><h3>The records could not load</h3><p>{message}</p><button className="oa-button" onClick={()=>location.reload()}>Try again</button></div>}
export function MarketBar({values,compact=false}:{values:(number|null)[];compact?:boolean}){return <div className={'oa-markets '+(compact?'compact':'')}><div className="oa-market-bar" role="img" aria-label={values.map((n,i)=>endMarketLabels[i]+': '+(n===null?'not separately reported':n+'%')).join('; ')}>{values.map((n,i)=>n!==null&&n>0?<span key={i} style={{width:n+'%',background:colours[i]}} title={endMarketLabels[i]+' '+n+'%'}/>:null)}</div><div className="oa-market-key">{values.map((n,i)=>n!==null?<div key={i}><i style={{background:colours[i]}}/><span>{endMarketLabels[i]}</span><strong>{n}%</strong></div>:null)}</div></div>}
export function FacilityCard({facility,onOpen}:{facility:Facility;onOpen:(f:Facility)=>void}){return <button className="oa-facility-card" onClick={()=>onOpen(facility)}><span className="oa-facility-type"><Factory size={16}/>{facility.kind}{facility.year?' · '+facility.year:''}</span><h3>{facility.name}</h3><p><MapPin size={14}/>{facility.place}</p><div><span>{facility.input}</span><ArrowRight size={15}/><strong>{facility.output}</strong></div><span className="oa-text-link">Inspect operation<ArrowUpRight size={16}/></span></button>}
export function FacilitySheet({facility,onChange}:{facility:Facility|null;onChange:(f:Facility|null)=>void}){return <Sheet open={!!facility} onOpenChange={o=>{if(!o)onChange(null)}}><SheetContent className="oa-sheet"><SheetTitle>{facility?.name||'Operation'}</SheetTitle><SheetDescription>{facility?.place} · {facility?.kind}</SheetDescription>{facility&&<><span className="oa-tag">Operator or program evidence{facility.year?' · '+facility.year:''}</span><p className="oa-sheet-lead">{facility.detail}</p><div className="oa-io vertical"><div><span>What comes in</span><h3>{facility.input}</h3></div><ArrowRight size={20}/><div><span>What comes out</span><h3>{facility.output}</h3></div></div><div className="oa-residue"><span>Other outputs & limits</span><p>{facility.residue}</p></div>{facility.next&&<section><h3>The next documented step</h3>{facility.nextId?<button className="oa-button" onClick={()=>onChange(facilities.find(f=>f.id===facility.nextId)!)}>{facility.next}<ArrowRight size={17}/></button>:<p>{facility.next}</p>}</section>}<h3>Source records</h3>{facility.refs.map(id=>references.find(r=>r.id===id)).filter(Boolean).map(s=><a className="oa-source-row" href={s!.url} key={s!.id} target="_blank" rel="noreferrer"><span><strong>{s!.title}</strong><small>{s!.publisher} · {s!.year||'Undated operator guidance'}{s!.retrievedAt?' · checked '+s!.retrievedAt.slice(0,10):''}</small>{s!.coverage&&<p>{s!.coverage}</p>}</span><ExternalLink size={17}/></a>)}</>}</SheetContent></Sheet>}
export function exportCSV(rows:Record<string,unknown>[],name:string){if(!rows.length)return;const keys=[...new Set(rows.flatMap(r=>Object.keys(r)))];const lines=[keys,...rows.map(r=>keys.map(k=>{const v=r[k];return typeof v==='object'?JSON.stringify(v):String(v??'')}))];const csv=lines.map(r=>r.map(v=>'"'+String(v).replaceAll('"','""')+'"').join(',')).join('\r\n');const url=URL.createObjectURL(new Blob([csv],{type:'text/csv;charset=utf-8;'}));const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}
