import local from '@/packages/overshoot-data/release7/local-evidence.json';

export type Reference={id:string;title:string;publisher:string;url:string;year:number|null;retrievedAt?:string;coverage?:string};
export const references:Reference[]=[
 ...local.sources,
 {id:'bc-disposal',title:'Municipal solid waste disposal, 1990–2024',publisher:'Government of British Columbia',url:'https://www.env.gov.bc.ca/soe/indicators/sustainability/municipal-solid-waste.html',year:2024,retrievedAt:'2026-09-21',coverage:'27 reporting areas; original tonnes, population and kg/person. Population-adjustment method changed in 2024.'},
 {id:'bc-boundaries',title:'Regional district boundaries, road centreline aligned',publisher:'BC Data Catalogue',url:'https://catalogue.data.gov.bc.ca/dataset/b66ed992-16c9-4527-b363-0ae4827d103b',year:null,retrievedAt:'2026-09-21',coverage:'Official polygons simplified for display; excludes Northern Rockies municipality and unincorporated Stikine.'},
 {id:'basel',title:'Basel Convention national waste-movement reports',publisher:'Basel Convention Secretariat',url:'https://www.basel.int/Countries/NationalReporting/NationalReports/BC2024Reports/tabid/10394/Default.aspx',year:2024,retrievedAt:'2026-09-19',coverage:'17,314 valid export-report sections across 2023–2024; 103 reporting countries across both years. Intended operations, not verified treatment.'},
 {id:'basel-codes',title:'Basel Convention annexes: waste categories and operations',publisher:'Basel Convention Secretariat',url:'https://www.basel.int/TheConvention/Overview/TextoftheConvention/tabid/1275/Default.aspx',year:null,retrievedAt:'2026-09-21',coverage:'Short explanations of retained waste codes. Historic 2023–2024 reports retain their original e-waste classification; no retrospective reclassification.'},
 {id:'basel-manual',title:'Manual for completing national reports',publisher:'Basel Convention Secretariat',url:'https://www.basel.int/Portals/4/download.aspx?d=UNEP-CHW-NationalReporting-Manual-2025.English.docx',year:2025,coverage:'Reporting units, Table 4 exports, classification and data-entry instructions.'},
 {id:'oecd-plastics',title:'Global Plastics Outlook: Economic Drivers, Environmental Impacts and Policy Options',publisher:'OECD',url:'https://www.oecd.org/en/publications/global-plastics-outlook_de747aef-en.html',year:2022,coverage:'2019 modeled plastic-waste fates, including ultimate recycling after process losses. World, Canada and United States.'},
 {id:'hartland-tonnage',title:'Hartland landfill tonnage report, December 2025',publisher:'Capital Regional District',url:'https://www.crd.ca/media/file/crd-hartland-tonnage-report-december2025pdf',year:2025,retrievedAt:'2026-09-21',coverage:'2021–2025 disposal excluding blended biosolids; separate population methodology and projected 2025 population.'},
 {id:'statcan-bc',title:'Canadian International Merchandise Trade: domestic exports',publisher:'Statistics Canada',url:'https://open.canada.ca/data/en/dataset/2909a648-5753-4924-878a-b069392d9cde',year:2024,coverage:'British Columbia province of production; HS6 products, foreign partners, native quantities and Canadian-dollar values'},
 {id:'hvc',title:'Highland Valley Copper operations and results',publisher:'Teck',url:'https://www.teck.com/operations/canada/operations/highland-valley-copper/',year:2025,retrievedAt:'2026-09-21',coverage:'Mine process, overseas concentrate markets, reported copper production'},
 {id:'ashcroft',title:'Concentrate transport to Ashcroft',publisher:'Teck',url:'https://www.teck.com/news/news-releases/2022/teck-to-pilot-electric-transport-truck-at-highland-valley-copper-operations',year:2022,retrievedAt:'2026-09-21',coverage:'Named mine-to-rail-terminal connection; electric-truck pilot announcement'},
 {id:'horne',title:'Horne smelting operations',publisher:'Glencore Canada',url:'https://www.glencore.ca/en/horne/ce-que-nous-faisons/nos-operations',year:null,retrievedAt:'2026-09-21',coverage:'Inputs, copper anodes, by-products and Horne-to-CCR connection'},
 {id:'copper-process',title:'From concentrate to finished product',publisher:'Glencore Canada',url:'https://www.glencore.ca/en/horne/ce-que-nous-faisons/du-concentre-au-produit-fini',year:null,retrievedAt:'2026-09-21',coverage:'Smelting, electrorefining and precious-metal recovery'},
 {id:'copper-usgs',title:'Copper statistics and information',publisher:'US Geological Survey',url:'https://www.usgs.gov/centers/national-minerals-information-center/copper-statistics-and-information',year:null,retrievedAt:'2026-09-21'},
 {id:'epa-recycling',title:'Common recyclables',publisher:'US EPA',url:'https://www.epa.gov/recycle/how-do-i-recycle-common-recyclables',year:null,retrievedAt:'2026-09-21',coverage:'General material recovery guidance; local collection rules vary'},
 {id:'epa-construction',title:'Construction and demolition materials',publisher:'US EPA',url:'https://www.epa.gov/smm/sustainable-management-construction-and-demolition-materials',year:null,retrievedAt:'2026-09-21',coverage:'Construction reuse and material recovery'},
 {id:'comtrade',title:'UN Comtrade annual trade',publisher:'United Nations',url:'https://comtradeplus.un.org/',year:2024,coverage:'Selected reporters and commodity headings; not shipment tracing'},
 {id:'climate-trace-2025',title:'Global industrial source inventory',publisher:'Climate TRACE',url:'https://climatetrace.org/data',year:2025,coverage:'Selected point-source sectors; glass source locations are not a complete census or a supplier register'},
 {id:'statcan-cimt-imports',title:'Canadian International Merchandise Trade Web Application',publisher:'Statistics Canada',url:'https://www150.statcan.gc.ca/n1/pub/71-607-x/71-607-x2021004-eng.htm',year:null,coverage:'Search import commodities and province or territory; this app has not yet acquired BC glass import records'},
 {id:'encorp2025',title:'2025 deposits, refunds, recovery and refillable milk reporting',publisher:'Encorp Pacific (Return-It)',url:'https://ar.return-it.ca/ar2025/deposits-refunds-recovery.html',year:2025,retrievedAt:'2026-09-25',coverage:'Deposit beverage glass counts, estimated mass, 28 regional entries and separate dairy-reported milk bottle return loop'},
 {id:'encorpFate2025',title:'2025 beverage-container recycling end fate',publisher:'Encorp Pacific (Return-It)',url:'https://ar.return-it.ca/ar2025/environmental-impact.html',year:2025,retrievedAt:'2026-09-25',coverage:'BC recycler and described subsequent glass uses; no branch weights or facility name'},
 {id:'encorpCollection2025',title:'2025 collection, transportation and processing map',publisher:'Encorp Pacific (Return-It)',url:'https://ar.return-it.ca/ar2025/collection-system.html',year:2025,retrievedAt:'2026-09-25',coverage:'Program map explicitly excludes glass; cannot establish glass transport paths'},
 {id:'irp',title:'Global Material Flows Database',publisher:'UNEP International Resource Panel',url:'https://www.resourcepanel.org/global-material-flows-database',year:2024,coverage:'National material accounts; later observations may be source estimates'},
 {id:'eurostat-treatment',title:'Waste treatment by operation',publisher:'Eurostat',url:'https://ec.europa.eu/eurostat/databrowser/view/env_wastrt/default/table?lang=en',year:2022,coverage:'Treatment inside each reporting country, including imports and excluding exports'},
 {id:'eurostat-weee',title:'Waste electrical and electronic equipment',publisher:'Eurostat',url:'https://ec.europa.eu/eurostat/databrowser/view/env_waseleeos/default/table?lang=en',year:2023,coverage:'Treatment locations of separately collected electronics; years vary'},
];

export type Step={title:string;input:string;process:string;output:string;residue:string;refs:string[];facilities?:string[]};
export type Profile={id:string;name:string;object:string;symbol:string;color:string;aliases:string;intro:string;origin:string;point:string;codes:string[];waste?:string;steps:Step[];questions:{q:string;a:string;refs:string[]}[]};
const step=(title:string,input:string,process:string,output:string,residue:string,refs:string[],facilities?:string[]):Step=>({title,input,process,output,residue,refs,facilities});
export const profiles:Profile[]=[
 {id:'paper',name:'Paper & cardboard',object:'A cardboard box',symbol:'Pp',color:'#19704d',aliases:'box cartons newspaper paper packaging',intro:'Wood fibres can move through several products. Collection, pulping and making a new box are separate operations.',origin:'Wood fibres from trees, plus fibres recovered from used paper.',point:'Most of BC’s recovered paper end markets are outside the province.',codes:['4707'],waste:'paper',steps:[
  step('Fibre','Trees and recovered paper','Wood or recovered paper supplies the fibres used in papermaking. A box can contain a mixture of new and recycled fibre.','Pulp for paper production','Wood residues and process water depend on the pulping method.',['epa-recycling','rbcPaper']),
  step('Make & use','Pulp, water and other papermaking inputs','Fibres are formed into sheets and dried. Corrugated board combines flat sheets with a fluted layer.','Boxes, cartons and paper products','Trimmings can return to the mill; product coatings affect later recovery.',['rbcPaper']),
  step('Collect','Used household paper and packaging','Accepted paper is kept in its collection stream. On Salt Spring, the Rainbow Road depot is a documented collection point.','Material ready for sorting','Food contamination and unaccepted items may be rejected.',['saltDepot','saltMaterials'],['rainbow']),
  step('Sort & bale','Collected paper and packaging','Sorting separates grades and removes unwanted material. Bales make recovered fibre practical to store, sell and transport.','Bales sent to paper makers','Sorting rejects require another treatment or disposal route.',['rbcPost','rbcReport2025'],['gfl','urban']),
  step('Repulp & remake','Recovered paper bales','A mill separates the fibres in water, cleans the pulp and uses suitable fibre in new products.','Paper products such as boxes, egg cartons and drywall paper','Unusable fibre, contaminants and treatment residues remain. No local mass yield is reported here.',['rbcPaper','rbcPost'])
 ],questions:[{q:'Does “recycled” mean it becomes another box?',a:'Recovered paper has several possible uses. The BC program lists new packaging, egg cartons, insulation and drywall paper. Its report does not assign a particular collected box to a particular new product.',refs:['rbcPaper']},{q:'Why does the paper leave BC?',a:'A collection system supplies recovered fibre to paper-making markets. Sorting can happen in BC while the mill using the fibre is elsewhere. The end-market table describes that geographic split.',refs:['rbcPost','rbcReport2025']}]},
 {id:'plastic',name:'Plastic packaging',object:'A plastic container',symbol:'PET',color:'#8755ad',aliases:'bottle tub yogurt container film bags packaging PET HDPE PP',intro:'“Plastic” covers different polymers. They must be separated into usable feedstocks before another manufacturer can use them.',origin:'Most conventional plastics start with fossil-derived chemical feedstocks; recovered plastic can also supply a manufacturer.',point:'99.5% of the program’s plastic end markets were in BC in 2025.',codes:['3915'],waste:'plastic',steps:[
  step('Make resin','Chemical feedstocks or recovered polymer','Polymer production makes the material that is shaped into packaging. PET, HDPE and PP are different materials.','Resin for manufacturing','Energy use and production residues sit upstream of the finished container.',['epa-recycling']),
  step('Shape & use','Resin and additives','Manufacturers mould or form packaging. Polymer type, colour and added layers affect how it can be recovered.','Containers, bottles and flexible packaging','A recycling symbol alone does not establish local acceptance.',['epa-recycling','rbcPlastic']),
  step('Collect separately','Accepted empty packaging','Local programs collect accepted material. Some packaging needs a depot stream rather than a mixed curbside bin.','Separated collection streams','Wrong items and contamination interfere with recovery.',['saltMaterials','rbcPlastic'],['rainbow']),
  step('Sort & reprocess','Collected plastic packaging','Sorting separates materials. Recycling prepares recovered plastic as feedstock for manufacturers. Recycle BC names Merlin as its primary plastics recycler.','Plastic pellets for new packaging and products','The program does not publish a bale-to-pellet yield in the evidence used here.',['rbcPost','rbcPlastic'],['gfl','urban','merlin']),
  step('Manufacture again','Recovered plastic pellets','A manufacturer uses the feedstock in another product. The output depends on the material specification and buyer.','New packaging or other plastic products','A named final product for an individual household item is not documented.',['rbcPlastic'])
 ],questions:[{q:'Does 99.5% mean almost all plastic gets recycled?',a:'No. This number describes the location of reported recycling end markets. It is not the share of all plastic sold, discarded or collected that became a new product.',refs:['rbcReport2025']},{q:'Do plastic chairs follow the same route?',a:'Not necessarily. Hartland describes some bulky rigid plastics being ground with wood for landfill cover. That is a different use from producing resin for new packaging.',refs:['hartlandDepot']}]},
 {id:'copper',name:'Copper',object:'Copper wire',symbol:'Cu',color:'#b85226',aliases:'cable wiring pipe motor copper ore concentrate scrap cathode',intro:'Copper moves as ore, concentrate, anodes, cathodes, wire and scrap. Each has a different composition, process and trade network.',origin:'Copper-bearing rock, and copper recovered from used products and industrial scrap.',point:'A mine and a wire factory do not handle the same material.',codes:['2603','7401','7402','7403','7408','7404'],steps:[
  step('Mine & concentrate','Copper-bearing rock','Crushing, grinding and flotation concentrate copper minerals. Highland Valley Copper reports producing copper and molybdenum concentrates.','Concentrate sold to smelters','The remaining rock and tailings do not travel with all of the recovered copper.',['hvc'],['hvc']),
  step('Smelt','Copper concentrates and suitable recycled feed','At Horne, smelting and converting produce copper that is cast into anodes. Recycled inputs can enter this industrial route.','Copper anodes, reported as 99.1% pure','The operation also handles slag and sulfur-bearing streams; sulfuric acid is a reported co-product.',['horne'],['horne']),
  step('Refine','Copper anodes','At CCR, electrorefining transfers copper onto cathodes. Some other elements collect in anode slimes and are processed separately.','Cathodes reported as 99.99% pure','Precious-metal recovery is a separate output path. Purity is not a recycling yield.',['copper-process'],['ccr']),
  step('Make & use','Refined copper and suitable scrap','Fabricators make wire, tube and other copper products. Copper remains in use in buildings, equipment and electrical systems.','Long-lived products and manufacturing scrap','Copper installed in a building is a material stock, not immediate waste.',['copper-usgs']),
  step('Recover','Old copper products and industrial scrap','Collection, sorting and preparation determine which scrap can be remelted or sent through further smelting and refining.','Copper feedstock for another production cycle','Mixed materials and contamination affect recovery; a trade declaration is not a recovery rate.',['horne','copper-usgs'])
 ],questions:[{q:'Why are there several copper trade categories?',a:'Ore and concentrate, unrefined metal, refined metal, wire and scrap are different traded goods. Compare the same form and reporting basis. Do not add successive border crossings into one copper-supply total.',refs:['comtrade']},{q:'Can you trace this wire back to a mine?',a:'Not from country trade statistics alone. Here you can inspect documented industrial connections and each country’s trade separately. A product-level trace would need its manufacturer and chain-of-custody records.',refs:['comtrade','hvc']}]},
 {id:'aluminium',name:'Aluminium',object:'An aluminium can',symbol:'Al',color:'#466f7a',aliases:'aluminum foil soda can window frame',intro:'New aluminium begins with mineral extraction. Used aluminium can become metal feedstock again when it is collected and separated.',origin:'Bauxite-derived alumina for primary metal; recovered aluminium for secondary metal.',point:'BC’s metal-packaging end markets were entirely in Canada in 2025.',codes:['7602','7601','2606'],waste:'metal',steps:[
  step('Primary metal','Bauxite-derived alumina','Primary aluminium production extracts the metal from alumina. This is distinct from remelting existing metal.','Aluminium for fabrication','Mining and refining leave residues upstream.',['epa-recycling']),
  step('Form & use','Aluminium metal','Metal is formed into packaging, frames and many other products. Beverage-deposit systems and packaging programs have different scopes.','Aluminium products','Manufacturing scrap can enter recovery before a product is used.',['rbcContainers']),
  step('Collect','Accepted metal packaging','Collection must match the relevant local program. The figures here describe Recycle BC packaging, not every aluminium product.','Separated metal packaging','Unaccepted materials need their own collection route.',['saltMaterials','rbcReport2025'],['rainbow']),
  step('Separate & remelt','Recovered metal','Sorting provides feedstock for metal recycling. Aluminium is separated from other materials before manufacturing again.','Metal feedstock','Contaminants and process residues still require management.',['rbcPost','epa-recycling'],['gfl','urban']),
  step('Use again','Recycled aluminium','Possible products include containers, signs and frames. The program does not identify each receiving mill.','New metal products','The exact product and yield for a particular shipment are unknown.',['rbcContainers'])
 ],questions:[{q:'Are the metal percentages aluminium-only?',a:'No. Recycle BC reports metal packaging as a group. The 81.6% BC and 18.4% elsewhere-in-Canada allocation must not be presented as an aluminium-only measurement.',refs:['rbcReport2025']}]},
 {id:'steel',name:'Iron & steel',object:'A steel can',symbol:'Fe',color:'#58616a',aliases:'iron steel tin can tool car beam',intro:'Iron ore and scrap both feed steelmaking. A food can, a car and a building beam can have very different collection routes and lifetimes.',origin:'Iron-bearing ores and recovered ferrous scrap.',point:'The life of the product determines when steel returns as scrap.',codes:['2601','7204','7208'],waste:'metal',steps:[
  step('Source metal','Iron ore or ferrous scrap','Steelmaking routes use ore-based iron, scrap, or combinations of these feedstocks.','Metal for steelmaking','Ore processing and steelmaking generate different residue streams.',['epa-recycling']),
  step('Make & use','Steel','Steel is shaped into products such as cans, vehicles and structural components.','Products in use','A building can retain its steel for decades before demolition.',['epa-construction']),
  step('Collect','Discarded products','Packaging collection, vehicle dismantling and building deconstruction are different systems.','Material prepared for separation','A local packaging result does not describe all industrial steel.',['rbcContainers','epa-construction']),
  step('Separate','Mixed scrap','Ferrous materials are separated and graded so they can become useful steelmaking feedstock.','Graded ferrous scrap','Other materials and contaminants need separate treatment.',['epa-recycling']),
  step('Return to production','Prepared scrap','Scrap re-enters metal production. The scrap trade identifies border crossings, not the receiving steelworks in every case.','Steel for new products','Source data here do not establish a closed loop for an individual item.',['comtrade','epa-recycling'])
 ],questions:[{q:'Is a scrap export proof that it was recycled?',a:'It establishes a reported cross-border trade in the scrap category. The receiving plant, actual treatment and residual disposal require additional evidence.',refs:['comtrade']}]},
 {id:'glass',name:'Glass',object:'A glass jar',symbol:'Gl',color:'#19827a',aliases:'jar glass bottle broken glass',intro:'Glass collection depends on the type of glass and the program. Packaging glass should not be mixed indiscriminately with ceramics or other glass products.',origin:'Mineral inputs and recovered glass.',point:'All reported Recycle BC glass end markets were in BC in 2025.',codes:['7001'],waste:'glass',steps:[
  step('Make glass','Mineral inputs and suitable recovered glass','Raw materials and recovered glass supply glassmaking. Different glass products can have incompatible compositions.','Glass for forming','Not all glass is suitable for the same furnace feed.',['epa-recycling']),
  step('Form & use','Molten glass','Manufacturers form containers and other glass products. Reuse can extend a container’s life before material recovery.','Glass products','Packaging and non-packaging products follow different systems.',['epa-recycling']),
  step('Collect separately','Accepted jars and packaging','Keeping glass separate prevents broken pieces contaminating paper and other streams.','A separate glass stream','Ceramics, drinking glasses and other products may not be accepted.',['rbcGlass','saltMaterials'],['rainbow']),
  step('Clean & prepare','Collected glass','Recyclers remove unwanted material and prepare usable glass for its next market.','Prepared recovered glass','Contaminants and unusable fractions remain.',['rbcGlass','rbcPost']),
  step('Find the next use','Prepared recovered glass','The BC program reports the geographic end market but does not identify every final factory or product in this snapshot.','Reported BC end markets','A 100% BC allocation is not a 100% collection or recycling rate.',['rbcReport2025'])
 ],questions:[{q:'Does the figure include all beverage bottles?',a:'These figures concern Recycle BC’s packaging-and-paper program. Beverage-deposit systems have separate reporting and should not be silently combined.',refs:['rbcReport2025','rbcGlass']}]},
 {id:'electronics',name:'Electronics',object:'An old computer',symbol:'Ee',color:'#7952a5',aliases:'phone laptop computer television electronics circuit board',intro:'A device splits into many materials. Dismantling and shredding are preparation stages; metals still need downstream recovery.',origin:'Metals, polymers, glass and other components from several supply chains.',point:'A computer does not become one recycled material.',codes:['8549'],waste:'electronics',steps:[
  step('Many inputs','Metals, plastics, glass and components','Manufacturing brings several material supply chains into one device. Some materials occur in very small amounts.','Electrical and electronic equipment','Manufacturing and extraction create upstream residues.',['epraFAQ']),
  step('Use & repair','Working equipment','Repair and reuse can keep a device performing its original function before material recovery.','Equipment kept in use','Unusable devices require a suitable collection route.',['epa-recycling']),
  step('Collect & dismantle','Accepted end-of-life equipment','Approved processors dismantle devices and separate components requiring special handling.','Prepared components and material fractions','Some fractions need specialized downstream treatment.',['epraFAQ','epra2025'],['ecycle','fcm','hitech']),
  step('Separate & recover','Metal-rich and other fractions','Material fractions move to downstream processors. Smelters can recover metals from suitable electronic scrap.','Recovered metals and other usable fractions','A fraction sent for further processing is not yet a measured final recycled output.',['epraFAQ','horne'],['horne']),
  step('Refine & reuse','Recovered metal streams','Further refining can produce material suitable for another manufacturing cycle. Horne-to-CCR is one documented copper-processing chain.','Refined copper and other recovered metals','The EPRA records do not establish a shipment from a particular BC device to Horne.',['copper-process','epra2025'],['ccr'])
 ],questions:[{q:'What does “sent for further processing” mean?',a:'It means material left a primary processor for another treatment stage. It does not prove that every tonne became a finished recycled material.',refs:['epra2025']}]},
 {id:'food',name:'Food & organics',object:'Food scraps',symbol:'Org',color:'#778929',aliases:'compost food scraps organics kitchen crops wheat',intro:'Organic matter can return to soil, become gas, or enter disposal. Collection and treatment choices determine the route.',origin:'Crops, livestock and other biological production systems.',point:'Food scraps change chemically; their mass does not simply disappear.',codes:['1001'],waste:'food',steps:[
  step('Grow','Biological production','Food draws on biological materials and agricultural systems. Harvested crops are one part of the material flow.','Food and agricultural products','Crop residues and losses occur before consumption.',['organics']),
  step('Use','Food','Preventing avoidable waste retains the value of the food and all its upstream inputs.','Food consumed or redistributed','Peels, inedible fractions and spoiled food remain.',['organics']),
  step('Separate','Food scraps','Separate organics collection keeps suitable biodegradable material out of mixed garbage.','Feedstock for biological treatment','Packaging and other contaminants must be removed.',['organics']),
  step('Biological treatment','Separated organic matter','Composting produces a soil amendment. Anaerobic treatment can produce biogas and digestate; the local treatment must be verified.','Compost, or outputs of another documented treatment','Biological processes release gases and require control of moisture and residues.',['organics']),
  step('Return or dispose','Treatment outputs','Useful compost can return organic matter to soil. Organic matter buried in landfill can generate gas and leachate.','Soil amendment or landfill outputs','The source does not assign Salt Spring scraps to a named composter.',['organics','hartlandProcess'])
 ],questions:[{q:'Is landfill-gas recovery the same as composting?',a:'No. Hartland captures some gas after waste has been buried. Composting is a separate management route for suitable organic material.',refs:['organics','hartlandProcess']}]},
 {id:'concrete',name:'Concrete & minerals',object:'A building',symbol:'Ca',color:'#967c55',aliases:'concrete cement sand gravel aggregate road construction demolition building',intro:'Much of the material around us stays in buildings and roads. Demolition creates a different flow years after construction.',origin:'Sand, gravel and crushed stone, with cement and water in concrete.',point:'A building is a store of material before it becomes a waste stream.',codes:['2523','2517'],steps:[
  step('Extract','Mineral deposits','Quarrying supplies aggregates and raw materials for cement production. These are different products and processes.','Mineral feedstocks','Extraction changes land and leaves material outside the saleable product.',['epa-construction']),
  step('Build','Cement, aggregates, water and other materials','Construction combines materials into infrastructure. Concrete and reinforcing steel are distinct recoverable streams.','Buildings, roads and structures','Construction generates offcuts, spoil and other residues.',['epa-construction']),
  step('Stay in use','Structures','Repair and longer use retain the material already in place. Annual waste figures do not count everything still standing.','Material stock in service','Future removal depends on the structure’s lifetime.',['epa-construction']),
  step('Deconstruct','Buildings and infrastructure at end of use','Selective removal and separation can preserve components and improve the quality of recovered materials.','Separated demolition materials','Mixed and contaminated fractions are harder to recover.',['epa-construction']),
  step('Reuse or crush','Recovered concrete and components','Concrete can be processed into aggregate. Recovering aggregate does not reverse cement production or recreate the original building.','Recovered aggregate and reusable components','Residual material still needs treatment or disposal.',['epa-construction'])
 ],questions:[{q:'Why isn’t all the stuff visible as rubbish?',a:'A large part is still in use in structures and products. Other material is buried, burned, dispersed or recovered. “Waste generated this year” and “material accumulated over time” measure different things.',refs:['irp','epa-construction']}]},
 {id:'wood',name:'Wood',object:'Wooden furniture',symbol:'Wd',color:'#976439',aliases:'wood lumber logs timber furniture table',intro:'Wood can remain in a building or product, be reused, become another feedstock, or be burned or disposed of.',origin:'Trees; reused timber and recovered wood can also supply products.',point:'Reuse preserves a component; chipping changes its function.',codes:['4403'],steps:[
  step('Harvest','Trees','Forestry supplies logs for different product streams. The trade category shown here covers unprocessed wood.','Logs','Harvest residues are outside the log shipment.',['irp','comtrade']),
  step('Process','Logs','Sawmilling and other processing create material for construction and manufactured products.','Wood products','Bark, sawdust and offcuts can have separate uses.',['epa-construction']),
  step('Use','Timber and wood products','Wood can remain in service in buildings and furniture. Repair and reuse extend that use.','Material retained in products','Coatings and treatments affect later options.',['epa-construction']),
  step('Recover','Discarded wood','Separate reusable components and suitable material from mixed or contaminated waste.','Reusable timber or prepared feedstock','Treated or contaminated wood may need a different route.',['epa-construction']),
  step('Next use','Recovered wood','Recovery can retain components or turn suitable wood into another material. Hartland has a separately documented landfill-cover use for certain mixed inputs.','Reused products or another documented use','Landfill cover is not a new furniture product.',['epa-construction','hartlandDepot'])
 ],questions:[{q:'Is every wood shipment sustainable?',a:'A commodity trade record identifies reported goods and countries. It does not establish forest management, legality, biodiversity impacts or product certification.',refs:['comtrade']}]},
 {id:'textiles',name:'Textiles',object:'A cotton shirt',symbol:'Tx',color:'#a84f72',aliases:'shirt clothes clothing cotton polyester textile fabric',intro:'A garment may be reused, sold across borders, reprocessed into fibre, or discarded. A used-clothing export does not identify its eventual fate.',origin:'Natural fibres and manufactured fibres, sometimes blended in one textile.',point:'A second-hand export is the start of another investigation.',codes:['6309','5201','5202'],steps:[
  step('Make fibre','Natural or manufactured fibre inputs','Textile supply chains produce fibres with different properties. Blends complicate material separation.','Fibres and yarn','Upstream residues depend on the fibre and process.',['epa-recycling']),
  step('Make & use','Yarn and fabric','Fabric is made into garments and other products. Keeping an item useful delays the need for a replacement.','Textile products','Cutting waste and worn-out products enter different streams.',['epa-recycling']),
  step('Collect & grade','Used textiles','Collected items are assessed for reuse and other options. Quality and condition affect which markets can use them.','Reuse grades and other fractions','Collection alone does not establish reuse or recycling.',['comtrade']),
  step('Trade or recover','Graded used goods','The retained trade category records worn clothing. It does not split successful reuse from onward disposal in the destination.','Used goods crossing a border','Receiving-country treatment remains a separate evidence question.',['comtrade']),
  step('Next fate','Used textile products','An item may continue in use or reach treatment and disposal. Shipment-level evidence is needed to identify the actual route.','Reuse, recovered material or disposal','No final-fate percentage is inferred from customs weight.',['comtrade'])
 ],questions:[{q:'Where does a donated shirt end up?',a:'That requires the collector’s sorting and buyer records. The worn-clothing trade can identify reported country connections, but not the path of a particular donation.',refs:['comtrade']}]},
 {id:'fuels',name:'Fossil fuels',object:'Fuel in a vehicle',symbol:'C',color:'#625953',aliases:'oil coal petrol gasoline diesel gas fuel petroleum',intro:'Where oil, gas and coal are produced, used and traded. Compare physical quantities by country and follow how they change.',origin:'Geological deposits of coal, oil and gas.',point:'Burning changes the material into other substances, including gases.',codes:['2709','2710','2701'],steps:[
  step('Extract','Fossil deposits','Extraction brings fuel feedstocks into the economy. Crude oil and coal are separate trade categories.','Fossil fuel feedstocks','Extraction and preparation produce their own residues.',['irp','comtrade']),
  step('Process','Extracted feedstocks','Preparation and refining produce materials suitable for different uses. Not every fossil feedstock becomes fuel.','Fuels and other products','Processing has several output and residual streams.',['irp']),
  step('Transport','Marketable products','Products move between producers, processors and users. Customs data records borders, not every domestic movement.','Fuel delivered for use','The recorded partner can be an intermediate destination.',['comtrade']),
  step('Use','Fuel and oxygen','Combustion releases energy and converts the fuel into other substances. Much of the carbon leaves as carbon dioxide.','Energy and combustion products','Other emissions and solid residues depend on the fuel and equipment.',['irp']),
  step('Disperse or manage','Gases and other residues','Atmospheric emissions and managed residues are material destinations too. They are not a closed recycling loop for the original fuel.','Dispersed and managed outputs','The app does not infer facility emissions from customs tonnage.',['irp'])
 ],questions:[{q:'Why can’t a fuel flow be treated like copper scrap?',a:'Copper may be recovered as metal. Burning fuel changes its chemistry and disperses much of the material in gaseous products. These require different accounts.',refs:['irp']}]},
 {id:'garbage',name:'Mixed garbage',object:'A bag of rubbish',symbol:'Mx',color:'#655449',aliases:'trash garbage landfill rubbish waste bin bag',intro:'A landfill stores some materials while other fractions keep changing. Solid waste, landfill gas and contaminated water have different paths.',origin:'A mixture of discarded materials from many upstream supply chains.',point:'Burial is followed by gas, water and long-term management.',codes:[],waste:'garbage',steps:[
  step('Discard','Items no longer wanted','A mixed bin combines materials that may have had other collection options. Its composition affects what happens later.','Mixed residual waste','The route of a particular truck needs hauler evidence.',['hartland']),
  step('Receive','Delivered waste','Hartland is the CRD’s documented regional solid-waste disposal facility. Acceptance at the site does not mean every received stream is buried.','Waste allocated to the appropriate operation','Salt Spring-to-Hartland delivery is not established for every hauler.',['hartland'],['hartland']),
  step('Place & manage','Waste assigned to disposal','An engineered landfill manages deposited waste and monitors environmental conditions. Much of the material remains stored on site.','A long-lived waste deposit','The deposit can produce gas and contaminated water.',['hartlandProcess'],['hartland']),
  step('Capture gas','Gas produced within the landfill','Hartland’s collection and upgrading route supplies the FortisBC gas network through Waga Energy equipment.','Upgraded gas entering the network','The acquired source does not give a measured capture fraction.',['hartlandProcess'],['hartland']),
  step('Collect leachate','Water that has contacted waste','Hartland collects leachate in lagoons, tests it and discharges it to the sanitary sewer.','A managed liquid stream','The specific next wastewater plant is not verified in this chain.',['hartlandProcess'],['hartland'])
 ],questions:[{q:'Does recovering landfill gas make the landfill circular?',a:'It recovers one output. Other material stays buried, gas can escape, and water needs management. One recovered stream does not account for all inputs.',refs:['hartlandProcess']}]},
 {id:'rigid-plastic',name:'Bulky rigid plastics',object:'A plastic lawn chair',symbol:'PP',color:'#855581',aliases:'plastic chair toys pool bulky plastic',intro:'A bulky plastic item can have a very different route from household packaging, even when both are dropped off at one site.',origin:'Plastic shaped into durable non-packaging products.',point:'At Hartland, some bulky plastics become landfill cover.',codes:[],waste:'rigid-plastic',steps:[
  step('Make','Plastic feedstock','Manufacturing makes a durable product such as a chair or toy. It sits outside the packaging stream described by Recycle BC’s end-market percentages.','Durable plastic products','Product composition affects possible recovery routes.',['hartlandDepot']),
  step('Use','A durable plastic item','Continued use, repair and reuse retain the product’s function.','Products kept in use','Broken or unwanted items need an appropriate destination.',['epa-recycling']),
  step('Collect','Accepted rigid plastic items','Hartland’s public depot names a separate route for certain bulky plastics.','Items accepted in that stream','Local acceptance is specific to the operator and item.',['hartlandDepot'],['hartland']),
  step('Grind & mix','Bulky plastic and contaminated wood','CRD describes grinding these inputs and combining them for a landfill operation.','A prepared cover mixture','This does not make new consumer plastic products.',['hartlandDepot'],['hartland']),
  step('Cover landfill','Prepared mixture','The mixture covers the active landfill area. This is a documented use at the disposal site.','Landfill cover','The source does not provide an item-level allocation or a mass balance.',['hartlandDepot'],['hartland'])
 ],questions:[{q:'Is this the same as recycling a yogurt tub?',a:'No. Recycle BC’s packaging route supplies recycling end markets. Hartland describes a landfill-cover use for certain non-packaging rigid plastics.',refs:['hartlandDepot','rbcPlastic']}]}
];

export type Facility={id:string;name:string;place:string;region:string;country:string;kind:string;materials:string[];input:string;output:string;residue:string;detail:string;refs:string[];year:number|null;next?:string;nextId?:string};
export const facilities:Facility[]=[
 {id:'rainbow',name:'Salt Spring Recycling Depot',place:'349 Rainbow Road · Salt Spring Island',region:'BC',country:'CAN',kind:'Collection',materials:['paper','plastic','glass','aluminium','steel'],input:'Accepted residential packaging and paper',output:'Separate collected streams',residue:'Unaccepted items need another route',detail:'A documented local collection point. The acquired sources do not identify the next receiving facility for a specific island shipment.',refs:['saltDepot','saltMaterials'],year:null},
 {id:'gfl',name:'GFL Richmond sorting facility',place:'Richmond · British Columbia',region:'BC',country:'CAN',kind:'Sorting',materials:['paper','plastic','glass','aluminium','steel'],input:'Recycling arriving through the program network',output:'Sorted material and bales',residue:'Sorting rejects',detail:'Named in Recycle BC’s 2025 network. This records a dated network role, not the destination of a particular Salt Spring load.',refs:['rbcReport2025','rbcTransition'],year:2025},
 {id:'urban',name:'Urban Impact sorting facility',place:'New Westminster · British Columbia',region:'BC',country:'CAN',kind:'Sorting',materials:['paper','plastic','glass','aluminium','steel'],input:'Material from the recycling network',output:'Sorted material and bales',residue:'Sorting rejects',detail:'Named in the 2025 program network. Read the 2026 transition source before treating the older network as a current shipment map.',refs:['rbcReport2025','rbcTransition'],year:2025},
 {id:'merlin',name:'Merlin Plastics',place:'British Columbia · operator network',region:'BC',country:'CAN',kind:'Reprocessing',materials:['plastic'],input:'Plastic packaging feedstock',output:'Plastic pellets for manufacturers',residue:'Plant-level yields are not acquired',detail:'Recycle BC identifies Merlin as its primary plastics recycler. This record concerns the operator relationship, not one geolocated plant or a final product brand.',refs:['rbcPlastic'],year:null},
 {id:'hartland',name:'Hartland landfill',place:'Capital Regional District · British Columbia',region:'BC',country:'CAN',kind:'Disposal',materials:['garbage','rigid-plastic','food'],input:'Waste delivered for the relevant site operation',output:'Stored waste, captured gas and managed leachate',residue:'Uncaptured gas and other releases are not quantified here',detail:'Gas is collected and upgraded for the FortisBC network. Leachate goes through lagoons and testing to the sanitary sewer. These are separate outputs, not one recycling flow.',refs:['hartland','hartlandProcess','hartlandDepot'],year:null},
 {id:'hvc',name:'Highland Valley Copper',place:'Near Logan Lake · British Columbia',region:'BC',country:'CAN',kind:'Extraction',materials:['copper'],input:'Copper- and molybdenum-bearing rock',output:'Copper and molybdenum concentrates',residue:'Tailings and other mine residues',detail:'Teck reports 127,000 tonnes of copper production in 2025. It describes grinding and flotation, with concentrates sold to overseas smelters. This figure is not gross rock or concentrate tonnage.',refs:['hvc','ashcroft'],year:2025,next:'Ashcroft rail-loading facility',nextId:'ashcroft'},
 {id:'ashcroft',name:'Ashcroft rail-loading facility',place:'Ashcroft · British Columbia',region:'BC',country:'CAN',kind:'Transfer',materials:['copper'],input:'Highland Valley copper concentrate',output:'Concentrate transferred to rail',residue:'No site material balance acquired',detail:'Teck’s 2022 transport announcement explicitly identifies the HVC-to-Ashcroft concentrate connection. It does not name the final overseas smelter.',refs:['ashcroft','hvc'],year:2022,next:'Overseas smelters; individual buyers not named'},
 {id:'horne',name:'Horne Smelter',place:'Rouyn-Noranda · Québec',region:'QC',country:'CAN',kind:'Smelting',materials:['copper','electronics'],input:'Copper concentrates and suitable recycled material',output:'Copper anodes reported as 99.1% pure',residue:'Slag and sulfur-bearing process streams; sulfuric acid is a co-product',detail:'The operator documents anode shipments by rail or truck to CCR. This is a separate case from Highland Valley; no HVC-to-Horne connection is claimed.',refs:['horne','copper-process'],year:null,next:'CCR refinery',nextId:'ccr'},
 {id:'ccr',name:'CCR refinery',place:'Montréal-Est · Québec',region:'QC',country:'CAN',kind:'Refining',materials:['copper','electronics'],input:'Copper anodes, including from Horne',output:'Copper cathodes reported as 99.99% pure',residue:'Anode slimes feed precious-metal recovery',detail:'Electrorefining separates copper from other elements. The operator also describes silver, gold and platinum/palladium recovery from the anode-slime stream.',refs:['copper-process'],year:null,next:'Metal buyers; individual product manufacturers not identified'},
 {id:'ecycle',name:'eCycle Solutions',place:'Chilliwack · British Columbia',region:'BC',country:'CAN',kind:'Electronics processing',materials:['electronics'],input:'Accepted end-of-life electronics',output:'Material fractions for downstream processing',residue:'Primary-processor output is not a final recycling yield',detail:'Listed as an approved primary processor in EPRA BC’s 2025 reporting. No shipment from a specific island device is established.',refs:['epra2025','epraFAQ'],year:2025},
 {id:'fcm',name:'FCM Recycling',place:'Delta · British Columbia',region:'BC',country:'CAN',kind:'Electronics processing',materials:['electronics'],input:'Accepted end-of-life electronics',output:'Material fractions for downstream processing',residue:'Downstream treatment and disposal must be verified separately',detail:'An approved primary processor in the 2025 BC program evidence, not proof of the final destination of every recovered fraction.',refs:['epra2025'],year:2025},
 {id:'hitech',name:'Hi-Tech Recyclers',place:'Edmonton · Alberta',region:'AB',country:'CAN',kind:'Electronics processing',materials:['electronics'],input:'Accepted end-of-life electronics',output:'Prepared material fractions',residue:'No final material balance acquired',detail:'EPRA BC’s 2025 approved-processor list includes an operation outside BC. Program geography and processing geography are not necessarily the same.',refs:['epra2025'],year:2025}
];

export const endMarkets=[
 {material:'paper',name:'Paper & cardboard',bc:6.3,canada:null,us:46.7,other:47},
 {material:'plastic',name:'Plastic packaging',bc:99.5,canada:null,us:null,other:.5},
 {material:'metal',name:'Metal packaging',bc:81.6,canada:18.4,us:null,other:null},
 {material:'glass',name:'Glass packaging',bc:100,canada:null,us:null,other:null}
];
export const colours=['#1c7154','#85b985','#d28e32','#9c6489'];
export const endMarketLabels=['British Columbia','Elsewhere in Canada','United States','Other export markets'];
export const profileById=(id:string)=>profiles.find(p=>p.id===id)||profiles[0];
export const formNames:Record<string,string>={'2603':'Copper ore & concentrate','7401':'Copper matte & cement copper','7402':'Unrefined copper','7403':'Refined copper & alloys','7404':'Copper waste & scrap','7408':'Copper wire','4707':'Recovered paper & cardboard','3915':'Plastic waste & scrap','7602':'Aluminium waste & scrap','2601':'Iron ore & concentrate','7204':'Iron & steel scrap','7001':'Glass waste & cullet','8549':'Electrical & electronic waste','1001':'Wheat & meslin','2523':'Cement','2517':'Pebbles, gravel & crushed stone','4403':'Unprocessed wood','6309':'Worn clothing','2709':'Crude oil','2701':'Coal','2710':'Refined petroleum products','2606':'Aluminium ores & concentrates','7601':'Unwrought aluminium','7208':'Flat-rolled iron & non-alloy steel, width ≥600 mm','5201':'Cotton, not carded or combed','5202':'Cotton waste'};
