'use client';
import {useMemo,useState} from 'react';
import {ArrowRight,ArrowUpRight,Check,Download,MapPin,Route} from 'lucide-react';
import {connectionsPath,modeLabels,selectNetworks,type ConnectionCatalog,type ConnectionNode} from '@/packages/material-world/connections';
import {journeyStageColors} from '@/packages/material-world/journey';
import {useMaterialArtifact} from '../material-data';
import WorldMap from '../world/WorldMap';
import type {Country,Flow,SiteFeature} from '../world/model';
import type {Profile} from './data';
import type {OpenMaterialSites} from './MaterialSitesMap';
import {ErrorState,Loading,exportCSV} from './common';
import {placeName} from './PlaceContext';
import './connections.css';

type Observation={label:string;value:number;unit:string;scope:string;source:string};
type OperatorEvidence={title:string;period:string;summary:string;observations:Observation[];qualification:string};
type ObservationCatalog={reviewedAt:string;method:string;networks:Record<string,OperatorEvidence>;sources:Record<string,{publisher:string;title:string;url:string;pages:string}>};
const observationsUrl='/data/v28/operator-observations.json';

export default function DocumentedConnections({profile,place,countries,networkId,onNetwork,onJourney,onPlace,onSites}:{profile:Profile;place:string;countries:Country[];networkId:string;onNetwork:(id:string,place:string)=>void;onJourney:()=>void;onPlace:(id:string)=>void;onSites:OpenMaterialSites}){
 const result=useMaterialArtifact<ConnectionCatalog>(connectionsPath);
 const coal=useMaterialArtifact<ConnectionCatalog>('/data/v30/coal-paths.json');
 const catalog=result.data?{...result.data,sources:[...result.data.sources,...(coal.data?.sources||[])],networks:[...(coal.data?.networks||[]),...result.data.networks]}:undefined;
 const operator=useMaterialArtifact<ObservationCatalog>(observationsUrl);
 const [selected,setSelected]=useState('');
 const [networkSearch,setNetworkSearch]=useState('');
 const country=['SSI','BC'].includes(place)?'CAN':place;
 const all=catalog?selectNetworks(catalog,profile.id):[],available=catalog?selectNetworks(catalog,profile.id,country):[];
 const network=available.find(n=>n.id===networkId)||available[0];
 const evidence=network&&operator.data?.networks[network.id];
 const nodes=network?.nodes||[],links=network?.links||[];
 const chosenLink=links.find(l=>l.id===selected)||(!nodes.some(n=>n.id===selected)?links[0]:undefined),chosenNode=nodes.find(n=>n.id===selected);
 const from=nodes.find(n=>n.id===chosenLink?.from),to=nodes.find(n=>n.id===chosenLink?.to);
 const flows=useMemo<Flow[]>(()=>links.flatMap(link=>{
  const a=nodes.find(n=>n.id===link.from),b=nodes.find(n=>n.id===link.to);if(!a?.coordinates||!b?.coordinates)return [];
  return [{id:link.id,origin:a.country,destination:b.country,originLabel:a.name,destinationLabel:b.name,amount:link.quantity||0,unit:link.quantityUnit||'Quantity not reported',year:link.quantity?2025:0,estimated:false,basis:link.scope,sourceUrl:catalog!.sources.find(s=>s.id===link.sourceIds[0])!.url,record:link,connection:{mode:modeLabels[link.mode],from:a.coordinates,to:b.coordinates,evidence:link.evidence}}];
 }),[network,catalog]);
 const sites=useMemo<SiteFeature[]>(()=>nodes.flatMap(n=>n.coordinates?[{type:'Feature',geometry:{type:'Point',coordinates:n.coordinates},properties:{id:n.id,name:n.name,type:n.stage,country:n.country,source_id:n.locationSource||'',year:null,value:null,unit:'',metric:'Source location',stage:n.stage,stageColor:journeyStageColors[n.stage as keyof typeof journeyStageColors]||'#328ca1',mapRadius:7}}]:[]),[network]);
 function choose(id:string){const n=all.find(n=>n.id===id);if(!n)return;const countries=[...new Set(n.nodes.map(n=>n.country))];setSelected('');onNetwork(id,countries.length===1?countries[0]:'WORLD')}
 function inspectNode(node:ConnectionNode){setSelected(node.id)}
 function download(){if(!network||!catalog)return;exportCSV(links.map(l=>({...l,from:nodes.find(n=>n.id===l.from)?.name,to:nodes.find(n=>n.id===l.to)?.name,sourceUrls:l.sourceIds.map(id=>catalog.sources.find(s=>s.id===id)?.url).join(' | '),reviewedAt:catalog.reviewedAt,geometryNote:network.id.startsWith('coal-')?coal.data?.geometry:catalog.geometry})),`overshoot-connections-${network.id}.csv`)}
 if(result.error)return <ErrorState message={result.error}/>;
 if(!result.data)return <Loading/>;
 return <section className="oc-connections" aria-label="Documented material connections">
  <div className="oc-heading"><div><span className="oa-kicker">WHERE THE LINKS ARE KNOWN</span><h2>Follow a documented connection.</h2><p>Trace named facilities and reported quantities. Select each step to see its source and the limits of the mapped line.</p></div><Route size={26}/></div>
  {!!all.length&&<div className="oc-picker"><label htmlFor="oc-network-search">Find a mine or plant</label><input id="oc-network-search" value={networkSearch} onChange={e=>setNetworkSearch(e.target.value)} placeholder="Search networks by plant or mine"/><label htmlFor="oc-network-select">Documented network</label><select id="oc-network-select" aria-label="Documented network" value={network?.id||''} onChange={e=>choose(e.target.value)}>{!network&&<option value="">Choose an available network</option>}{all.filter(n=>!networkSearch||n.id===network?.id||(n.title+' '+n.region+' '+n.nodes.map(node=>node.name).join(' ')).toLowerCase().includes(networkSearch.toLowerCase())).map(n=><option key={n.id} value={n.id}>{n.title} · {n.region}</option>)}</select></div>}
  {!network?<div className="oc-empty"><h3>No documented links retained for {placeName(place,countries)}.</h3><p>{all.length?'The facility layers still show available locations here. Choose a reviewed network above to examine the evidence in another place.':'The facility layers show individual locations. A supplier, buyer or transport link needs separate evidence; this material has no reviewed network in this release.'}</p><button className="oa-text-link" onClick={onJourney}>Explore stage locations <ArrowRight size={15}/></button></div>:<>
   <div className="oc-network-intro"><div><h3>{network.title}</h3><p>{network.summary}</p></div><span>{links.length} sourced {links.length===1?'link':'links'}<br/>{flows.length} mapped connections</span></div>
   {evidence&&<div className="oc-operator" aria-label="Recent operator observations"><div className="oc-operator-heading"><div><span className="oa-kicker">RECENT OPERATOR RECORD · {evidence.period}</span><h3>{evidence.title}</h3><p>{evidence.summary}</p></div><a href={observationsUrl} target="_blank" rel="noreferrer">Download data <ArrowUpRight size={15}/></a></div><div className="oc-operator-metrics">{evidence.observations.map(o=><div key={o.label}><span>{o.label}</span><strong>{new Intl.NumberFormat('en-US',{maximumFractionDigits:0}).format(o.value)}<small> {o.unit}</small></strong><p>{o.scope}</p></div>)}</div><p className="oc-operator-scope">{evidence.qualification} {Object.entries(operator.data!.sources).filter(([id])=>evidence.observations.some(o=>o.source===id)).map(([id,s])=><a key={id} href={s.url} target="_blank" rel="noreferrer">{s.publisher} · pp. {s.pages} <ArrowUpRight size={13}/></a>)}</p></div>}
   {network.generationMWh!==undefined&&<div className="oc-operator" aria-label="Coal to electricity evidence stages"><div className="oc-operator-heading"><div><span className="oa-kicker">FOUR EVIDENCE STAGES · 2025</span><h3>Mine → delivery → generation → unknown grid destination</h3><p>Named mine and plant IDs establish each delivery. EIA separately reports the plant’s annual coal generation; the records do not allocate output to a specific mine or electricity customer.</p></div><a href="https://www.eia.gov/electricity/data/eia923/index.php" target="_blank" rel="noreferrer">EIA source <ArrowUpRight size={15}/></a></div><div className="oc-operator-metrics"><div><span>Coal generation at this plant</span><strong>{new Intl.NumberFormat('en-US').format(network.generationMWh)}<small> MWh</small></strong><p>Separate plant level measure for 2025</p></div><div><span>Measured mine connections</span><strong>{links.length}</strong><p>Final 2025 receipts, aggregated by mine ID</p></div></div></div>}
   <p className="oc-map-guide"><MapPin size={16}/>Select a step or map marker to inspect the source. Lines join known endpoints schematically; they do not follow roads, rail tracks, or a vessel course.</p>
   <div className="oc-steps" role="group" aria-label="Documented connections">{links.map((l,i)=><button key={l.id} onClick={()=>setSelected(l.id)} aria-pressed={chosenLink?.id===l.id}><span className="oc-step-number">{String(i+1).padStart(2,'0')}</span><span><strong>{l.quantity!==null?nodes.find(n=>n.id===l.from)?.name+' → '+nodes.find(n=>n.id===l.to)?.name:l.materialForm}</strong><small>{l.quantity!==null?new Intl.NumberFormat('en-US').format(l.quantity)+' '+l.quantityUnit+' · ':''}{modeLabels[l.mode]}{l.geometry==='unmapped'?' · location gap':''}</small></span><Check size={15}/></button>)}</div>
   <div className="oa-map-workspace oc-workspace"><div>{sites.length?<WorldMap flows={flows} sites={sites} countries={countries} place={country} selected={chosenNode?.id||chosenLink?.id||''} onFlow={f=>setSelected(f.id)} onSite={s=>setSelected(s.properties.id)} onPlace={onPlace} color={profile.color} siteView/>:<div className="oc-no-geography"><MapPin size={28}/><h3>This connection has no mapped endpoints.</h3><p>The source names a manufacturing network and a recycler. Individual originating plants are not identified, so there is no guessed route on this map.</p></div>}<p className="oc-geometry"><Route size={14}/>{network.id.startsWith('coal-')?coal.data?.geometry:result.data.geometry}</p></div>
   <aside className="oa-map-inspector oc-inspector" aria-live="polite">{chosenNode?<><span className="oa-kicker">{chosenNode.stage} · {placeName(chosenNode.country,countries)}</span><h3>{chosenNode.name}</h3><p>{chosenNode.locationNote}</p><dl className="oa-facts"><dt>Coordinates</dt><dd>{chosenNode.coordinates?chosenNode.coordinates[1].toFixed(4)+', '+chosenNode.coordinates[0].toFixed(4):'Not retained'}</dd><dt>Location source</dt><dd>{chosenNode.locationSource||'No source point'}</dd></dl>{chosenNode.facility&&<button className="oa-button" onClick={()=>onSites({kind:chosenNode.facility!.kind,place:chosenNode.country,site:chosenNode.facility!.id})}>Inspect facility record<ArrowUpRight size={15}/></button>}{chosenNode.portId&&<a className="oa-button" href={'/materials?'+new URLSearchParams({material:profile.id,place:country,layer:'connections',network:network.id,port:chosenNode.portId,ports:'1'})}>Open monthly port activity<ArrowUpRight size={15}/></a>}<button className="oa-text-link" onClick={()=>setSelected(links[0].id)}>Back to the connection<ArrowRight size={15}/></button></>:chosenLink&&<>
    <span className="oa-kicker">{modeLabels[chosenLink.mode]} · {chosenLink.evidence==='government-reported'?'government reported':'operator reported'}</span><h3>{chosenLink.materialForm}</h3><div className="oc-endpoints"><button onClick={()=>from&&inspectNode(from)}>{from?.name}</button><ArrowRight size={18}/><button onClick={()=>to&&inspectNode(to)}>{to?.name}</button></div>
    <p>{chosenLink.claim}</p><p className="oc-period">{chosenLink.period}</p>
    <dl className="oa-facts"><dt>Quantity</dt><dd>{chosenLink.quantity===null?'Not reported for this link':new Intl.NumberFormat('en-US').format(chosenLink.quantity)+' '+chosenLink.quantityUnit}</dd><dt>Map</dt><dd>{chosenLink.geometry==='unmapped'?'Not drawn · endpoint location missing':'Schematic · sourced endpoints only'}</dd>{chosenLink.months&&<><dt>Reported months</dt><dd>{chosenLink.months.length} of 12 in 2025</dd></>}</dl>
    <p className="oa-small">{chosenLink.scope}</p><div className="oc-citations">{chosenLink.sourceIds.map(id=>{const s=catalog!.sources.find(s=>s.id===id)!;return <a key={id} href={s.url} target="_blank" rel="noreferrer"><span><strong>{s.publisher}</strong><small>{s.title}{s.publishedAt?' · '+s.publishedAt:''}</small></span><ArrowUpRight size={15}/></a>})}</div>
   </>}</aside></div>
   <div className="oc-boundary"><div><span className="oa-kicker">WHERE THE EVIDENCE STOPS</span><ul>{network.gaps.map(g=><li key={g}>{g}</li>)}</ul></div><button className="oa-button outline" onClick={download}><Download size={15}/>Export connections</button></div>
  </>}
  <details className="oa-method oc-method"><summary>Sources, locations and coverage</summary><p>{network?.id.startsWith('coal-')?coal.data?.method:result.data.method}</p><p>Reviewed {network?.id.startsWith('coal-')?coal.data?.reviewedAt:result.data.reviewedAt}. Dates describe the evidence; these are not live operating-status reports. A mapped location may represent a larger production area.</p><p>Operator text is paraphrased; no blanket open license applies to the upstream publications.</p><a href={network?.id.startsWith('coal-')?'/data/v30/coal-paths.json':connectionsPath} target="_blank" rel="noreferrer">Download the relationship catalog ↗</a>{network?.id.startsWith('coal-')&&<a href="/data/v30/coal-receipts-2025.json" target="_blank" rel="noreferrer">Download every identified-mine monthly receipt ↗</a>}</details>
 </section>;
}
