/** Interpretive copy tied to the retained material profiles and source definitions. */
export const materialGuides:Record<string,{moving:string;boundary:string;next:string;stage:number}>={
 paper:{moving:'HS 4707 is recovered paper and paperboard: material traded for another use after collection.',boundary:'This view begins with recovered fibre. It does not map the forests behind all paper products, or prove that a shipment becomes another cardboard box.',next:'See how sorting and repulping turn recovered paper into a usable fibre feedstock.',stage:4},
 plastic:{moving:'HS 3915 covers plastic waste, parings and scrap. Different polymers and levels of contamination can sit inside this broad heading.',boundary:'A destination country does not tell us whether the plastic was washed, reprocessed, burned or discarded. The receiving process matters.',next:'See why sorting by polymer and removing contamination determine what can be made next.',stage:3},
 copper:{moving:'Copper travels in several forms, from ore and concentrate to refined metal, wire and scrap. Select a form to see a different part of the chain.',boundary:'A tonne of ore is not a tonne of copper. Keep source net weight, contained-metal quantity and product purity separate.',next:'Follow the changes from concentrate to anodes and cathodes, and inspect the documented Canadian operations.',stage:2},
 aluminium:{moving:'HS 7602 covers aluminium waste and scrap, a feedstock for secondary production.',boundary:'Scrap trade describes one side of aluminium supply. It does not include the full bauxite-to-alumina-to-primary-metal chain.',next:'See how recovered aluminium is sorted and remelted, and what remains after processing.',stage:3},
 steel:{moving:'Iron ore and ferrous scrap are different inputs to steelmaking. Switching the material form changes which trade you are seeing.',boundary:'Steel in a building can stay in use for decades. This year’s traded scrap is not a measure of this year’s discarded products.',next:'Connect steelmaking inputs with the stock held in products and the scrap that eventually returns.',stage:3},
 glass:{moving:'Glass cullet is a recovered feedstock. Its suitability depends on the glass type and the contamination in the collected material.',boundary:'The retained customs snapshot does not include a glass series. Recycle BC end-market figures below provide a separate, regional observation.',next:'See why sorting glass correctly matters before cullet can become a new product.',stage:3},
 electronics:{moving:'HS 8549 covers electrical and electronic waste and scrap. A device contains several material streams that separate during treatment.',boundary:'The weight of traded equipment is not the weight of recovered copper or precious metal. A first processor is only one stage in the chain.',next:'Follow collection, dismantling and downstream refining as distinct operations.',stage:3},
 food:{moving:'The retained food-related trade series is wheat (HS 1001). It describes a food-system input, not the trade or disposal of all food waste.',boundary:'National food-waste estimates and wheat imports describe different populations of material. They cannot be added into a single journey.',next:'See the different paths through prevention, separate collection, composting and digestion.',stage:3},
 concrete:{moving:'Cement and aggregate enter construction and can remain in buildings and infrastructure for years.',boundary:'No cement or aggregate observations are retained in this customs snapshot. National non-metallic mineral extraction offers wider context.',next:'See how demolition material can become aggregate, and why this differs from reversing cement production.',stage:4},
 wood:{moving:'HS 4403 covers wood in the rough. This is an upstream product, before many transformations into buildings, furniture or paper.',boundary:'A customs declaration identifies trade, not forest-management certification or the eventual fate of a timber product.',next:'Compare reuse, material recovery, combustion and disposal after wood leaves use.',stage:4},
 textiles:{moving:'HS 6309 covers worn clothing and other worn articles. Clothing collection can lead to reuse, further sorting or disposal.',boundary:'A reported export is not proof that each donated garment was worn again. Buyers, grading and downstream destinations remain separate questions.',next:'See what happens when mixed fibres and different garment qualities reach a sorter.',stage:3},
 fuels:{moving:'Compare crude oil, refined petroleum products and coal as separate trade categories. Burning fuel changes its chemical form.',boundary:'Combustion outputs do not appear as a return shipment of solid waste. Trade weight alone cannot establish emissions at a particular facility.',next:'Follow combustion and dispersion to understand where the material goes after use.',stage:3},
 garbage:{moving:'Mixed garbage combines many materials, so there is no single commodity line that follows the whole bin.',boundary:'Municipal disposal records measure an area’s waste system. Basel reports cover specified controlled wastes; they are not a general garbage ledger.',next:'Inspect the Hartland example: deposited waste, captured gas and collected leachate follow different paths.',stage:2},
 'rigid-plastic':{moving:'The local example follows bulky rigid plastic handled at Hartland, outside the packaging-and-paper end-market figures.',boundary:'Grinding a material for landfill cover gives it a documented use, but does not establish that it became another consumer plastic product.',next:'Follow the documented handling and cover-material use, with the boundary kept visible.',stage:3}
};
