'use client';
import {useDeferredValue,useEffect,useMemo,useState,useRef} from 'react';
import {useOnChange} from '../useOnChange';
import {ArrowLeft,ArrowRight,ArrowUpRight,BookOpen,Check,ChevronLeft,ChevronRight,Copy,Database,Download,MapPin,Search,X} from 'lucide-react';
import {useMaterialArtifact} from '../material-data';
import WorldMap from '../world/WorldMap';
import type {Country,Flow,SiteFeature} from '../world/model';
import Link from 'next/link'; import {profiles} from './data';
import {ErrorState,Loading,exportCSV,number} from './common';
import {basisLabels,sourceAreaNames,facilityCatalogPath,facilityPins,type FacilityIndex,facilityKinds,kindLabels,kindQuestions,matchesFacility,measurementNote,type CountryCoverage,type FacilityKind,type FacilityCatalog,type FacilityPin,type FacilityRecord,type DataSource} from '@/packages/material-world/model';
import {materialSiteLayers} from './materialSites';
import './facilities.css';
export type SiteKind=FacilityKind|'documented';
export type SiteFilters={siteQuery:string;siteRegion:string;siteType:string;siteBasis:string;siteSource:string;siteSort:'name'|'quantity'};
export const emptySiteFilters:SiteFilters={siteQuery:'',siteRegion:'',siteType:'',siteBasis:'',siteSource:'',siteSort:'name'};
type SiteChange=Partial<SiteFilters>&{place?:string;kind?:SiteKind;site?:string};
const EMPTY_FLOWS:Flow[]=[];
const EMPTY_SITES:SiteFeature[]=[];
const EMPTY_PINS:FacilityPin[]=[];
const provinces:Record<string,string>={AB:'Alberta',BC:'British Columbia',MB:'Manitoba',NB:'New Brunswick',NL:'Newfoundland and Labrador',NS:'Nova Scotia',NT:'Northwest Territories',NU:'Nunavut',ON:'Ontario',PE:'Prince Edward Island',QC:'Québec',SK:'Saskatchewan',YT:'Yukon'};
const kindColor:Record<FacilityKind,string>={industry:'#9d6354',power:'#a48b35',landfill:'#347c5b',wastewater:'#327e91',energy:'#8c7335',mining:'#b5653c',river:'#7662a4'};
const typeNotes:Record<FacilityKind,string>={industry:'Cement, steel, aluminium, glass, paper and petrochemicals turn raw materials into the built world. Climate TRACE locates these operations and estimates their climate emissions. Activity and capacity are shown only where the source makes them available, with their original units.',power:'Installed capacity measures how much power a plant is rated to produce. Annual generation measures energy actually generated over time. This archived WRI baseline preserves both, including the distinction between reported and modeled generation.',landfill:'Collection, sorting, recovery and disposal are different steps. Canadian and US records describe waste infrastructure and reported intake; Climate TRACE adds global disposal sites with emissions estimates. Tonnes of CO₂e are not tonnes of waste handled.',wastewater:'Treatment removes pollutants before water returns to the environment. A plant’s effluent is liquid volume, not solid-waste mass. Reported flow, design capacity and modeled flow are separate. Climate TRACE adds emissions estimates; use the source filter to compare the same measure.',energy:'Oil and gas move through extraction, processing, storage and distribution. Global Climate TRACE records locate production areas and refineries, with 2025 emissions estimates. Canada’s ODI adds gathering, processing and storage infrastructure. National production and trade are available in the Fossil fuels guide.',mining:'Mining changes more than the pit: tailings, waste rock, ponds and processing areas also occupy land. Named mine records identify the commodity and estimate climate emissions. Satellite-mapped footprints describe disturbed land, including tailings and processing areas, without identifying a mineral or production quantity.',river:'These outfalls locate modeled plastic leakage to the ocean. The source model estimates annual emissions; it does not observe individual discharges or identify shipment routes.'};
function asFeature(r:FacilityPin):SiteFeature{return {type:'Feature',geometry:{type:'Point',coordinates:r.coordinates},properties:{id:r.id,name:r.name,type:r.type,country:r.country,source_id:r.source,year:r.year,value:r.value,unit:r.unit,metric:r.metric,estimated:r.basis==='modeled'||r.basis==='estimated',basis:r.basis,state:r.region}}}
function locationLabel(r:FacilityPin){return [r.locality,provinces[r.region]||r.region].filter(Boolean).join(' · ')||(r.country==='UNASSIGNED'?'Country not assigned by source':r.country)}
function basisSummary(rows:FacilityPin[]){const c=new Map<string,number>();rows.forEach(r=>c.set(r.basis,(c.get(r.basis)||0)+1));return [...c].sort((a,b)=>b[1]-a[1])}

export default function FacilitiesPage({place,kind,countries,site='',filters=emptySiteFilters,onChange}:{place:string;kind:SiteKind;countries:Country[];site?:string;filters?:SiteFilters;onChange:(p:SiteChange)=>void}){
 const catalog=useMaterialArtifact<FacilityCatalog>(facilityCatalogPath);
 const names=useMemo(()=>new Map([...countries.map(c=>[c.id,c.name] as const),...Object.entries(sourceAreaNames)]),[countries]);
 const country=['BC','SSI'].includes(place)?'CAN':place;
 const placeLabel=place==='WORLD'?'the world':place==='BC'?'British Columbia':place==='SSI'?'Salt Spring Island':names.get(place)||place;
 return <div className="fw-page">
  <div className="fw-heading"><div><span className="oa-kicker">THE PLACES BEHIND THE NUMBERS</span><h1>Facilities & footprints.</h1><p>Find a site. See what it handles, what is measured, and who reported it.</p></div><Link className="fw-data-link" href="/data"><Database size={17}/><span>{catalog.data?number(catalog.data.totalRecords,0):'…'} records<small>Open data & MCP <ArrowUpRight size={12}/></small></span></Link></div>
  <nav className="fw-layers" aria-label="Facility datasets">{facilityKinds.map(id=>{const d=catalog.data?.datasets[id];const count=country==='WORLD'?d?.count:d?.countries[country]?.count;return <button key={id} aria-pressed={kind===id} onClick={()=>onChange({...emptySiteFilters,kind:id,site:''})}><i style={{background:kindColor[id]}}/><span>{kindLabels[id]}</span><small>{count?number(count,0):'—'}</small></button>})}</nav>
  {catalog.error?<ErrorState message={catalog.error}/>:!catalog.data?<Loading/>:kind==='documented'?<div className="fw-no-results"><h2>Use source-mapped locations</h2><p>The curated operation showcase has been retired from this data view. Search the geolocated inventories or investigate a coordinate.</p><Link className="oa-button" href="/local">Open the local lens <ArrowRight size={16}/></Link></div>:<FacilityWorkspace catalog={catalog.data} kind={kind} country={country} place={place} placeLabel={placeLabel} countries={countries} names={names} site={site} filters={filters} onChange={onChange}/>}
 </div>
}
function FacilityWorkspace({catalog,kind,country,place,placeLabel,countries,names,site,filters,onChange}:{catalog:FacilityCatalog;kind:FacilityKind;country:string;place:string;placeLabel:string;countries:Country[];names:Map<string,string>;site:string;filters:SiteFilters;onChange:(p:SiteChange)=>void}){
 const dataset=catalog.datasets[kind],world=country==='WORLD',riverUnassigned=world&&kind==='river';
 const loadedCountry=country;
 const entry:CountryCoverage|undefined=world?dataset.world:dataset.countries[loadedCountry];
 const [query,setQuery]=useState(filters.siteQuery),[page,setPage]=useState(0),[showOutfall,setShowOutfall]=useState(false);
 useOnChange([site],()=>setShowOutfall(false));
 const region=filters.siteRegion||(place==='BC'?'BC':''),type=filters.siteType,basis=filters.siteBasis,sort=filters.siteSort;
 const setRegion=(v:string)=>onChange({siteRegion:v,site:'',...(place==='BC'&&!v?{place:'CAN'}:{})});const setType=(v:string)=>onChange({siteType:v,site:''});const setBasis=(v:string)=>onChange({siteBasis:v,site:''});const setSort=(v:string)=>onChange({siteSort:v as 'name'|'quantity'});
 useOnChange([filters.siteQuery],()=>setQuery(filters.siteQuery));
 useEffect(()=>{if(query===filters.siteQuery)return;const timer=setTimeout(()=>onChange({siteQuery:query,site:''}),350);return()=>clearTimeout(timer)},[query,filters.siteQuery,onChange]);
 const resultsRef=useRef<HTMLDivElement>(null);
 const search=useDeferredValue(query);
 const pinData=useMaterialArtifact<FacilityIndex>(entry?.index||null);
 const pins=useMemo(()=>pinData.data?Array.from(facilityPins(pinData.data)):EMPTY_PINS,[pinData.data]);
 const provinceSupported=!!Object.keys(entry?.regions||{}).length;
 const effectiveRegion=provinceSupported?region:'';
 const visible=useMemo(()=>{const filtered=pins.filter(r=>matchesFacility(r,{query:search,region:effectiveRegion,type,basis,source:filters.siteSource}));if(sort==='quantity'&&new Set(filtered.map(r=>[r.metric,r.unit,r.basis].join('|'))).size===1)filtered.sort((a,b)=>(b.value??-1)-(a.value??-1)||a.name.localeCompare(b.name));return filtered},[pins,search,effectiveRegion,type,basis,sort,filters.siteSource]);
 const comparableSelection=new Set(visible.map(r=>[r.metric,r.unit,r.basis].join('|'))).size===1&&visible.some(r=>r.value!==null);
 const siteFeatures=useMemo(()=>visible.map(asFeature),[visible]);
 const selected=pins.find(r=>r.id===site)||null;
 const detail=useMaterialArtifact<FacilityRecord[]>(selected?dataset.countries[selected.country]?.parts[selected.part]:null);
 const record=detail.data?.find(r=>r.id===site)||null;
 const outfall=useMemo<SiteFeature|null>(()=>{const a=record?.attributes;if(record?.source!=='hydrowaste-2022'||a?.LAT_OUT==null||a?.LON_OUT==null||a.LAT_OUT===''||a.LON_OUT==='')return null;const x=Number(a.LON_OUT),y=Number(a.LAT_OUT);if(!Number.isFinite(x)||!Number.isFinite(y)||Math.abs(x)>180||Math.abs(y)>90)return null;return {type:'Feature',geometry:{type:'Point',coordinates:[x,y]},properties:{id:record.id+'-outfall',name:'Modeled outfall · '+record.name,country:record.country,type:'Modeled wastewater outfall',source_id:record.source,value:null,unit:'',metric:'Modeled discharge location',year:null,basis:'modeled'}}},[record]);
 const features=useMemo(()=>showOutfall&&outfall?[...siteFeatures,outfall]:siteFeatures,[siteFeatures,showOutfall,outfall]);
 const summary=useMemo(()=>basisSummary(visible),[visible]);
 const countryRows=useMemo(()=>Object.entries(dataset.countries).filter(([id])=>id!=='UNASSIGNED').map(([id,v])=>({id,name:names.get(id)||id,...v})).filter(r=>r.name.toLowerCase().includes(search.toLowerCase())).sort((a,b)=>b.count-a.count),[dataset,names,search]);
 const layer=useMemo(()=>({values:new Map(countryRows.map(r=>[r.id,r.count])),label:'Source records by country',unit:'records',year:'Source dates vary',thresholds:[10,100,1000,5000]}),[countryRows]);
 const sources=(entry?.sources||[...new Set(Object.values(dataset.countries).flatMap(e=>e.sources))]).map(id=>[id,catalog.sources[id]] as const);
 const pages=Math.max(1,Math.ceil(visible.length/30));
 useOnChange([search,region,type,basis,sort,kind,place,filters.siteSource],()=>setPage(0));
 useEffect(()=>{if(resultsRef.current)resultsRef.current.scrollTop=0},[page,search,region,type,basis,sort,kind,place,filters.siteSource]);
 function open(id:string){onChange({site:id})}
 function reset(){setQuery('');onChange({...emptySiteFilters,site:''});setPage(0)}
 const loading=!!entry&&!pinData.data&&!pinData.error;
 const isCountryOverview=false;
 return <>
  <div className="fw-question"><h2>{kindQuestions[kind]}</h2><p>{world&&!riverUnassigned?`${number(dataset.count,0)} source records across ${countryRows.length} countries / areas. Search a site, choose a facility type, or select a country on the map.`:isCountryOverview?`${number(dataset.count,0)} source records · ${countryRows.length} countries / areas. Choose a country to load every retained location.`:riverUnassigned?'All 31,819 retained river outfalls are mapped worldwide. Most country assignments are unavailable; the coordinates and original estimates are preserved.':`${kindLabels[kind]} in ${placeLabel} · ${entry?number(entry.count,0):'No assigned'} source records${place==='BC'?' across Canada; province filter applied where supplied':''}.`}</p></div>
  {kind==='power'&&(!filters.siteSource||filters.siteSource==='wri-power-plants')&&<p className="fw-archive-note"><BookOpen size={15}/><span>Two different views: WRI’s archived inventory reports capacity and generation; Climate TRACE adds 2025 emissions estimates. Use the source filter to keep their boundaries separate.</span></p>}
  <div className="fw-workspace">
   <div className="fw-map-column"><WorldMap flows={EMPTY_FLOWS} sites={isCountryOverview?EMPTY_SITES:features} countries={countries} place={place==='SSI'?'CAN':place} selected={showOutfall&&outfall?outfall.properties.id:site} onFlow={()=>{}} onSite={s=>{if(s.properties.id!==outfall?.properties.id)open(s.properties.id)}} onPlace={p=>onChange({place:p,site:''})} color={kindColor[kind]} siteView countryLayer={isCountryOverview?layer:undefined}/><div className="fw-map-context"><span className="fw-live-dot"/><p>{isCountryOverview?'Country colour shows the number of source records. It does not measure the size of the industry.':loading?'Loading source locations…':'Zoom to separate nearby locations. Select a marker or a result to inspect its evidence.'}</p></div></div>
   <section className="fw-results" aria-label="Facility results">
    {selected?<><div className="fw-panel-top"><button className="fw-back" onClick={()=>open('')}><ArrowLeft size={16}/>Results</button><small>RECORD INSPECTOR</small></div><div className="fw-inspector" key={selected.id}>{detail.error?<ErrorState message={detail.error}/>:!record?<Loading/>:<RecordInspector record={record} source={catalog.sources[record.source]} kind={kind} onOutfall={outfall?()=>setShowOutfall(v=>!v):undefined} showOutfall={showOutfall}/>}</div></>:<>
     <div className="fw-search"><Search size={17}/><input aria-label={isCountryOverview?'Search countries with facility data':'Search facility records'} placeholder={isCountryOverview?'Find a country…':'Name, city, facility type…'} value={query} onChange={e=>setQuery(e.target.value.slice(0,120))}/>{query&&<button aria-label="Clear facility search" onClick={()=>setQuery('')}><X size={15}/></button>}</div>
     {!isCountryOverview&&entry&&<div className="fw-filters"><label><span>Source</span><select aria-label="Facility source" value={filters.siteSource} onChange={e=>onChange({siteSource:e.target.value,site:''})}><option value="">All sources</option>{entry.sources.map(id=><option key={id} value={id}>{catalog.sources[id].title}</option>)}</select></label>{provinceSupported&&<label><span>Region</span><select aria-label="Facility region" value={effectiveRegion} onChange={e=>setRegion(e.target.value)} disabled={!provinceSupported}><option value="">{provinceSupported?'All regions':'Not supplied by source'}</option>{Object.entries(entry.regions).sort(([a],[b])=>a.localeCompare(b)).map(([id,n])=><option key={id} value={id}>{provinces[id]||id} · {number(n,0)}</option>)}</select></label>}<label><span>{kind==='power'?'Primary fuel':'Facility type'}</span><select aria-label="Facility type" value={type} onChange={e=>setType(e.target.value)}><option value="">All types</option>{Object.entries(entry.types).sort((a,b)=>b[1]-a[1]).map(([id,n])=><option key={id} value={id}>{id} · {number(n,0)}</option>)}</select></label><label><span>Evidence</span><select aria-label="Measurement basis" value={basis} onChange={e=>setBasis(e.target.value)}><option value="">All evidence</option>{Object.keys(entry.bases).map(id=><option key={id} value={id}>{basisLabels[id as keyof typeof basisLabels]}</option>)}</select></label><label><span>Order</span><select aria-label="Sort facilities" value={sort} onChange={e=>setSort(e.target.value)}><option value="name">Name A–Z</option><option value="quantity" disabled={!comparableSelection}>{comparableSelection?'Largest quantity':'Filter to one measure to rank'}</option></select></label></div>}
     {place==='SSI'&&<p className="fw-local-note">The source has no reliable island boundary. Showing Canada; search “Salt Spring” for named local records.</p>}
     {place==='BC'&&!provinceSupported&&<p className="fw-local-note">This source has no province field. Showing Canada; inspect locations on the map.</p>}
     <div className="fw-result-heading" aria-live="polite"><strong>{isCountryOverview?countryRows.length.toLocaleString()+' countries':loading?'Loading records…':visible.length.toLocaleString()+' results'}</strong>{!!visible.length&&<button title="Export filtered records with provenance" aria-label="Export filtered facility records" onClick={()=>exportCSV(visible.map(r=>({id:r.id,name:r.name,country:r.country,region:r.region,locality:r.locality,type:r.type,longitude:r.coordinates[0],latitude:r.coordinates[1],value:r.value,unit:r.unit,metric:r.metric,basis:r.basis,observation_year:r.year,source:catalog.sources[r.source].title,source_url:catalog.sources[r.source].url,license:catalog.sources[r.source].license,source_edition:catalog.sources[r.source].edition,snapshot:catalog.publishedAt})),`overshoot-${kind}-${loadedCountry}.csv`)}><Download size={15}/>CSV</button>}</div>
     <div className="fw-result-list" ref={resultsRef} aria-busy={loading}>
      {isCountryOverview?countryRows.map(r=><button className="fw-country-row" key={r.id} onClick={()=>onChange({place:r.id,site:''})}><span>{r.name}<small>{Object.keys(r.bases).map(b=>basisLabels[b as keyof typeof basisLabels]).join(' · ')}</small></span><strong>{number(r.count,0)}</strong><ArrowRight size={16}/></button>):pinData.error?<ErrorState message={pinData.error}/>:loading?<Loading/>:visible.length?visible.slice(page*30,page*30+30).map(r=><button className="fw-result-row" key={r.id} onClick={()=>open(r.id)}><span className={'fw-basis-dot '+r.basis}/><span><strong>{r.name}</strong><small>{world?[names.get(r.country)||r.country,locationLabel(r)].filter((v,i,a)=>a.indexOf(v)===i).join(' · '):locationLabel(r)}</small><em>{r.type}</em></span><span className="fw-result-value">{r.value===null?<small>Location<br/>record</small>:<>{number(r.value,1)}<small>{r.unit}</small></>}<i>{r.basis==='modeled'?'Modeled':r.basis==='estimated'?'Estimate · '+r.year:r.basis==='capacity'?'Capacity':r.year||''}</i></span><ArrowUpRight size={14}/></button>):<div className="fw-no-results"><MapPin size={27}/><h3>{entry?'No records match these filters.':'This source does not cover this place.'}</h3><p>{entry?'Try another name, region or evidence type.':'Missing coverage does not mean there are no sites here. Choose another layer or inspect the source coverage.'}</p>{entry?<button className="oa-button outline" onClick={reset}>Clear filters</button>:<><button className="oa-button outline" onClick={()=>onChange({place:'WORLD',site:''})}>See source coverage<ArrowRight size={16}/></button>{facilityKinds.filter(k=>k!==kind&&catalog.datasets[k].countries[country]).slice(0,3).map(k=><button key={k} className="oa-text-link" onClick={()=>onChange({kind:k,site:''})}>{kindLabels[k]} here · {number(catalog.datasets[k].countries[country].count,0)}<ArrowRight size={14}/></button>)}{kind==='energy'&&<a className="oa-text-link" href={`/materials?material=fuels&place=${country}&layer=production`}>National energy data<ArrowRight size={15}/></a>}</>}</div>}
     </div>
     {!isCountryOverview&&visible.length>30&&<div className="fw-pagination"><button aria-label="Previous results" disabled={page===0} onClick={()=>setPage(p=>p-1)}><ChevronLeft size={17}/></button><span>{page*30+1}–{Math.min((page+1)*30,visible.length)} of {number(visible.length,0)}</span><button aria-label="Next results" disabled={page+1>=pages} onClick={()=>setPage(p=>p+1)}><ChevronRight size={17}/></button></div>}
    </>}
   </section>
  </div>
  {!isCountryOverview&&summary.length>0&&<div className="fw-evidence-key"><span>IN THIS SELECTION</span>{summary.map(([id,n])=><button key={id} onClick={()=>{setBasis(basis===id?'':id);open('')}} aria-pressed={basis===id}><i className={'fw-basis-dot '+id}/>{number(n,0)} {basisLabels[id as keyof typeof basisLabels].toLowerCase()}</button>)}</div>}
  <div className="fw-explain"><div><span className="oa-kicker">READ THE PHYSICAL SYSTEM</span><h3>{kind==='wastewater'?'A treatment plant is a step, not the end.':kind==='landfill'?'Where waste arrives matters. So does what leaves.':kindQuestions[kind]}</h3><p>{typeNotes[kind]}</p><p className="fw-small">{catalog.countDefinition}</p></div><div><span className="oa-kicker">FOLLOW THE EVIDENCE</span>{sources.map(([id,s])=><details className="fw-source" key={id}><summary><span>{s.title}<small>{s.edition} · {s.license}</small></span><ChevronRight size={17}/></summary><p>{s.coverage}</p><p>{s.method}</p><ul>{s.limits.map(l=><li key={l}>{l}</li>)}</ul><div><a href={s.url} target="_blank" rel="noreferrer">Source & documentation <ArrowUpRight size={14}/></a><a href={s.download} target="_blank" rel="noreferrer">Original download <Download size={14}/></a></div></details>)}</div></div>
 </>
}
function RecordInspector({record:r,source,kind,onOutfall,showOutfall}:{record:FacilityRecord;source:DataSource;kind:FacilityKind;onOutfall?:()=>void;showOutfall:boolean}){
 const [copied,setCopied]=useState(false),[copyError,setCopyError]=useState(false);
 const a=r.attributes;
 const treatment=String(a.LEVEL||'');
 const fact=(label:string,value:unknown)=>value!=null&&value!==''?<div key={label}><dt>{label}</dt><dd>{String(value)}</dd></div>:null;
 async function copy(){try{await navigator.clipboard.writeText(location.href);setCopied(true);setCopyError(false)}catch{setCopyError(true)}}
 return <>
  <div className={'fw-basis-tag '+r.basis}>{basisLabels[r.basis]}</div><h3>{r.name}</h3>{a.name_not_reported&&<p className="fw-small">The source gives a facility class but no site name.</p>}<p className="fw-record-place"><MapPin size={15}/>{[r.locality,provinces[r.region]||r.region,r.country].filter(Boolean).join(' · ')}</p>
  <div className="fw-measure"><span>{r.metric}</span><strong>{r.value===null?'No quantity reported':number(r.value,2)}</strong>{r.value!==null&&<small>{r.unit}{r.year?' · '+r.year:' · observation year not supplied'}</small>}<p>{measurementNote(r.basis)}</p></div>
  {r.source==='hydrowaste-2022'&&<div className="fw-treatment"><span className="oa-kicker">TREATMENT</span><div className="fw-treatment-steps">{['Primary','Secondary','Advanced'].map((name,i)=><span key={name} className={name.toLowerCase()===treatment.toLowerCase()?'active':''}><b>0{i+1}</b>{name}</span>)}</div><p>{treatment||'Treatment level not supplied'} · {a.QUAL_LEVEL==='1'?'reported by source':'estimated by source'}. Primary treatment separates solids; secondary treatment removes organic pollution; advanced treatment adds further removal.</p>{a.POP_SERVED&&<p><strong>{number(Number(a.POP_SERVED),0)}</strong> {a.QUAL_POP==='2'?'population equivalent':'people served'} · {['3','4'].includes(String(a.QUAL_POP))?'source estimate':'source report'}.</p>}</div>}
  {r.source==='wri-power-plants'&&<PowerEvidence attributes={a}/>}
  {r.source==='climate-trace-2025'&&<TraceEvidence attributes={a}/>}
  {r.source==='hydrowaste-2022'&&<WaterContext attributes={a} onOutfall={onOutfall} showOutfall={showOutfall}/>}
  <dl className="fw-facts">{fact('Facility class',r.type)}{fact('Status at source snapshot',r.status)}{fact('Provider',a.provider||a.source||a.SOURCE)}{fact('Owner in source',a.ownership||a.owner)}{fact('Native identifier',a.source_id||a.ORG_ID||r.sourceRow)}{fact('Address',a.address)}{fact('Mapped position',r.coordinates[1].toFixed(5)+', '+r.coordinates[0].toFixed(5))}{fact('Location method',a.location_method|| (kind==='mining'?'Representative point within the mining polygon':kind==='river'?'Modeled river outfall':'Source-reported plant coordinates'))}{a.QUAL_LOC&&fact('Country-level location assessment',({'1':'>80% match rate','2':'50–80% match rate','3':'<50% match rate','4':'Not assessed'} as Record<string,string>)[String(a.QUAL_LOC)]+' · not a probability for this plant')}</dl>
  {typeof a.url==='string'&&/^https?:\/\//.test(a.url)&&<a className="oa-text-link" href={a.url} target="_blank" rel="noreferrer">Original plant data provider <ArrowUpRight size={14}/></a>}
  <div className="fw-record-source"><BookOpen size={17}/><div><strong>{source.title}</strong><small>{source.edition}</small><a href={source.url} target="_blank" rel="noreferrer">Read the primary source <ArrowUpRight size={13}/></a></div></div>
  <details className="fw-record-details"><summary>What this record cannot tell you</summary><ul>{source.limits.map(l=><li key={l}>{l}</li>)}</ul></details>
  <details className="fw-record-details"><summary>Original fields & derivation</summary><p>{source.method}</p><pre>{JSON.stringify(r,null,2)}</pre><a href={source.licenseUrl} target="_blank" rel="noreferrer">{source.license}</a></details>
  <div className="fw-continue"><span className="oa-kicker">PUT THIS SITE IN CONTEXT</span>{Object.entries(materialSiteLayers).filter(([,layers])=>layers.some(l=>l.kind===kind&&l.type===r.type)).slice(0,2).map(([id])=><a key={id} className="oa-text-link" href={`/materials?material=${id}&place=${r.country==='ZNC'?'WORLD':r.country}&layer=sites`}>{profiles.find(p=>p.id===id)?.name} guide<ArrowRight size={15}/></a>)}{!['UNASSIGNED','ZNC'].includes(r.country)&&<a className="oa-text-link" href={`/places?place=${r.country}${kind==='landfill'||kind==='wastewater'?'&lens=waste':''}`}>This country’s material & waste accounts<ArrowRight size={15}/></a>}</div><button className="oa-button outline fw-copy" onClick={copy}>{copied?<Check size={15}/>:<Copy size={15}/>} {copied?'Record link copied':'Copy record link'}</button>{copyError&&<p role="status">Copy the address from your browser to share this record.</p>}
 </>
}
function WaterContext({attributes:a,onOutfall,showOutfall}:{attributes:FacilityRecord['attributes'];onOutfall?:()=>void;showOutfall:boolean}){
 const numeric=(v:unknown)=>v!==null&&v!==undefined&&v!==''&&Number.isFinite(Number(v));
 return <section className="fw-water-context"><h4>Where the treated water goes</h4><dl className="fw-facts">{numeric(a.RIVER_DIS)&&<div><dt>Estimated river flow at outfall</dt><dd>{number(Number(a.RIVER_DIS),2)} m³/second</dd></div>}{numeric(a.DF)&&<div><dt>Estimated dilution factor</dt><dd>{number(Number(a.DF),1)} : 1</dd></div>}{a.HYRIV_ID&&<div><dt>RiverATLAS reach</dt><dd>{a.HYRIV_ID}</dd></div>}{numeric(a.LAT_OUT)&&numeric(a.LON_OUT)&&<div><dt>Modeled outfall position</dt><dd>{Number(a.LAT_OUT).toFixed(5)}, {Number(a.LON_OUT).toFixed(5)}</dd></div>}</dl><p>HydroWASTE links the plant to an estimated receiving waterbody. Dilution compares natural river discharge with the plant’s effluent; a lower ratio means less river water is available for dilution. It does not measure pollution concentration or ecological harm.</p>{onOutfall&&<button className="oa-button outline" aria-pressed={showOutfall} onClick={onOutfall}>{showOutfall?'Return to plant':'Locate modeled outfall'}<MapPin size={15}/></button>}<a className="oa-text-link" href="https://essd.copernicus.org/articles/14/559/2022/" target="_blank" rel="noreferrer">HydroWASTE & HydroATLAS method<ArrowUpRight size={14}/></a></section>
}
function TraceEvidence({attributes:a}:{attributes:FacilityRecord['attributes']}){
 const fields=[['Activity in 2025','activity','activityUnits'],['Capacity in source','capacity','capacityUnits']] as const;
 return <div className="fw-power-evidence"><span className="oa-kicker">PRODUCTION CONTEXT</span><dl className="fw-facts">{fields.map(([label,key,unit])=>{const restricted=String(a[unit]||'').toLowerCase().includes('restricted');return <div key={key}><dt>{label}</dt><dd>{restricted?'Unavailable · upstream licence restriction':a[key]==null||!a[unit]?'Not supplied':number(Number(a[key]),2)+' '+a[unit]}</dd></div>})}</dl><p>Original units are retained. Emissions describe climate impact; they do not measure waste intake or material output. No operating rate is inferred from restricted fields.</p><a className="oa-text-link" href="https://climatetrace.org/sectors" target="_blank" rel="noreferrer">Sector methods <ArrowUpRight size={14}/></a></div>
}
function PowerEvidence({attributes:a}:{attributes:FacilityRecord['attributes']}){
 const generation=[2013,2014,2015,2016,2017,2018,2019].map(year=>({year,reported:a['generation_gwh_'+year],modeled:a['estimated_generation_gwh_'+year]})).filter(r=>r.reported!=null||r.modeled!=null);
 const fuels=[a.primary_fuel,a.other_fuel1,a.other_fuel2,a.other_fuel3].filter(Boolean);
 return <div className="fw-power-evidence"><span className="oa-kicker">FUEL & ELECTRICITY</span><p>{fuels.join(' · ')}. Other fuels are not ranked by use.</p>{generation.length?<><table><caption>Annual generation · GWh</caption><thead><tr><th>Year</th><th>Reported</th><th>Modeled</th></tr></thead><tbody>{generation.map(r=><tr key={r.year}><th>{r.year}</th><td>{r.reported==null?'—':number(Number(r.reported),1)}</td><td>{r.modeled==null?'—':number(Number(r.modeled),1)}</td></tr>)}</tbody></table><p>Reported and modeled values are alternatives, not additive. A dash is unavailable, not zero.</p></>:<p>No annual generation values are supplied for this plant.</p>}</div>
}
