'use client';
import {useState} from 'react';
import {ArrowLeft,ArrowRight,ArrowUpRight,BookOpen,Factory,Globe2,Recycle,Search} from 'lucide-react';
import {useMaterialArtifact} from '../material-data';
import type {AtlasState} from './atlasState';
import {number,Refs} from './common';
import GlassReturnsMap from './GlassReturnsMap';
import './investigation.css';

type Step={title:string;eyebrow:string;icon:typeof Recycle;claim:string;detail:string;unknown:string;sources:string[];action:string;view:Partial<AtlasState>;symbol:string};
type GlassData={depositBeverage:{containersRecovered:number;reportedUnitRecoveryPercent:number;estimatedTonnesRecovered:number};refillableMilk:{containersReturned:number;reportedReturnPercent:number}};
const jar:Step[]=[
 {title:'Collect',eyebrow:'NON-DEPOSIT JAR · SEPARATE COLLECTION',icon:Recycle,claim:'Accepted food jars enter Recycle BC’s separate glass stream.',detail:'The program managed over 200,000 tonnes of all residential packaging and paper in 2025. That is not a glass-only figure. Deposit beverage bottles and dairy refillables belong to different systems.',unknown:'A published, province-wide collected tonnage for this jar stream.',sources:['rbcGlass','rbcReport2025'],action:'Explore the glass guide',view:{view:'materials',material:'glass',place:'BC'},symbol:'↻'},
 {title:'End market',eyebrow:'REPORTED END MARKET · BC · 2025',icon:BookOpen,claim:'The program reports all its glass-packaging recycling end markets in BC.',detail:'100% describes where reported end markets are located. It is not a collection rate, recycling yield, or proof of where a particular jar became a new product.',unknown:'The receiving facility and final product of this specific jar.',sources:['rbcReport2025'],action:'Compare BC material destinations',view:{view:'places',place:'BC',placeView:'materials'},symbol:'100%'},
 {title:'Origin',eyebrow:'UPSTREAM · NOT TRACED',icon:Globe2,claim:'The origin of a jar used in BC cannot be read from the recycling report.',detail:'Trade data describes border crossings by product code and reporter. The retained glass trade view contains selected glass-scrap reports, not a supply-chain register for food jars.',unknown:'The supplier, furnace, mineral inputs and recycled content of this jar.',sources:['comtrade','statcan-cimt-imports'],action:'Inspect glass trade evidence',view:{view:'trade',material:'glass',place:'CAN',form:'7001',direction:'in'},symbol:'?'},
 {title:'Production',eyebrow:'FACILITIES · CONTEXT ONLY',icon:Factory,claim:'Glass-industry sites locate possible production activity, not this jar’s maker.',detail:'Climate TRACE maps 482 source locations globally, including four assigned to Canada. Its inventory estimates emissions. These points cannot be connected to a particular BC purchase.',unknown:'Whether any mapped site made this product.',sources:['climate-trace-2025'],action:'Inspect the glass plant map',view:{view:'materials',material:'glass',place:'WORLD',layer:'journey',journeyLayers:'manufacturing'},symbol:'482'}
];
const deposit:Step[]=[
 {title:'Sold & used',eyebrow:'DEPOSIT BEVERAGE GLASS · BC · 2025',icon:Globe2,claim:'178,924,240 deposit glass containers were sold in BC.',detail:'Return-It reports sales and recoveries by container type. The count concerns beverage containers in its deposit system; it cannot be used to estimate the origin of a bottle or the mass of non-deposit jars.',unknown:'Which furnace or producer made a bottle bought here.',sources:['encorp2025'],action:'Research glass imports',view:{view:'trade',material:'glass',place:'CAN',form:'7001',direction:'in'},symbol:'179m'},
 {title:'Returned',eyebrow:'RETURN-IT · REPORTED RECOVERY',icon:Recycle,claim:'159,640,710 glass containers were recovered: a reported 89.2% unit rate.',detail:'The published recovered weight is an estimate of 54,542 metric tonnes. The recovery accounting also includes audited estimates of refundable containers captured by curbside and commercial systems. The 28 regional entries compare reported returns, not processor destinations.',unknown:'Which depot accepted a particular bottle or the exact weight of its shipment.',sources:['encorp2025'],action:'Inspect BC return regions',view:{view:'places',place:'BC'},symbol:'89.2%'},
 {title:'Processed',eyebrow:'REPORTED DOWNSTREAM · BC',icon:Factory,claim:'Return-It says the collected bottles are sold to a recycler in BC.',detail:'The recycler is unnamed in the published end-fate table. Its collection and transport map explicitly excludes glass, so we cannot draw a depot-to-processor path or assign a share of recovered weight to any facility.',unknown:'The processing facility name, route and yield.',sources:['encorpFate2025','encorpCollection2025'],action:'Read the evidence and methods',view:{view:'data'},symbol:'BC'},
 {title:'Next use',eyebrow:'THREE REPORTED PRODUCT MARKETS',icon:BookOpen,claim:'Reported uses include US bottles, BC sandblasting media and Alberta insulation.',detail:'These describe destinations after BC processing. Return-It does not publish tonnage for each branch. The same 54,542 estimated tonnes must not be repeated on each branch or drawn as three weighted shipments.',unknown:'The quantities, companies and exact routes for each end use.',sources:['encorpFate2025'],action:'Open the source register',view:{view:'data'},symbol:'↗'}
];
const milk:Step[]=[
 {title:'Sold',eyebrow:'DAIRY REFILLABLES · DIFFERENT PROGRAM',icon:Globe2,claim:'Participating dairies reported 3,191,599 refillable milk bottles sold in 2025.',detail:'These bottles carry producer-managed deposits. They are not part of the Return-It beverage deposit totals above; the dairies submitted the numbers for Encorp’s annual reporting.',unknown:'Origin and recycled content of every reusable bottle.',sources:['encorp2025'],action:'Read the dairy report',view:{view:'data'},symbol:'3.2m'},
 {title:'Returned',eyebrow:'REPORTED BY DAIRIES · 2025',icon:Recycle,claim:'2,666,659 milk bottles returned: a reported 83.6% rate.',detail:'A customer may bring an undamaged bottle back to the original store or another retailer carrying that brand. These dairy-submitted figures were not independently verified by Encorp.',unknown:'Returns by store, journey distance and precise breakage.',sources:['encorp2025'],action:'See evidence definitions',view:{view:'data'},symbol:'83.6%'},
 {title:'Refilled',eyebrow:'DOCUMENTED REUSE LOOP',icon:Factory,claim:'Returned bottles go back to dairies for cleaning, sterilizing and refilling.',detail:'Unlike the two one-way collection examples, this is a reported reuse loop. Damaged bottles unsuitable for reuse are sent to local glass recyclers. The report does not give separate loop counts or damaged-bottle tonnage.',unknown:'The number of refills per bottle and quantities sent to recyclers.',sources:['encorp2025'],action:'Explore recovery and reuse',view:{view:'waste'},symbol:'↻'}
];
const journeys={deposit:{label:'Beverage bottle · deposit',steps:deposit},jar:{label:'Food jar · non-deposit',steps:jar},milk:{label:'Milk bottle · refillable',steps:milk}};
type Mode=keyof typeof journeys;
export default function GlassInvestigation({onGo}:{onGo:(view:Partial<AtlasState>)=>void}){
 const [mode,setMode]=useState<Mode>('deposit'),[index,setIndex]=useState(0);
 const glass=useMaterialArtifact<GlassData>('/data/v29/bc-glass.json');
 const steps=journeys[mode].steps,current=steps[index],Icon=current.icon;
 return <section className="gi" id="bc-glass" aria-labelledby="gi-heading">
  <div className="gi-heading"><div><span className="oa-kicker">THREE REAL SYSTEMS · BRITISH COLUMBIA · 2025</span><h2 id="gi-heading">Where did this glass come from? Where can it go?</h2><p>Choose an object. Follow what its own program reports, from use to recovery, and see exactly where its evidence ends.</p></div><span className="gi-symbol" aria-hidden="true">Gl</span></div>
  <div className="gi-modes" role="group" aria-label="Choose a glass journey">{(Object.entries(journeys) as [Mode,typeof journeys[Mode]][]).map(([id,journey])=><button key={id} aria-pressed={mode===id} onClick={()=>{setMode(id);setIndex(0)}}>{journey.label}<ArrowRight size={15}/></button>)}</div>
  {mode==='deposit'&&glass.data&&<div className="gi-stats" aria-label="2025 deposit beverage glass"><div><strong>{number(glass.data.depositBeverage.containersRecovered,0)}</strong><span>containers recovered · reported count</span></div><div><strong>{number(glass.data.depositBeverage.estimatedTonnesRecovered,0)} t</strong><span>recovered glass · estimated weight</span></div><div><strong>{glass.data.depositBeverage.reportedUnitRecoveryPercent}%</strong><span>unit recovery · sold versus recovered</span></div></div>}
  {mode==='milk'&&glass.data&&<p className="gi-program-note"><strong>{number(glass.data.refillableMilk.containersReturned,0)}</strong> returned dairy bottles · {glass.data.refillableMilk.reportedReturnPercent}% reported return rate · independently operated by participating dairies.</p>}
  <div className="gi-track" role="group" aria-label="Evidence stages">{steps.map((step,i)=><button key={step.title} aria-current={index===i?'step':undefined} onClick={()=>setIndex(i)} style={{'--progress':i<=index?'100%':'0%'} as React.CSSProperties}><span className="gi-step-index">0{i+1}</span><span>{step.title}</span><i/></button>)}</div>
  <div className="gi-scene" key={mode+'-'+index} aria-live="polite"><div className="gi-scene-art" aria-hidden="true"><span>BC · {mode==='deposit'?'DEPOSIT':mode==='milk'?'REUSE':'PACKAGING'}</span><Icon size={86} strokeWidth={1}/><small>{current.symbol}</small></div><div className="gi-scene-copy"><span className="oa-kicker">{current.eyebrow}</span><h3>{current.claim}</h3><p>{current.detail}</p><div className="gi-limit"><Search size={17}/><span><strong>Still unknown</strong>{current.unknown}</span></div><Refs ids={current.sources}/><button className="oa-text-link gi-evidence-link" onClick={()=>onGo(current.view)}>{current.action}<ArrowUpRight size={16}/></button></div></div>
  <div className="gi-bottom"><div><button disabled={index===0} onClick={()=>setIndex(index-1)}><ArrowLeft size={16}/>Previous stage</button><button disabled={index===steps.length-1} onClick={()=>setIndex(index+1)}>Next stage<ArrowRight size={16}/></button></div><a href="https://www150.statcan.gc.ca/n1/pub/71-607-x/71-607-x2021004-eng.htm" target="_blank" rel="noreferrer">Research BC import commodities <ArrowUpRight size={14}/></a></div>
  {mode==='deposit'&&<GlassReturnsMap/>}
  <p className="gi-method">Reported recovery counts, estimated weight, geographic end-market shares and reuse counts are different measures. Encorp also counts some refundable containers captured by Recycle BC and commercial streams; these program figures cannot simply be added. No missing route or origin is interpolated. For annual national energy series, the separate estimate tool interpolates only between two nearby reported years and returns its inputs and formula.</p>
 </section>;
}
