'use client';
import {useState} from 'react';
import {ArrowRight,ArrowUpRight,BookOpen,LocateFixed,Layers3,Search} from 'lucide-react';
import {Tabs,TabsList,TabsTrigger} from '@/components/ui/tabs';
import type {Country} from '../world/model';
import {compact} from './common';
import {profiles,profileById,formNames} from './data';
import {useTradeEvidence} from './useTradeEvidence';
import {atlasUrl,defaultAtlasState,type AtlasState} from './atlasState';
import {AtlasLink} from './AtlasLink';
import HomeGlobe from './HomeGlobe';

const mappedForms=[{id:'copper',form:'7403',label:'Copper'},{id:'plastic',form:'3915',label:'Plastic scrap'},{id:'paper',form:'4707',label:'Recovered paper'}];
const stages:[string,string,string,string,Partial<AtlasState>][]=[
 ['01','Extract or grow','National accounts measure mass. A mapped mine, well or field locates activity; it does not give the output of your neighbourhood.','Place accounts',{view:'places',place:'WORLD'}],
 ['02','Make and refine','Facilities and production series locate transformation. Capacity, emissions and actual output are different measurements.','Material guides',{view:'materials',material:'copper'}],
 ['03','Move across borders','Customs reports product weight and trading partners. Ports and vessel activity give transport context, not a tracked cargo route.','Reported trade',{view:'trade',place:'WORLD'}],
 ['04','Remain in use','Material builds homes, roads and products, or is burned as fuel. Stocks and annual flows answer different questions.','Material accounts',{view:'places',place:'WORLD'}],
 ['05','Leave or return','Collection, sorting, recovery, disposal and leakage have separate measures. Follow the source year and definition for each.','Waste evidence',{view:'waste'}],
];
export default function HomePage({countries,onGo,onSources,onSearch}:{countries:Country[];onGo:(state:Partial<AtlasState>)=>void;onSources:()=>void;onSearch:()=>void}){
 const [selection,setSelection]=useState('copper');
 const current=mappedForms.find(e=>e.id===selection)!;
 const profile=profileById(current.id);
 const {flows,loading,error}=useTradeEvidence({profile,place:'WORLD',form:current.form,direction:'out',countries});
 const leading=flows[0];
 function link(update:Partial<AtlasState>){const next={...defaultAtlasState,...update};if(!profileById(next.material).codes.includes(next.form))next.form=profileById(next.material).codes[0]||'';return {href:atlasUrl(next),onNavigate:()=>onGo(next)}}
 function materialLink(id:string){const p=profileById(id);return link({view:'materials',material:id,form:p.codes[0]||'',place:'WORLD',product:'',layer:'',direction:'out'})}
 return <div className="oa-home">
  <section className="oa-home-hero" aria-labelledby="home-heading"><div className="oa-home-intro">
   <p className="oa-kicker oa-home-eyebrow">OVERSHOOT · A PLANETARY MATERIAL ATLAS</p>
   <h1 id="home-heading">Where did it come from?<span>Where did it go?</span></h1>
   <p className="oa-home-lead">Follow materials from source to production, trade and after use. Start with a documented journey, then inspect the map, the quantities and the gaps yourself.</p>
   <div className="oa-home-actions"><AtlasLink className="oa-button" {...link({view:'local'})}>Investigate a place<ArrowRight size={18}/></AtlasLink><a className="oa-home-place" href="#choose-material"><Layers3 size={17}/>Choose a material<ArrowUpRight size={16}/></a></div>
   <div className="oa-home-origin-note"><span>Origins</span><i/><span>Production</span><i/><span>Transport</span><i/><span>Use</span><i/><span>After use</span></div>
  </div><div className="oa-home-map-panel"><div className="oa-home-map-head"><span className="oa-kicker">REPORTED BILATERAL TRADE</span><Tabs value={selection} onValueChange={setSelection}><TabsList aria-label="Trade map material">{mappedForms.map(e=><TabsTrigger key={e.id} value={e.id}>{e.label}</TabsTrigger>)}</TabsList></Tabs></div>
   <HomeGlobe flows={flows} countries={countries} label={formNames[current.form]}/><div className="oa-home-connection" aria-live="polite" aria-atomic="true"><div><span className="oa-kicker">{formNames[current.form]}</span>{leading?<><strong>{leading.originLabel}<ArrowRight size={17}/>{leading.destinationLabel}</strong><span>Largest available reported connection · {leading.year}</span></>:<strong>{error?'Records unavailable':loading?'Loading trade records…':'No records available'}</strong>}</div>{leading&&<div className="oa-home-connection-value"><strong>{compact(leading.amount)}<span> t</span></strong><AtlasLink {...link({view:'trade',dataset:'commodity',material:current.id,form:current.form,place:leading.origin,product:'',direction:'out'})}>Inspect source<ArrowUpRight size={14}/></AtlasLink></div>}</div><p className="oa-home-map-caption">UN Comtrade · 20 largest available connections. Curves join country centres, not shipment routes. <a href="https://www.naturalearthdata.com/" target="_blank" rel="noreferrer">Geography: Natural Earth</a></p>
  </div></section>
  <section className="oa-home-questions" aria-labelledby="question-heading"><div className="oa-home-section-heading"><div><span className="oa-kicker">START WITH THE STRONGEST TRAILS</span><h2 id="question-heading">Real places. Named links. Recent measurements.</h2></div><p>Each journey separates a documented physical connection from a production total and shows where the evidence ends.</p></div><div className="oa-home-question-grid">
   <AtlasLink {...link({view:'materials',material:'copper',layer:'connections',network:'escondida-ports',place:'CHL'})}><span className="oa-kicker">01 · COPPER · CHILE · FY2026</span><h3>From Escondida to the coast: which form takes which route?</h3><p>Trace concentrate by pipeline toward Coloso and cathodes by rail toward two export ports. BHP reports 1.047m tonnes of payable copper in concentrate and 214,400 tonnes of cathodes at Escondida.</p><span className="oa-home-question-stat">3 sourced links · 3 mapped · BHP FY2026</span><span className="oa-home-question-link">Explore the copper journey<ArrowUpRight size={18}/></span></AtlasLink>
   <AtlasLink {...link({view:'materials',material:'aluminium',layer:'connections',network:'para-aluminium',place:'BRA'})}><span className="oa-kicker">02 · BAUXITE · BRAZIL · 2025</span><h3>How does bauxite become aluminium in Pará?</h3><p>Follow Paragominas through a 244 km pipeline to Alunorte, then to Albras and a documented residue store. Hydro reports 10.496m tonnes of bauxite produced at the mine in 2025.</p><span className="oa-home-question-stat">3 sourced links · 2 mapped · Hydro 2025</span><span className="oa-home-question-link">Explore the aluminium journey<ArrowUpRight size={18}/></span></AtlasLink>
   <AtlasLink {...link({view:'materials',material:'fuels',layer:'connections',network:'coal-6002',place:'USA'})}><span className="oa-kicker">03 · COAL · UNITED STATES · 2025</span><h3>Which mines supplied the James H. Miller Jr power plant?</h3><p>Follow final 2025 mine to plant receipts, joined to government coordinates and monthly reported quantities. See what the plant generated and where the trail to electricity customers stops.</p><span className="oa-home-question-stat">189 power plants · 626 named mine to plant pairs in the complete ledger</span><span className="oa-home-question-link">Trace a coal delivery<ArrowUpRight size={18}/></span></AtlasLink>
  </div></section>
  <section className="wr-home-tasks" aria-label="Ways to investigate"><AtlasLink {...link({view:'local'})}><span className="wr-home-task-icon"><LocateFixed size={22}/></span><div><span className="oa-kicker">START WITH A COORDINATE</span><h2>What is near me?</h2><p>Find source-mapped facilities anywhere and distinguish local evidence from national extraction totals.</p><span className="wr-home-task-link">Open the local lens <ArrowRight size={16}/></span></div></AtlasLink><AtlasLink {...link({view:'materials'})}><span className="wr-home-task-icon"><Layers3 size={22}/></span><div><span className="oa-kicker">FOLLOW A MATERIAL</span><h2>Where does it go?</h2><p>Switch between extraction, processing, trade, use and disposal without pretending every link is known.</p><span className="wr-home-task-link">Choose a material <ArrowRight size={16}/></span></div></AtlasLink><AtlasLink {...link({view:'waste'})}><span className="wr-home-task-icon"><BookOpen size={22}/></span><div><span className="oa-kicker">COMPARE THE EVIDENCE</span><h2>What becomes waste?</h2><p>Compare generation, collection and treatment by place and year. Keep the source definitions in view.</p><span className="wr-home-task-link">Research waste <ArrowRight size={16}/></span></div></AtlasLink></section>
  <section className="oa-home-method" aria-labelledby="home-method-heading"><div className="oa-home-method-head"><div><span className="oa-kicker">HOW TO READ THE ATLAS</span><h2 id="home-method-heading">A material changes form. The evidence changes with it.</h2></div><p>OVERSHOOT joins several views of the physical world. It shows the handoffs we can document and leaves unknown links visible.</p></div><ol className="oa-home-chain">{stages.map(([n,name,description,cta,destination])=><li key={n}><span className="oa-home-chain-num">{n}</span><h3>{name}</h3><p>{description}</p><AtlasLink {...link(destination)}>{cta}<ArrowUpRight size={15}/></AtlasLink></li>)}</ol></section>
  <section className="oa-home-materials" id="choose-material" aria-labelledby="material-heading"><div className="oa-home-section-heading"><div><span className="oa-kicker">WHAT IS IT MADE OF?</span><h2 id="material-heading">Choose a material.</h2></div><button className="oa-home-search" onClick={onSearch}><Search size={17}/>Search the atlas</button></div><div className="oa-home-material-grid">{profiles.map(p=><AtlasLink key={p.id} {...materialLink(p.id)} style={{'--tile-accent':p.color} as React.CSSProperties}><span className="oa-home-material-symbol">{p.symbol}</span><strong>{p.name}</strong><small>{p.object}</small><ArrowUpRight size={17}/></AtlasLink>)}</div></section>
  <section className="oa-home-evidence"><BookOpen size={24}/><div><h2>Every map has a method.</h2><p>A mapped point may be a facility, an emissions estimate or a model output. Trade is reported between countries, not traced to a final buyer. Inspect the year, unit, geography and source before combining claims.</p></div><button className="oa-text-link" onClick={onSources}>Sources & coverage<ArrowUpRight size={17}/></button></section>
 </div>;
}
