'use client';
import {useEffect,useMemo,useState} from 'react';
import {ArrowRight,ArrowUpRight,Check,Layers3,MapPin} from 'lucide-react';
import {materialArtifact,useMaterialArtifact} from '../material-data';
import type {JourneyCatalog,JourneyPin} from '@/packages/material-world/journey';
import type {FacilityCatalog} from '@/packages/material-world/model';
import type {Country,SiteFeature} from '../world/model';
import type {Profile} from './data';
import type {OpenMaterialSites} from './MaterialSitesMap';
import {ErrorState,Loading,compact,number} from './common';
import {placeName} from './PlaceContext';
import WorldMap from '../world/WorldMap';
import {CapacityEvidence,capacityLayer,capacityOptions,type CapacitySnapshot} from './CapacityEvidence';
import './journey.css';

type LayerData={path:string;rows:JourneyPin[]};
export default function JourneyMap({profile,place,countries,layers,onLayers,onPlace,onSites,onConnections,onAccounts,onEnergy}:{profile:Profile;place:string;countries:Country[];layers:string;onLayers:(layers:string)=>void;onPlace:(place:string)=>void;onSites:OpenMaterialSites;onConnections:()=>void;onAccounts:()=>void;onEnergy:()=>void}){
 const catalog=useMaterialArtifact<JourneyCatalog>('/data/v16/journeys/'+profile.id+'.json');
 const sources=useMaterialArtifact<FacilityCatalog>(catalog.data?.sourceCatalog||null);
 const capacity=useMaterialArtifact<CapacitySnapshot>(profile.id==='concrete'?'/data/v35/cement-country.json':profile.id==='steel'?'/data/v35/steel-country.json':null);
 const [capacityMetric,setCapacityMetric]=useState('');
 const [focus,setFocus]=useState(''),[selected,setSelected]=useState(''),[query,setQuery]=useState(''),[result,setResult]=useState<{key:string;data:LayerData[];error:string}>({key:'',data:[],error:''});
 const country=place==='BC'||place==='SSI'?'CAN':place;
 const stages=useMemo(()=>(catalog.data?.stages||[]).filter(s=>s.path),[catalog.data?.stages]),uncovered=(catalog.data?.stages||[]).filter(s=>!s.path);
 const requested=useMemo(()=>{const defaults=stages.filter(s=>s.path&&['extraction','refining','manufacturing'].includes(s.id));return layers?layers.split(','):profile.id==='concrete'?['manufacturing']:profile.id==='steel'?['refining']:(defaults.length?defaults:stages.filter(s=>s.path).slice(0,2)).map(s=>s.id)},[layers,stages,profile.id]);
 const active=useMemo(()=>stages.filter(s=>requested.includes(s.id)&&s.path),[stages,requested]);
 const paths=useMemo(()=>[...new Set(active.map(s=>s.path!))],[active]),key=paths.join('|');
 useEffect(()=>{let current=true;Promise.all(paths.map(async path=>({path,rows:await materialArtifact<JourneyPin[]>(path)}))).then(data=>{if(current)setResult({key,data,error:''})},error=>{if(current)setResult({key,data:[],error:error.message})});return()=>{current=false}},[key,paths]);
 const loading=!catalog.data||result.key!==key;
 const rows=useMemo(()=>{if(result.key!==key)return [];return result.data.flatMap(d=>d.rows.filter(r=>country==='WORLD'||r.country===country).map(r=>({...r,stage:active.find(s=>s.path===d.path)!})))},[result,key,country,active]);
 const filtered=useMemo(()=>rows.filter(r=>(r.name+' '+r.region+' '+r.locality+' '+r.type).toLocaleLowerCase().includes(query.toLocaleLowerCase())),[rows,query]);
 const features=useMemo<SiteFeature[]>(()=>filtered.map(r=>({type:'Feature',geometry:{type:'Point',coordinates:r.coordinates},properties:{id:r.kind+':'+r.id,name:r.name,type:r.type,country:r.country,source_id:r.source,year:r.year,value:null,unit:'',metric:'Source location',basis:'location',stageColor:r.stage.color,mapRadius:5.5,stage:r.stage.label}})),[filtered]);
 const chosen=filtered.find(r=>r.kind+':'+r.id===selected),currentStage=stages.find(s=>s.id===focus)||active[0]||stages[0];
 const showCapacity=!!capacity.data&&((profile.id==='concrete'&&currentStage?.id==='manufacturing')||(profile.id==='steel'&&currentStage?.id==='refining'));
 const metric=capacityOptions(profile.id).some(o=>o[0]===capacityMetric)?capacityMetric:capacityOptions(profile.id)[0][0];
 const shaded=showCapacity&&capacity.data?capacityLayer(capacity.data,metric):undefined;
 const shownSource=chosen?sources.data?.sources[chosen.source]:undefined;
 const leadingCountries=useMemo(()=>currentStage?Object.entries(currentStage.countries).sort((a,b)=>b[1]-a[1]).slice(0,5):[],[currentStage]);
 function showStage(id:string){setFocus(id);const s=stages.find(s=>s.id===id);onLayers(s?.path?id:'none');setSelected('')}
 function showAll(){setFocus('');const core=stages.filter(s=>s.path&&['extraction','refining','manufacturing'].includes(s.id));onLayers((core.length?core:stages.filter(s=>s.path).slice(0,2)).map(s=>s.id).join(',')||'none');setSelected('')}
 const stageIndex=currentStage?stages.findIndex(s=>s.id===currentStage.id):-1;
 return <section className="oj-map" aria-label="Material journey layers">
  <div className="oj-heading"><div><span className="oa-kicker">ONE MATERIAL · MANY PLACES</span><h2>Where does this material go?</h2><p>Choose a step to see the places and quantities we can document. A map point marks a source record; it does not prove that material moved between two points.</p></div><Layers3 size={27}/></div>
  {profile.id==='fuels'&&<FuelEvidence country={country} countries={countries} onEnergy={onEnergy}/>}
  {profile.id==='copper'&&<CopperUseEvidence active={currentStage?.id==='use'}/>}
  <div className="oj-stages" role="group" aria-label="Material journey stages">{stages.map((s,i)=>{const count=country==='WORLD'?s.count:s.countries[country]||0,on=active.some(a=>a.id===s.id);return <button key={s.id} className={currentStage?.id===s.id?'is-focused':''} style={{'--stage-color':s.color} as React.CSSProperties} aria-current={currentStage?.id===s.id?'step':undefined} aria-pressed={on} onClick={()=>showStage(s.id)}><span className="oj-stage-top"><small>{String(i+1).padStart(2,'0')}</small><i>{on?<Check size={11}/>:null}</i></span><strong>{s.label}</strong><span>{s.path?number(count,0)+(count===1?' record':' records'):'Coverage gap'}</span></button>})}</div>
  {uncovered.length>0&&<p className="oa-small oj-uncovered">No source location layer for: {uncovered.map(s=>s.label).join(', ')}.</p>}
  {currentStage&&<div className="oj-stage-scope"><span className="oj-stage-dot" style={{background:currentStage.color}}/><div><strong>{currentStage.label} · step {stageIndex+1} of {stages.length}</strong><p className="oj-stage-description">{currentStage.description}</p><p>{currentStage.scope}</p>{currentStage.path&&<div className="oj-stage-places"><span>Explore source coverage:</span>{leadingCountries.map(([code,count])=><button key={code} onClick={()=>onPlace(code)} aria-pressed={country===code}>{placeName(code,countries)} <b>{number(count,0)}</b></button>)}{country!=='WORLD'&&<button onClick={()=>onPlace('WORLD')}>Worldwide</button>}</div>}{!currentStage.path&&<button className="oa-text-link" onClick={onAccounts}>Open national material & waste accounts<ArrowRight size={14}/></button>}<div className="oj-stage-navigation"><button onClick={()=>showStage(stages[stageIndex-1].id)} disabled={stageIndex<=0}>← Previous stage</button><button onClick={showAll}>Compare source stages</button><button onClick={()=>showStage(stages[stageIndex+1].id)} disabled={stageIndex>=stages.length-1}>Next stage →</button></div></div></div>}
  {showCapacity&&capacity.data&&<CapacityEvidence data={capacity.data} metric={metric} onMetric={setCapacityMetric} place={country} countries={countries} onPlace={onPlace}/> }
  {catalog.error||result.error?<ErrorState message={catalog.error||result.error}/>:<div className="oa-map-workspace oj-workspace"><div><WorldMap countryLayer={shaded} flows={[]} sites={features} countries={countries} place={country} selected={chosen?selected:''} color={profile.color} siteView focusCoordinates={active.length===1?rows.map(r=>r.coordinates):undefined} focusKey={country+':'+active.map(s=>s.id).join(',')+':'+result.key} onPlace={onPlace} onSite={s=>setSelected(s.properties.id)} onFlow={()=>{}}/><div className="oj-map-key">{active.map(s=><span key={s.id}><i style={{background:s.color}}/>{s.label}</span>)}<small>Clusters can contain several stages. Port and shipping overlays are optional context, not evidence of this material’s route.</small></div></div><aside className="oa-map-inspector oj-inspector">
   {loading?<Loading/>:chosen?<><span className="oa-kicker">{chosen.stage.label} · {chosen.year||'Year not supplied'}</span><h3>{chosen.name}</h3><p className="oa-small"><MapPin size={13}/>{placeName(chosen.country,countries)}{chosen.region?' · '+chosen.region:''}</p><dl className="oa-facts"><dt>Source category</dt><dd>{chosen.type}</dd><dt>Coordinates</dt><dd>{chosen.coordinates[1].toFixed(4)}, {chosen.coordinates[0].toFixed(4)}</dd><dt>Source</dt><dd>{shownSource?.publisher||chosen.source}</dd><dt>Location</dt><dd>A source point; it can represent a facility or a larger production area.</dd></dl>{chosen.value!==null&&<div className="oj-record-measure"><strong>{compact(chosen.value)}</strong><span>{chosen.unit} · {chosen.year||'Undated'}</span><p>{chosen.metric} · {chosen.basis}</p></div>}<p className="oa-small">No supplier, buyer or material shipment is inferred from this location.</p><button className="oa-button" onClick={()=>onSites({kind:chosen.kind,place:chosen.country,site:chosen.id,siteType:chosen.type})}>Inspect the full source record<ArrowUpRight size={15}/></button>{shownSource&&<a className="oa-text-link" href={shownSource.url} target="_blank" rel="noreferrer">Primary source<ArrowUpRight size={14}/></a>}<button className="oa-text-link" onClick={()=>setSelected('')}>Back to mapped stages<ArrowRight size={14}/></button></>:<><span className="oa-kicker">{placeName(place,countries)}</span><h3>{number(filtered.length,0)} mapped source records</h3><p>{active.length} selected {active.length===1?'stage':'stages'}. Select any point to see what it represents, when it was recorded and where it came from.</p><div className="oj-stage-counts">{stages.filter(s=>s.path).map(s=><button key={s.id} aria-pressed={active.some(a=>a.id===s.id)} onClick={()=>showStage(s.id)}><span><i style={{background:s.color}}/>{s.label}</span><b>{number(country==='WORLD'?s.count:s.countries[country]||0,0)}</b></button>)}</div>{!rows.length&&<p className="oa-small">{active.length?'The selected source layers have no assigned records for this place. This is a coverage gap.':'This stage has no retained location records. Continue to the next stage or compare the mapped stages.'}</p>}{country!=='WORLD'&&<button className="oa-text-link" onClick={()=>onPlace('WORLD')}>Compare worldwide coverage<ArrowRight size={14}/></button>}<div className="oj-reading-note"><strong>Nearby sites are not necessarily connected.</strong><p>These records come from different sources and years. To follow a shipment or a named mine-to-plant delivery, open the documented connections.</p></div></>}
  </aside></div>}
  <details className="oj-records"><summary>Find a mapped facility <span>{number(rows.length,0)} available records</span></summary><label className="oa-inline-search"><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search name, process or region" aria-label="Search journey facilities"/></label><div className="oj-record-list">{filtered.slice(0,12).map(r=><button key={r.kind+':'+r.id} onClick={()=>setSelected(r.kind+':'+r.id)}><i style={{background:r.stage.color}}/><span>{r.name}<small>{r.type} · {placeName(r.country,countries)}</small></span><ArrowUpRight size={15}/></button>)}</div>{filtered.length>12&&<p className="oa-small">First twelve matching source records. Refine the search to find another facility.</p>}{query&&!filtered.length&&<p>No matching facility in the active layers. Try another stage or a broader name.</p>}</details>
  {['fuels','copper','aluminium','steel'].includes(profile.id)&&<p className="oj-connections-link"><button className="oa-text-link" onClick={onConnections}>Follow documented material connections <ArrowRight size={16}/></button></p>}
  <details className="oa-method"><summary>What connects these stages?</summary><p>The order explains a possible material lifecycle. It is not a traced supply chain. Source records, customs observations and port activity use different boundaries and years; their quantities must not be added.</p><p>Operator-described links are available in the Documented links view. Missing manufacturers, consumers and recovery outcomes remain explicit gaps. General waste infrastructure does not establish a destination for this product.</p><p>{catalog.data?.method}</p><a href={'/data/v16/journeys/'+profile.id+'.json'} target="_blank" rel="noreferrer">Download this layer catalog ↗</a></details>
 </section>;
}

function FuelEvidence({country,countries,onEnergy}:{country:string;countries:Country[];onEnergy:()=>void}){
 const data=useMaterialArtifact<{rows:Array<{country:string;period:string;value:number|null}>}>('/data/v13/energy/crude-production.json');
 const rows=(data.data?.rows||[]).filter(r=>r.country===country&&r.value!==null).sort((a,b)=>b.period.localeCompare(a.period)),latest=rows[0];
 return <div className="oj-fuel-evidence"><div><span className="oa-kicker">{country==='WORLD'?'WORLD · CRUDE OIL':placeName(country,countries).toUpperCase()+' · CRUDE OIL'}</span>{latest?<><strong>{number(latest.value!,0)} <small>barrels / day</small></strong><p>{latest.period} annual average · EIA · includes lease condensate</p></>:<><strong>Oil, gas & coal production</strong><p>National histories are separate from facility and bilateral trade coverage.</p></>}</div><button className="oa-button outline" onClick={onEnergy}>Production & trade totals<ArrowRight size={15}/></button></div>;
}

function CopperUseEvidence({active}:{active:boolean}){
 const result=useMaterialArtifact<{measure:string;publication:string;referenceYear:string;source:string;attribution:string;sectors:{name:string;share:number}[];qualification:string}>('/data/v34/copper-use.json');
 if(!active||!result.data)return null;
 return <div className="oj-use-evidence"><div><span className="oa-kicker">USE STAGE · UNITED STATES</span><h3>Where copper products are used</h3><p>{result.data.measure}. These are national sector shares, separate from the mapped mine locations.</p></div><div className="oj-use-bars">{result.data.sectors.map(s=><div key={s.name}><span>{s.name}</span><div aria-hidden="true"><i style={{width:s.share+'%'}}/></div><strong>{s.share}%</strong></div>)}</div><p>{result.data.qualification} <a href={result.data.source} target="_blank" rel="noreferrer">{result.data.publication} ↗</a></p></div>
}
