'use client';
import {useState} from 'react';
import {Tabs,TabsList,TabsTrigger} from '@/components/ui/tabs';
import {useMaterialArtifact} from '../material-data';
import {Choice,ErrorState,Loading,Refs,number,compact} from './common';
type Metric={country:string;metric:string;value:number;year:number;estimated:boolean};
const fates=[['recycled','Recycled after processing losses','#337257'],['incinerated','Incinerated','#c18549'],['sanitary_landfill','Sanitary landfill','#9a927b'],['mismanaged','Mismanaged waste','#b1664a'],['uncollected_litter','Uncollected litter','#b6a5c2']];
export function PlasticFates(){
 const data=useMaterialArtifact<{records:Metric[]}>('/data/v10/plastic-fates.json');
 const [place,setPlace]=useState('WORLD'),[mode,setMode]=useState('share');
 const rows=data.data?.records.filter(r=>r.country===place)||[],total=rows.find(r=>r.metric==='plastic_waste_generated')?.value;
 const values=fates.map(([code,label,color])=>({code,label,color,value:rows.find(r=>r.metric==='plastic_waste_'+code)?.value}));
 return <section className="oa-material-numbers"><div className="oa-section-heading"><div><span className="oa-kicker">BEYOND THE COLLECTION BIN · OECD MODEL · 2019</span><h2>Out of 100 kg of discarded plastic…</h2><p>A whole-economy view of what ultimately happens to plastic waste.</p></div><Choice label="Plastic waste geography" value={place} onChange={setPlace} options={[{id:'WORLD',name:'World'},{id:'CAN',name:'Canada'},{id:'USA',name:'United States'}]}/></div>{data.error?<ErrorState message={data.error}/>:!total?<Loading/>:<><div className="oa-plastic-stack" role="img" aria-label={values.map(v=>v.label+': '+number((v.value||0)/total*100,2)+'%').join('; ')}>{values.map(v=><span key={v.code} style={{width:((v.value||0)/total*100)+'%',background:v.color}} title={v.label+': '+number((v.value||0)/total*100,2)+'%'}>{(v.value||0)/total>.08?number((v.value||0)/total*100,1)+'%':''}</span>)}</div><Tabs value={mode} onValueChange={setMode} className="oa-dataset-tabs"><TabsList><TabsTrigger value="share">Per 100 kg discarded</TabsTrigger><TabsTrigger value="tonnes">Estimated annual tonnes</TabsTrigger></TabsList></Tabs><div className="oa-fate-cards">{values.map(v=><article key={v.code}><i style={{background:v.color}}/><strong>{v.value==null?'Unreported':mode==='share'?number(v.value/total*100,2)+' kg':compact(v.value)+' t'}</strong><span>{v.label}</span></article>)}</div><p className="oa-note">{compact(total)} tonnes of plastic waste in this model for 2019. The 100 kg view rescales those estimates; it does not predict an individual container’s fate. “Mismanaged” is not the same as ocean leakage. These figures cover all plastic waste, while BC’s end-market shares above describe destinations within one packaging program.</p><Refs ids={['oecd-plastics']}/><details className="oa-method"><summary>Source observations and calculation</summary><p>Each share = modeled fate ÷ modeled waste generated × 100. Values keep the source’s 2019 reference year and modeled status. Small total differences can result from published rounding.</p><pre>{JSON.stringify(rows,null,2)}</pre></details></>}</section>
}
export function HartlandNumbers(){
 const data=useMaterialArtifact<{rows:{year:number;tonnes:number;rate:number;population:number;biosolids:number|null}[]}>('/data/v10/hartland.json');
 const [year,setYear]=useState(2025);const row=data.data?.rows.find(r=>r.year===year);
 return <section className="oa-material-numbers"><div className="oa-section-heading"><div><span className="oa-kicker">A MEASURED LOCAL OUTPUT · CAPITAL REGION</span><h2>How much material stays at Hartland?</h2></div><Choice label="Hartland reporting year" value={String(year)} onChange={v=>setYear(+v)} options={[2025,2024,2023,2022,2021].map(y=>({id:String(y),name:String(y)}))}/></div>{data.error?<ErrorState message={data.error}/>:!row?<Loading/>:<><div className="oa-local-numbers"><div><strong>{number(row.tonnes,0)}</strong><span>tonnes landfilled · {year}</span></div><div><strong>{row.rate}</strong><span>kg per resident · CRD calculation</span></div></div><p>These landfilled quantities exclude blended biosolids. The CRD reports those separately: {row.biosolids==null?'not available':number(row.biosolids,0)+' tonnes'} in {year}.</p><p className="oa-note">Population: {number(row.population,0)}{year===2025?' (projected)':''}. For 2024, CRD uses 464,934 residents; BC’s provincial indicator uses 460,317. Both report 157,189 tonnes, producing different per-person rates: 338 and 341 kg. Keep the two reporting methods separate.</p><Refs ids={['hartland-tonnage']}/></>}</section>
}
