'use client';
import {useEffect,useState} from 'react';
import {ArrowDownRight,ArrowLeft,ArrowRight,ArrowUpRight,BookOpen,Check,ChevronDown,Code2,Copy,Factory,Globe2,Layers3,MapPin,Search,Share2,MoreHorizontal,X,LocateFixed} from 'lucide-react';
import {CommandDialog,CommandEmpty,CommandGroup,CommandInput,CommandItem,CommandList} from '@/components/ui/command';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {Sheet,SheetContent,SheetTitle,SheetDescription} from '@/components/ui/sheet';
import type {Country} from '../world/model';
import {facilityKinds,kindLabels} from '@/packages/material-world/model';
import {facilities,profiles,profileById,type Facility} from './data';
import {FacilitySheet} from './common';
import {PlacePicker,placeName} from './PlaceContext';
import {useBrowserLocale} from '../useBrowserLocale';
import {setNumberLocale} from '../world/model';
import placeDirectory from '@/public/data/v11/countries.json';
import MaterialPage from './MaterialPage';
import TradePage from './TradePage';
import PlacesPage from './PlacesPage';
import WastePage from './WastePage';
import {materialSiteLayers} from './materialSites';
import FacilitiesPage,{emptySiteFilters} from './FacilitiesPage';
import AboutPage from './AboutPage';
import SourcesContent from './SourcesContent';
import DataPage from './DataPage';
import {ThemeToggle} from './AppTheme';
import HomePage from './HomePage';
import LocalPage from './LocalPage';
import {atlasUrl,defaultAtlasState as defaults,readAtlasState,type AtlasState as State} from './atlasState';
import {moveToView} from './motion';
import {AtlasLink} from './AtlasLink';
import {DropdownMenu,DropdownMenuContent,DropdownMenuItem,DropdownMenuTrigger} from '@/components/ui/dropdown-menu';
import {TransportContext} from '../world/TransportState';
import './atlas.css';
import './evidence.css';
import './experience.css';
import './theme.css';
import './clarity.css';
import './release.css';
import './depth.css';
import './energy.css';
import './refinement.css';
import './research.css';
import './brand-home.css';
export type {AtlasView} from './atlasState';
const nav=[{id:'home',label:'Home',icon:Globe2},{id:'local',label:'Local',icon:LocateFixed},{id:'materials',label:'Materials',icon:Layers3},{id:'waste',label:'Waste',icon:BookOpen},{id:'places',label:'Places',icon:MapPin},{id:'trade',label:'Trade',icon:ArrowDownRight},{id:'facilities',label:'Facilities',icon:Factory},{id:'data',label:'Data / MCP',icon:Code2}] as const;
function productMaterial(hs:string){
 if(hs.startsWith('2603')||hs.startsWith('74'))return 'copper';
 const chapter=+hs.slice(0,2);
 return chapter===39?'plastic':chapter===47||chapter===48?'paper':chapter===72||chapter===73?'steel':chapter===76?'aluminium':chapter===70?'glass':chapter===85?'electronics':chapter===44?'wood':chapter===27?'fuels':chapter===25||chapter===68?'concrete':chapter>=1&&chapter<=24?'food':chapter>=50&&chapter<=63?'textiles':'paper';
}
export default function MaterialAtlas({initial={}}:{initial?:Partial<State>}){
 const [state,setState]=useState<State>({...defaults,...initial}),[canBack,setCanBack]=useState(false),[search,setSearch]=useState(false),[searchQuery,setSearchQuery]=useState(''),[filter,setFilter]=useState(''),[sources,setSources]=useState(false),[materialPicker,setMaterialPicker]=useState(false),[materialQuery,setMaterialQuery]=useState(''),[sharing,setSharing]=useState(false),[copied,setCopied]=useState(false),[copyError,setCopyError]=useState(false),[shareUrl,setShareUrl]=useState(''),[facility,setFacility]=useState<Facility|null>(null);
 const countries=placeDirectory as Country[];
 const profile=profileById(state.material);

 const materialContext=state.view==='materials'||state.view==='trade'&&state.dataset==='commodity';
 const displayLocale=useBrowserLocale();
 useEffect(()=>setNumberLocale(displayLocale),[displayLocale]);
 // The URL is only readable on the client; sync it into state once after hydration.
 // eslint-disable-next-line react-hooks/set-state-in-effect
 useEffect(()=>{setState(readAtlasState(location,initial));if(typeof history.state?.overshootDepth!=='number')history.replaceState({...history.state,overshootDepth:0},'');setCanBack(history.state.overshootDepth>0);const pop=()=>{moveToView(()=>setState(readAtlasState(location,initial)));setCanBack((history.state?.overshootDepth||0)>0);setFacility(null)};window.addEventListener('popstate',pop);return()=>window.removeEventListener('popstate',pop)},[]);
 useEffect(()=>{document.title=state.view==='home'?'OVERSHOOT — A planetary atlas of material flows':`${state.view==='materials'?profile.name:state.view==='about'?'About':state.view==='data'?'Open data & MCP':nav.find(n=>n.id===state.view)?.label} · OVERSHOOT`},[state.view,profile.name]);
 useEffect(()=>{const key=(event:KeyboardEvent)=>{if((event.metaKey||event.ctrlKey)&&event.key==='k'){event.preventDefault();setSearch(open=>!open)}};window.addEventListener('keydown',key);return()=>window.removeEventListener('keydown',key)},[]);
 function go(update:Partial<State>,scroll=true){const next={...state,...update};if(update.place&&update.place!==state.place){if(!('portId' in update))next.portId='';if(!('wastePlace' in update))next.wastePlace='';if(!('site' in update))next.site=''}if(update.kind&&update.kind!==state.kind&&!('site' in update))next.site='';if(update.material&&update.material!==state.material){if(!update.layer)next.layer='';next.journeyLayers='';if(!('network' in update))next.network='';next.portId='';if(!update.productionItem)next.productionItem=''}if(!next.product&&!profileById(next.material).codes.includes(next.form))next.form=profileById(next.material).codes[0]||'';if(next.place==='WORLD')next.direction='out';const depth=history.state?.overshootDepth||0;if(Object.keys(update).every(k=>['portMonth','portId','siteQuery','site','wasteQuery'].includes(k)))history.replaceState({...history.state,overshootDepth:depth},'',atlasUrl(next));else if(atlasUrl(next)!==location.pathname+location.search){history.pushState({overshootDepth:depth+1},'',atlasUrl(next));setCanBack(true)}setFacility(null);if(scroll){moveToView(()=>setState(next),true);document.getElementById('material-content')?.focus({preventScroll:true})}else setState(next)}
 function material(id:string){const p=profileById(id);go({view:'materials',material:id,form:p.codes[0]||'',product:'',direction:'out'})}
 function trade(place=state.place,product=''){const id=product?productMaterial(product):state.material;go({view:'trade',dataset:'commodity',place,material:id,product,form:product?product.slice(0,4):profileById(id).codes[0]||'',direction:'out'})}
 function siteState(place=state.place):State{const related=materialContext?materialSiteLayers[profile.id]?.[0]:undefined;return {...state,...emptySiteFilters,view:'facilities',place,site:'',kind:related?.kind||(['CAN','BC','SSI','USA'].includes(place)?'landfill':'industry'),siteType:related?.type||''}}
 function sites(place=state.place){go(siteState(place))}
 async function share(){setShareUrl(location.href);setSharing(true);setCopied(false);setCopyError(false);try{await navigator.clipboard.writeText(location.href);setCopied(true)}catch{}}
 const filtered=profiles.filter(p=>(p.name+' '+p.object+' '+p.aliases).toLowerCase().includes(filter.toLowerCase()));
 return <TransportContext.Provider value={{state,update:patch=>go(patch,false)}}><div className={'oa oa-release'+(state.view==='home'?' oa-is-home':state.view==='facilities'?' oa-view-facilities':'')} data-number-locale={displayLocale}>
  <a className="oa-skip" href="#material-content">Skip to content</a>
  <header className="oa-header"><AtlasLink className="oa-brand" href="/" onNavigate={()=>go({...defaults})} aria-label="Overshoot home"><span className="oa-brand-lockup"><img src="/overshoot-lockup.png" alt="" width="1500" height="750"/></span><small>A planetary atlas of material flows</small></AtlasLink><nav className="oa-nav" aria-label="Primary navigation"><div data-slot="tabs-list">{nav.map(n=>{const next=n.id==='home'?defaults:n.id==='facilities'?(state.view==='facilities'?state:siteState()):{...state,view:n.id};return <AtlasLink key={n.id} href={atlasUrl(next)} onNavigate={()=>go(next)} data-slot="tabs-trigger" data-state={state.view===n.id?'active':'inactive'} aria-current={state.view===n.id?'page':undefined}><n.icon size={17}/>{n.label}</AtlasLink>})}</div></nav><div className="oa-header-actions"><ThemeToggle/><button className="oa-about-link" onClick={()=>go({view:'about'})} aria-label="About OVERSHOOT">About</button><button onClick={()=>setSearch(true)} aria-label="Search materials, places and operations" title="Search (⌘ / Ctrl K)"><Search size={19}/><span>Search</span></button><button onClick={()=>setSources(true)} aria-label="Sources and coverage"><BookOpen size={18}/></button><button onClick={share} aria-label="Share this view"><Share2 size={18}/></button><DropdownMenu><DropdownMenuTrigger asChild><button className="oa-more-menu" aria-label="More options"><MoreHorizontal size={20}/></button></DropdownMenuTrigger><DropdownMenuContent align="end"><DropdownMenuItem onSelect={()=>go({view:'about'})}><Globe2 size={16}/>About & how to use</DropdownMenuItem><DropdownMenuItem onSelect={()=>setSearch(true)}><Search size={16}/>Search everything</DropdownMenuItem><DropdownMenuItem onSelect={()=>setSources(true)}><BookOpen size={16}/>Sources & coverage</DropdownMenuItem><DropdownMenuItem onSelect={share}><Share2 size={16}/>Share this view</DropdownMenuItem></DropdownMenuContent></DropdownMenu></div></header>
  <div className={'oa-layout'+(!materialContext?' oa-layout-wide':'')}>
   {materialContext&&<aside className="oa-sidebar" aria-label="Materials"><div className="oa-sidebar-heading"><span className="oa-kicker">MATERIAL GUIDES</span><h2>Choose a material.</h2></div><label className="oa-sidebar-search"><Search size={15}/><input aria-label="Find a material" value={filter} onChange={e=>setFilter(e.target.value)} placeholder="A box, phone, can…"/>{filter&&<button aria-label="Clear material search" onClick={()=>setFilter('')}><X size={14}/></button>}</label><div className="oa-material-list">{filtered.map(p=><button key={p.id} className={materialContext&&state.material===p.id?'active':''} onClick={()=>material(p.id)} aria-current={materialContext&&state.material===p.id?'true':undefined}><span style={{color:p.color,background:p.color+'13'}}>{p.symbol}</span><div><strong>{p.name}</strong><small>{p.object}</small></div><ArrowRight size={14}/></button>)}{!filtered.length&&<p className="oa-small">No matching material. Try a broader name.</p>}</div><button className="oa-primer-link" onClick={()=>go({view:'about'})}><Globe2 size={23}/><span>About OVERSHOOT<small>How to use the app</small></span><ArrowUpRight size={16}/></button></aside>}
   <main id="material-content" className="oa-content" tabIndex={-1}>
    {state.view==='local'&&<nav className="oa-scope-trail" aria-label="Investigation scope">{canBack&&<button onClick={()=>history.back()}><ArrowLeft size={15}/>Previous view</button>}<button onClick={()=>go({view:'places',place:'WORLD',placeView:'materials',wastePlace:'',site:''})}><Globe2 size={15}/>World overview</button><ArrowRight size={13} aria-hidden="true"/><span aria-current="location">Local lens{state.localPlace?' · '+state.localPlace:''}</span></nav>}
    {state.view!=='about'&&state.view!=='home'&&state.view!=='data'&&state.view!=='local'&&<><nav className="oa-scope-trail" aria-label="Investigation scope">{canBack&&<button onClick={()=>history.back()}><ArrowLeft size={15}/>Previous view</button>}<button onClick={()=>go({view:'places',place:'WORLD',placeView:'materials',wastePlace:'',site:''})}><Globe2 size={15}/>World overview</button><ArrowRight size={13} aria-hidden="true"/>{state.place!=='WORLD'&&<><button onClick={()=>go({place:'WORLD',wastePlace:'',site:'',product:'',direction:'out'})}>Compare this view worldwide</button><ArrowRight size={13} aria-hidden="true"/></>}<span aria-current="location">{state.place==='WORLD'?'Worldwide':placeName(state.place,countries)} · {state.view==='places'?'Material account':state.view==='materials'?profile.name:nav.find(n=>n.id===state.view)?.label}</span></nav><div className="oa-context-bar"><PlacePicker value={state.place} countries={countries} onChange={place=>go({place,product:'',direction:'out'},false)}/><div className="oa-view-purpose"><strong>{state.view==='materials'?'Follow a material':state.view==='waste'?'Research waste':state.view==='places'?'Compare places':state.view==='trade'?'Follow trade':'Find a site'}</strong><span>{state.view==='materials'?'Origins, uses and what happens next.':'Choose a place to see its available records.'}</span></div>{materialContext&&<button className="oa-mobile-material" onClick={()=>{setMaterialQuery('');setMaterialPicker(true)}}><Layers3 size={17}/>{profile.name}<ChevronDown size={16}/></button>}</div></>}
    <div className="oa-view" key={state.view}>
    {state.view==='local'&&<LocalPage state={state} countries={countries} onChange={patch=>go(patch,!!patch.view)}/>}
    {state.view==='home'&&<HomePage countries={countries} onGo={go} onSources={()=>setSources(true)} onSearch={()=>setSearch(true)}/>}
    {state.view==='waste'&&<WastePage state={state} countries={countries} onChange={patch=>go(patch,false)} onGo={go}/>}
    {state.view==='data'&&<DataPage onGo={go}/>}
    {state.view==='about'&&<AboutPage onGo={update=>go({...update,product:''})} onSources={()=>setSources(true)}/>}
    {state.view==='materials'&&<MaterialPage network={state.network} onNetwork={(network,place)=>go({network,place,layer:'connections'},false)} journeyLayers={state.journeyLayers} onJourneyLayers={journeyLayers=>go({journeyLayers},false)} productionSelection={state} onProductionSelection={update=>go(update,false)} energySelection={state} onEnergySelection={update=>go(update,false)} layer={state.layer} onLayer={layer=>go({layer,...(layer==='production'?{energyRegion:'all' as const}:{})},false)} key={profile.id} profile={profile} place={state.place} countries={countries} form={profile.codes.includes(state.form)?state.form:profile.codes[0]||''} direction={state.direction} onMapChange={p=>go({...p,product:''},false)} onSites={selection=>go({...siteState(),...selection})} onMaterial={material} onTrade={(form,place)=>go({view:'trade',dataset:'commodity',form:form||state.form||profile.codes[0]||'',place:place||state.place,product:''})} onFacility={setFacility} onPlaces={(place=state.place,waste=false)=>go({view:'places',place,placeView:waste?'waste':'materials',wastePlace:''})} onControlledTrade={(direction='out',place=state.place)=>go({view:'trade',dataset:'controlled',place,direction})}/>}
    {state.view==='trade'&&<TradePage key={profile.id} dataset={state.dataset} profile={profile} place={state.place} form={state.form} product={state.product} direction={state.direction} countries={countries} onChange={p=>go(p,false)} onCountry={place=>go({view:'places',place})}/>}
    {state.view==='places'&&<PlacesPage onGo={go} onEnergy={energyMeasure=>go({view:'materials',material:'fuels',form:'2709',layer:'production',energyMeasure,energyPeriod:'',energyRegion:'all'})} placeView={state.placeView} wastePlace={state.wastePlace} year={state.accountYear} onYear={accountYear=>go({accountYear},false)} onView={placeView=>go({placeView,wastePlace:''},false)} onWastePlace={(place,wastePlace)=>go({place,wastePlace,placeView:'waste'},false)} onWaste={(direction,place=state.place)=>go({view:'trade',dataset:'controlled',place,direction})} place={state.place} countries={countries} onPlace={place=>go({place})} onMaterial={material} onTrade={trade} onFacility={setFacility} onSites={sites}/>}
    {state.view==='facilities'&&<FacilitiesPage filters={state} site={state.site} place={state.place} kind={state.kind} countries={countries} onChange={p=>go(p,false)}/>}
    </div>
    <footer className="oa-footer"><button className="oa-footer-brand" onClick={()=>go({...defaults})}><span className="oa-footer-lockup"><img src="/overshoot-lockup.png" alt="" width="1500" height="750"/></span> <i>by Gaia AI</i></button><span className="oa-footer-note">A planetary atlas of material flows</span><button onClick={()=>go({view:'about'})}>About & how to use</button><button onClick={()=>setSources(true)}>Sources & coverage<ArrowUpRight size={14}/></button><AtlasLink href="/data" onNavigate={()=>go({view:'data'})}>Open data & MCP</AtlasLink></footer>
   </main>
  </div>
  <FacilitySheet facility={facility} onChange={setFacility}/>
  <CommandDialog open={materialPicker} onOpenChange={setMaterialPicker} title="Choose a material" description="Start with an everyday object or material." className="oa-dialog"><CommandInput value={materialQuery} onValueChange={setMaterialQuery} placeholder="A box, phone, can…"/><CommandList><CommandEmpty>Try a broader material name.</CommandEmpty><CommandGroup heading="Materials">{profiles.map(p=><CommandItem key={p.id} value={p.name+' '+p.object+' '+p.aliases} onSelect={()=>{material(p.id);setMaterialPicker(false)}}><span className="oa-search-symbol" style={{color:p.color}}>{p.symbol}</span><span>{p.name}<small>{p.object}</small></span></CommandItem>)}</CommandGroup></CommandList></CommandDialog>
  <CommandDialog open={search} onOpenChange={setSearch} title="Find a material, place or operation" description="Jump directly to a material, regional account or named facility." className="oa-dialog"><CommandInput value={searchQuery} onValueChange={setSearchQuery} placeholder="A material, country, city or facility name…"/><CommandList><CommandEmpty>No guide or place matches. Search the site records below.</CommandEmpty>{searchQuery.trim().length>1&&<CommandGroup heading="Search source records worldwide">{facilityKinds.map(kind=><CommandItem key={kind} value={searchQuery+' ' +kindLabels[kind]} onSelect={()=>{go({...siteState('WORLD'),kind,siteQuery:searchQuery.trim()});setSearch(false)}}><Search size={17}/><span>“{searchQuery.trim()}” in {kindLabels[kind].toLowerCase()}</span><ArrowRight size={15}/></CommandItem>)}</CommandGroup>}<CommandGroup heading="Materials">{profiles.map(p=><CommandItem key={p.id} value={p.name+' '+p.object+' '+p.aliases} onSelect={()=>{material(p.id);setSearch(false)}}><span className="oa-search-symbol" style={{color:p.color}}>{p.symbol}</span><span>{p.name}<small>{p.object}</small></span></CommandItem>)}</CommandGroup><CommandGroup heading="Named operations">{facilities.map(f=><CommandItem key={f.id} value={f.name+' '+f.place+' '+f.kind} onSelect={()=>{setFacility(f);setSearch(false)}}><Factory size={17}/><span>{f.name}<small>{f.place} · {f.kind}</small></span></CommandItem>)}</CommandGroup><CommandGroup heading="Places">{[{id:'BC',name:'British Columbia'},{id:'SSI',name:'Salt Spring Island'},...countries].map(c=><CommandItem key={c.id} value={c.name+' '+c.id} onSelect={()=>{go({view:'places',place:c.id});setSearch(false)}}><MapPin size={17}/>{c.name}</CommandItem>)}</CommandGroup></CommandList></CommandDialog>
  <Sheet open={sources} onOpenChange={setSources}><SheetContent className="oa-sheet"><SheetTitle>Sources & coverage</SheetTitle><SheetDescription>Data sources, reporting years and coverage.</SheetDescription><SourcesContent onGo={update=>{setSources(false);go({...defaults,...update})}}/></SheetContent></Sheet>
  <Dialog open={sharing} onOpenChange={setSharing}><DialogContent className="oa-dialog"><DialogTitle>{copied?'Link copied':'Share this view'}</DialogTitle><DialogDescription>The link keeps the material, place, year, filters and selected record.</DialogDescription><input aria-label="Shareable view URL" className="oa-share-input" value={shareUrl} readOnly onFocus={e=>e.target.select()}/><button className="oa-button" onClick={async()=>{try{await navigator.clipboard.writeText(shareUrl);setCopied(true);setCopyError(false)}catch{setCopied(false);setCopyError(true)}}}>{copied?<Check size={17}/>:<Copy size={17}/>}Copy link</button>{copyError&&<p role="status" className="oa-small">Select the link above and copy it.</p>}</DialogContent></Dialog>
 </div></TransportContext.Provider>
}
