'use client';
import {useState} from 'react';
import type {ProductionSelection} from '@/packages/material-world/production';
import type {OpenMaterialSites} from './MaterialSitesMap';
import type {EnergySelection} from './EnergyMap';
import MaterialGeography,{type MaterialLayer} from './MaterialGeography';
import {PlaceCoverage,placeName} from './PlaceContext';
import type {Country} from '../world/model';
import {PlasticFates,HartlandNumbers} from './MaterialNumbers';
import {ArrowRight,ArrowUpRight,ChevronDown,Factory,Leaf,MapPin as MapPinIcon,Package,Pickaxe,Recycle,Route,Trash2,Waves,Zap} from 'lucide-react';
import {Tabs,TabsList,TabsTrigger} from '@/components/ui/tabs';
import {profiles,facilities,endMarkets,type Profile,type Facility} from './data';
import {MarketBar,Refs} from './common';
const icons=[Pickaxe,Factory,Package,Recycle,ArrowRight];
const takeaways:Record<string,string>={paper:'A fibre’s origin and the paper mill can be in different countries.',plastic:'A recycling shipment is not yet a recycling outcome.',copper:'Ore, concentrate and refined metal are different material flows.',aluminium:'Mining bauxite and recovering aluminium scrap are different routes to metal.',steel:'Steel production can begin with iron ore or recovered scrap.',glass:'Collection, sorting and remelting are separate steps.',electronics:'One device contains many materials with different recovery paths.',food:'Food production, consumption and waste are different quantities.',concrete:'Buildings hold material for decades before demolition.',wood:'Harvested wood can become fuel, construction material or fibre.',textiles:'Fibre, fabric, clothing and used garments have different production histories.',fuels:'Fuel production, use and emissions need separate accounts.',garbage:'Disposal creates a long-lived stock, with water and gas outputs.','rigid-plastic':'A polymer’s recyclability does not establish its local collection route.'};

export default function MaterialPage({network,onNetwork,journeyLayers,onJourneyLayers,profile,place,countries,form,direction,layer,onLayer,energySelection,onEnergySelection,productionSelection,onProductionSelection,onMapChange,onSites,onMaterial,onTrade,onFacility,onPlaces,onControlledTrade}:{network:string;onNetwork:(id:string,place:string)=>void;journeyLayers:string;onJourneyLayers:(layers:string)=>void;layer:MaterialLayer;onLayer:(layer:MaterialLayer)=>void;productionSelection:ProductionSelection;onProductionSelection:(v:Partial<ProductionSelection>)=>void;energySelection:EnergySelection;onEnergySelection:(v:Partial<EnergySelection>)=>void;profile:Profile;place:string;countries:Country[];form:string;direction:'in'|'out';onMapChange:(p:{form?:string;direction?:'in'|'out';place?:string})=>void;onSites:OpenMaterialSites;onMaterial:(id:string)=>void;onTrade:(form?:string,place?:string)=>void;onFacility:(f:Facility)=>void;onPlaces:(place?:string,waste?:boolean)=>void;onControlledTrade:(direction?:'in'|'out',place?:string)=>void}){
 const [stage,setStage]=useState(0),[caseId,setCaseId]=useState('bc');
 function showStage(next:number){setStage(next);document.getElementById('material-process')?.scrollIntoView({behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'instant':'smooth',block:'start'})}
 const s=profile.steps[stage]||profile.steps[0];
 const market=endMarkets.find(m=>m.material===profile.waste);
 return <div className="oa-material-page" style={{'--material':profile.color} as React.CSSProperties}>
  <div className="oa-page-title"><div><span className="oa-kicker">MATERIAL GUIDE</span><h1>{profile.name}<span className="oa-material-symbol">{profile.symbol}</span></h1><p>{profile.intro}</p></div></div>
  {profile.id==='textiles'&&<aside className="oa-textile-scope"><div><span className="oa-kicker">WHAT THE FACILITY COUNT MEANS</span><h2>10,736 tagged source locations. Not all textile producers.</h2><p>Climate TRACE’s 2025 category combines textile, leather and apparel sites. This inventory has uneven source coverage and estimated emissions; it is not a global factory census. FAO production below measures natural fibre inputs by country, not garment factories. Do not read either number as the number of producers on Earth.</p><Refs ids={['climate-trace-2025']}/></div><button className="oa-button outline" onClick={()=>{onLayer('journey');onJourneyLayers('manufacturing');document.getElementById('material-map')?.scrollIntoView({behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'instant':'smooth'})}}>See mapped manufacturing <ArrowRight size={16}/></button></aside>}
  <nav className="oa-section-nav" aria-label="On this material page"><a href="#material-map"><span>Map & data</span></a><a href="#material-process"><span>How it changes</span></a><a href="#material-evidence"><span>After use & local evidence</span></a></nav>
  <div id="material-map"><MaterialGeography network={network} onNetwork={onNetwork} journeyLayers={journeyLayers} onJourneyLayers={onJourneyLayers} productionSelection={productionSelection} onProductionSelection={onProductionSelection} onSites={onSites} energySelection={energySelection} onEnergySelection={onEnergySelection} layer={layer} onLayer={onLayer} profile={profile} place={place} countries={countries} form={form} direction={direction} onChange={onMapChange} onTrade={()=>onTrade()} onPlaces={onPlaces} onStage={showStage}/></div>
  <div className="oa-answer-layout" id="material-process">
   <section className="oa-answer-main">
    <div className="oa-section-heading"><div><span className="oa-kicker">02 / THE PROCESS</span><h2>What happens to it?</h2></div><span className="oa-small">Select any stage</span></div>
    <div className="oa-process" role="group" aria-label="Material transformation stages">{profile.steps.map((st,i)=>{const Icon=icons[i];return <button key={st.title} onClick={()=>setStage(i)} aria-pressed={stage===i}><span className="oa-step-number">0{i+1}</span><Icon size={25}/><strong>{st.title}</strong>{i<4&&<ArrowRight className="oa-step-arrow" size={17}/>}</button>})}</div>
    <div className="oa-process-detail" key={stage} aria-live="polite">
     <span className="oa-kicker">STAGE {stage+1} · HOW THE MATERIAL CHANGES</span>{s.facilities?.length?<span className="oa-example-label">Named operations are documented Canadian examples</span>:null}<h3>{s.title}</h3><p>{s.process}</p>
     <div className="oa-io"><div><span>Comes in</span><strong>{s.input}</strong></div><ArrowRight size={21}/><div><span>Comes out</span><strong>{s.output}</strong></div></div>
     <div className="oa-residue"><Trash2 size={17}/><div><strong>What else remains?</strong><p>{s.residue}</p></div></div>
     {s.facilities&&<div className="oa-step-facilities">{s.facilities.map(id=>{const f=facilities.find(f=>f.id===id)!;return <button key={id} onClick={()=>onFacility(f)}><Factory size={15}/>{f.name}<ArrowUpRight size={15}/></button>})}</div>}
     <Refs ids={s.refs}/>
    </div>
   </section>
   <aside className="oa-material-answer oa-material-origin"><span className="oa-kicker">START AT THE SOURCE</span><h2>Where does it come from?</h2><div className="oa-origin"><Leaf size={23}/><p>{profile.origin}</p></div><div className="oa-origin-next"><span className="oa-kicker">LOOK BEYOND THE BIN</span><h3>{takeaways[profile.id]}</h3><p>Each stage has an input, a useful output and something left over. Select a stage to see all three and inspect its sources.</p><button className="oa-text-link" onClick={()=>onPlaces()}>Material accounts for {placeName(place,countries)}<ArrowRight size={16}/></button></div></aside>
  </div>
  <div id="material-evidence"><div className="oa-section-heading"><div><span className="oa-kicker">03 / LOCAL RECORDS</span><h2>What happens locally?</h2><p>Check the source coverage for your place. The documented regional cases below have their own boundaries and sources.</p></div></div></div>
  <PlaceCoverage place={place} countries={countries} onAccounts={()=>onPlaces()} onWaste={onControlledTrade} onSites={onSites}/>
  {market&&<details className="oa-regional-fold" open={['CAN','BC','SSI'].includes(place)}><summary>See a regional example: British Columbia’s recycling end markets<ChevronDown size={18}/></summary><aside className="oa-regional-example"><span className="oa-kicker">REGIONAL EXAMPLE · BRITISH COLUMBIA · 2025</span><h2>{profile.point}</h2><MarketBar values={[market.bc,market.canada,market.us,market.other]}/><p className="oa-small">{profile.waste==='metal'?'Metal packaging is reported as a combined group. ':''}Shares of reported recycling end markets. These are not collection or recycling rates.</p><Refs ids={['rbcReport2025']}/><button className="oa-text-link" onClick={()=>onPlaces('BC')}>Compare the region’s material streams<ArrowRight size={16}/></button></aside></details>}

  {['plastic','rigid-plastic'].includes(profile.id)&&<PlasticFates/>}
  {profile.id==='garbage'&&<HartlandNumbers/>}
  {profile.id==='copper'&&<section className="oa-case-study"><div className="oa-section-heading"><div><span className="oa-kicker">A DOCUMENTED INDUSTRIAL CONNECTION</span><h2>Follow a real industrial route</h2></div><Tabs value={caseId} onValueChange={setCaseId}><TabsList><TabsTrigger value="bc">BC concentrate</TabsTrigger><TabsTrigger value="qc">Québec refining</TabsTrigger></TabsList></Tabs></div>{caseId==='bc'?<><div className="oa-route-case"><button onClick={()=>onFacility(facilities.find(f=>f.id==='hvc')!)}><Pickaxe size={25}/><strong>Highland Valley</strong><span>Mine & concentrator</span><small>Copper concentrate</small></button><div className="oa-route-label"><span>Truck</span><ArrowRight/></div><button onClick={()=>onFacility(facilities.find(f=>f.id==='ashcroft')!)}><Route size={25}/><strong>Ashcroft</strong><span>Rail-loading facility</span><small>Concentrate remains concentrate</small></button><div className="oa-route-label"><span>Onward export</span><ArrowRight/></div><div className="oa-route-unknown"><Factory size={25}/><strong>Overseas smelters</strong><span>Individual buyers not identified</span></div></div><p>Teck names the mine-to-Ashcroft connection in its 2022 transport announcement and describes overseas smelters as concentrate customers. This is an operator-described route, not a tracked shipment.</p><Refs ids={['ashcroft','hvc']}/></>:<><div className="oa-route-case"><button onClick={()=>onFacility(facilities.find(f=>f.id==='horne')!)}><Factory size={25}/><strong>Horne Smelter</strong><span>Rouyn-Noranda</span><small>99.1% copper anodes</small></button><div className="oa-route-label"><span>Rail or truck</span><ArrowRight/></div><button onClick={()=>onFacility(facilities.find(f=>f.id==='ccr')!)}><Zap size={25}/><strong>CCR refinery</strong><span>Montréal-Est</span><small>Electrorefining</small></button><div className="oa-route-label"><span>Product</span><ArrowRight/></div><div className="oa-route-unknown"><Package size={25}/><strong>Copper cathodes</strong><span>99.99% reported purity</span></div></div><p>Horne documents sending anodes to CCR. Anode slimes follow another path for precious-metal recovery. Purity describes the product’s composition; it is not the percentage of incoming waste recycled.</p><Refs ids={['horne','copper-process']}/></>}</section>}
  {profile.id==='garbage'&&<section className="oa-case-study"><span className="oa-kicker">ONE INPUT, SEVERAL OUTPUTS</span><h2>What leaves a landfill?</h2><div className="oa-output-branches"><button onClick={()=>onFacility(facilities.find(f=>f.id==='hartland')!)}><Trash2/><h3>Waste stays in place</h3><p>Some material remains in an engineered deposit and needs long-term management.</p></button><button onClick={()=>{showStage(3)}}><Zap/><h3>Gas enters another system</h3><p>Hartland’s captured gas is upgraded for the FortisBC network.</p></button><button onClick={()=>{showStage(4)}}><Waves/><h3>Water needs treatment</h3><p>Collected leachate passes through lagoons and testing to the sanitary sewer.</p></button></div><Refs ids={['hartlandProcess']}/></section>}
  <section className="oa-evidence-section"><div className="oa-section-heading"><div><span className="oa-kicker">CONTINUE YOUR INVESTIGATION</span><h2>Follow the evidence</h2></div><span className="oa-small">Each view retains its own geography and measurement</span></div><div className="oa-next-actions"><button onClick={()=>onSites({place})}><MapPinIcon/><h3>Map source locations</h3><p>Find mapped facilities near a place, with source records and coverage limits.</p><ArrowRight/></button><button onClick={()=>onTrade()}><Route/><h3>Investigate reported trade</h3><p>Choose a place and material form to see its reported partners.</p><ArrowRight/></button><button onClick={()=>onPlaces()}><Factory/><h3>Inspect a country’s material accounts</h3><p>See extraction, imports, exports and treatment within the country.</p><ArrowRight/></button></div></section>
  <section className="oa-questions-section"><span className="oa-kicker">QUESTIONS WORTH ASKING</span>{profile.questions.map((q,i)=><details key={q.q} open={i===0}><summary>{q.q}<ChevronDown size={19}/></summary><p>{q.a}</p><Refs ids={q.refs}/></details>)}</section>
  <div className="oa-continue"><div><span className="oa-kicker">KEEP FOLLOWING</span><h2>Choose another material</h2></div><div>{profiles.filter(p=>p.id!==profile.id).slice(0,5).map(p=><button onClick={()=>onMaterial(p.id)} key={p.id}><span style={{color:p.color}}>{p.symbol}</span>{p.name}<ArrowUpRight size={15}/></button>)}</div></div>
 </div>
}
