'use client';
import {useEffect,useRef,useState} from 'react';
import {X} from 'lucide-react';
import './newsletter.css';

const KEY='overshoot-mail-invite-v1';
export function NewsletterInvite(){
 const [open,setOpen]=useState(false),[email,setEmail]=useState(''),[consent,setConsent]=useState(false),[status,setStatus]=useState(''),[sending,setSending]=useState(false);
 const dialog=useRef<HTMLDivElement>(null),closeButton=useRef<HTMLButtonElement>(null),previous=useRef<HTMLElement|null>(null);
 useEffect(()=>{let seen=false;try{seen=localStorage.getItem(KEY)==='seen'}catch{}if(seen)return;const timer=window.setTimeout(()=>{previous.current=document.activeElement as HTMLElement;setOpen(true)},2200);return()=>clearTimeout(timer)},[]);
 useEffect(()=>{if(!open)return;closeButton.current?.focus();function keydown(e:KeyboardEvent){if(e.key==='Escape')dismiss();if(e.key==='Tab'){const items=dialog.current?.querySelectorAll<HTMLElement>('button:not([disabled]),input:not([disabled]),a[href]');if(!items?.length)return;const first=items[0],last=items[items.length-1];if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus()}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus()}}}window.addEventListener('keydown',keydown);return()=>window.removeEventListener('keydown',keydown)},[open]);
 function dismiss(){try{localStorage.setItem(KEY,'seen')}catch{}setOpen(false);previous.current?.focus()}
 async function submit(e:React.FormEvent){e.preventDefault();if(!consent)return;setSending(true);setStatus('');try{const response=await fetch('/api/subscribe',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({email,consent,path:location.pathname,website:''})});const result=await response.json() as {ok?:boolean;error?:string};if(!response.ok||!result.ok)throw new Error(result.error||'Please try again.');try{localStorage.setItem(KEY,'seen')}catch{}setStatus('You’re on the list. Thank you.');setEmail('');setTimeout(()=>{setOpen(false);previous.current?.focus()},1800)}catch(error){setStatus(error instanceof Error?error.message:'Please try again.')}finally{setSending(false)}}
 if(!open)return null;
 return <div className="oa-invite-backdrop" onMouseDown={e=>{if(e.target===e.currentTarget)dismiss()}}><div className="oa-invite" role="dialog" aria-modal="true" aria-labelledby="oa-invite-title" aria-describedby="oa-invite-desc" ref={dialog}><button className="oa-invite-close" ref={closeButton} onClick={dismiss} aria-label="Dismiss email invitation"><X size={20}/></button><span className="oa-invite-kicker">OVERSHOOT · FIELD NOTES</span><h2 id="oa-invite-title">Keep following the material story.</h2><p id="oa-invite-desc">Get occasional notes when new journeys, maps and source data are added to the atlas.</p><form onSubmit={submit}><label htmlFor="oa-invite-email">Email address</label><div className="oa-invite-row"><input id="oa-invite-email" type="email" autoComplete="email" required maxLength={254} value={email} onChange={e=>setEmail(e.target.value)} placeholder="you@example.com"/><button type="submit" disabled={sending||!consent}>{sending?'Joining…':'Join the list'}</button></div><label className="oa-invite-consent"><input type="checkbox" checked={consent} onChange={e=>setConsent(e.target.checked)} required/><span>Email me occasional OVERSHOOT updates from Gaia AI. I can unsubscribe from future messages.</span></label><input className="oa-invite-trap" aria-hidden="true" tabIndex={-1} name="website" autoComplete="off"/><p className="oa-invite-status" role="status">{status}</p></form><p className="oa-invite-privacy">We store your email, signup date and entry page for this list. We do not use it for atlas research.</p><button className="oa-invite-later" onClick={dismiss}>No thanks, keep exploring</button></div></div>
}
