'use client';
import {useEffect,useMemo,useState} from 'react';
import {ArrowRight,Check,ChevronDown,Globe2,MapPin,Search} from 'lucide-react';
import {CommandDialog,CommandEmpty,CommandGroup,CommandInput,CommandItem,CommandList} from '@/components/ui/command';
import {useMaterialArtifact} from '../material-data';
import type {Country} from '../world/model';
import {sourceAreaNames} from '@/packages/material-world/model';
import {browserLocale,number} from '../world/model';
export type PlaceRecord=Country&{alpha2?:string;region?:string;subregion?:string};
export type Coverage={accounts:number[];metrics:Record<string,number>;trade:Record<string,number>;basel:Record<string,number>;sites:Record<string,number>};
export function useCoverage(place:string){const data=useMaterialArtifact<{countries:Record<string,Coverage>}>('/data/v16/coverage.json');return {data:data.data?.countries[place],loading:!data.data&&!data.error,error:data.error};}
export function placeName(place:string,countries:Country[]){return place==='WORLD'?'Worldwide':place==='BC'?'British Columbia':place==='SSI'?'Salt Spring Island':countries.find(c=>c.id===place)?.name||sourceAreaNames[place]||place;}
const regional=[{id:'BC',name:'British Columbia',region:'Canada · regional evidence'},{id:'SSI',name:'Salt Spring Island',region:'Canada · local collection evidence'}];
export function PlacePicker({value,countries,onChange}:{value:string;countries:Country[];onChange:(id:string)=>void}){
 const [open,setOpen]=useState(false),[query,setQuery]=useState(''),[locale,setLocale]=useState('en');
 useEffect(()=>setLocale(browserLocale()),[]);
 const places=useMemo(()=>{const local=new Intl.DisplayNames([locale],{type:'region'});const multilingual=['es','fr','pt','de','ar','zh','ja','hi','ru'].map(l=>new Intl.DisplayNames([l],{type:'region'}));return (countries as PlaceRecord[]).map(c=>({...c,localName:c.alpha2?local.of(c.alpha2!):c.name,aliases:c.alpha2?multilingual.map(l=>l.of(c.alpha2!)).join(' '):''}));},[countries,locale]);
 function choose(id:string){onChange(id);setOpen(false)}
 return <><button className="oa-place-picker" onClick={()=>{setQuery('');setOpen(true)}} aria-label={'Change place: '+placeName(value,countries)} aria-haspopup="dialog"><Globe2 size={19}/><span><small>Looking at</small><strong>{placeName(value,countries)}</strong></span><ChevronDown size={17}/></button><CommandDialog filter={(value,search)=>value.normalize('NFKD').replace(/[\u0300-\u036f]/g,'').toLowerCase().includes(search.normalize('NFKD').replace(/[\u0300-\u036f]/g,'').toLowerCase())?1:0} open={open} onOpenChange={setOpen} className="oa-dialog oa-place-dialog" title="Choose a place" description="Search countries and territories, or open a documented regional example."><div className="oa-picker-heading"><h2>Where in the world?</h2><p>Choose a country or territory. Available evidence follows your selection.</p></div><CommandInput value={query} onValueChange={setQuery} placeholder="Search a place or country code…"/><CommandList><CommandEmpty>No matching place. Search its country or territory; city-level coverage is currently limited to the regional examples.</CommandEmpty><CommandGroup heading="Global view"><CommandItem value="Worldwide World Global Earth" onSelect={()=>choose('WORLD')}><Globe2 size={19}/><span>Worldwide<small>Compare the evidence across countries</small></span>{value==='WORLD'&&<Check/>}</CommandItem></CommandGroup><CommandGroup heading="Countries & territories">{places.map(c=><CommandItem key={c.id} value={[c.name,c.id,c.alpha2,c.localName,c.aliases].filter(Boolean).join(' ')} onSelect={()=>choose(c.id)}><MapPin size={17}/><span><bdi>{c.name}</bdi><small>{c.localName!==c.name?<><bdi>{c.localName}</bdi> · </>:null}{c.subregion||c.region||'Country or territory'}</small></span>{value===c.id&&<Check/>}</CommandItem>)}</CommandGroup><CommandGroup heading="Regional evidence in depth">{regional.map(c=><CommandItem key={c.id} value={c.name+' '+c.id+' Canada'} onSelect={()=>choose(c.id)}><MapPin size={17}/><span>{c.name}<small>{c.region}</small></span>{value===c.id&&<Check/>}</CommandItem>)}</CommandGroup></CommandList><p className="oa-picker-note">{countries.length} countries and areas are selectable. Data depth varies; an absent record never means zero.</p></CommandDialog></>;
}
export function PlaceCoverage({place,countries,onAccounts,onWaste,onSites}:{place:string;countries:Country[];onAccounts?:()=>void;onWaste:(direction:'in'|'out',place?:string)=>void;onSites:()=>void}){
 const {data,loading,error}=useCoverage(place),name=placeName(place,countries),regionalPlace=['BC','SSI'].includes(place);
 const sites=Object.values(data?.sites||{}).reduce((a,b)=>a+b,0),wasteOut=data?.basel['2024-out']||0,wasteIn=data?.basel['2024-in']||0;
 const years=data?.accounts||[],metricCount=Object.keys(data?.metrics||{}).length;
 const AccountTile=onAccounts?'button':'div';
 return <section className="oa-place-coverage" aria-label={'Evidence available for '+name}><div className="oa-coverage-heading"><span className="oa-kicker">EVIDENCE FOR {name.toUpperCase()}</span><p>{loading?'Checking available records…':error?'Coverage index unavailable. Source panels below can still be opened.':regionalPlace?'A detailed regional example, within a wider national system.':'Start with an available record. Each source keeps its own year and scope.'}</p></div><div className="oa-coverage-options"><AccountTile onClick={onAccounts} className={!onAccounts?'current':''}><span>Material & waste accounts</span><strong>{loading?'Loading evidence…':regionalPlace?'Local & regional records':years.length?years[0]+'–'+years.at(-1):metricCount?metricCount+' waste indicators':'No retained account'}</strong><small>{regionalPlace?'Collection, disposal & end markets':years.length?'Extraction, imports, exports & use':metricCount?'Source-specific years':'Read global material processes'}</small>{onAccounts&&<ArrowRight size={17}/>}</AccountTile><button onClick={()=>onWaste(wasteOut?'out':wasteIn?'in':'out',regionalPlace?'CAN':!wasteOut&&!wasteIn?'WORLD':place)}><span>Waste across borders</span><strong>{loading?'Loading evidence…':regionalPlace?'Canada’s reports':wasteOut||wasteIn?number(wasteOut||wasteIn,0)+' report section'+((wasteOut||wasteIn)===1?'':'s'):'Check world connections'}</strong><small>{wasteOut||wasteIn?'2024 · '+(wasteOut?'reported exports':'partners’ reports of exports here'):'Country reporting is incomplete'}</small><ArrowRight size={17}/></button><button onClick={onSites}><span>Mapped sites & operations</span><strong>{loading?'Loading evidence…':regionalPlace?'Documented local operations':sites?number(sites,0)+' mapped record'+(sites===1?'':'s'):'Check available datasets'}</strong><small>{sites?'Full retained facility & footprint records':'Coverage differs by site type'}</small><ArrowRight size={17}/></button></div></section>;
}
