'use client';
import {useState} from 'react';
import RegionalWaste from './RegionalWaste';
import WasteSystems from './WasteSystems';
import CountryTrends from './CountryTrends';
import CountryEnergy from './CountryEnergy';
import {Tabs,TabsList,TabsTrigger} from '@/components/ui/tabs';
import PlaceAccountMap,{type Account} from './PlaceAccountMap';
import {PlaceCoverage,useCoverage} from './PlaceContext';
import {ArrowRight,ArrowUpRight,Download,Globe2,MapPin,Search} from 'lucide-react';
import {useMaterialArtifact} from '../material-data';
import type {Country} from '../world/model';
import {endMarkets,facilities,type Facility} from './data';
import {Choice,Empty,ErrorState,FacilityCard,Loading,MarketBar,Refs,compact,number,exportCSV} from './common';
import GlassInvestigation from './GlassInvestigation';
import type {AtlasState} from './atlasState';
type Treatment={country:string;name:string;year:number;scope:string;values:Record<string,number|undefined>;flags:Record<string,string>;source_cells:Record<string,string>};
type Metric={country:string;metric:string;year:number;value:number;unit:string;source_id:string;estimated?:boolean;footnotes?:string[]};
type Basket={products:{hs6:string;commodity:string;valueCAD:number;destinations:Record<string,number>;units:Record<string,number>}[]};
const treatmentNames:Record<string,string>={RCV_R:'Recycling',RCV_B:'Backfilling',RCV_R_B:'Recycling + backfilling (combined)',RCV_E:'Energy recovery',DSP_I:'Incineration without energy recovery',DSP_L:'Landfill',DSP_OTH:'Other disposal',DSP_L_OTH:'Landfill + other disposal (combined)'};
const metricNames:Record<string,string>={in_use_stock:'Material held in buildings and products',plastic_waste_generated:'Plastic waste generated',ewaste_generated:'Electronic waste generated',food_waste:'Food waste generated',municipal_waste_generated:'Municipal waste generated',municipal_waste_recycled:'Municipal waste recycled',municipal_recycling_rate:'Municipal waste recycling rate'};
function partition(v:Treatment['values']){
 const recovery=v.RCV_R!==undefined&&v.RCV_B!==undefined?['RCV_R','RCV_B']:v.RCV_R_B!==undefined?['RCV_R_B']:['RCV_R','RCV_B'];
 const disposal=v.DSP_L!==undefined&&v.DSP_OTH!==undefined?['DSP_L','DSP_OTH']:v.DSP_L_OTH!==undefined?['DSP_L_OTH']:['DSP_L','DSP_OTH'];
 return [...recovery,'RCV_E','DSP_I',...disposal];
}
function TreatmentBars({row,codes,labels}:{row:Treatment;codes:string[];labels:Record<string,string>}){
 const total=row.values.TRT;
 return <div className="oa-treatment-bars">{codes.map((code,i)=>{const n=row.values[code];return <div key={code}><div><span>{labels[code]}{row.flags[code]&&<small> · source flag: {row.flags[code]}</small>}</span><strong>{n===undefined?'Not reported':number(n,0)+' t'}</strong></div><div className="oa-horizontal-bar"><i style={{width:n!==undefined&&total?Math.min(100,n/total*100)+'%':'0%',background:['#287359','#84946a','#bd8942','#b96947','#80776b','#aea193'][i%6]}}/></div><small>{n!==undefined&&total?number(n/total*100)+'% of reported treatment total':'No share inferred'}</small></div>})}</div>
}
export default function PlacesPage({place,countries,onPlace,onMaterial,onEnergy,onTrade,onFacility,onSites,onWaste,placeView,wastePlace,year,onYear,onView,onWastePlace,onGo}:{placeView:'materials'|'waste';wastePlace:string;year:string;onYear:(v:string)=>void;onView:(v:'materials'|'waste')=>void;onWastePlace:(country:string,id:string)=>void;place:string;countries:Country[];onPlace:(id:string)=>void;onMaterial:(id:string)=>void;onEnergy:(measure:string)=>void;onTrade:(place:string,product?:string)=>void;onFacility:(f:Facility)=>void;onSites:(place:string)=>void;onWaste:(direction:'in'|'out',place?:string)=>void;onGo:(update:Partial<AtlasState>)=>void}){
 const coverage=useCoverage(place);
 const materialView=placeView==='materials';
 const regional=['BC','SSI'].includes(place),[scope,setScope]=useState('TOTAL'),[query,setQuery]=useState(''),[limit,setLimit]=useState(10);
 const basket=useMaterialArtifact<Basket>(regional&&materialView?'/data/v9/bc-export-basket.json':null);
 const accounts=useMaterialArtifact<{rows:Account[]}>(!regional&&materialView?'/data/v2/resources/'+year+'.json':null);
 const extraction=useMaterialArtifact<{observations:(string|number|boolean|null)[][]}>(!regional&&materialView?'/data/v2/extraction.json':null);
 const metrics=useMaterialArtifact<{records:Metric[]}>(!regional&&materialView?'/data/v3/metrics-latest.json':null);
 const treatment=useMaterialArtifact<{records:Treatment[];flag_labels:Record<string,string>}>(!regional&&materialView?'/data/v9/treatment-latest.json':null);
 const weee=useMaterialArtifact<{records:Treatment[];flag_labels:Record<string,string>}>(!regional&&materialView?'/data/v9/weee-treatment-latest.json':null);
 const sources=useMaterialArtifact<{id:string;title:string;url:string}[]>(!regional&&materialView?'/data/v3/sources.json':null);
 const name=place==='BC'?'British Columbia':place==='SSI'?'Salt Spring Island':place==='WORLD'?'World':countries.find(c=>c.id===place)?.name||place;
 const account=accounts.data?.rows.find(r=>r.country===place);
 const materialMix=extraction.data?.observations.find(r=>r[0]===place&&r[1]===+year);
 const localMetrics=metrics.data?.records.filter(r=>r.country===place&&metricNames[r.metric])||[];
 const fate=treatment.data?.records.find(r=>r.country===place&&r.scope===scope);
 const ewaste=weee.data?.records.find(r=>r.country===place);
 const products=(basket.data?.products||[]).filter(p=>(p.commodity+' '+p.hs6).toLowerCase().includes(query.toLowerCase()));
 return <div className="oa-places-page">
  <div className="oa-page-title"><div><span className="oa-kicker">A PLACE IN THE MATERIAL WORLD</span><h1>{name}</h1>{!regional&&<p>Follow the material entering an economy, the stock it builds, and the waste that is treated.</p>}</div><MapPin size={48} className="oa-title-icon"/></div>

  <div className="oa-place-lenses"><Tabs value={placeView} onValueChange={v=>onView(v as 'materials'|'waste')}><TabsList aria-label="Place investigation"><TabsTrigger value="materials">Material use & trade</TabsTrigger><TabsTrigger value="waste">Waste & recovery</TabsTrigger></TabsList></Tabs><span>{placeView==='waste'?'National and city records · World Bank':regional?'Regional accounts and documented operations':'Extraction, consumption and history'}</span></div>
  {placeView==='waste'?<WasteSystems place={place} wastePlace={wastePlace} countries={countries} onSelect={onWastePlace} onTrade={country=>onWaste('out',country)}/>:regional?<>
   {place==='BC'&&<GlassInvestigation onGo={onGo}/>}
   <RegionalWaste/>
  <PlaceCoverage place={place} countries={countries} onWaste={onWaste} onSites={()=>onSites(place)}/>

   <section className="oa-region-lead"><div><span className="oa-kicker">WHAT YOUR RECYCLING BECOMES DEPENDS ON THE MATERIAL</span><h2>Paper travels. Most plastic stays in BC.</h2><p>In Recycle BC’s 2025 packaging and paper program, 93.7% of reported paper end markets were outside the province. For plastic, 99.5% were within BC.</p><Refs ids={['rbcReport2025']}/></div><div className="oa-stat"><strong>93.7%</strong><span>of paper end markets outside BC · 2025</span></div></section>
   <div className="oa-region-streams">{endMarkets.map(m=><button key={m.material} onClick={()=>onMaterial(m.material==='metal'?'aluminium':m.material)}><div><h3>{m.material==='paper'?'Paper & cardboard':m.material==='metal'?'Metal packaging':m.material==='plastic'?'Plastic packaging':'Glass packaging'}</h3><ArrowUpRight size={19}/></div><MarketBar values={[m.bc,m.canada,m.us,m.other]} compact/></button>)}</div>
   <p className="oa-note">These are end-market shares for one packaging and paper program. They do not measure all BC waste, the collection rate, or an individual household’s destination. Metal is a combined material group.</p>
   {place==='SSI'&&<section className="oa-local-proof"><span className="oa-kicker">A LOCAL CONNECTION, WITH ITS ACTUAL LIMIT</span><h2>Start at 349 Rainbow Road</h2><div className="oa-output-branches"><button onClick={()=>onFacility(facilities.find(f=>f.id==='rainbow')!)}><MapPin/><h3>Verified collection point</h3><p>The Salt Spring Island depot is a documented place to bring accepted materials.</p><span className="oa-text-link">Inspect the depot<ArrowRight size={16}/></span></button><div><h3>The specific receiver is unreported</h3><p>The retained sources do not establish which sorter receives each shipment from this depot.</p></div><button onClick={()=>onPlace('BC')}><Globe2/><h3>Widen to the BC system</h3><p>Inspect the named sorters, regional processor network and reported end markets.</p><span className="oa-text-link">Follow the regional evidence<ArrowRight size={16}/></span></button></div><Refs ids={['saltDepot']}/></section>}
   <section className="oa-export-basket"><div className="oa-section-heading"><div><span className="oa-kicker">WHAT ELSE LEAVES THE PROVINCE?</span><h2>BC’s export basket</h2><p>Search 3,140 products. Open one to see its foreign destinations and source quantity.</p></div><span className="oa-tag">2024 · domestic exports</span></div><label className="oa-inline-search"><Search size={18}/><input aria-label="Search BC export products" placeholder="Try copper, coal, salmon, wood pulp or an HS code" value={query} onChange={e=>{setQuery(e.target.value);setLimit(10)}}/></label>{basket.error?<ErrorState message={basket.error}/>:!basket.data?<Loading/>:<><div className="oa-table-labels"><span>Product · largest destination by value</span><span>Reported value, C$</span></div>{products.slice(0,limit).map((p,i)=>{const destination=Object.entries(p.destinations).sort((a,b)=>b[1]-a[1])[0]?.[0];return <button key={p.hs6} className="oa-trade-row" onClick={()=>onTrade('BC',p.hs6+':'+Object.keys(p.units)[0])}><span className="oa-row-index">{i+1}</span><span><strong>{p.commodity}</strong><small>HS {p.hs6} · {destination||'Destination unreported'}</small><i style={{width:(p.valueCAD/(products[0]?.valueCAD||1)*100)+'%'}}/></span><b>{compact(p.valueCAD)}</b><ArrowUpRight size={16}/></button>})}{!products.length&&<Empty title="No matching export product">Try a broader material or a six-digit customs code.</Empty>}{products.length>limit&&<button className="oa-button outline oa-more" onClick={()=>setLimit(n=>n+20)}>Show more products</button>}</>}<p className="oa-note">Ranked by reported Canadian-dollar value. Different product quantities use different units and are not combined. The origin is the province of production; these records exclude re-exports and interprovincial trade.</p><a className="oa-text-link" href="https://open.canada.ca/data/en/dataset/2909a648-5753-4924-878a-b069392d9cde" target="_blank" rel="noreferrer">Statistics Canada · Canadian International Merchandise Trade<ArrowUpRight size={15}/></a></section>
   <section><div className="oa-section-heading"><div><span className="oa-kicker">INSIDE THE REGIONAL SYSTEM</span><h2>Collection, processing and disposal</h2></div><button className="oa-text-link" onClick={()=>onSites('BC')}>All operations<ArrowRight size={17}/></button></div><div className="oa-facility-grid">{facilities.filter(f=>f.region==='BC').map(f=><FacilityCard key={f.id} facility={f} onOpen={onFacility}/>)}</div></section>
   <button className="oa-country-link" onClick={()=>onPlace('CAN')}><div><h3>Widen to Canada</h3><p>See the country’s extraction, imports, exports and material stocks.</p></div><ArrowRight/></button>
  </>:<>
   <nav className="oa-section-nav" aria-label="On this place page"><a href="#place-geography">Map</a><a href="#place-account">Material balance</a><a href="#place-history">History</a><a href="#place-energy">Oil, gas & coal</a><a href="#place-discard">Waste</a></nav>
   <div id="place-geography"><PlaceAccountMap loading={!accounts.data&&!accounts.error} rows={accounts.data?.rows||[]} countries={countries} place={place} year={year} years={coverage.data?.accounts?.length?[...coverage.data.accounts].reverse():[2024]} onYear={onYear} onPlace={onPlace} onSites={()=>onSites(place)}/></div>
   {accounts.error?<ErrorState message={accounts.error}/>:!accounts.data?<Loading/>:account?<section className="oa-account" id="place-account"><span className="oa-kicker">02 / MATERIAL ENTERING AND LEAVING THE ECONOMY · {year}</span><h2>How much material does {name==='World'?'the world':name} use?</h2><div className="oa-account-equation">{(['extraction','imports','exports','domesticConsumption'] as const).map((k,i)=><div key={k}>{i>0&&<span className="oa-equation-sign">{['','+','−','='][i]}</span>}<span>{['Taken from the environment','Imported','Exported','Domestic material consumption'][i]}</span><strong>{account[k]===null?'Unreported':compact(account[k]!)}</strong><small>tonnes · {year}</small></div>)}</div><p>Domestic material consumption is extraction plus physical imports minus physical exports. It includes material that becomes buildings and products, fuel that is burned, and material that later becomes waste. It is not a waste total.</p>{account.estimated&&<p className="oa-note">The source marks this account as estimated.</p>}<Refs ids={['irp']}/>{materialMix&&<div className="oa-material-mix"><h3>What is extracted?</h3>{['Biomass','Fossil fuels','Metal ores','Non-metallic minerals'].map((label,i)=>{const n=typeof materialMix[i+2]==='number'?materialMix[i+2] as number:null;const total=typeof materialMix[6]==='number'?materialMix[6] as number:0;return <div key={label}><span>{label}</span><div className="oa-horizontal-bar"><i style={{width:n!==null&&total?n/total*100+'%':'0%',background:['#58814b','#76685e','#b56b44','#a3956c'][i]}}/></div><strong>{n===null?'Unreported':compact(n)+' t'}</strong></div>})}<p className="oa-small">Ore and mineral tonnage is the source’s extracted-material basis, not refined metal content.</p></div>}<div className="oa-inline-actions"><button className="oa-button" onClick={()=>onTrade(place)}>Inspect traded materials<ArrowRight size={16}/></button><button className="oa-button outline" onClick={()=>exportCSV([account],'overshoot-material-account-'+place+'-'+year+'.csv')}><Download size={16}/>Export account</button></div><details className="oa-method"><summary>Original material-account record</summary><pre>{JSON.stringify(account,null,2)}</pre></details></section>:<Empty title="No material account is retained for this place">This territory remains selected. You can still learn how materials move, inspect the sources, or widen your view. <button className="oa-text-link" onClick={()=>onPlace('WORLD')}>Open worldwide accounts<ArrowRight size={16}/></button><button className="oa-text-link" onClick={()=>onMaterial('paper')}>Follow an everyday material<ArrowRight size={16}/></button></Empty>}
   <CountryEnergy place={place} onOpen={onEnergy}/>
   <CountryTrends key={place} place={place} countries={countries} year={year} onYear={onYear}/>
   <section className="oa-waste-entry" id="place-discard"><div><span className="oa-kicker">FOLLOW WHAT IS DISCARDED</span><h2>What is collected, recycled, or disposed of?</h2><p>Open national and city records for waste composition, collection coverage and treatment methods.</p></div><button className="oa-button" onClick={()=>onView('waste')}>Waste & recovery<ArrowRight size={17}/></button></section>
   {localMetrics.length>0&&<section className="oa-stock-section"><span className="oa-kicker">03 / MATERIAL DOES NOT ALL BECOME WASTE AT ONCE</span><h2>Some stays in use. Some is discarded.</h2><p>Buildings, roads and products can retain material for years. The observations below describe different stocks and waste streams, using each source’s own reference year.</p>{localMetrics.length?<div className="oa-metric-grid">{localMetrics.map(m=><article key={m.source_id+m.metric}><span>{metricNames[m.metric]}</span><strong>{compact(m.value)}</strong><small>{m.unit} · {m.year}{m.estimated?' · source estimate':''}</small><details><summary>Source and scope</summary><p>{m.metric==='municipal_recycling_rate'?'This is a percentage, not a quantity of waste. Use the source year and definition when comparing countries.':m.metric==='in_use_stock'?'Stock is material accumulated in use, not material discarded in this year.':'This is a separate waste estimate; do not add it to an overlapping waste category.'}</p>{m.footnotes?.map((n,i)=><p key={i}>{n}</p>)}<a href={sources.data?.find(s=>s.id===m.source_id)?.url} target="_blank" rel="noreferrer">{sources.data?.find(s=>s.id===m.source_id)?.title||m.source_id}<ArrowUpRight size={14}/></a></details></article>)}</div>:<p className="oa-note">No retained stock or specific waste-stream observation for this place.</p>}</section>}
   {(fate||treatment.error)&&<section className="oa-treatment"><div className="oa-section-heading"><div><span className="oa-kicker">04 / WHAT HAPPENS TO WASTE INSIDE THE COUNTRY?</span><h2>Treatment by destination</h2></div><Choice label="Waste scope" value={scope} onChange={setScope} options={[{id:'TOTAL',name:'All waste categories'},{id:'TOT_X_MIN',name:'Excluding major mineral waste'}]}/></div>{treatment.error?<ErrorState message={treatment.error}/>:!treatment.data?<Loading/>:fate?<><p className="oa-big-value">{fate.values.TRT===undefined?'Unreported':compact(fate.values.TRT)}<span>tonnes treated · {fate.year} · all economic sectors</span></p><TreatmentBars row={fate} codes={partition(fate.values)} labels={treatmentNames}/><p className="oa-note">This measures treatment within the country, including imported waste and excluding exported waste. It is not household waste alone. Shares use the published treatment total; unreported categories are not inferred or redistributed.</p>{Object.keys(fate.flags).length>0&&<p className="oa-small">Source flags: {[...new Set(Object.values(fate.flags))].map(f=>f+' = '+(treatment.data?.flag_labels[f]||'see source metadata')).join('; ')}.</p>}<Refs ids={['eurostat-treatment']}/><details className="oa-method"><summary>Original treatment record</summary><pre>{JSON.stringify(fate,null,2)}</pre></details></>:<Empty title="No retained national treatment breakdown">This dataset covers European reporting countries. <button className="oa-text-link" onClick={()=>onPlace('DEU')}>Inspect Germany’s treatment<ArrowRight size={15}/></button></Empty>}</section>}
   {ewaste&&<section className="oa-treatment"><span className="oa-kicker">05 / ELECTRONIC WASTE CAN CROSS ANOTHER BORDER</span><h2>Where is separately collected e-waste treated?</h2>{ewaste?<><p>{ewaste.name} reported {ewaste.values.TRT===undefined?'an unreported total of':number(ewaste.values.TRT,0)} tonnes treated in {ewaste.year}.</p><TreatmentBars row={ewaste} codes={['TRT_NAT','TRT_EU_FOR','TRT_NEU']} labels={{TRT_NAT:place==='DEU'?'National line, including confidential exports':'Within the reporting country',TRT_EU_FOR:'In another EU member state',TRT_NEU:'Outside the EU'}}/>{place==='DEU'&&<p className="oa-note">Germany includes confidential export quantities in the national-treatment line. That line cannot be interpreted as wholly domestic treatment.</p>}{place==='HUN'&&<p className="oa-note">Hungary reports the location of first treatment.</p>}<p className="oa-small">This covers separately collected equipment. It does not account for every device discarded, or identify receiving countries and factories.</p><Refs ids={['eurostat-weee']}/><details className="oa-method"><summary>Original e-waste record</summary><pre>{JSON.stringify(ewaste,null,2)}</pre></details></>:<p className="oa-note">No retained e-waste treatment-location breakdown for this country. This series covers European reporting countries.</p>}</section>}
  <PlaceCoverage place={place} countries={countries} onWaste={onWaste} onSites={()=>onSites(place)}/>
   {!regional&&<div className="oa-scope-footnote"><h3>How local is this evidence?</h3><p>These records describe {place==='WORLD'?'the world or a sample of reporting countries':'the selected country or territory'}. They do not locate your household’s recycling or establish a city-to-facility route. The Waste & recovery view includes 262 World Bank city records. Detailed disposal districts and documented operator chains are available as British Columbia case studies.</p><button className="oa-text-link" onClick={()=>onPlace('BC')}>Open the British Columbia case study<ArrowRight size={16}/></button>{!fate&&<p>The all-sector treatment series below covers European reporting countries. Municipal waste records are available more widely under Waste & recovery. <button className="oa-text-link" onClick={()=>onPlace('DEU')}>See a documented example: Germany<ArrowRight size={15}/></button></p>}</div>}
  </>}
 </div>
}
