'use client';
import {useMemo,useState} from 'react';
import {geoConicConformal,geoPath} from 'd3-geo';
import type {FeatureCollection} from 'geojson';
import {ArrowUpRight,Download,MapPin,Search} from 'lucide-react';
import {Tabs,TabsList,TabsTrigger} from '@/components/ui/tabs';
import {useMaterialArtifact} from '../material-data';
import {Choice,ErrorState,Loading,Refs,compact,number,exportCSV} from './common';
type Row={district:string;year:number;tonnes:number|null;population:number|null;rate:number|null;source_row:number;original:Record<string,string>};
type Data={rows:Row[];links:Record<string,{url?:string;swmPlan?:string;wComposition?:string}>;source:string};
const colors=['#dbe8c8','#a8c498','#689775','#306f54'];
const display=(name:string)=>name.replace('Metro-Vancouver','Metro Vancouver').replace('Comox-Strathcona','Comox Valley + Strathcona');
export default function RegionalWaste({initialDistrict='Capital'}:{initialDistrict?:string}){
 const data=useMaterialArtifact<Data>('/data/v10/bc-disposal.json');
 const geo=useMaterialArtifact<FeatureCollection>('/data/v10/bc-districts.json');
 const [year,setYear]=useState('2024'),[measure,setMeasure]=useState<'rate'|'tonnes'>('rate'),[district,setDistrict]=useState(initialDistrict),[query,setQuery]=useState(''),[all,setAll]=useState(false);
 const rows=useMemo(()=>(data.data?.rows||[]).filter(r=>r.year===+year).sort((a,b)=>(b[measure]??-1)-(a[measure]??-1)),[data.data,year,measure]);
 const selected=rows.find(r=>r.district===district);
 const history=(data.data?.rows||[]).filter(r=>r.district===district&&r.year>=2012);
 const max=Math.max(1,...history.map(r=>r[measure]??0));
 const projection=useMemo(()=>geo.data?geoConicConformal().parallels([50,58]).rotate([126,0]).fitExtent([[22,25],[518,535]],geo.data):null,[geo.data]);
 const path=geoPath(projection);
 const thresholds=measure==='rate'?[400,600,800]:[25000,100000,500000];
 const colour=(value:number|null|undefined)=>value==null?'#ecece4':colors[thresholds.filter(n=>value>=n).length];
 const filtered=rows.filter(r=>display(r.district).toLowerCase().includes(query.toLowerCase()));
 const links=data.data?.links[district];
 const mapped=new Set(geo.data?.features.map(f=>f.properties?.district));
 return <section className="oa-regional-waste">
  <div className="oa-section-heading"><div><span className="oa-kicker">LOCAL DISPOSAL · 27 REPORTING AREAS</span><h2>How much waste does each region dispose of?</h2><p>Choose a district. Compare its annual disposal and the amount per resident.</p></div><Choice label="Disposal year" value={year} onChange={setYear} options={Array.from({length:13},(_,i)=>({id:String(2024-i),name:String(2024-i)}))}/></div>
  <Tabs value={measure} onValueChange={v=>setMeasure(v as 'rate'|'tonnes')} className="oa-dataset-tabs"><TabsList aria-label="Disposal map measure"><TabsTrigger value="rate">Per person · kg</TabsTrigger><TabsTrigger value="tonnes">Total disposed · tonnes</TabsTrigger></TabsList></Tabs>
  {data.error?<ErrorState message={data.error}/>:!data.data?<Loading/>:<>
   <div className="oa-district-layout" id="regional-waste-map"><div className="oa-district-map"><div className="oa-map-eyebrow"><MapPin size={16}/>British Columbia · {year}</div>{geo.error?<p role="alert">Boundaries could not load. Select a district from the list below.</p>:!geo.data?<Loading/>:<svg viewBox="0 0 540 570" role="group" aria-label="BC regional waste disposal map">{geo.data.features.map((f,i)=>{const id=String(f.properties?.district),r=rows.find(r=>r.district===id),value=r?.[measure];return <path key={i} d={path(f)||''} fill={colour(value)} stroke={district===id?'#a54c23':'#fffef6'} strokeWidth={district===id?2.5:1} role="button" tabIndex={0} aria-label={display(id)+', '+(value==null?'no observation':number(value,0)+(measure==='rate'?' kilograms per person':' tonnes'))} aria-pressed={district===id} onClick={()=>setDistrict(id)} onKeyDown={e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();setDistrict(id)}}}><title>{display(id)}: {value==null?'Not reported':number(value,0)+' '+(measure==='rate'?'kg/person':'t')}</title></path>})}{geo.data.features.filter(f=>f.properties?.district===district).slice(0,1).map(f=>{const p=path.centroid(f);return <g key="selected" pointerEvents="none"><circle cx={p[0]} cy={p[1]} r={4} fill="#a54c23"/><text x={Math.max(85,Math.min(450,p[0]))} y={p[1]-12} textAnchor="middle" className="oa-district-label">{display(district)}</text></g>})}<text x="25" y="553" fill="#667361" fontSize="12">Reporting areas · not landfill locations</text></svg>}
    <div className="oa-map-legend">{colors.map((c,i)=><span key={c}><i style={{background:c}}/>{i===0?'Under '+compact(thresholds[0]):i===3?compact(thresholds[2])+'+':compact(thresholds[i-1])+'–'+compact(thresholds[i])}</span>)}<span><i style={{background:'#ecece4'}}/>No observation</span></div><p className="oa-small">{measure==='rate'?'kg per resident per year':'Tonnes disposed per year'}. Comox Valley and Strathcona share one reported value. Northern Rockies is in the list; this boundary layer does not include its municipality or unincorporated Stikine.</p>
   </div><div className="oa-district-detail" aria-live="polite"><span className="oa-kicker">SELECTED REPORTING AREA</span><h3>{display(district)}</h3><p className="oa-district-value">{selected?.[measure]==null?'Not reported':number(selected[measure]!,0)}<span>{measure==='rate'?'kg per resident':'tonnes disposed'} · {year}</span></p><dl className="oa-facts"><dt>Waste disposed</dt><dd>{selected?.tonnes==null?'No verified observation':number(selected.tonnes,0)+' tonnes'}</dd><dt>Per resident</dt><dd>{selected?.rate==null?'No verified observation':number(selected.rate,0)+' kg'}</dd><dt>Source population</dt><dd>{selected?.population==null?'Not reported':number(selected.population,0)}</dd></dl><h4>How has it changed?</h4><div className="oa-history-bars" role="group" aria-label={display(district)+' disposal history'}>{history.map(r=><button key={r.year} aria-label={r.year+': '+(r[measure]==null?'not reported':number(r[measure]!,0)+' '+(measure==='rate'?'kg per person':'tonnes'))} aria-pressed={r.year===+year} title={r.year+': '+(r[measure]==null?'not reported':number(r[measure]!,0))} onClick={()=>setYear(String(r.year))}><span style={{height:r[measure]==null?'2px':Math.max(2,r[measure]!/max*95)+'px',background:r.year===+year?'#a95d37':r[measure]==null?'#dedfd4':'#7e9c78'}}/><small>{String(r.year).slice(2)}</small></button>)}</div><p className="oa-small">2012–2024 · select a bar for its year.</p>{<p className="oa-method-change"><strong>2024 method change.</strong> The province stopped adjusting population for factors such as tourism. A change in rate can reflect this denominator change.</p>}{district==='Capital'&&<p className="oa-small">Salt Spring is part of the Capital region. This regional rate is not a separate island estimate.</p>}{links?.swmPlan&&<a href={links.swmPlan} target="_blank" rel="noreferrer" className="oa-text-link">Regional waste-management plan<ArrowUpRight size={15}/></a>}{links?.wComposition&&links.wComposition!==links.swmPlan&&<a href={links.wComposition} target="_blank" rel="noreferrer" className="oa-text-link">Waste composition report<ArrowUpRight size={15}/></a>}<details className="oa-method"><summary>Original observation</summary><pre>{JSON.stringify(selected?.original||{status:'No source observation'},null,2)}</pre></details></div></div>
   <div className="oa-section-heading"><h3>Compare regional districts</h3><button className="oa-button outline" onClick={()=>exportCSV(rows.map(r=>({...r.original,normalized_rate:r.rate,normalized_tonnes:r.tonnes,source_url:data.data!.source})),'overshoot-bc-disposal-'+year+'.csv')}><Download size={16}/>Export year</button></div><label className="oa-inline-search"><Search size={17}/><input aria-label="Find a regional district" placeholder="Find Capital, Metro Vancouver, Peace River…" value={query} onChange={e=>setQuery(e.target.value)}/></label><div className="oa-table-labels"><span>District · ranked within this year</span><span>{measure==='rate'?'kg / resident':'tonnes disposed'}</span></div>{filtered.slice(0,all||query?30:6).map((r,i)=><button className="oa-trade-row" key={r.district} onClick={()=>{setDistrict(r.district);document.getElementById('regional-waste-map')?.scrollIntoView({behavior:'smooth',block:'start'})}} aria-pressed={district===r.district}><span className="oa-row-index">{i+1}</span><span><strong>{display(r.district)}</strong><small>{r.tonnes===null?'Observation unavailable':number(r.population||0,0)+' source population'}{!mapped.has(r.district)?' · not mapped':''}</small><i style={{width:Math.max(0,(r[measure]??0)/(rows[0]?.[measure]||1)*100)+'%'}}/></span><b>{r[measure]==null?'Not reported':number(r[measure]!,0)}</b><ArrowUpRight size={16}/></button>)}{!all&&!query&&<button className="oa-button outline oa-more" onClick={()=>setAll(true)}>Show all {rows.length} reporting areas</button>}
   <p className="oa-note">The map locates reporting areas, not final disposal sites or haul routes. Disposal includes landfilling and other disposal, including incineration. It is not a household-only measure or a recycling rate. Missing observations remain missing; the province’s placeholder zero rates are not mapped as zero waste. Boundaries are simplified for display.</p><Refs ids={['bc-disposal','bc-boundaries']}/>
  </>}
 </section>
}
