'use client';
import {useState} from 'react';
import {ArrowUpRight,Database,Search} from 'lucide-react';
import {useMaterialArtifact} from '../material-data';
type Source={id:string;name:string;publisher:string;year:string;geography:string;materials:string[];status:'retained'|'source identified';value:string;gap:string;url:string;localData?:string};
type Catalog={reviewedAt:string;method:string;sources:Source[]};
export default function SourceObservatory(){
 const data=useMaterialArtifact<Catalog>('/data/v39/source-opportunities.json');
 const [term,setTerm]=useState(''),[status,setStatus]=useState('all');
 const sources=(data.data?.sources||[]).filter(s=>(status==='all'||s.status===status)&&(s.name+' '+s.publisher+' '+s.materials.join(' ')+' '+s.geography).toLowerCase().includes(term.toLowerCase()));
 return <section className="od-observatory" id="source-observatory"><div className="od-section-head"><div><span className="oa-kicker">SOURCE REGISTER · SEPTEMBER 2026</span><h2>What we have, and what we still need.</h2><p>Filter the sources behind this atlas. “Retained” means records are downloadable here. “Source identified” means a relevant publisher has data we have not yet integrated.</p></div><Database size={26}/></div><div className="od-observatory-filters"><label><Search size={17}/><input aria-label="Search research sources" placeholder="Find a material, place or publisher" value={term} onChange={e=>setTerm(e.target.value)}/></label><select aria-label="Filter data acquisition status" value={status} onChange={e=>setStatus(e.target.value)}><option value="all">All source statuses</option><option value="retained">Retained here</option><option value="source identified">Source identified</option></select></div>{data.error?<p role="alert">Research source catalog could not load.</p>:!data.data?<p>Loading source catalog…</p>:<><p className="od-small">{data.data.method}</p><div className="od-observatory-list">{sources.map(s=><article key={s.id}><span className={s.status==='retained'?'od-status-retained':'od-status-identified'}>{s.status}</span><h3>{s.name}</h3><p className="od-small">{s.publisher} · {s.year} · {s.geography}</p><p>{s.value}</p><p className="od-small"><strong>Still missing:</strong> {s.gap}</p><div>{s.materials.map(m=><span className="od-material-tag" key={m}>{m}</span>)}</div><a href={s.localData||s.url} target="_blank" rel="noreferrer">{s.localData?'Download retained records':'Inspect original source'}<ArrowUpRight size={15}/></a>{s.localData&&<a href={s.url} target="_blank" rel="noreferrer">Publisher report<ArrowUpRight size={15}/></a>}</article>)}</div>{!sources.length&&<p>No sources match those filters.</p>}</>}</section>;
}
