'use client';
import {useState,useEffect} from 'react';
import {ArrowRight,ArrowUpRight,Download,Globe2,Search,SlidersHorizontal} from 'lucide-react';
import {Tabs,TabsList,TabsTrigger} from '@/components/ui/tabs';
import {Checkbox} from '@/components/ui/checkbox';
import {CommandDialog,CommandEmpty,CommandGroup,CommandInput,CommandItem,CommandList} from '@/components/ui/command';
import {Sheet,SheetContent,SheetTitle,SheetDescription} from '@/components/ui/sheet';
import BaselTrade from './BaselTrade';
import WorldMap from '../world/WorldMap';
import {type Country,type Flow} from '../world/model';
import {useTradeEvidence} from './useTradeEvidence';
import {formNames,type Profile} from './data';
import {Choice,Empty,ErrorState,Loading,Refs,compact,number,exportCSV} from './common';

type Props={dataset:'commodity'|'controlled';profile:Profile;place:string;form:string;product:string;direction:'in'|'out';countries:Country[];onChange:(p:{dataset?:'commodity'|'controlled';place?:string;form?:string;product?:string;direction?:'in'|'out'})=>void;onCountry:(country:string)=>void};
export default function TradePage({dataset,profile,place,form,product:productKey,direction,countries,onChange,onCountry}:Props){
 const bc=place==='BC'||place==='SSI',world=place==='WORLD';
 const [estimates,setEstimates]=useState(false),[picker,setPicker]=useState(false),[query,setQuery]=useState(''),[filter,setFilter]=useState(''),[limit,setLimit]=useState(12),[selected,setSelected]=useState<Flow|null>(null),[measure,setMeasure]=useState<'quantity'|'value'>('quantity'),[allProducts,setAllProducts]=useState(!!productKey&&!profile.codes.some(c=>productKey.startsWith(c)));
 const {flows,loading,error,catalog,options,product,names,disagreement,reportingBasis,reporterCount}=useTradeEvidence({profile,place,form,productKey,direction,countries,estimates,measure,allProducts});
 const shown=flows.filter(f=>(f.originLabel+' '+f.destinationLabel).toLowerCase().includes(filter.toLowerCase()));
 const top=shown[0]||flows[0],comparable=shown.length>0&&new Set(shown.map(f=>f.unit+'|'+f.basis)).size===1;
 const sum=comparable?shown.reduce((a,f)=>a+f.amount,0):0,share=top&&sum?top.amount/sum*100:0;
 const title=bc?'British Columbia':world?'Selected world connections':names.get(place)||place;
 const activeForm=bc?product?.commodity:formNames[form]||profile.name;
 useEffect(()=>setSelected(null),[place,form,productKey,direction,measure,dataset,estimates]);
 const selectedPeer=selected?(direction==='in'?selected.origin:selected.destination):'';
 const knownPeer=countries.some(c=>c.id===selectedPeer);
 return <div className="oa-trade-page">
  <div className="oa-page-title"><div><span className="oa-kicker">COUNTRIES, COMMODITIES & BORDER CROSSINGS</span><h1>Follow the trade</h1>{dataset==='commodity'&&<p>See who reports sending a material, who receives it, and what the records actually measure.</p>}</div><Globe2 className="oa-title-icon" size={48}/></div>
  <Tabs value={dataset} onValueChange={d=>{setSelected(null);onChange({dataset:d as 'commodity'|'controlled'})}} className="oa-dataset-tabs"><TabsList aria-label="Trade evidence"><TabsTrigger value="commodity">Commodity trade · customs</TabsTrigger><TabsTrigger value="controlled">Controlled waste · Basel</TabsTrigger></TabsList></Tabs>
  {dataset==='controlled'?<BaselTrade place={place} direction={direction} countries={countries} onChange={onChange}/>:<>
  <div className="oa-trade-controls"><Choice label="Material form" value={allProducts&&bc?'all':form||'none'} onChange={f=>{setAllProducts(f==='all');setSelected(null);onChange({form:f==='all'?'':f,product:''})}} options={[...profile.codes.map(c=>({id:c,name:formNames[c]||c})),...(bc?[{id:'all',name:'All BC export products'}]:[]),...(!profile.codes.length?[{id:'none',name:'No customs series available'}]:[])]}/><div className="oa-choice"><span>Direction</span><Tabs value={direction} onValueChange={d=>onChange({direction:d as 'in'|'out'})}><TabsList><TabsTrigger value="in" disabled={world}>Comes from</TabsTrigger><TabsTrigger value="out">Goes to</TabsTrigger></TabsList></Tabs></div><div className="oa-year"><strong>2024</strong><span>Retained annual records</span></div></div>
  {bc&&product&&<div className="oa-product-select"><span>Specific product</span><button onClick={()=>{setQuery('');setPicker(true)}}>{product.commodity}<Search size={18}/></button><small>HS {product.hs6} · {product.unit}</small><Tabs value={measure} onValueChange={v=>setMeasure(v as 'quantity'|'value')}><TabsList><TabsTrigger value="quantity">Source quantity</TabsTrigger><TabsTrigger value="value">Trade value</TabsTrigger></TabsList></Tabs></div>}
  {profile.id==='copper'&&!bc&&<label className="oa-estimates"><Checkbox checked={estimates} onCheckedChange={x=>setEstimates(x===true)}/>Include source-estimated weights<span>Estimated entries are marked</span></label>}

  <p className="oa-small oa-market-freshness">For newer reported commodity markets, check <a href="https://comtradeapi.un.org/" target="_blank" rel="noreferrer">UN Comtrade</a>. For British Columbia, check <a href="https://www150.statcan.gc.ca/t1/tbl1/en/tv.action?pid=1210017501" target="_blank" rel="noreferrer">Statistics Canada’s provincial commodity table</a>. Those releases may use different reporting years, units and revisions; they are separate from this 2024 map.</p>
  {place==='SSI'&&<p className="oa-note">The trade records resolve to British Columbia. They cannot identify Salt Spring exports.</p>}
  {error?<ErrorState message={error}/>:loading?<Loading/>:flows.length?<>
  <p className="oa-note">{bc?'Province of production → last-known foreign destination. This excludes interprovincial trade. ':reportingBasis==='partner-importers'?'Partners report these imports from the selected origin. The origin’s own export report is absent from this snapshot. ':reportingBasis==='mixed'?'Exporter declarations, supplemented by partner import reports only where an origin/product/year has no retained exports. The two sides are never added for the same group. ':reportingBasis==='importer'?'The selected country’s import declarations. ':reportingBasis==='partners'?'Selected partners’ export declarations. Coverage is incomplete. ':`Export declarations from ${reporterCount} retained reporters; availability varies by material form. `}{world?'A material may cross borders more than once. ':''}{bc&&product?product.quantityBasis+'. ':''}Open a connection for its reporting basis and original record.</p>
  <label className="oa-inline-search"><Search size={17}/><input value={filter} onChange={e=>{setFilter(e.target.value);setLimit(12)}} placeholder="Find an origin or destination" aria-label="Filter trade partners"/></label><p className="oa-small oa-result-count">Map and list · {shown.length} of {flows.length} available connections</p><div className="oa-map-workspace oa-trade-map-workspace"><div><WorldMap flows={shown} sites={[]} countries={countries} place={bc?'BC':place} selected={selected?.id||''} onFlow={setSelected} onSite={()=>{}} onPlace={p=>{onChange({place:p,product:''});setSelected(null)}} color={profile.color} siteView={false}/></div><aside className="oa-map-inspector">{shown.length?<section className="oa-trade-answer"><div><span className="oa-kicker">{title.toUpperCase()} · {direction==='out'?'REPORTED DESTINATIONS':'REPORTED ORIGINS'}</span><h2>{world?top.originLabel+' → '+top.destinationLabel:(comparable?(direction==='out'?'Largest reported destination: ':'Largest reported origin: '):'Reported connection: ')+(direction==='out'?top.destinationLabel:top.originLabel)}</h2><p>{activeForm}</p></div><div className="oa-stat"><strong>{compact(top.amount)}</strong><span>{top.unit}</span></div>{comparable&&<div className="oa-stat"><strong>{number(share)}%</strong><span>of comparable records in this filtered view</span></div>}<div className="oa-stat"><strong>{shown.length}</strong><span>matching partner records</span></div></section>:<div className="oa-filter-empty"><h3>No matching connection</h3><p>Clear or change the partner filter to see the retained records.</p><button className="oa-text-link" onClick={()=>setFilter('')}>Clear filter<ArrowRight size={15}/></button></div>}</aside></div>
  {disagreement&&shown.some(f=>f.origin===disagreement.origin&&f.destination===disagreement.destination)&&<details className="oa-method oa-mirror-disclosure"><summary>Source check: Chile and China report different weights for this connection</summary><section className="oa-mirror-note"><span className="oa-kicker">SOURCE CHECK · CHILE → CHINA · COPPER ORE & CONCENTRATE · 2024</span><h3>Two declarations. Two very different weights.</h3><p>The exporter and importer report different net weights for this connection. Both fields are marked non-estimated by Comtrade. The difference remains unresolved; the app keeps each reporting side separate.</p><div className="oa-mirror-values"><div><strong>{number(disagreement.exporter_reported_tonnes,0)} t</strong><span>Chile’s export declaration</span><button className="oa-text-link" onClick={()=>{setSelected(null);onChange({place:'CHL',direction:'out'})}}>Inspect exporter report<ArrowRight size={15}/></button></div><div><strong>{number(disagreement.importer_reported_tonnes,0)} t</strong><span>China’s import declaration</span><button className="oa-text-link" onClick={()=>{setSelected(null);onChange({place:'CHN',direction:'in'})}}>Inspect importer report<ArrowRight size={15}/></button></div></div><p className="oa-small">A targeted check of this corridor, not a systematic audit of every trade record. No averaging or ore-grade conversion.</p><Refs ids={['comtrade']}/></section></details>}
  <section className="oa-trade-ledger"><div className="oa-section-heading"><div><h2>{direction==='out'?'Where it goes':'Where it comes from'}</h2><span className="oa-small">{activeForm}</span></div><button className="oa-button outline" disabled={!shown.length} onClick={()=>exportCSV(shown.map(f=>({...f.record,displayedAmount:f.amount,displayedUnit:f.unit,sourceUrl:f.sourceUrl})),'overshoot-trade-'+place+'-'+form+'.csv')}><Download size={17}/>Export records</button></div><div className="oa-table-labels"><span>Reported connection</span><span>{comparable?top.unit:'Source units vary'}</span></div>{shown.slice(0,limit).map((f,i)=><button className="oa-trade-row" key={f.id} onClick={()=>setSelected(f)}><span className="oa-row-index">{String(i+1).padStart(2,'0')}</span><span><strong>{world?f.originLabel+' → '+f.destinationLabel:direction==='out'?f.destinationLabel:f.originLabel}</strong><small>{f.year}{String(f.record.reported_flow)==='M'?' · importer report':''}{f.estimated?' · source-estimated weight':''}</small><i style={{width:(comparable&&top.amount?Math.max(.3,f.amount/top.amount*100):0)+'%',background:profile.color}}/></span><b>{number(f.amount,2)}{!comparable?' '+f.unit:''}</b><ArrowUpRight size={17}/></button>)}{!shown.length&&<p>No connections match this filter.</p>}{shown.length>limit&&<button className="oa-button outline oa-more" onClick={()=>setLimit(n=>n+30)}>Show more · {shown.length-limit} remaining</button>}</section></>:<Empty title={bc&&direction==='in'?'BC import records are not in this snapshot':'No trade records for this selection'}>{bc&&direction==='in'?<>Canadian import records provide a wider view. <button className="oa-text-link" onClick={()=>onChange({place:'CAN',direction:'in'})}>Open Canada’s imports<ArrowRight size={15}/></button></>:<>This is a bilateral trade coverage gap, not evidence of zero production or exports. Country accounts and production records are available separately.  <button className="oa-text-link" onClick={()=>onCountry(place)}>Open country production & accounts<ArrowRight size={15}/></button><button className="oa-text-link" onClick={()=>onChange({dataset:'controlled'})}>Check controlled-waste reports<ArrowRight size={15}/></button><button className="oa-text-link" onClick={()=>onChange({place:'WORLD',direction:'out'})}>View this material worldwide<ArrowRight size={15}/></button> {bc&&<button className="oa-text-link" onClick={()=>{setAllProducts(true);onChange({form:'',product:''})}}>Open the full BC product catalogue<ArrowRight size={15}/></button>}</>}</Empty>}
  <details className="oa-method"><summary><SlidersHorizontal size={17}/>How to read these connections</summary><p>A customs record names reported trading partners. It does not identify a mine, transport route, final factory or waste-treatment outcome. The same material may cross several borders.</p><p>BC HS 26.02–26.17 quantities can follow metal-content or assay conventions. Air-dry mass, gross weight, contained metal, item counts and currency remain distinct. Do not combine them into an overall tonnage.</p><p>Incoming views use import declarations where the oil or detailed copper series supports them; otherwise they use selected partners’ export reports. For copper, the selected reporter’s own imports and exports are kept separate. Source-estimated copper weights are excluded unless selected.</p><Refs ids={['comtrade']}/>{catalog.data&&<a href={catalog.data.source.conceptsUrl} target="_blank" rel="noreferrer">Statistics Canada concepts<ArrowUpRight size={14}/></a>}</details>
  <CommandDialog open={picker} onOpenChange={setPicker} title="Choose a traded product" description="Search the BC commodity catalogue." className="oa-dialog"><CommandInput value={query} onValueChange={setQuery} placeholder="Search a product, material or HS code…"/><CommandList><CommandEmpty>No matching product in this selection.</CommandEmpty><CommandGroup heading={allProducts?'All BC exports':formNames[form]||'Products'}>{options.filter(p=>(p.commodity+' '+p.hs6).toLowerCase().includes(query.toLowerCase())).slice(0,80).map(p=><CommandItem key={p.hs6+':'+p.unit} value={p.commodity+' '+p.hs6+' '+p.unit} onSelect={()=>{onChange({product:p.hs6+':'+p.unit});setPicker(false)}}><span>{p.commodity}<small>{p.hs6} · {p.unitLabel}</small></span></CommandItem>)}</CommandGroup></CommandList></CommandDialog>
  <Sheet open={!!selected} onOpenChange={o=>{if(!o)setSelected(null)}}><SheetContent className="oa-sheet"><SheetTitle>{selected?selected.originLabel+' → '+selected.destinationLabel:'Trade connection'}</SheetTitle><SheetDescription>{activeForm} · 2024</SheetDescription>{selected&&<><p className="oa-big-value">{number(selected.amount,3)}<span>{selected.unit}</span></p><dl className="oa-facts"><dt>Quantity basis</dt><dd>{selected.basis}</dd><dt>Reporting basis</dt><dd>{bc?'BC domestic exports':String(selected.record.reported_flow)==='M'?'Importer’s declaration':'Exporter’s declaration'}</dd><dt>Estimated by source</dt><dd>{selected.estimated?'Yes':'No source-estimated weight in this record'}</dd></dl><p>This establishes a trading partner. It does not establish where the material was finally used or treated.</p><a className="oa-source-row" href={selected.sourceUrl} target="_blank" rel="noreferrer">Open the primary trade source<ArrowUpRight size={17}/></a>{knownPeer&&<div className="oa-sheet-actions"><button className="oa-button" onClick={()=>{onChange({place:selectedPeer,direction:'out',product:''});setSelected(null)}}>Inspect this country’s exports<ArrowRight size={17}/></button><button className="oa-button outline" onClick={()=>onCountry(selectedPeer)}>Open its material accounts<ArrowRight size={17}/></button><p className="oa-small">These open another set of observations, not a trace of this same shipment.</p></div>}<details className="oa-method"><summary>Original source record</summary><pre>{JSON.stringify(selected.record,null,2)}</pre></details></>}</SheetContent></Sheet>
 </>}
 </div>
}
