'use client';
import {useMemo,useState} from 'react';
import {ArrowRight,ArrowUpRight,BookOpen,Check,Download,Factory,Search,X} from 'lucide-react';
import {Tabs,TabsList,TabsTrigger} from '@/components/ui/tabs';
import {Sheet,SheetContent,SheetDescription,SheetTitle} from '@/components/ui/sheet';
import {useMaterialArtifact} from '../material-data';
import type {Country} from '../world/model';
import {researchBase,collectionRows,comparisonDate,uniqueYearPoints,type WasteCatalog,type WasteObservation,type CityCollection,type CityCollectionData,type WasteComparison,type ComparisonPlace,type WasteSource} from '@/packages/material-world/wasteResearch';
import {exportCSV,number,Loading,ErrorState} from './common';
import type {AtlasState} from './atlasState';
import WasteSystems from './WasteSystems';

type Props={state:AtlasState;countries:Country[];onChange:(patch:Partial<AtlasState>)=>void;onGo:(patch:Partial<AtlasState>)=>void};
type Inspect={title:string;subtitle:string;data:Record<string,unknown>;source:WasteSource;description?:string};
const groups=['Municipal waste','Packaging','Electronic waste','Hazardous waste','Food waste'];
const palette=['#478e6c','#d08a39','#6d8fca','#b77dab'];
const primaryFields=['perPerson','tonnes','collection_waste','collection_population','treatment_recycling','treatment_open_dumpsite','treatment_controlled_landfill','treatment_sanitary_landfill_landfill_gas_system','treatment_compost','treatment_incineration','uncollected'];
const textValue=(v:unknown)=>typeof v==='object'?JSON.stringify(v,null,2):String(v??'Not specified');
const show=(n:number|null|undefined)=>n===null||n===undefined?'Not reported':number(n,2);
function SourceLink({source}:{source:WasteSource}){return <a href={source.metadataUrl||source.url} target="_blank" rel="noreferrer">Definition & source <ArrowUpRight size={14}/></a>}
function Pager({total,page,onPage}:{total:number;page:number;onPage:(n:number)=>void}){const pages=Math.max(1,Math.ceil(total/25));return <div className="wr-pagination"><span aria-live="polite">{total?`${number(page*25+1,0)}–${number(Math.min((page+1)*25,total),0)} of ${number(total,0)}`:'No matching records'}</span><div><button disabled={page===0} onClick={()=>onPage(page-1)}>Previous</button><span>Page {page+1} / {pages}</span><button disabled={page+1>=pages} onClick={()=>onPage(page+1)}>Next</button></div></div>}
function SearchBox({value,onChange,label}:{value:string;onChange:(s:string)=>void;label:string}){return <label className="wr-search"><Search size={18}/><input aria-label={label} placeholder={label} value={value} onChange={e=>onChange(e.target.value)}/>{value&&<button aria-label="Clear search" onClick={()=>onChange('')}><X size={16}/></button>}</label>}
function Export({onClick,disabled,label='Export results'}:{onClick:()=>void;disabled:boolean;label?:string}){const [done,setDone]=useState(false);return <button className="oa-button outline" aria-label={done?'CSV downloaded':label} disabled={disabled} onClick={()=>{onClick();setDone(true);setTimeout(()=>setDone(false),2500)}}>{done?<Check size={16}/>:<Download size={16}/>}<span role="status">{done?'CSV downloaded':label}</span></button>}
export default function WastePage(props:Props){
 const {state,countries,onChange,onGo}=props;
 const catalog=useMaterialArtifact<WasteCatalog>(researchBase+'catalog.json');
 const [inspect,setInspect]=useState<Inspect|null>(null);
 return <div className="wr-page">
  <header className="wr-heading"><div><span className="oa-kicker">WASTE / RESEARCH WORKSPACE</span><h1>Waste research, from local to global.</h1><p>Compare places. Follow change over time. Check the evidence behind every figure.</p></div><button className="oa-button outline" onClick={()=>onGo({view:'facilities',kind:'landfill',site:'',siteQuery:'',siteType:''})}><Factory size={17}/>Find waste facilities<ArrowRight size={16}/></button></header>
  <div className="wr-scope"><span><strong>{catalog.data?number(catalog.data.counts.historyRecords,0):'…'}</strong> historical observations</span><span><strong>{catalog.data?number(catalog.data.counts.cities,0):'…'}</strong> city / area identifiers</span><span><strong>3</strong> source families: World Bank, UN, Eurostat</span><span className="wr-scope-note">Fixed snapshots · source years vary</span></div>
  <Tabs value={state.wasteTab} onValueChange={v=>onChange({wasteTab:v as AtlasState['wasteTab'],wasteQuery:''})} className="wr-tabs"><TabsList aria-label="Waste research view"><TabsTrigger value="compare">Compare places</TabsTrigger><TabsTrigger value="trends">Trends & materials</TabsTrigger><TabsTrigger value="cities">City collection</TabsTrigger><TabsTrigger value="records">Maps & source records</TabsTrigger></TabsList></Tabs>
  <div className="wr-panel" key={state.wasteTab}>
   {state.wasteTab==='compare'&&<Compare {...props} onInspect={setInspect}/>}
   {state.wasteTab==='trends'&&(catalog.error?<ErrorState message={catalog.error}/>:catalog.data?<Trends {...props} catalog={catalog.data} onInspect={setInspect}/>:<Loading/>)}
   {state.wasteTab==='cities'&&<Cities {...props} onInspect={setInspect}/>}
   {state.wasteTab==='records'&&<WasteSystems focusRecord={Boolean(state.wastePlace)} place={state.place} wastePlace={state.wastePlace} countries={countries} onSelect={(place,wastePlace)=>onChange({place,wastePlace})} onTrade={place=>onGo({view:'trade',place,dataset:'controlled'})}/>}
  </div>
  <section className="wr-research-guide"><div><BookOpen size={21}/><h2>A useful comparison starts<br/>with the same question.</h2></div><p><b>Check the denominator.</b> Waste collected, population served and material recycled measure different things.</p><p><b>Read the year and scope.</b> A 2026 edition can contain an older observation. A city is not always a municipality.</p><p><b>Keep the gaps visible.</b> Missing values stay missing. Collection does not prove safe treatment; recycling input is not recovered output.</p></section>
  <div className="wr-next"><button onClick={()=>onGo({view:'trade',dataset:'controlled'})}>Follow reported waste trade<ArrowRight size={17}/></button><button onClick={()=>onGo({view:'facilities',kind:'river',place:'WORLD',site:''})}>Investigate river plastic reaching the ocean<ArrowRight size={17}/></button><button onClick={()=>onGo({view:'data'})}>Use the data API & MCP<ArrowRight size={17}/></button></div>
  <Sheet open={!!inspect} onOpenChange={o=>{if(!o)setInspect(null)}}><SheetContent className="oa-sheet wr-inspector"><SheetTitle>{inspect?.title||'Source observation'}</SheetTitle><SheetDescription>{inspect?.subtitle}</SheetDescription>{inspect&&<><p>{inspect.description}</p><a className="oa-source-row" href={inspect.source.metadataUrl||inspect.source.url} target="_blank" rel="noreferrer"><span><strong>{inspect.source.title}</strong><small>{inspect.source.publisher}</small></span><ArrowUpRight size={18}/></a><p className="oa-small">Snapshot acquired {inspect.source.retrievedAt?.slice(0,10)} · {inspect.source.license}</p><ObservationNotes data={inspect.data}/><Export disabled={false} onClick={()=>exportCSV([{...inspect.data,dataset:inspect.source.title,source_url:inspect.source.url,metadata_url:inspect.source.metadataUrl,retrieved_at:inspect.source.retrievedAt,license:inspect.source.license}],'overshoot-observation.csv')}/></>}</SheetContent></Sheet>
 </div>
}
function ObservationNotes({data}:{data:Record<string,unknown>}){
 const notes=Array.isArray(data.footnotes)?data.footnotes.map(String):data.footnotes?[String(data.footnotes)]:[];
 const flags=Array.isArray(data.flagLabels)?data.flagLabels.filter(Boolean).join(' · '):'';
 const links=[...new Set(([String(data.source||''),...notes].join(' ').match(/https?:\/\/[^\s;<>]+/g)||[]).map(s=>s.replace(/[.,)]+$/,'')))];
 return <><p className="wr-source-value">{show(data.value as number|null)} <small>{String(data.unit||'')}</small></p><p>{String(data.year||'Year not specified')} · {String(data.basis||'Basis not specified')}{flags?' · '+flags:''}</p><h3>Original provider</h3><p>{String(data.source||'See dataset attribution')}</p><h3>What the source says</h3>{notes.length?notes.map((n,i)=><p className="wr-source-note" key={i}>{n}</p>):<p className="oa-small">No observation-specific footnote. The dataset definition and status flags still apply.</p>}{links.map((url,i)=><a className="oa-source-row" key={url} href={url} target="_blank" rel="noreferrer">Open cited source{links.length>1?' '+(i+1):''}<ArrowUpRight size={15}/></a>)}<details className="oa-method"><summary>Original values, units & source fields</summary><pre>{JSON.stringify(data,null,2)}</pre></details></>
}
function OriginalReferences({observation}:{observation:Record<string,unknown>}){
 const refs=(observation.references||[]) as Array<Record<string,unknown>>;
 return <><h3>Original references</h3>{refs.map((r,i)=>{const urls=[...new Set((Object.values(r).join(' ').match(/https?:\/\/[^\s;<>]+/g)||[]).map(s=>s.replace(/[.,)]+$/,'')))];return <article className="wr-reference" key={i}><h4>{String(r.source||'Source reference '+(i+1))}</h4><dl>{Object.entries(r).filter(([k,v])=>!['source','url','workbook','sheet','row'].includes(k)&&v!==null&&v!==undefined&&v!=='').map(([k,v])=><div key={k}><dt>{k.replaceAll('_',' ')}</dt><dd>{textValue(v)}</dd></div>)}</dl>{urls.map((url,j)=><a key={url} href={url} target="_blank" rel="noreferrer">Open original source{urls.length>1?' '+(j+1):''} <ArrowUpRight size={14}/></a>)}</article>})}<details className="oa-method"><summary>Original fields & workbook lineage</summary><pre>{JSON.stringify(observation,null,2)}</pre></details></>
}
function Compare({state,onChange}:Props&{onInspect:(d:Inspect)=>void}){
 const data=useMaterialArtifact<WasteComparison>(researchBase+'comparison.json');
 const [sort,setSort]=useState('name'),[pageState,setPageState]=useState({key:'',page:0}),[fieldRecord,setFieldRecord]=useState<{id:string;field:string}|null>(null);
 const full=useMaterialArtifact<{observations:Record<string,Record<string,unknown>>;name:string;year:number;workbook:string;sheet:string;row:number}>(fieldRecord?'/data/v12/waste/'+fieldRecord.id+'.json':null);
 const metric=data.data?.fields[state.wasteMetric]?state.wasteMetric:'perPerson';const field=data.data?.fields[metric];
 const key=[state.wasteQuery,state.place,state.wasteLevel,metric,sort].join('|'),page=key===pageState.key?pageState.page:0;
 const selected=(state.compare||'').split(',').filter(Boolean);const chosen=data.data?.records.filter(r=>selected.includes(r.id))||[];
 const rows=useMemo(()=>{const r=(data.data?.records||[]).filter(r=>r.level===state.wasteLevel&&(state.place==='WORLD'||r.country===(['SSI','BC'].includes(state.place)?'CAN':state.place))&&(!state.wasteQuery||(r.name+' '+r.countryName).toLowerCase().includes(state.wasteQuery.toLowerCase())));return r.sort((a,b)=>sort==='value'?(b.observations[metric]?.value??-Infinity)-(a.observations[metric]?.value??-Infinity)||a.name.localeCompare(b.name):a.name.localeCompare(b.name))},[data.data,state.wasteLevel,state.place,state.wasteQuery,metric,sort]);
 function toggle(r:ComparisonPlace){onChange({compare:(selected.includes(r.id)?selected.filter(id=>id!==r.id):selected.length<4?[...selected,r.id]:selected).join(',')})}
 function download(records:ComparisonPlace[]){exportCSV(records.map(r=>({place:r.name,country:r.country,level:r.level,measure:field!.label,value:r.observations[metric]?.value??null,unit:field!.unit,source_dates:comparisonDate(r.observations[metric]),source_field:r.observations[metric]?.sourceField,issue:r.observations[metric]?.issue,definition:field!.description,dataset:data.data!.source.title,source_url:data.data!.source.url,record_url:'/data/v12/waste/'+r.id+'.json',license:data.data!.source.license})),'overshoot-waste-comparison.csv')}
 if(data.error)return <ErrorState message={data.error}/>;if(!data.data||!field)return <Loading/>;
 const coreFields=[...new Set([metric,...primaryFields])];
 return <>
  <div className="wr-section-head"><div><h2>Compare the same measure, place by place.</h2><p>World Bank · What a Waste 3.0. Choose up to four records for a side-by-side view.</p></div><SourceLink source={data.data.source}/></div>
  <div className="wr-controls"><label>Measure<select aria-label="Comparison measure" value={metric} onChange={e=>onChange({wasteMetric:e.target.value})}>{['generation','collection','composition','treatment','other','projection','local'].map(group=><optgroup key={group} label={group}>{Object.entries(data.data!.fields).filter(([,f])=>f.group===group).map(([id,f])=><option key={id} value={id}>{f.label} · {f.unit}</option>)}</optgroup>)}</select></label><label>Record level<select aria-label="Record level" value={state.wasteLevel} onChange={e=>onChange({wasteLevel:e.target.value as 'country'|'city'})}><option value="country">Countries & economies</option><option value="city">Cities & service areas</option></select></label><SearchBox value={state.wasteQuery} onChange={wasteQuery=>onChange({wasteQuery})} label="Find a country or city"/></div>
  <div className="wr-definition"><b>{field.label} · {field.unit}</b><p>{field.description} Source years vary; the table is not a performance league table.</p></div>
  {chosen.length>0&&<section className="wr-comparison" aria-label="Selected place comparison"><div className="wr-section-head"><h3>{chosen.length} / 4 places selected</h3><Export label="Export comparison" disabled={!chosen.length} onClick={()=>exportCSV(chosen.flatMap(r=>coreFields.map(f=>({place:r.name,country:r.country,level:r.level,measure:data.data!.fields[f].label,value:r.observations[f]?.value??null,unit:data.data!.fields[f].unit,source_dates:comparisonDate(r.observations[f]),source_field:r.observations[f]?.sourceField,definition:data.data!.fields[f].description,dataset:data.data!.source.title,source_url:data.data!.source.url,record_url:'/data/v12/waste/'+r.id+'.json',license:data.data!.source.license}))),'overshoot-selected-comparison.csv')}/><button className="oa-text-link" onClick={()=>onChange({compare:''})}>Clear comparison <X size={15}/></button></div><div className="wr-table-scroll" tabIndex={0} role="region" aria-label="Side-by-side waste comparison"><table><thead><tr><th>Measure</th>{chosen.map(r=><th key={r.id}>{r.name}<small>{r.level==='city'?r.countryName:'National record'}</small><button aria-label={'Remove '+r.name+' from comparison'} onClick={()=>toggle(r)}><X size={14}/></button></th>)}</tr></thead><tbody>{coreFields.map(f=><tr key={f}><th>{data.data!.fields[f].label}<small>{data.data!.fields[f].unit}</small></th>{chosen.map(r=><td key={r.id}><button className="wr-cell" disabled={!r.observations[f]} onClick={()=>setFieldRecord({id:r.id,field:f})}><b>{show(r.observations[f]?.value)}</b><small>{comparisonDate(r.observations[f])}</small>{r.observations[f]&&<span>Source <ArrowUpRight size={12}/></span>}</button></td>)}</tr>)}</tbody></table></div><p className="wr-caption">Values retain each source’s date and boundary. Treatment shares can overlap; missing categories are not inferred. Select any value to inspect its original references.</p></section>}
  <div className="wr-result-head"><div><b>{number(rows.length,0)} matching records</b><span>{rows.filter(r=>r.observations[metric]?.value!=null).length} report this measure · {field.unit}</span></div><label className="wr-sort">Order<select aria-label="Comparison order" value={sort} onChange={e=>setSort(e.target.value)}><option value="name">Place name</option><option value="value">Value: high to low</option></select></label><Export disabled={!rows.length} onClick={()=>download(rows)}/></div>
  <div className="wr-table-scroll" tabIndex={0} role="region" aria-label="Waste records"><table><thead><tr><th>Compare</th><th>Place</th><th className="wr-number">{field.label}<small>{field.unit}</small></th><th>Source year / date</th><th>Evidence</th></tr></thead><tbody>{rows.slice(page*25,page*25+25).map(r=><tr key={r.id}><td><input type="checkbox" aria-label={'Compare '+r.name} checked={selected.includes(r.id)} disabled={!selected.includes(r.id)&&selected.length>=4} onChange={()=>toggle(r)}/></td><th>{r.name}<small>{r.level==='city'?r.countryName:'Country / economy'}</small></th><td className="wr-number">{show(r.observations[metric]?.value)}</td><td>{comparisonDate(r.observations[metric])}{r.observations[metric]?.issue&&<small>Check source note</small>}</td><td><button className="wr-source-button" disabled={!r.observations[metric]} onClick={()=>setFieldRecord({id:r.id,field:metric})} aria-label={'Inspect '+field.label+' for '+r.name}>Source <ArrowUpRight size={14}/></button></td></tr>)}</tbody></table></div>
  {!rows.length&&<div className="wr-empty"><h3>No matching records in this source.</h3><p>Change the record level, search or place. An empty result does not mean no waste.</p><button className="oa-button outline" onClick={()=>onChange({place:'WORLD',wasteQuery:''})}>Search worldwide</button></div>}
  <Pager total={rows.length} page={page} onPage={n=>setPageState({key,page:n})}/>
  <Sheet open={!!fieldRecord} onOpenChange={o=>{if(!o)setFieldRecord(null)}}><SheetContent className="oa-sheet wr-inspector"><SheetTitle>{fieldRecord?data.data.fields[fieldRecord.field]?.label:'Original source'}</SheetTitle><SheetDescription>{full.data?.name||'Loading source record'}</SheetDescription>{full.error?<ErrorState message={full.error}/>:!full.data?<Loading/>:fieldRecord&&<><p>{data.data.fields[fieldRecord.field]?.description}</p><p className="wr-source-value">{show(full.data.observations[fieldRecord.field]?.value as number|null)} <small>{data.data.fields[fieldRecord.field]?.unit}</small></p><p>Source date: {comparisonDate(data.data.records.find(r=>r.id===fieldRecord.id)?.observations[fieldRecord.field])}</p><OriginalReferences observation={full.data.observations[fieldRecord.field]||{}}/><a className="oa-source-row" href={data.data.source.url} target="_blank" rel="noreferrer">World Bank dataset & codebooks <ArrowUpRight size={16}/></a><p className="oa-small">{full.data.workbook} · {full.data.sheet} · row {full.data.row} · {data.data.source.license}</p><button className="oa-button outline" onClick={()=>{onChange({wasteTab:'records',place:data.data!.records.find(r=>r.id===fieldRecord.id)!.country,wastePlace:fieldRecord.id});setFieldRecord(null)}}>Open complete place record <ArrowRight size={16}/></button></>}</SheetContent></Sheet>
 </>
}
function Trends({state,countries,onChange,catalog,onInspect}:Props&{catalog:WasteCatalog;onInspect:(d:Inspect)=>void}){
 const meta=catalog.series.find(s=>s.id===state.wasteSeries)||catalog.series.find(s=>s.id==='eu-municipal-gen-kg-hab')!;
 const dataset=useMaterialArtifact<WasteObservation[]>(meta.path);const source=catalog.sources[meta.sourceId];
 const [pageState,setPageState]=useState({key:'',page:0});
 const requested=state.compare.split(',').filter(s=>/^[A-Z]{3}$/.test(s));
 const selected=requested.length?requested:state.place!=='WORLD'?[['BC','SSI'].includes(state.place)?'CAN':state.place]:['DEU','FRA'];
 const available=countries.filter(c=>meta.countries[c.id]).sort((a,b)=>a.name.localeCompare(b.name));
 const rows=(dataset.data||[]).filter(r=>selected.includes(r.country)&&(!state.wasteFrom||r.year>=Number(state.wasteFrom))&&(!state.wasteTo||r.year<=Number(state.wasteTo))).sort((a,b)=>b.year-a.year||a.country.localeCompare(b.country));
 const key=meta.id+selected.join(',')+state.wasteFrom+state.wasteTo,page=key===pageState.key?pageState.page:0;
 const label=(id:string)=>countries.find(c=>c.id===id)?.name||id;
 function inspect(r:WasteObservation){onInspect({title:label(r.country)+' · '+r.year,subtitle:meta.label+' · '+meta.unit,data:r,source,description:meta.description})}
 return <>
  <div className="wr-section-head"><div><h2>See what changed. Keep the source in view.</h2><p>123 separate series across municipal, packaging, electronic, hazardous and food waste.</p></div><SourceLink source={source}/></div>
  <div className="wr-controls wr-trend-controls"><label>Waste stream<select aria-label="Waste stream" value={meta.group} onChange={e=>onChange({wasteFrom:'',wasteTo:'',wasteSeries:catalog.series.find(s=>s.group===e.target.value&&s.operation==='GEN')?.id||catalog.series.find(s=>s.group===e.target.value)!.id})}>{groups.map(g=><option key={g}>{g}</option>)}</select></label><label>Measure & source<select aria-label="Trend measure" value={meta.id} onChange={e=>onChange({wasteSeries:e.target.value,wasteFrom:'',wasteTo:''})}>{catalog.series.filter(s=>s.group===meta.group).map(s=><option key={s.id} value={s.id}>{s.label} · {s.unit} · {s.sourceId.startsWith('eu')?'Eurostat':'UN'}</option>)}</select></label></div>
  <div className="wr-definition"><b>{meta.unit} · {meta.years[0]}–{meta.years.at(-1)} · {available.length} countries / areas available</b><p>{meta.description} {meta.comparability}</p></div>
  <div className="wr-period"><label>From<select aria-label="Trend start year" value={state.wasteFrom||'all'} onChange={e=>onChange({wasteFrom:e.target.value==='all'?'':e.target.value,...(state.wasteTo&&e.target.value!=='all'&&+e.target.value>+state.wasteTo?{wasteTo:''}:{})})}><option value="all">First available</option>{state.wasteFrom&&!meta.years.includes(+state.wasteFrom)&&<option value={state.wasteFrom}>{state.wasteFrom} · outside source years</option>}{meta.years.map(y=><option key={y} value={y}>{y}</option>)}</select></label><label>To<select aria-label="Trend end year" value={state.wasteTo||'all'} onChange={e=>onChange({wasteTo:e.target.value==='all'?'':e.target.value})}><option value="all">Latest available</option>{state.wasteTo&&!meta.years.includes(+state.wasteTo)&&<option value={state.wasteTo}>{state.wasteTo} · outside source years</option>}{meta.years.filter(y=>!state.wasteFrom||y>=+state.wasteFrom).map(y=><option key={y} value={y}>{y}</option>)}</select></label></div>
  <div className="wr-country-controls"><div>{selected.map((id,i)=><button key={id} className="wr-chip" onClick={()=>onChange({compare:(selected.length>1?selected.filter(s=>s!==id):selected).join(',')})} aria-label={'Remove '+label(id)} disabled={selected.length===1}><i style={{background:palette[i]}}/>{label(id)}{selected.length>1&&<X size={14}/>}</button>)}</div><label>Add or replace a country<select aria-label="Add trend country" value="" onChange={e=>{if(e.target.value)onChange({compare:(selected.length>=4?[...selected.slice(0,3),e.target.value]:[...selected,e.target.value]).join(',')})}}><option value="">Choose a country…</option>{available.filter(c=>!selected.includes(c.id)).map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label></div>
  {selected.some(id=>!meta.countries[id])&&<div className="wr-gap" role="status"><p>No observations for {selected.filter(id=>!meta.countries[id]).map(label).join(', ')} in this series. These alternative measures have some coverage for your selection:</p><div>{catalog.series.filter(s=>s.id!==meta.id&&s.group===meta.group&&selected.some(id=>s.countries[id])).slice(0,3).map(s=><button className="oa-text-link" key={s.id} onClick={()=>onChange({wasteSeries:s.id,wasteFrom:'',wasteTo:''})}>{s.label} · {s.unit}<ArrowRight size={14}/></button>)}</div></div>}
  {dataset.error?<ErrorState message={dataset.error}/>:!dataset.data?<Loading/>:<>
   {!rows.length&&<div className="wr-empty"><h3>No observations match this selection.</h3><p>Check the available countries and source period above.</p>{(state.wasteFrom||state.wasteTo)&&<button className="oa-button outline" onClick={()=>onChange({wasteFrom:'',wasteTo:''})}>Show all source years</button>}</div>}
   {!!rows.length&&<TrendChart rows={rows} selected={selected} unit={meta.unit} label={label} onInspect={inspect}/>}
   <div className="wr-result-head"><div><b>{number(rows.length,0)} source observations</b><span>{source.publisher} · snapshot {source.retrievedAt.slice(0,10)}</span></div><Export disabled={!rows.length} onClick={()=>exportCSV(rows.map(r=>({...r,measure:meta.label,dataset:source.title,source_url:source.url,metadata_url:source.metadataUrl,retrieved_at:source.retrievedAt,license:source.license})),'overshoot-waste-history.csv')}/></div>
   <div className="wr-table-scroll" tabIndex={0} role="region" aria-label="Historical waste observations"><table><thead><tr><th>Place</th><th>Year</th><th className="wr-number">Value<small>{meta.unit}</small></th><th>Basis & quality flags</th><th>Evidence</th></tr></thead><tbody>{rows.slice(page*25,page*25+25).map(r=><tr key={r.id}><th>{label(r.country)}</th><td>{r.year}</td><td className="wr-number">{show(r.value)}</td><td>{r.basis}<small>{r.flagLabels.filter(Boolean).join(' · ')||'No additional status flag'}</small></td><td><button className="wr-source-button" onClick={()=>inspect(r)} aria-label={'Inspect '+label(r.country)+' '+r.year}>Source<ArrowUpRight size={14}/></button></td></tr>)}</tbody></table></div><Pager total={rows.length} page={page} onPage={n=>setPageState({key,page:n})}/>
  </>}
 </>
}
function TrendChart({rows,selected,unit,label,onInspect}:{rows:WasteObservation[];selected:string[];unit:string;label:(id:string)=>string;onInspect:(r:WasteObservation)=>void}){
 const minYear=Math.min(...rows.map(r=>r.year)),maxYear=Math.max(...rows.map(r=>r.year)),max=Math.max(1,...rows.map(r=>r.value));const left=85,right=855,top=30,bottom=255;
 const x=(y:number)=>left+(y-minYear)/Math.max(1,maxYear-minYear)*(right-left),y=(n:number)=>bottom-n/max*(bottom-top);
 return <figure className="wr-chart"><div className="wr-chart-heading"><strong>{unit}</strong><span>Select a point to read its source</span></div><svg viewBox="0 0 900 300" role="img" aria-label={'Waste trend from '+minYear+' to '+maxYear+'. All values are in the table below.'}>
  {[0,0.25,0.5,0.75,1].map(t=><g key={t}><line x1={left} x2={right} y1={y(max*t)} y2={y(max*t)} className="wr-gridline"/><text x={left-10} y={y(max*t)+4} textAnchor="end">{new Intl.NumberFormat(undefined,{notation:'compact',maximumFractionDigits:1}).format(max*t)}</text></g>)}
  {[...new Set([minYear,Math.round((minYear+maxYear)/2),maxYear])].map(year=><text key={year} x={x(year)} y={285} textAnchor="middle">{year}</text>)}
  {selected.map((id,i)=>{const points=uniqueYearPoints(rows.filter(r=>r.country===id));return <g key={id} fill={palette[i]} stroke={palette[i]}>{points.map((r,k)=>{const prev=points[k-1];return <g key={r.id}>{prev&&r.year===prev.year+1&&!r.flags.includes('b')&&<line x1={x(prev.year)} y1={y(prev.value)} x2={x(r.year)} y2={y(r.value)} strokeWidth="2"/>}<circle cx={x(r.year)} cy={y(r.value)} r="4" role="button" tabIndex={0} aria-label={label(id)+' '+r.year+': '+show(r.value)+' '+unit} onClick={()=>onInspect(r)} onKeyDown={e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();onInspect(r)}}}><title>{label(id)} · {r.year}: {show(r.value)} {unit}{r.flags?' · '+r.flagLabels.join(', '):''}</title></circle></g>})}</g>})}
 </svg><figcaption>Lines join consecutive observations only. Gaps and marked breaks remain disconnected. Projections and estimates retain their source labels in the table.</figcaption></figure>
}
function Cities({state,onChange,onInspect}:Props&{onInspect:(d:Inspect)=>void}){
 const data=useMaterialArtifact<CityCollectionData>(researchBase+'city-collection.json');const [pageState,setPageState]=useState({key:'',page:0});
 const country=['BC','SSI'].includes(state.place)?'CAN':state.place;
 const rows=useMemo(()=>collectionRows(data.data?.records||[],country,state.wasteQuery,state.wasteYear),[data.data,country,state.wasteQuery,state.wasteYear]);
 const key=country+'|'+state.wasteQuery+'|'+state.wasteYear,page=key===pageState.key?pageState.page:0;
 if(data.error)return <ErrorState message={data.error}/>;if(!data.data)return <Loading/>;
 const years=[...new Set(data.data.records.map(r=>r.year))].sort((a,b)=>b-a);const source=data.data.source;
 function inspect(r:CityCollection){onInspect({title:r.city,subtitle:r.countryName+' · '+r.year+' · '+show(r.value)+'% collection coverage',data:r,source,description:'Read the original notes to check the collection denominator and service boundary. This figure alone does not establish recycling or controlled disposal.'})}
 return <>
  <div className="wr-section-head"><div><h2>How much of a city’s waste is collected?</h2><p>UN SDG source records · 4,452 city / area identifiers across 152 mapped countries and areas.</p></div><SourceLink source={source}/></div>
  <div className="wr-controls wr-city-controls"><SearchBox value={state.wasteQuery} onChange={wasteQuery=>onChange({wasteQuery})} label="Search city or country"/><label>Observation year<select aria-label="City observation year" value={state.wasteYear} onChange={e=>onChange({wasteYear:e.target.value})}><option value="latest">Latest available per city</option><option value="all">All retained years</option>{years.map(y=><option key={y} value={y}>{y}</option>)}</select></label></div>
  <div className="wr-definition"><b>Collection coverage · not a recycling rate</b><p>Years and city boundaries vary. The intended measure is waste collected as a share of waste generated; some providers use service-population coverage. Inspect the notes before comparing. Collection does not establish safe disposal.</p></div>
  <div className="wr-result-head"><div><b>{number(rows.length,0)} observations · {number(new Set(rows.map(r=>r.cityId)).size,0)} city / area identifiers</b><span>Latest means latest in the source, not the current year.</span></div><Export disabled={!rows.length} onClick={()=>exportCSV(rows.map(r=>({...r,dataset:source.title,source_url:source.url,metadata_url:source.metadataUrl,retrieved_at:source.retrievedAt,license:source.license})),'overshoot-city-collection.csv')}/></div>
  <div className="wr-table-scroll" tabIndex={0} role="region" aria-label="City waste collection records"><table><thead><tr><th>City / source area</th><th>Year</th><th className="wr-number">Collection coverage</th><th>Observation basis</th><th>Evidence</th></tr></thead><tbody>{rows.slice(page*25,page*25+25).map(r=><tr key={r.id}><th>{r.city}<small>{r.countryName}</small></th><td>{r.year}</td><td className="wr-number">{show(r.value)}%{r.issue&&<small>Check source</small>}</td><td>{r.basis}</td><td><button className="wr-source-button" onClick={()=>inspect(r)} aria-label={'Inspect '+r.city+' '+r.year}>Source<ArrowUpRight size={14}/></button></td></tr>)}</tbody></table></div>
  {!rows.length&&<div className="wr-empty"><h3>No matching city observations.</h3><p>Try a broader search or another source year. No location or quantity is inferred for an unreported city.</p><button className="oa-button outline" onClick={()=>onChange({place:'WORLD',wasteQuery:'',wasteYear:'latest'})}>Reset to worldwide coverage</button></div>}
  <Pager total={rows.length} page={page} onPage={n=>setPageState({key,page:n})}/><p className="wr-caption">Source city identifiers are preserved, not joined to World Bank city records or inferred coordinates. A source area can cover a municipality, metropolitan area or service boundary.</p>
 </>
}
