'use client';
import {useEffect,useMemo,useRef,useState} from 'react';
import {useOnChange} from '../useOnChange';
import {ArrowRight,ArrowUpRight,BookOpen,Building2,Download,Globe2,Search} from 'lucide-react';
import {CommandDialog,CommandEmpty,CommandGroup,CommandInput,CommandItem,CommandList} from '@/components/ui/command';
import {Sheet,SheetContent,SheetDescription,SheetTitle} from '@/components/ui/sheet';
import {Tabs,TabsList,TabsTrigger} from '@/components/ui/tabs';
import {useMaterialArtifact} from '../material-data';
import WorldMap from '../world/WorldMap';
import type {Country} from '../world/model';
import {Choice,compact,Empty,ErrorState,exportCSV,Loading,number} from './common';

export type WasteEntry={id:string;country:string;level:'country'|'city';name:string;countryName:string;region:string;year:number|null;tonnes:number|null;perPerson:number|null;projection_2022:number|null;treatment_recycling:number|null;treatment_open_dumpsite:number|null;treatment_recyclingDates?:string[];treatment_open_dumpsiteDates?:string[];compositionCount:number;treatmentCount:number};
type Field={label:string;group:string;unit:string;description:string};
type Reference={workbook:string;sheet:string;row:number;date?:string|number;source?:string;page?:string|number;url?:string;method?:string;point?:string;notes?:string;collectionNotes?:string};
type Observation={value:number|null;rawValue:number|string;sourceField:string;unit:string;references:Reference[];issue?:string};
type WasteRecord={id:string;country:string;name:string;countryName:string;level:'country'|'city';year:number|null;point:string;workbook:string;sheet:string;row:number;observations:Record<string,Observation>};
export type WasteIndex={title:string;publisher:string;edition:number;retrievedAt:string;url:string;citation:string;license:string;fields:Record<string,Field>;records:WasteEntry[];counts:{countryRecords:number;cityRecords:number;observations:number}};
const measures={
 projection_2022:{label:'Waste generated · 2022 model',unit:'tonnes',year:'2022 · modeled',description:'A common-year estimate from the World Bank. The country and city records below retain their original reporting years.'},
 tonnes:{label:'Waste generated · reported',unit:'tonnes',year:'Reporting years vary',description:'The latest amounts retained in this edition. Reporting years and measurement boundaries differ between places.'},
 perPerson:{label:'Waste per person · reported',unit:'kg/person/day',year:'Reporting years vary',description:'Municipal waste relative to the source population. This compares area averages, not individual households.'},
 treatment_recycling:{label:'Sent for recycling',unit:'%',year:'Source dates vary',description:'Waste collected for recycling, as defined by the World Bank. Processing losses and actual recovered output are not measured here.'},
 treatment_open_dumpsite:{label:'Open dumping',unit:'%',year:'Source dates vary',description:'The reported share sent to land disposal with no or limited controls. A missing record does not mean no dumping.'}
};
function dates(o:Observation){return [...new Set(o.references.map(r=>r.date).filter(v=>v!==undefined&&v!==null))].join(' / ')}
function display(value:number,unit:string){return unit==='tonnes/year'||unit==='tonnes'?compact(value):number(value,unit.startsWith('%')?1:2)}
function sourceLinks(text=''){return [...new Set((text.match(/https?:\/\/[^\s;<>]+/g)||[]).map(s=>s.replace(/[.,)]+$/,'')))];}

export default function WasteSystems({place,wastePlace,countries,onSelect,onTrade,focusRecord=false}:{focusRecord?:boolean;place:string;wastePlace:string;countries:Country[];onSelect:(country:string,id:string)=>void;onTrade:(place:string)=>void}){
 const index=useMaterialArtifact<WasteIndex>('/data/v12/waste-index.json');
 const [measure,setMeasure]=useState<keyof typeof measures>('projection_2022'),[picker,setPicker]=useState(false),[type,setType]=useState('all'),[selectedField,setSelectedField]=useState<string|null>(null),[limit,setLimit]=useState(8);
 const scrollToRecord=useRef(false);
 const records=index.data?.records||[],regional=['BC','SSI'].includes(place),id=wastePlace||(regional?'CAN':place);
 const entry=records.find(r=>r.id===id);
 const record=useMaterialArtifact<WasteRecord>(entry?'/data/v12/waste/'+entry.id+'.json':null);
 const meta=measures[measure];
 const ids=useMemo(()=>new Set(countries.map(c=>c.id)),[countries]);
 const ranked=useMemo(()=>records.filter(r=>r.level==='country'&&r[measure]!==null).sort((a,b)=>(b[measure] as number)-(a[measure] as number)),[index.data,measure]);
 const values=useMemo(()=>new Map(ranked.filter(r=>ids.has(r.country)).map(r=>[r.country,r[measure] as number])),[ranked,ids,measure]);
 const relatedCities=records.filter(r=>r.level==='city'&&(entry?r.country===entry.country:true));
 useOnChange([id],()=>{setSelectedField(null);setLimit(8)});
 useEffect(()=>{if(scrollToRecord.current){document.getElementById('waste-record')?.scrollIntoView({behavior:window.matchMedia('(prefers-reduced-motion: reduce)').matches?'auto':'smooth'});scrollToRecord.current=false}},[id]);
 function select(r:WasteEntry){scrollToRecord.current=true;onSelect(ids.has(r.country)?r.country:'WORLD',r.id);setPicker(false);if(r.id===id){document.getElementById('waste-record')?.scrollIntoView({behavior:window.matchMedia('(prefers-reduced-motion: reduce)').matches?'auto':'smooth'});scrollToRecord.current=false}}
 useEffect(()=>{if(focusRecord&&record.data)document.getElementById('waste-record')?.scrollIntoView({behavior:window.matchMedia('(prefers-reduced-motion: reduce)').matches?'auto':'smooth',block:'start'})},[focusRecord,record.data?.id]);
 const o=selectedField?record.data?.observations[selectedField]:undefined;
 const field=selectedField?index.data?.fields[selectedField]:undefined;
 const yearFor=(r:WasteEntry)=>measure==='projection_2022'?'2022 · model':measure==='tonnes'||measure==='perPerson'?(r.year===null?'Year not specified':String(r.year)):((r[measure+'Dates' as keyof WasteEntry] as string[]|undefined)||[]).join(' / ')||'Date in source record';
 return <div className="oa-waste-systems">
  <div className="oa-depth-heading"><div><span className="oa-kicker">MUNICIPAL WASTE · WORLD BANK · 2026 EDITION</span><h2>From the bin to the next destination.</h2><p>See what is discarded, how much is collected, and which treatment methods are reported.</p></div><button className="oa-button" onClick={()=>{setType('all');setPicker(true)}} disabled={!index.data}><Search size={18}/>Find a country or city</button></div>
  {index.error?<ErrorState message={index.error}/>:!index.data?<Loading/>:<>
   <div className="oa-dataset-strip"><span><strong>{index.data.counts.countryRecords}</strong> countries & economies</span><span><strong>{index.data.counts.cityRecords}</strong> city records</span><span><strong>{number(index.data.counts.observations,0)}</strong> retained values</span><a href={index.data.url} target="_blank" rel="noreferrer">World Bank data & codebooks<ArrowUpRight size={15}/></a></div>
   <section className="oa-waste-map" aria-label="Compare municipal waste by country"><div className="oa-map-toolbar"><Choice label="Map measure" value={measure} onChange={v=>setMeasure(v as keyof typeof measures)} options={Object.entries(measures).map(([id,m])=>({id,name:m.label}))}/><p>{meta.description}</p></div>
    <div className="oa-map-workspace"><WorldMap flows={[]} sites={[]} countries={countries} place={entry&&ids.has(entry.country)?entry.country:entry?'WORLD':place} selected="" onFlow={()=>{}} onSite={()=>{}} onPlace={country=>onSelect(country,country)} color="#448466" siteView={false} countryLayer={{values,label:meta.label,unit:meta.unit,year:meta.year,thresholds:meta.unit==='%'?[10,25,50,75]:meta.unit==='kg/person/day'?[0.5,1,1.5,2]:[1e6,1e7,5e7,1e8],loading:!index.data}}/>
     <aside className="oa-map-inspector"><span className="oa-kicker">{entry?.level==='city'?'COUNTRY CONTEXT':entry?entry.name.toUpperCase():'COUNTRY COMPARISON'}</span><h3>{meta.label}</h3>{entry&&(()=>{const nation=records.find(r=>r.id===entry.country);const v=nation?.[measure];return <p className="oa-map-value">{typeof v==='number'?display(v,meta.unit):'Not reported'}<span>{entry.countryName} · {meta.unit}{nation?' · '+yearFor(nation):''}</span></p>})()}<p className="oa-small">{values.size} mapped countries / areas. Select a country to open its source records below.</p><div className="oa-connection-list"><span className="oa-kicker">LARGEST AVAILABLE FIGURES</span>{ranked.slice(0,4).map(r=><button key={r.id} onClick={()=>select(r)}><span>{r.name}<small>{yearFor(r)}</small></span><b>{display(r[measure] as number,meta.unit)}</b></button>)}</div>{entry&&<a className="oa-text-link" href="#waste-record">Read this place’s records<ArrowRight size={15}/></a>}</aside>
    </div>
   </section>
   {entry?<section id="waste-record" className="oa-waste-place-record" key={entry.id}>
    <div className="oa-depth-heading"><div><span className="oa-kicker">{entry.level==='city'?'CITY RECORD · '+entry.countryName:'NATIONAL RECORD'}</span><h2>{entry.name}</h2><p>{regional&&!wastePlace?'National context for the selected region. ':''}{entry.level==='city'?'The reporting boundary may cover a city, service area, or wider metropolitan region. Open a source note to check.':'Municipal waste covers households and similar waste from businesses and institutions.'}</p></div><div className="oa-inline-actions">{entry.level==='city'&&records.find(r=>r.id===entry.country)&&<button className="oa-text-link" onClick={()=>select(records.find(r=>r.id===entry.country)!)}>National record<ArrowRight size={15}/></button>}<button className="oa-button outline" onClick={()=>{setType('all');setPicker(true)}}><Search size={16}/>Change record</button></div></div>
    {record.error?<ErrorState message={record.error}/>:!record.data?<Loading/>:<>
     <div className="oa-evidence-stats">{['tonnes','perPerson',...(['collection_population','collection_households','collection_waste'].filter(k=>record.data?.observations[k]?.value!==null&&record.data?.observations[k]?.value!==undefined).slice(0,1))].map(k=>{const v=record.data!.observations[k],f=index.data!.fields[k];return <button key={k} onClick={()=>setSelectedField(k)} disabled={!v}><span>{f.label}</span><strong>{v?.value===null||v?.value===undefined?'Not reported':display(v.value,f.unit)}{f.unit.startsWith('%')&&v?.value!==null&&v?.value!==undefined?'%':''}</strong><small>{f.unit} · {k==='tonnes'||k==='perPerson'?(v&&dates(v)||entry.year||'Year not specified'):dates(v)||'Date in source notes'}</small><span className="oa-inspect-label"><BookOpen size={14}/>Inspect source</span></button>})}</div>
     <div className="oa-evidence-columns"><ObservationGroup title="What’s in the waste?" group="composition" record={record.data} fields={index.data.fields} onInspect={setSelectedField}/><ObservationGroup title="Where is it sent?" group="treatment" record={record.data} fields={index.data.fields} onInspect={setSelectedField}/></div>
     <p className="oa-record-note">Shares retain their published values. Missing categories stay missing; overlapping stages and different source years can prevent a complete balance. “Sent for recycling” measures collection for recycling, not the output recovered.</p>
     <details className="oa-method"><summary>Collection coverage and other waste streams</summary><div className="oa-evidence-columns"><ObservationGroup title="How much is collected?" group="collection" record={record.data} fields={index.data.fields} onInspect={setSelectedField}/><ObservationGroup title="Other reported quantities" group="other" record={record.data} fields={index.data.fields} onInspect={setSelectedField}/></div><p className="oa-small">These measures have different denominators and boundaries. Separate waste streams are not added to municipal waste.</p>{record.data.observations.distance&&<button className="oa-source-data-row" onClick={()=>setSelectedField('distance')}><span>City centre → main treatment/disposal facility</span><strong>{record.data.observations.distance.value} km</strong><BookOpen size={16}/></button>}</details>
     {entry.level==='country'&&record.data.observations.projection_2050&&<details className="oa-method"><summary>What could change by 2050?</summary><p>These are the World Bank’s modeled quantities, including its comparable 2022 baseline. Future values describe a projection; they are not observations or the result of a change you make in this app.</p><div className="oa-projection-row">{[2022,2030,2040,2050].map(y=>{const v=record.data!.observations['projection_'+y];return <button key={y} onClick={()=>setSelectedField('projection_'+y)} disabled={!v}><span>{y}</span><strong>{v?.value!==null&&v?.value!==undefined?compact(v.value):'Not reported'}</strong><small>tonnes · modeled</small></button>})}</div></details>}
     <div className="oa-data-source-line"><span>World Bank · What a Waste 3.0 · CC BY 4.0 · acquired September 2026</span><button className="oa-text-link" onClick={()=>{const r=record.data!;exportCSV(Object.entries(r.observations).map(([key,v])=>({place:r.name,country:r.country,level:r.level,measure:index.data!.fields[key].label,value:v.value,unit:v.unit,source_dates:dates(v),generation_year:r.year,original_value:v.rawValue,source_field:v.sourceField,references:v.references,source_url:index.data!.url})),'overshoot-waste-'+entry.id+'.csv')}}><Download size={15}/>Download this record</button></div>
     {ids.has(entry.country)&&<button className="oa-country-link" onClick={()=>onTrade(entry.country)}><div><h3>Does waste cross a border?</h3><p>Inspect {entry.countryName}’s available controlled-waste trade reports. These cover a different set of wastes and reporting years.</p></div><ArrowRight/></button>}
    </>}
   </section>:place!=='WORLD'?<Empty title="No World Bank record for this selection">Keep the selected place’s material accounts, or search another country or city in this dataset. <button className="oa-text-link" onClick={()=>setPicker(true)}>Browse available records<ArrowRight size={15}/></button></Empty>:<section className="oa-country-register"><div className="oa-section-heading"><div><span className="oa-kicker">OPEN A COUNTRY RECORD</span><h2>Look beneath the total.</h2></div><button className="oa-text-link" onClick={()=>setPicker(true)}>Search all places<Search size={16}/></button></div><div className="oa-register-heading"><span>{meta.label}</span><span>{meta.unit}</span></div>{ranked.slice(0,limit).map((r,i)=><button className="oa-source-data-row" key={r.id} onClick={()=>select(r)}><span className="oa-rank">{i+1}</span><span>{r.name}<small>{yearFor(r)} · {r.treatmentCount} treatment categories available</small></span><strong>{display(r[measure] as number,meta.unit)}</strong><ArrowUpRight size={17}/></button>)}{limit<ranked.length&&<button className="oa-button outline oa-more" onClick={()=>setLimit(l=>l+15)}>Show more countries</button>}</section>}
   <section className="oa-city-register"><div className="oa-depth-heading"><div><span className="oa-kicker">LOCAL RECORDS</span><h2>{entry?'Inside '+entry.countryName:'A closer view of cities.'}</h2><p>{entry?relatedCities.length+' city records available in this edition.':'City data can reveal details that national totals hide. Boundaries and reporting dates vary.'}</p></div><button className="oa-text-link" onClick={()=>{setType('city');setPicker(true)}}>Find any city<Search size={16}/></button></div><div className="oa-city-grid">{(entry?relatedCities.slice(0,8):['CAN-vcvr','GHA-acra','JPN-tkyo','COL-bogo'].map(id=>records.find(r=>r.id===id)!).filter(Boolean)).map(r=><button key={r.id} onClick={()=>select(r)} aria-pressed={entry?.id===r.id}><Building2 size={22}/><span>{r.countryName}</span><h3>{r.name}</h3><strong>{r.tonnes!==null?compact(r.tonnes)+' t':'Quantity not reported'}</strong><small>municipal waste · {r.year??'Year not specified'}</small><span className="oa-text-link">Open the record<ArrowUpRight size={16}/></span></button>)}</div>{entry&&!relatedCities.length&&<p className="oa-small">No city record is retained for this country. This does not imply an absence of local waste services.</p>}</section>
  </>}
  <CommandDialog open={picker} onOpenChange={setPicker} title="Find a waste record" description="Countries, economies and city records from the World Bank." className="oa-dialog"><CommandInput placeholder="Search a city, country or country code…"/><Tabs value={type} onValueChange={setType}><TabsList aria-label="Waste record type"><TabsTrigger value="all">All places</TabsTrigger><TabsTrigger value="country">Countries</TabsTrigger><TabsTrigger value="city">Cities</TabsTrigger></TabsList></Tabs><CommandList><CommandEmpty>No matching record in this edition.</CommandEmpty><CommandGroup heading="Available records">{records.filter(r=>type==='all'||r.level===type).map(r=><CommandItem key={r.id} value={[r.name,r.countryName,r.country,r.id].join(' ')} onSelect={()=>select(r)}>{r.level==='city'?<Building2 size={17}/>:<Globe2 size={17}/>}<span>{r.name}<small>{r.level==='city'?r.countryName+' · ':''}{r.level==='city'?'City record':'National record'} · {r.year??'Year not specified'}</small></span></CommandItem>)}</CommandGroup></CommandList></CommandDialog>
  <Sheet open={!!selectedField} onOpenChange={open=>{if(!open)setSelectedField(null)}}><SheetContent className="oa-sheet oa-evidence-sheet"><SheetTitle>{field?.label||'Source record'}</SheetTitle><SheetDescription>{record.data?.name} · World Bank What a Waste 3.0</SheetDescription>{o&&field&&record.data&&<><p className="oa-evidence-value">{o.value===null?(o.issue?'Value withheld':'No numeric value'):display(o.value,field.unit)}<span>{field.unit}</span></p><p>{field.description}</p>{o.issue&&<p className="oa-note">{o.issue}</p>}<dl className="oa-evidence-facts"><div><dt>Dataset edition</dt><dd>2026 · acquired 21 September 2026</dd></div><div><dt>Source date(s)</dt><dd>{dates(o)||'Not separately specified in the codebook'}</dd></div>{['tonnes','perPerson'].includes(selectedField!)&&<div><dt>Generation year in data table</dt><dd>{record.data.year??'Not specified in data table'}</dd></div>}{['tonnes','perPerson'].includes(selectedField!)&&record.data.point&&<div><dt>Measurement point in data table</dt><dd>{record.data.point}</dd></div>}<div><dt>Original cell</dt><dd>{String(o.rawValue)}{field.unit.startsWith('%')?' · fraction stored in workbook':''}</dd></div><div><dt>Location in workbook</dt><dd>{record.data.sheet} · row {record.data.row}</dd></div></dl>{['tonnes','perPerson'].includes(selectedField!)&&record.data.year!==null&&dates(o)&&dates(o)!==String(record.data.year)&&<p className="oa-note">The data table’s year and the codebook’s source date differ. Both are retained here; the app does not resolve that discrepancy.</p>}<h3>Underlying sources and methods</h3>{o.references.length?o.references.map((r,i)=><section className="oa-evidence-reference" key={i}><span className="oa-kicker">SOURCE {i+1}{r.date?' · '+r.date:''}</span><p>{r.source||'Source citation not specified'}</p>{r.page&&<p className="oa-small">Page / figure: {r.page}</p>}{r.method&&r.method!=='Not stated'&&<p><strong>Method: </strong>{r.method}</p>}{r.point&&r.point!=='Not stated'&&<p><strong>Measurement point: </strong>{r.point}</p>}{r.collectionNotes&&<p>{r.collectionNotes}</p>}{r.notes&&<p>{r.notes}</p>}{sourceLinks(r.url).map((url,n)=><a className="oa-text-link" key={url} href={url} target="_blank" rel="noreferrer">Open original source{sourceLinks(r.url).length>1?' '+(n+1):''}<ArrowUpRight size={15}/></a>)}<small>{r.sheet} · row {r.row}</small></section>):<p>No matching field-level citation is present in the supplied codebook. This value is retained from the dataset; open the workbook for its broader context.</p>}<a className="oa-button outline" href={index.data?.url} target="_blank" rel="noreferrer">Dataset and original workbooks<ArrowUpRight size={16}/></a><details className="oa-method"><summary>Machine-readable record</summary><pre>{JSON.stringify({place:record.data.name,field:selectedField,...o},null,2)}</pre></details></>}</SheetContent></Sheet>
 </div>
}
function ObservationGroup({title,group,record,fields,onInspect}:{title:string;group:string;record:WasteRecord;fields:Record<string,Field>;onInspect:(key:string)=>void}){
 const rows=Object.entries(record.observations).filter(([k])=>fields[k].group===group).sort(([,a],[,b])=>(b.value??-1)-(a.value??-1));
 return <section className="oa-observation-group"><h3>{title}</h3><p className="oa-small">{group==='composition'?'Share by weight · municipal waste':group==='treatment'?'Share of municipal waste · reported destinations':'Select a value to inspect its definition and source.'}</p>{rows.length?rows.map(([k,o])=><button key={k} onClick={()=>onInspect(k)} className="oa-observation-row"><span><strong>{fields[k].label}</strong><small>{dates(o)||'Date not separately specified'}</small></span><b>{o.value===null?'Check source':display(o.value,fields[k].unit)+(fields[k].unit.startsWith('%')?'%':' t')}</b><BookOpen size={15}/>{fields[k].unit.startsWith('%')&&o.value!==null&&<i className="oa-observation-track"><i style={{width:o.value+'%'}}/></i>}</button>):<p className="oa-empty-inline">No breakdown reported in this edition.</p>}</section>
}
