'use client';
import {useEffect,useState} from 'react';
import type {Feature,Point} from 'geojson';
const release3=new Set(['sources.json','treatment.json','weee-treatment.json','metrics-latest.json','metrics/XKX.json']);
export const artifactUrl=(name:string)=>`/data/${release3.has(name)?'v3':'v2'}/${name}`;
const cache=new Map<string,Promise<unknown>>();
export function fetchArtifact<T>(name:string):Promise<T>{let found=cache.get(name);if(!found){found=fetch(artifactUrl(name)).then(r=>{if(!r.ok)throw new Error('No acquired snapshot for this selection.');return r.json()});cache.set(name,found)}return found as Promise<T>}
export function useArtifact<T>(name:string|null){const[state,setState]=useState<{key:string|null;data:T|null;error:string}>({key:null,data:null,error:''});useEffect(()=>{if(!name)return;let active=true;fetchArtifact<T>(name).then(data=>{if(active)setState({key:name,data,error:''})}).catch(e=>{if(active)setState({key:name,data:null,error:e.message})});return()=>{active=false}},[name]);return state.key===name?state:{key:name,data:null,error:''}}
export interface ResourceRow{country:string;year:number;extraction:number|null;footprint:number|null;domesticConsumption:number|null;imports:number|null;exports:number|null;physicalTradeBalance:number|null;extractionPerCapita:number|null;footprintPerCapita:number|null;source_id:string;estimated:boolean}
export interface MetricRecord{country:string;metric:string;year:number;value:number;unit:string;source_id:string;estimated?:boolean;method?:string;original_value?:number;original_unit?:string;dimensions?:Record<string,string>;footnotes?:string[];source_detail?:string;status?:string;flag?:string}
export interface TradeFlow{origin:string;destination:string;commodity:string;year:number;tonnes:number;type:string;source_id:string;original_value?:number;original_unit?:string;hs_revision?:string;snapshot?:string;row_index?:number;record_ids?:string[]}
export interface TradeData{flows:TradeFlow[];years:number[];commodities?:{id:string;name:string;type:string}[];reporters?:string[];coverage_note?:string;source_id:string}
export type SiteFeature=Feature<Point,{id:string;type:string;name:string;country:string|null;source_id:string;year:number|null;value:number|null;unit:string;metric:string;estimated?:boolean;source_row?:number}>;
export interface SiteData{features:SiteFeature[];metadata?:Record<string,unknown>}
export const siteFiles:Record<string,string>={'river-plastic':'river-sites.geojson',landfill:'landfill-sites.geojson','mining-area':'mining-sites.geojson','wastewater-treatment':'wastewater-sites.geojson'};
export function latestMetric(records:MetricRecord[],country:string,metric:string,source?:string){return records.filter(r=>r.country===country&&r.metric===metric&&(!source||r.source_id===source)).sort((a,b)=>b.year-a.year)[0]}
export function metricLabel(key:string){const labels:Record<string,string>={in_use_stock:'Material in use',stock_additions:'Additions to material stock',stock_end_of_life:'Materials leaving stock',ewaste_generated:'E-waste generated',ewaste_recycled:'E-waste formally collected / recycled',ewaste_recycling_rate:'E-waste recycling rate',ewaste_per_capita:'E-waste per person',municipal_waste_generated:'Municipal waste generated',municipal_recycling_rate:'Municipal recycling rate',municipal_waste_recycled:'Municipal waste recycled',hazardous_waste_generated:'Hazardous waste generated',circular_material_use_rate:'Circular material use rate',food_waste:'Food waste',household_food_waste:'Household food waste',food_service_food_waste:'Food-service waste',retail_food_waste:'Retail food waste',food_loss_rate:'Food loss before retail',plastic_waste_generated:'Plastic waste generated',plastic_production:'Plastics production',plastic_secondary_production:'Secondary plastics production',plastic_waste_recycled:'Plastic waste recycled',plastic_waste_incinerated:'Plastic waste incinerated',plastic_waste_landfilled:'Plastic waste in sanitary landfill',plastic_waste_mismanaged:'Mismanaged plastic waste'};return labels[key]||key.replaceAll('_',' ').replace(/\b\w/g,c=>c.toUpperCase())}
