'use client';
import {useMemo} from 'react';
import {ArrowRight,MapPin,Route,ArrowUpRight} from 'lucide-react';
import {geoDistance,geoInterpolate} from 'd3-geo';
import {Select,SelectContent,SelectItem,SelectTrigger,SelectValue} from '@/components/ui/select';
import {useAtlas} from './state';
import {SourceButton} from './SourceButton';
import {useArtifact,type TradeData,type TradeFlow} from './data';
import {getWasteDestinations,treatmentLeaves,type TreatmentData} from '@/packages/overshoot-data/destinations';
import {formatMass} from '@/packages/overshoot-data/queries';
import type {Country} from '@/packages/overshoot-data/types';
const mass=(value:number)=>`${formatMass(value).number} ${formatMass(value).unit}`;
export default function Destinations({placement,onSource}:{placement:'narrative'|'visual';onSource:(id:string)=>void}){
 const s=useAtlas(),{data,error}=useArtifact<TradeData>('trade.json'),{data:countries}=useArtifact<Country[]>('countries.json');
 const routes=useMemo(()=>getWasteDestinations(data?.flows||[],s.country,s.commodity,s.year,s.destination),[data,s.country,s.commodity,s.year,s.destination]);
 const countryName=(id:string)=>countries?.find(c=>c.id===id)?.name||id;
 const items=data?.commodities?.filter(c=>c.type==='discard')||[];
 function selectRoute(flow:TradeFlow){const start=countries?.find(c=>c.id===flow.origin)?.center,end=countries?.find(c=>c.id===flow.destination)?.center,middle=start&&end?geoInterpolate(start,end)(.5):null;s.set({country:flow.origin,destination:flow.destination,...(middle?{longitude:middle[0],latitude:middle[1],zoom:start&&end&&geoDistance(start,end)>.9?.45:1.25}:{})})}
 if(placement==='narrative')return <div className="destination-settings"><label className="field-label">Follow a material<Select value={s.commodity} onValueChange={commodity=>s.set({commodity,destination:'WORLD'})}><SelectTrigger className="commodity-select" aria-label="Waste material"><SelectValue placeholder="Select scrap material"/></SelectTrigger><SelectContent>{items.map(item=><SelectItem key={item.id} value={item.id}>{item.name}</SelectItem>)}</SelectContent></Select></label><div className="destination-year"><span>Reported exports · {s.year}</span><SourceButton onClick={()=>onSource('comtrade')} label="UN Comtrade"/></div><p className="scene-caveat">Trace reported scrap shipments to the receiving country. A destination is known; its eventual treatment often isn’t.</p><div className="destination-presets" aria-label="Starting points">{[['USA','United States'],['DEU','Germany'],['JPN','Japan']].map(([country,label])=><button key={country} className="neu-button" onClick={()=>{const center=countries?.find(c=>c.id===country)?.center;s.set({country,destination:'WORLD',year:2024,...(center?{longitude:center[0],latitude:center[1],zoom:.7}:{})})}}>{label}<ArrowUpRight size={14}/></button>)}</div></div>;
 return <section className="destinations-panel"><div className="visual-label"><span>{s.country==='WORLD'?'LARGEST ACQUIRED ROUTES':`FROM ${countryName(s.country).toUpperCase()}`}</span><Route size={18}/></div>{s.destination!=='WORLD'&&<button className="source-link" onClick={()=>s.set({destination:'WORLD'})}>← Show all receiving countries</button>}{error?<p className="data-gap">Export snapshot unavailable.</p>:!data?<p className="data-gap">Loading reported destinations…</p>:routes.length?<div className="destination-list">{routes.slice(0,8).map(flow=><div key={`${flow.origin}-${flow.destination}`} className={`destination-row ${s.destination===flow.destination?'active':''}`}><button className="destination-place" onClick={()=>selectRoute(flow)}><span><small>{s.country==='WORLD'?countryName(flow.origin)+' →':'RECEIVING COUNTRY'}</small>{countryName(flow.destination)}</span><ArrowRight size={19}/></button><button className="destination-mass" onClick={()=>onSource(flow.source_id)} aria-label={`Source for ${mass(flow.tonnes)} exported to ${countryName(flow.destination)}`}>{mass(flow.tonnes)}<span>HS {flow.commodity} · {flow.year}</span></button><i style={{width:`${Math.sqrt(flow.tonnes/routes[0].tonnes)*100}%`}}/></div>)}</div>:<p className="data-gap">No acquired exports for this country, material and year. This does not mean no waste moves.</p>}
 <p className="chart-method">Exporter-reported net weight. Coverage is a selected set of reporters, not a complete world account. Width is a square-root scale within the current selection. Receiving scrap does not establish dumping, recycling or a particular facility.</p>
 {s.destination!=='WORLD'&&<button className="neu-button destination-next" onClick={()=>{const country=s.destination,center=countries?.find(c=>c.id===country)?.center;s.set({country,wasteStream:'treatment',destination:'WORLD',...center?{longitude:center[0],latitude:center[1],zoom:1.1}:{}})}}>Treatment records for {countryName(s.destination)}<ArrowRight size={18}/></button>}
 <button className="source-link" onClick={()=>s.set({wasteStream:'places',site:''})}><MapPin size={16}/>Explore independently mapped places</button></section>;
}
const COLORS:Record<string,string>={RCV_R:'#6ae5c1',RCV_R_B:'#6ae5c1',RCV_B:'#8be5a5',RCV_E:'#ffd16c',DSP_I:'#ffb599',DSP_L:'#91bfff',DSP_L_OTH:'#91bfff',DSP_OTH:'#ff927b'};
export function TreatmentView({onSource,weee=false}:{onSource:(id:string)=>void;weee?:boolean}){
 const s=useAtlas(),{data,error}=useArtifact<TreatmentData>(weee?'weee-treatment.json':'treatment.json');
 const records=data?.records.filter(r=>r.country===s.country&&r.scope===(weee?'EE6':s.wasteScope))||[];
 const years=records.map(r=>r.year).sort((a,b)=>b-a);
 const row=records.find(r=>r.year===(s.treatmentYear||years[0]));
 const source=data?.source_id||(weee?'eurostat-weee':'eurostat-waste-treatment');
 const locationRestricted=weee&&s.country==='DEU';
 const leaves=row&&!locationRestricted?(weee?['TRT_NAT','TRT_EU_FOR','TRT_NEU'].filter(code=>row.values[code]!==undefined).map(code=>({code,value:row.values[code],flag:row.flags[code],source_cell:row.source_cells[code]})):treatmentLeaves(row)):[];
 const labels:Record<string,string>=weee?{TRT_NAT:'Treated in the reporting country',TRT_EU_FOR:'Treated in another EU member state',TRT_NEU:'Treated outside the EU'}:{RCV_R:'Recycling',RCV_B:'Backfilling',RCV_E:'Energy recovery',DSP_I:'Incineration without energy recovery',DSP_L:'Landfill and other land disposal',DSP_OTH:'Other disposal',RCV_R_B:'Recycling and backfilling',DSP_L_OTH:'Land disposal and other disposal'};
 const max=Math.max(1,...leaves.map(r=>r.value));
 return <div className="scene-visual discard-visual treatment-visual"><div className="visual-label"><span>{weee?'E-WASTE · REPORTED TREATMENT LOCATION':'WHERE TREATMENT HAPPENS'}</span><SourceButton onClick={()=>onSource(source)} label="Eurostat"/></div>
 <div className="treatment-controls">{!weee&&<label className="field-label">Account boundary<Select value={s.wasteScope} onValueChange={wasteScope=>s.set({wasteScope})}><SelectTrigger aria-label="Treatment waste scope" className="commodity-select"><SelectValue/></SelectTrigger><SelectContent><SelectItem value="TOT_X_MIN">Excluding major mineral waste</SelectItem><SelectItem value="TOTAL">All waste</SelectItem></SelectContent></Select></label>}{years.length>0&&<label className="field-label">Reference year<Select value={String(s.treatmentYear||years[0])} onValueChange={v=>s.set({treatmentYear:Number(v)})}><SelectTrigger aria-label="Treatment reference year" className="commodity-select"><SelectValue/></SelectTrigger><SelectContent>{years.map(year=><SelectItem key={year} value={String(year)}>{year}</SelectItem>)}</SelectContent></Select></label>}</div>
 {error?<p className="data-gap">Treatment snapshot unavailable.</p>:!data?<p className="data-gap">Loading treatment records…</p>:!row?<div className="waste-empty"><h2>{s.country==='WORLD'?'Choose a reporting country.':'No acquired treatment record.'}</h2><p>{s.country==='WORLD'?'This account covers European reporting countries; it is not a global total.':'Select another year or country. Missing values are never replaced with a regional average.'}</p><div className="destination-presets">{(weee?[['IRL','Ireland'],['DEU','Germany'],['FRA','France']]:[['DEU','Germany'],['IRL','Ireland'],['FRA','France']]).map(([country,label])=><button key={country} className="neu-button" onClick={()=>s.set({country,treatmentYear:0})}>{label}</button>)}</div></div>:<><button className="treatment-total" onClick={()=>onSource(source)}><span>{row.name} · {row.year}</span><strong>{row.values.TRT===undefined?'Total not reported':mass(row.values.TRT)}</strong><small>{weee?'E-waste treated':'Waste treated inside this country'}{row.flags.TRT?` · source flag ${row.flags.TRT}`:''}</small></button>{weee&&data?.country_notes?.[s.country]&&<p className={locationRestricted?"treatment-warning":"treatment-note"}>{data.country_notes[s.country]}{locationRestricted?' Geographic split withheld to avoid implying all treatment was domestic.':''}</p>}<div className="waste-fates">{leaves.map(item=><button key={item.code} onClick={()=>onSource(source)} title={item.source_cell}><span>{labels[item.code]||item.code}<small>{item.code}{item.flag?` · flag ${item.flag}`:''}</small></span><strong>{mass(item.value)}</strong><i style={{width:`${item.value/max*100}%`,background:COLORS[item.code]||'#91bfff'}}/></button>)}</div></>}
 <p className="chart-method">{weee?'The destination is reported as three geographic groups, not named receiving countries or facilities. Treatment does not necessarily mean recycling.':'Treatment inside a country includes imported waste and excludes exported waste. These are all-economy treatment accounts, separate from municipal waste. They do not identify the fate of any selected shipment.'} Native categories and rounding are preserved.</p><SourceButton onClick={()=>onSource(source)} label="Read coverage, flags & source cells"/></div>;
}
