'use client';
import {useMemo} from 'react';
import {ArrowRight,ArrowUpRight} from 'lucide-react';
import {Tabs,TabsList,TabsTrigger} from '@/components/ui/tabs';
import {Select,SelectContent,SelectItem,SelectTrigger,SelectValue} from '@/components/ui/select';
import {SourceButton} from './SourceButton';
import {useAtlas} from './state';
import {useArtifact,type TradeData,type ResourceRow} from './data';
import {formatMass} from '@/packages/overshoot-data/queries';
import type {Country} from '@/packages/overshoot-data/types';
export function FootprintComparison({onSource}:{onSource:(id:string)=>void}){
 const s=useAtlas(),{data}=useArtifact<{rows:ResourceRow[]}>(`resources/${s.year}.json`);
 const row=data?.rows.find(r=>r.country===s.country);
 const fields=[['Domestic extraction',row?.extraction,'#ffd16c'],['Material footprint',row?.footprint,'#91bfff']] as const;
 const max=Math.max(...fields.map(([,v])=>v??0),1);
 return <section className="footprint-comparison" aria-label="Extraction and material footprint"><div className="visual-label"><span>EXTRACTION / DEMAND · {s.year}</span><SourceButton onClick={()=>onSource('irp-resource-accounts-2026')} label="UN IRP"/></div>{fields.map(([label,v,color])=><button key={label} onClick={()=>onSource('irp-resource-accounts-2026')} className="account-bar"><span>{label}</span><strong>{v===null||v===undefined?'Unavailable':`${formatMass(v).number} ${formatMass(v).unit}`}</strong><i style={{width:`${Math.max(0,v??0)/max*100}%`,background:color}}/></button>)}<p className="chart-method">Footprint assigns upstream extraction to final demand. It includes materials used abroad; it is not the weight of imported products.{row?.estimated?' These are source estimates.':''}</p>{row?.imports!==null&&row?.imports!==undefined&&row?.exports!==null&&row?.exports!==undefined&&<div className="trade-account-pair"><button onClick={()=>onSource(row.source_id)}><span>Physical imports</span><strong>{formatMass(row.imports).number} {formatMass(row.imports).unit}</strong></button><button onClick={()=>onSource(row.source_id)}><span>Physical exports</span><strong>{formatMass(row.exports).number} {formatMass(row.exports).unit}</strong></button></div>}</section>
}
export default function FlowDetail({placement,onSource}:{placement:'narrative'|'visual';onSource:(id:string)=>void}){
 const s=useAtlas(),{data}=useArtifact<TradeData>(s.flow==='controlled'?null:'trade.json'),{data:countries}=useArtifact<Country[]>('countries.json');
 const {data:quality}=useArtifact<{notes:{origin:string;destination:string;commodity:string;year:number;message:string;exporter_reported_tonnes:number;importer_reported_tonnes:number;source_id:string}[]}>('trade-quality.json');
 const commodities=data?.commodities?.filter(c=>c.type===s.flow)||[];
 const selected=commodities.find(c=>c.id===s.commodity);
 const countryName=(id:string)=>countries?.find(c=>c.id===id)?.name||id;
 const flows=useMemo(()=>data?.flows.filter(f=>f.year===s.year&&(s.flow==='controlled'||f.commodity===s.commodity&&f.type===s.flow)&&(s.country==='WORLD'||f.origin===s.country)&&(s.destination==='WORLD'||f.destination===s.destination)).sort((a,b)=>b.tonnes-a.tonnes)||[],[data,s.year,s.commodity,s.flow,s.country,s.destination]);
 const note=quality?.notes.find(n=>n.year===s.year&&n.commodity===s.commodity&&(s.country==='WORLD'||n.origin===s.country)&&(s.destination==='WORLD'||n.destination===s.destination));
 if(s.flow==='controlled')return placement==='narrative'?<div className="flow-settings"><Tabs value={s.flow} onValueChange={v=>s.set({flow:v as 'raw'|'discard'|'controlled',commodity:v==='raw'?'2603':'3915'})}><TabsList className="neu-segment flow-tabs"><TabsTrigger value="raw">Raw / products</TabsTrigger><TabsTrigger value="discard">Scrap</TabsTrigger><TabsTrigger value="controlled">Basel</TabsTrigger></TabsList></Tabs><p className="data-gap">Basel’s reporting adapter is prepared. Quantitative republication is pending reuse permission under the publisher’s terms.</p><SourceButton onClick={()=>onSource('basel-national-reporting')} label="Basel coverage & access"/></div>:<div className="scene-visual flow-visual"><FootprintComparison onSource={onSource}/></div>;
 if(placement==='narrative')return <div className="flow-settings">
  <Tabs value={s.flow} onValueChange={v=>s.set({flow:v as 'raw'|'discard'|'controlled',commodity:v==='raw'?'2603':'3915',site:''})}><TabsList className="neu-segment flow-tabs"><TabsTrigger value="raw">Raw / products</TabsTrigger><TabsTrigger value="discard">Scrap</TabsTrigger><TabsTrigger value="controlled">Basel</TabsTrigger></TabsList></Tabs>
  {<label className="field-label">Commodity<Select value={selected?s.commodity:''} onValueChange={commodity=>s.set({commodity})}><SelectTrigger aria-label="Trade commodity" className="commodity-select"><SelectValue placeholder="Choose a commodity"/></SelectTrigger><SelectContent>{commodities.map(c=><SelectItem key={c.id} value={c.id}>{c.id} · {c.name}</SelectItem>)}</SelectContent></Select></label>}
  <div className="flow-selects"><label className="field-label">Year<Select value={String(s.year)} onValueChange={v=>s.set({year:Number(v)})}><SelectTrigger aria-label="Trade year" className="commodity-select"><SelectValue/></SelectTrigger><SelectContent>{[...new Set([s.year,...(data?.years||[])])].sort((a,b)=>b-a).map(y=><SelectItem key={y} value={String(y)}>{y}{!data?.years.includes(y)?' · no snapshot':''}</SelectItem>)}</SelectContent></Select></label><label className="field-label">Destination<Select value={s.destination} onValueChange={destination=>s.set({destination})}><SelectTrigger aria-label="Trade destination" className="commodity-select"><SelectValue/></SelectTrigger><SelectContent><SelectItem value="WORLD">All destinations</SelectItem>{countries?.filter(c=>c.id!=='WORLD').map(c=><SelectItem key={c.id} value={c.id}>{c.name}</SelectItem>)}</SelectContent></Select></label></div>
  <SourceButton onClick={()=>onSource('comtrade')} label="UN Comtrade · reported export weight"/>
  <p className="scene-caveat">{s.commodity==='2603'?'The weight of copper ores and concentrates—not contained copper. Exporter and importer reports can disagree.':s.commodity==='6309'?'Worn clothing includes reusable articles. This code does not identify waste status.':'Only non-estimated reported net weights. Empty routes mean no qualifying record, not zero trade.'}</p>
  {!data?.years.includes(s.year)&&data&&<button className="neu-button" onClick={()=>s.set({year:Math.max(...data.years)})}>Open {Math.max(...data.years)} snapshot <ArrowUpRight size={16}/></button>}
 </div>;
 return <div className="scene-visual flow-visual"><section className="route-summary"><div className="visual-label"><span>{s.country==='WORLD'?'LARGEST ACQUIRED ROUTES':'REPORTED EXPORT ROUTES'}</span><span>{s.year}</span></div>{flows.length?flows.slice(0,4).map((f,i)=><button className="route-row" key={`${f.origin}:${f.destination}:${i}`} onClick={()=>{const c=countries?.find(c=>c.id===f.origin);s.set({country:f.origin,destination:f.destination,...(c?.center?{longitude:c.center[0],latitude:c.center[1],zoom:.8}:{})});onSource(f.source_id)}}><span>{countryName(f.origin)} <ArrowRight size={13}/> {countryName(f.destination)}</span><strong>{formatMass(f.tonnes).number} {formatMass(f.tonnes).unit}</strong></button>):<p className="data-gap">No qualifying routes in this snapshot for your selection.</p>}<p className="chart-method">Selected reporters and commodities; this is not a complete global trade matrix. Links connect country centres, not shipping routes. Width encodes the square root of tonnes; the map shows up to 60 largest qualifying links.</p>{s.destination!=='WORLD'&&<button className="source-link" onClick={()=>s.set({destination:'WORLD'})}>Show all destinations <ArrowUpRight size={14}/></button>}{note&&<button className="quality-note" onClick={()=>onSource('comtrade')}>Reporting discrepancy: this snapshot includes a Chile–China copper-ore route where the two countries report different weights. Exporter: {formatMass(note.exporter_reported_tonnes).number} {formatMass(note.exporter_reported_tonnes).unit}; importer: {formatMass(note.importer_reported_tonnes).number} {formatMass(note.importer_reported_tonnes).unit}. Values remain separate.</button>}</section><FootprintComparison onSource={onSource}/></div>;
}
