'use client';
import {lazy,Suspense,useCallback,useEffect,useMemo,useRef,useState} from 'react';
import {geoOrthographic,geoPath,geoContains,geoDistance,geoInterpolate} from 'd3-geo';
import type {FeatureCollection,Feature,Geometry} from 'geojson';
import {useAtlas} from './state';
import {type ExtractionData,MATERIALS} from '@/packages/overshoot-data/types';
import {getExtraction,formatMass} from '@/packages/overshoot-data/queries';
import {fetchArtifact,useArtifact,siteFiles,type TradeData,type TradeFlow,type SiteData,type SiteFeature} from './data';
import FlowMotion from './FlowMotion';
import GlobeBoundary from './GlobeBoundary';
import {safeCamera,interpolateCamera,cameraEquals,wrapLongitude,type Camera} from './camera';
const WebGLGlobe=lazy(()=>import('./WebGLGlobe'));
type GeoFeature=Feature<Geometry,{name:string;numeric:string;center:[number,number]}>;
export type MappedFlow=TradeFlow&{start:[number,number];end:[number,number];width:number};
export default function Globe({data,onCountry}:{data:ExtractionData|null;onCountry:(id:string,center?:[number,number])=>void}){
 const s=useAtlas(),[geo,setGeo]=useState<FeatureCollection<Geometry,GeoFeature['properties']>|null>(null),[grid,setGrid]=useState<Feature|null>(null),[ready,setReady]=useState(false),[motionPaused,setMotionPaused]=useState(false),[mapError,setMapError]=useState(''),[failed,setFailed]=useState(false),[webgl,setWebgl]=useState(false),[hover,setHover]=useState<{x:number;y:number;name:string;value:string}|null>(null);
 const [view,setView]=useState({longitude:s.longitude,latitude:s.latitude,zoom:s.zoom,minZoom:-.5,maxZoom:4});
 const wrapper=useRef<HTMLDivElement>(null),[size,setSize]=useState({width:900,height:750}),drag=useRef<{x:number;y:number;lng:number;lat:number;distance?:number;zoom?:number}|null>(null),pointers=useRef(new Map<number,{x:number;y:number}>()),flight=useRef(0),reduced=useRef(false);
 const routeScene=s.scene==='flow'||s.scene==='discard'&&s.wasteStream==='destinations';
 const routeType=s.scene==='discard'?'discard':s.flow;
 const {data:trade}=useArtifact<TradeData>(routeScene&&routeType!=='controlled'?'trade.json':null);
 const {data:sites}=useArtifact<SiteData>(s.scene==='discard'&&s.wasteStream==='places'?siteFiles[s.siteType]:null);
 useEffect(()=>{
  try{const probe=document.createElement('canvas');const gl=probe.getContext('webgl2');setWebgl(!!gl);if(!gl)setFailed(true);gl?.getExtension('WEBGL_lose_context')?.loseContext()}catch{setFailed(true)}
  const motion=matchMedia('(prefers-reduced-motion: reduce)');const updateMotion=()=>{reduced.current=motion.matches;setMotionPaused(motion.matches)};updateMotion();motion.addEventListener('change',updateMotion);
  Promise.all([fetchArtifact<FeatureCollection<Geometry,GeoFeature['properties']>>('geography.json'),fetchArtifact<Feature>('graticule.json')]).then(([g,l])=>{setGeo(g);setGrid(l)}).catch(()=>{setFailed(true);setMapError('The geographic snapshot could not load. Country controls and source records remain available.')});
  const observer=new ResizeObserver(([entry])=>{const width=Math.round(entry.contentRect.width),height=Math.round(entry.contentRect.height);if(width&&height)setSize(previous=>previous.width===width&&previous.height===height?previous:{width,height})});if(wrapper.current)observer.observe(wrapper.current);return()=>{observer.disconnect();motion.removeEventListener('change',updateMotion);cancelAnimationFrame(flight.current)};
 },[]);
 const viewRef=useRef(view);viewRef.current=view;
 const updateView=useCallback((camera:Camera)=>{const next={...safeCamera(camera),minZoom:-.5,maxZoom:4};viewRef.current=next;setView(next)},[]);
 const stopFlight=useCallback(()=>{cancelAnimationFrame(flight.current);flight.current=0;setHover(null)},[]);
 const commitCamera=useCallback(()=>{const camera=safeCamera(viewRef.current);useAtlas.getState().set(camera)},[]);
 useEffect(()=>{stopFlight();const start=viewRef.current,target=safeCamera({longitude:s.longitude,latitude:s.latitude,zoom:s.zoom});if(cameraEquals(start,target))return;if(reduced.current){updateView(target);return;}const then=performance.now();
  function tick(now:number){const p=Math.min(1,(now-then)/1000),e=p*p*(3-2*p);updateView(interpolateCamera(start,target,e));if(p<1)flight.current=requestAnimationFrame(tick)}
  flight.current=requestAnimationFrame(tick);return stopFlight;
 },[s.longitude,s.latitude,s.zoom,stopFlight,updateView]);
 useEffect(()=>{if(geo&&!webgl)requestAnimationFrame(()=>performance.mark('overshoot-svg-globe-ready'))},[geo,webgl]);
 const countryByNumeric=useMemo(()=>new Map(data?.countries.filter(c=>c.numeric).map(c=>[c.numeric,c])||[]),[data]);
 const values=useMemo(()=>new Map(data?.countries.map(c=>{const r=getExtraction(data,c.id,s.material,s.year,s.metric);return[c.id,r.status==='available'?r.data.value:null]})||[]),[data,s.year,s.material,s.metric]);
 const max=Math.max(1,...Array.from(values.entries()).filter(([id,v])=>id!=='WORLD'&&v!==null).map(([,v])=>v as number));
 const rgb=s.material==='all'?[255,209,108]:MATERIALS.find(m=>m.id===s.material)!.color.match(/\w\w/g)!.map(c=>parseInt(c,16));
 const country=(f:GeoFeature)=>countryByNumeric.get(f.properties.numeric);
 const color=(f:GeoFeature):[number,number,number,number]=>{const c=country(f),v=c?values.get(c.id):null;if(v===null||v===undefined||s.scene!=='extraction')return [44,62,81,255];const t=.2+.8*Math.pow(v/max,.35);return [Math.round(25+(rgb[0]-25)*t),Math.round(30+(rgb[1]-30)*t),Math.round(29+(rgb[2]-29)*t),255]};
 const mappedFlows=useMemo(()=>{const centers=new Map(data?.countries.filter(c=>c.center).map(c=>[c.id,c.center!])||[]);const rows=trade?.flows.filter(f=>f.year===s.year&&(f.commodity===s.commodity&&f.type===routeType)&&(s.country==='WORLD'||f.origin===s.country)&&(s.destination==='WORLD'||f.destination===s.destination)&&centers.has(f.origin)&&centers.has(f.destination)).sort((a,b)=>b.tonnes-a.tonnes).slice(0,60)||[];const largest=Math.max(1,...rows.map(f=>f.tonnes));return rows.map(f=>({...f,start:centers.get(f.origin)!,end:centers.get(f.destination)!,width:.6+6*Math.sqrt(f.tonnes/largest)}))},[trade,data,s.year,routeType,s.commodity,s.country,s.destination]);
 const mappedSites=useMemo(()=>sites?.features.filter(f=>s.country==='WORLD'||f.properties.country===s.country).sort((a,b)=>(b.properties.value||0)-(a.properties.value||0))||[],[sites,s.country]);
 const siteMax=Math.max(1,...mappedSites.map(f=>f.properties.value||0));
 function selectSite(f:SiteFeature){const [longitude,latitude]=f.geometry.coordinates;s.set({site:f.properties.id,longitude,latitude,zoom:2.1})}
 function selectFlow(f:MappedFlow){const middle=geoInterpolate(f.start,f.end)(.5);s.set({country:f.origin,destination:f.destination,longitude:middle[0],latitude:middle[1],zoom:geoDistance(f.start,f.end)>.9?.45:1.25})}
 const projection=useMemo(()=>geoOrthographic().rotate([-view.longitude,-view.latitude]).translate([size.width/2,size.height/2]).scale(Math.min(size.width,size.height)*.45*Math.pow(2,view.zoom-.55)).clipAngle(90),[size,view]);
 const path=geoPath(projection);
 return <div ref={wrapper} className={`globe-stage ${s.scene==='stock'||s.scene==='return'||s.scene==='discard'&&!['places','destinations'].includes(s.wasteStream)?'globe-muted':''}`} tabIndex={0} aria-label="Interactive globe. Drag horizontally to rotate; use the zoom controls or arrow keys. Country and site menus provide the same selections." onKeyDown={e=>{if(['ArrowLeft','ArrowRight','ArrowUp','ArrowDown'].includes(e.key)){e.preventDefault();s.set({longitude:wrapLongitude(viewRef.current.longitude+(e.key==='ArrowLeft'?-12:e.key==='ArrowRight'?12:0)),latitude:Math.max(-80,Math.min(80,viewRef.current.latitude+(e.key==='ArrowUp'?8:e.key==='ArrowDown'?-8:0)))})}}}>
 {!ready&&<svg className="globe-fallback" width={size.width} height={size.height} viewBox={`0 0 ${size.width} ${size.height}`} aria-hidden="true" onPointerDown={e=>{stopFlight();pointers.current.set(e.pointerId,{x:e.clientX,y:e.clientY});const points=[...pointers.current.values()];drag.current={x:e.clientX,y:e.clientY,lng:viewRef.current.longitude,lat:viewRef.current.latitude,...(points.length===2?{distance:Math.hypot(points[0].x-points[1].x,points[0].y-points[1].y),zoom:viewRef.current.zoom}:{})};e.currentTarget.setPointerCapture(e.pointerId)}}
  onPointerMove={e=>{if(!pointers.current.has(e.pointerId)||!drag.current)return;pointers.current.set(e.pointerId,{x:e.clientX,y:e.clientY});const d=drag.current,points=[...pointers.current.values()];if(points.length===2&&d.distance){const distance=Math.hypot(points[0].x-points[1].x,points[0].y-points[1].y);updateView({...viewRef.current,zoom:(d.zoom??viewRef.current.zoom)+Math.log2(Math.max(1,distance)/Math.max(1,d.distance))})}else if(points.length===1&&!d.distance){const sensitivity=80/Math.max(200,Math.min(size.width,size.height));updateView({...viewRef.current,longitude:d.lng-(e.clientX-d.x)*sensitivity,latitude:d.lat+(e.clientY-d.y)*sensitivity})}}}
  onPointerCancel={()=>{drag.current=null;pointers.current.clear();commitCamera()}}
  onPointerUp={e=>{const d=drag.current;pointers.current.delete(e.pointerId);if(!d)return;if(pointers.current.size===0){drag.current=null;if(!d.distance&&Math.hypot(e.clientX-d.x,e.clientY-d.y)<5){const rect=e.currentTarget.getBoundingClientRect(),pixel:[number,number]=[e.clientX-rect.left,e.clientY-rect.top],radius=projection.scale();if(Math.hypot(pixel[0]-size.width/2,pixel[1]-size.height/2)<=radius){const point=projection.invert?.(pixel);const f=point&&geo?.features.find(f=>geoContains(f,point));const c=f&&country(f);if(c&&f)onCountry(c.id,f.properties.center)}}else commitCamera()}}}>
  <defs><radialGradient id="ocean"><stop offset="0" stopColor="#223d56"/><stop offset=".85" stopColor="#162d43"/><stop offset="1" stopColor="#0c1727"/></radialGradient></defs><path d={path({type:'Sphere'})||''} fill="url(#ocean)" stroke="#aec8e359" strokeWidth="1"/>
  {grid&&<path d={path(grid)||''} fill="none" stroke="#87adce30" strokeWidth=".65"/>}
  {geo?.features.map((f,i)=><path key={i} d={path(f)||''} fill={`rgb(${color(f).slice(0,3).join(',')})`} stroke={country(f)?.id===s.country?'#ffe5a6':'#abc9e655'} strokeWidth={country(f)?.id===s.country?1.5:.55}/>)}
  {routeScene&&mappedFlows.map((f,i)=>{const interpolate=geoInterpolate(f.start,f.end),coordinates=Array.from({length:45},(_,n)=>interpolate(n/44));return <path key={i} d={path({type:'LineString',coordinates})||''} fill="none" stroke={routeType==='raw'?'#ffd16c':'#6ae5c1'} strokeOpacity=".74" strokeWidth={f.width} onPointerDown={e=>e.stopPropagation()} onClick={e=>{e.stopPropagation();selectFlow(f)}}><title>{f.origin} → {f.destination}: {formatMass(f.tonnes).number} {formatMass(f.tonnes).unit}, {f.year}. Reported export weight.</title></path>})}
  {routeScene&&<FlowMotion flows={mappedFlows} projection={projection} view={view} paused={motionPaused}/>}
  {routeScene&&s.destination!=='WORLD'&&mappedFlows.slice(0,1).flatMap(f=>[{id:f.origin,point:f.start,label:data?.countries.find(c=>c.id===f.origin)?.name||f.origin},{id:f.destination,point:f.end,label:data?.countries.find(c=>c.id===f.destination)?.name||f.destination}]).map(endpoint=>{const xy=projection(endpoint.point);if(!xy||geoDistance(endpoint.point,[view.longitude,view.latitude])>Math.PI/2)return null;return <g key={endpoint.id} pointerEvents="none"><circle cx={xy[0]} cy={xy[1]} r="6" fill="#f2f8ff" stroke="#6ae5c1" strokeWidth="3"/><text className="map-place-label" x={xy[0]+12} y={xy[1]-12}>{endpoint.label}</text></g>})}
  {mappedSites.filter((f,i)=>i<500||f.properties.id===s.site).map(f=>{if(geoDistance(f.geometry.coordinates as [number,number],[view.longitude,view.latitude])>Math.PI/2)return null;const xy=projection(f.geometry.coordinates as [number,number]);if(!xy)return null;return <circle key={f.properties.id} cx={xy[0]} cy={xy[1]} r={2+7*Math.sqrt((f.properties.value||0)/siteMax)} fill={s.siteType==='river-plastic'?'#91bfff':s.siteType==='landfill'?'#ff927b':s.siteType==='mining-area'?'#ffd16c':'#6ae5c1'} opacity=".85" stroke={f.properties.id===s.site?'#fff':'#11243b'} strokeWidth={f.properties.id===s.site?2:1} onPointerDown={e=>e.stopPropagation()} onClick={e=>{e.stopPropagation();selectSite(f)}}><title>{f.properties.name} · {f.properties.metric}</title></circle>})}
 </svg>}
 {webgl&&!failed&&geo&&<GlobeBoundary onFailure={()=>{setFailed(true);setReady(false)}}><Suspense fallback={null}><WebGLGlobe width={size.width} height={size.height} geo={geo} grid={grid} view={view} color={color} countryId={f=>country(f)?.id} selected={s.country} layerKey={`${s.year}:${s.material}:${s.metric}:${s.scene}:${max}`} flows={mappedFlows} sites={mappedSites} siteType={s.siteType} selectedSite={s.site} onSite={selectSite} onFlow={selectFlow} motionPaused={motionPaused} onInteraction={stopFlight} onCamera={(v,commit)=>{stopFlight();updateView(v);if(commit)commitCamera()}} onCountry={onCountry} onHover={(f,x,y)=>{if(!f){setHover(null);return;}const c=country(f),v=c?values.get(c.id):null;setHover({x,y,name:c?.name||f.properties.name,value:s.scene==='extraction'?(v===null||v===undefined?'No data for this selection':`${formatMass(v,s.metric).number} ${formatMass(v,s.metric).unit}`):'Select country'})}} onReady={()=>{setReady(true);performance.mark('overshoot-globe-ready')}} onFailure={()=>{setFailed(true);setReady(false)}}/></Suspense></GlobeBoundary>}
 {hover&&<div className="globe-tooltip" style={{left:Math.min(hover.x+12,size.width-230),top:Math.min(hover.y+12,size.height-70)}}><strong>{hover.name}</strong><span>{hover.value}</span></div>}
 {routeScene&&mappedFlows.length>0&&<div className="flow-map-key"><span><i/>Width = reported mass</span><button className="source-link" onClick={()=>setMotionPaused(!motionPaused)} aria-pressed={!motionPaused}>{motionPaused?'Play direction':'Pause direction'}</button><small>Country-to-country links · not shipping tracks</small></div>}
 {mapError&&<p className="map-error" role="status">{mapError}</p>}
 {failed&&<span className="render-note">Interactive geographic fallback{mappedSites.length>500?' · 500 largest markers':''}</span>}
 </div>;
}
