'use client';
import {useEffect,useMemo,useState} from 'react';
import Link from 'next/link';
import {ArrowDownLeft,ArrowUpRight,Download,MapPin,Search,BookOpen,Globe2} from 'lucide-react';
import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';
import {Checkbox} from '@/components/ui/checkbox';
import {Select,SelectContent,SelectItem,SelectTrigger,SelectValue} from '@/components/ui/select';
import {Dialog,DialogContent,DialogDescription,DialogTitle} from '@/components/ui/dialog';
import {Tabs,TabsList,TabsTrigger} from '@/components/ui/tabs';
import MaterialMap,{type QuantityFlow,type MapCountry} from './MaterialMap';
import {useMaterialArtifact} from './material-data';
import {bcQuantity,families,initialMaterialState,materialQuery,productMatches,readMaterialState,selectBC,selectCopper,type BCObservation,type CopperObservation,type MaterialState,type Product} from './material-model';
import './materials.css';
type BCCatalog={source:Record<string,string>;products:Product[];recordCount:number;year:number};
type CopperCatalog={reporters:string[];countries:{iso:string;name:string}[];commodities:{id:string;name:string}[];coverage:Record<string,unknown>[];coverage_note:string};
type TradeSnapshot={flows:CopperObservation[];estimated_flows:CopperObservation[]};
const shortForms:Record<string,string>={'2603':'Ore & concentrate','7401':'Matte & cement','7402':'Unrefined copper','7403':'Refined & alloys','7404':'Waste & scrap','7408':'Wire'};
function Choice({label,value,onChange,options}:{label:string;value:string;onChange:(v:string)=>void;options:{id:string;name:string}[]}){return <label className="material-field"><span>{label}</span><Select value={value} onValueChange={onChange}><SelectTrigger aria-label={label}><SelectValue/></SelectTrigger><SelectContent>{options.map(o=><SelectItem key={o.id} value={o.id}>{o.name}</SelectItem>)}</SelectContent></Select></label>}
function download(rows:QuantityFlow[]){const columns=['origin','destination','originLabel','destinationLabel','quantity','unit','estimated','record'];const csv=[columns.join(','),...rows.map(row=>columns.map(c=>'"'+String(c==='record'?JSON.stringify(row.record):row[c as keyof QuantityFlow]).replaceAll('"','""')+'"').join(','))].join('\n');const url=URL.createObjectURL(new Blob([csv],{type:'text/csv'}));const a=document.createElement('a');a.href=url;a.download='overshoot-material-flows-2024.csv';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}
export default function MaterialExplorer({regional=false}:{regional?:boolean}){
 const [state,setState]=useState<MaterialState>(initialMaterialState),[ready,setReady]=useState(false),[evidence,setEvidence]=useState<Record<string,unknown>|null>(null),[regionView,setRegionView]=useState('exports');
 useEffect(()=>{const read=()=>{setState(readMaterialState(location.search));setRegionView(new URLSearchParams(location.search).get('view')==='collection'?'collection':'exports')};read();setReady(true);addEventListener('popstate',read);return()=>removeEventListener('popstate',read)},[]);
 useEffect(()=>{if(ready)history.replaceState(null,'',`${location.pathname}?${materialQuery(state)}${regionView==='collection'?'&view=collection':''}`)},[state,regionView,ready]);
 const change=(patch:Partial<MaterialState>)=>setState(s=>({...s,...patch,destination:patch.destination??''}));
 const bc=useMaterialArtifact<BCCatalog>(regional?'/data/v6/bc/catalog.json.gz':null),copper=useMaterialArtifact<CopperCatalog>(!regional?'/data/v6/copper/catalog.json':null),countryMap=useMaterialArtifact<Record<string,string>>(regional?'/data/v6/country-codes.json':null),countries=useMaterialArtifact<MapCountry[]>('/data/v2/countries.json');
 const rows=useMaterialArtifact<BCObservation[]>(regional?`/data/v6/bc/${state.product.slice(0,2)}.json.gz`:null);
 const trade=useMaterialArtifact<TradeSnapshot>(!regional&&copper.data?.reporters.includes(state.country)?`/data/v6/copper/${state.country}.json.gz`:null);
 const collection=useMaterialArtifact<{source:{url:string};collectionFacility:{name:string;address:string};observations:{material:string;relationship:string;basis:string}[];limitations:string[]}>(regional&&regionView==='collection'?'/data/v6/bc/collection.json':null);
 const product=bc.data?.products.find(p=>p.hs6===state.product&&p.unit===state.unit);
 const matches=useMemo(()=>bc.data?.products.filter(p=>productMatches(p,state))||[],[bc.data,state]);
 const options=matches.slice(0,80);if(product&&!options.includes(product))options.unshift(product);
 const names=useMemo(()=>new Map(countries.data?.map(c=>[c.id,c.name])),[countries.data]);
 const flows:QuantityFlow[]=useMemo(()=>regional?selectBC(rows.data||[],state).map(r=>({id:r.id,origin:'BC',destination:countryMap.data?.[r.destination]||r.destination,originLabel:'British Columbia',destinationLabel:r.destinationLabel,quantity:bcQuantity(r,r.quantity).value,unit:bcQuantity(r,r.quantity).unit,estimated:false,record:{...r,source:bc.data?.source}})):selectCopper([...(trade.data?.flows||[]),...(state.estimates?trade.data?.estimated_flows||[]:[])],state).map(r=>({id:r.id,origin:r.origin,destination:r.destination,originLabel:names.get(r.origin)||r.origin,destinationLabel:names.get(r.destination)||r.destination,quantity:r.tonnes,unit:'tonnes · source net weight',estimated:r.is_net_weight_estimated,record:r})),[regional,rows.data,state,countryMap.data,bc.data,trade.data,names]);
 const selected=flows.find(f=>f.id===state.destination),loaded=regional?!!rows.data:!!trade.data,err=bc.error||copper.error||rows.error||trade.error;
 const title=regional?'What leaves your region?':'Follow the copper.';
 const heading=regional?product?.commodity||'Copper ores and concentrates':copper.data?.commodities.find(c=>c.id===state.commodity)?.name||'Copper ores and concentrates';
 const nestedSource=evidence?.source as Record<string,unknown>|undefined;
 const evidenceUrl=String(evidence?.source_url||evidence?.url||nestedSource?.url||'');
 const missingReporter=!regional&&copper.data&&!copper.data.reporters.includes(state.country);
 return <main className="material-explorer"><header className="material-top"><Link className="material-brand" href="/">OVERSHOOT <span>Gaia AI</span></Link><nav aria-label="Primary"><Link href="/materials" aria-current={!regional?'page':undefined}><Globe2 size={18}/> Materials</Link><Link href="/region" aria-current={regional?'page':undefined}><MapPin size={18}/> My region</Link><Link href="/journey">Follow waste</Link><Link href="/extraction?mode=explore">Atlas</Link></nav></header>
 <div className="material-intro"><p className="material-eyebrow">{regional?'A place in the material world':'Material explorer / Copper'}</p><h1>{title}</h1><p>{regional?'Explore products made or extracted in British Columbia, and the foreign destinations declared for them.':'Choose a form of copper and a reporting country. Follow the material arriving at, or leaving, its borders.'}</p>{flows[0]&&regionView==='exports'?<button className="material-leading" onClick={()=>setEvidence(flows[0].record)}><span>Largest retained {regional||state.direction==='X'?'destination':'origin'} · inspect source</span><strong>{regional||state.direction==='X'?flows[0].destinationLabel:flows[0].originLabel}</strong><span>{new Intl.NumberFormat('en',{maximumFractionDigits:3}).format(flows[0].quantity)} {flows[0].unit}{flows[0].estimated?' · estimated':''}</span></button>:null}</div>
 {regional?<Tabs value={regionView} onValueChange={setRegionView} className="material-region-tabs"><TabsList><TabsTrigger value="exports">BC exports</TabsTrigger><TabsTrigger value="collection">Salt Spring collection</TabsTrigger></TabsList></Tabs>:null}
 {regional&&regionView==='collection'?<section className="material-local"><p className="material-eyebrow">Home region / Salt Spring Island</p><h2>{collection.data?.collectionFacility.name||'Local collection'}</h2><p>{collection.data?.collectionFacility.address}</p>{collection.error?<p role="alert">{collection.error}</p>:!collection.data?<p role="status">Loading the operator’s evidence…</p>:<><div className="material-local-chain"><div><h3>Collected here</h3>{collection.data.observations.map(o=><p key={o.material}><strong>{o.material}</strong><br/>{o.relationship}</p>)}</div><div><h3>Next processor</h3><p>Not identified in the operator’s published information.</p></div><div><h3>Final fate</h3><p>No verified destination or recovery quantity in this source.</p></div></div><p>Collection does not prove recycling. This source does not identify a final destination for Salt Spring household garbage, or a route to Hartland.</p><p>Scrap metal and large appliances are currently listed as not accepted here.</p><Button onClick={()=>setEvidence(collection.data as unknown as Record<string,unknown>)}><BookOpen size={18}/> Inspect operator evidence</Button></>}</section>:<>
 <section className="material-controls" aria-label="Select material and geography">{regional?<><div className="material-scope"><MapPin/><div><strong>British Columbia</strong><span>Province of production · domestic exports · 2024</span></div><Link href="/materials?country=CAN">Change to country view</Link></div><div className="material-families" aria-label="Material families">{families.map(f=><Button key={f.id} variant="ghost" aria-pressed={state.family===f.id} onClick={()=>change({family:f.id})}>{f.name}</Button>)}</div><label className="material-search"><Search size={18}/><Input aria-label="Search all BC export products" placeholder="Search copper, salmon, lumber, plastic… or an HS code" value={state.search} onChange={e=>change({search:e.target.value})}/></label><Choice label="Product and reported unit" value={`${state.product}:${state.unit}`} onChange={v=>{const [product,unit]=v.split(':');change({product,unit})}} options={options.map(p=>({id:`${p.hs6}:${p.unit}`,name:`${p.hs6} · ${p.commodity} · ${p.unit}`}))}/><p className="material-small">{bc.data?`${matches.length.toLocaleString()} matching product/unit selections; showing up to 80. Refine your search to find others.`:'Loading the product catalogue…'}</p></>:<><div className="material-control-row"><Choice label="Reporting country" value={state.country} onChange={country=>change({country})} options={(copper.data?.countries||[{iso:'CAN',name:'Canada'}]).filter(c=>copper.data?.reporters.includes(c.iso)||c.iso===state.country).map(c=>({id:c.iso,name:c.name}))}/><Choice label="Direction" value={state.direction} onChange={direction=>change({direction:direction as 'X'|'M'})} options={[{id:'X',name:'Leaving · exporter report'},{id:'M',name:'Arriving · importer report'}]}/><span className="material-year">2024<br/><small>Acquired annual snapshot</small></span></div><div className="material-forms" aria-label="Copper form">{Object.entries(shortForms).map(([id,name],i)=><Button key={id} variant="ghost" aria-pressed={state.commodity===id} onClick={()=>change({commodity:id})}><span>{String(i+1).padStart(2,'0')}</span>{name}</Button>)}</div><label className="material-estimates"><Checkbox checked={state.estimates} onCheckedChange={v=>change({estimates:v===true})}/> Include UN Comtrade estimated weights (marked in every record)</label><p className="material-small">Explore other materials through <Link href="/region">BC’s complete acquired export catalogue</Link> or the <Link href="/flow?mode=explore">atlas’s raw-material and scrap flows</Link>.</p></>}
 </section>
 <section className="material-result" aria-live="polite"><div><p className="material-eyebrow">{regional?'Province → last-known country':state.direction==='X'?'Reported departures':'Reported arrivals'}</p><h2>{heading}</h2><p>{regional?`${bcQuantity(product||{unit:'KGM',unitLabel:'kilograms',quantityBasis:'contained metal',hs6:'260300',commodity:''},0).unit} · ${product?.quantityBasis||'assay quantity'}`:'Tonnes from the source net-weight field · one form, one reporting direction'}</p></div><Button variant="outline" onClick={()=>download(flows)} disabled={!flows.length}><Download size={18}/> Export records</Button></section>
 <div className="material-caveat">{regional?'Origin means the province where the product was grown, extracted or manufactured. Destination is the last-known foreign country when declared. These records do not identify the mine, port, customer or final use.':state.country==='CAN'&&state.commodity==='2603'?'Canadian ore weights need caution: national quantity rules use assay/metal content, and these Comtrade weight fields match source quantities. The basis is unresolved; do not interpret these as verified gross ore weights. Major destinations can have estimated weights—enable the option to inspect them.':'Country partners do not identify a mine, refinery or final user. These forms can contain alloys and other materials; weight is not a measure of pure copper. Import and export reports are independent and may differ.'}</div>
 {err?<p role="alert">{err}</p>:missingReporter?<p className="material-empty">No acquired reporter snapshot for this country.</p>:!loaded?<p role="status" className="material-empty">Loading source records…</p>:!flows.length?<p className="material-empty">No usable records for this selection. Missing or excluded weights are not zero.</p>:<><MaterialMap flows={flows} selected={state.destination} onSelect={destination=>change({destination})} regional={regional}/>
 <section className="material-partners"><div className="material-list-heading"><h3>{regional||state.direction==='X'?'Where it goes':'Where it comes from'}</h3><span>{flows.length} retained partner records · not a complete global total</span></div>{selected?<div className="material-selection"><strong>{selected.originLabel} → {selected.destinationLabel}</strong><Button onClick={()=>setEvidence(selected.record)}>Inspect selected record</Button><Button variant="ghost" onClick={()=>change({destination:''})}>Clear selection</Button></div>:null}<ol>{flows.map(f=><li key={f.id} className={state.destination===f.id?'is-selected':''}><button className="material-partner" onClick={()=>change({destination:f.id})} aria-pressed={state.destination===f.id}>{regional||state.direction==='X'?<ArrowUpRight size={20}/>:<ArrowDownLeft size={20}/>}<span>{regional||state.direction==='X'?f.destinationLabel:f.originLabel}<small>{f.estimated?'Estimated net weight':'Source observation'}</small></span><strong>{new Intl.NumberFormat('en',{maximumFractionDigits:3}).format(f.quantity)}<small>{f.unit}</small></strong><i aria-hidden="true" style={{width:`${Math.max(0,f.quantity/(flows[0]?.quantity||1)*100)}%`}}/></button><Button variant="ghost" aria-label={`Inspect source for ${f.originLabel} to ${f.destinationLabel}`} onClick={()=>setEvidence(f.record)}><BookOpen size={18}/><span>Source</span></Button></li>)}</ol></section></>}
 <footer className="material-foot"><h3>What this can tell you</h3><p>{regional?'These are recorded international domestic exports from BC, not all material leaving the province. Interprovincial trade, household movements and re-exports are outside this snapshot. Zero reported quantity can coexist with a positive trade value; it is not proof of no movement.':'This snapshot covers six copper headings and 19 requested reporting economies, of which 18 have usable mass records. DR Congo returned no source records. Do not add processing stages together: the same copper may cross borders more than once.'}</p><Button variant="outline" onClick={()=>setEvidence(regional?(bc.data?.source||{}):{source_id:'comtrade',source_url:'https://comtradeplus.un.org/',coverage:copper.data?.coverage_note,method:'Original-classification netWgt kg / 1000. Nonestimated weights default; source-estimated weights opt-in. No mirror filling or price-to-mass conversion.'})}><BookOpen size={18}/> Sources and methodology</Button><a href="https://overshoot.gaiaai.chatgpt.site/data">Open the data room</a></footer>
 </>}
 <Dialog open={!!evidence} onOpenChange={open=>{if(!open)setEvidence(null)}}><DialogContent className="material-evidence"><DialogTitle>Follow the evidence</DialogTitle><DialogDescription>Original units, geographic scope and source lineage for this selection.</DialogDescription>{evidenceUrl?<a href={evidenceUrl} target="_blank" rel="noreferrer">Open primary source ↗</a>:null}{evidence?<dl><dt>Source</dt><dd>{String(evidence.source_id||evidence.sourceId||nestedSource?.publisher||evidence.publisher||'Source snapshot')}</dd><dt>Original quantity</dt><dd>{String(evidence.original_value??evidence.quantity??'See methodology')} {String(evidence.original_unit||evidence.unit||'')}</dd><dt>Quantity basis</dt><dd>{String(evidence.quantityBasis||evidence.quantity_basis_note||evidence.method||'See source notes below')}</dd></dl>:null}<pre>{JSON.stringify(evidence,null,2)}</pre></DialogContent></Dialog>
 </main>
}
