export interface Product {hs6:string;commodity:string;unit:string;unitLabel:string;quantityBasis:string}
export interface BCObservation extends Product {id:string;year:number;origin:string;originLabel:string;destination:string;destinationLabel:string;quantity:number;valueCAD:number;sourceRows:number;monthsReported:number;sourceId:string}
export interface CopperObservation {id:string;origin:string;destination:string;commodity:string;year:number;tonnes:number;reporter:string;reported_flow:'X'|'M';is_net_weight_estimated:boolean;source_id:string;original_value:number;original_unit:string;quantity_basis_note:string;source_url:string;snapshot:string;snapshot_sha256:string;row_index:number;[key:string]:unknown}
export interface MaterialState {country:string;commodity:string;direction:'X'|'M';estimates:boolean;product:string;unit:string;destination:string;search:string;family:string}
export const initialMaterialState:MaterialState={country:'CAN',commodity:'2603',direction:'X',estimates:false,product:'260300',unit:'KGM',destination:'',search:'',family:'all'};
export function readMaterialState(search:string):MaterialState {const q=new URLSearchParams(search);return {...initialMaterialState,country:/^[A-Z]{3}$/.test(q.get('country')||'')?q.get('country')!:'CAN',commodity:/^\d{4}$/.test(q.get('commodity')||'')?q.get('commodity')!:'2603',direction:q.get('direction')==='M'?'M':'X',estimates:q.get('estimates')==='1',product:/^\d{6}$/.test(q.get('product')||'')?q.get('product')!:'260300',unit:q.get('unit')||'KGM',destination:q.get('destination')||'',search:q.get('search')||'',family:q.get('family')||'all'}}
export function materialQuery(s:MaterialState){const q=new URLSearchParams();for(const [k,v] of Object.entries(s))if(v!==''&&v!==false)q.set(k,v===true?'1':String(v));return q.toString()}
export function selectBC(rows:BCObservation[],state:MaterialState){return rows.filter(r=>r.hs6===state.product&&r.unit===state.unit).sort((a,b)=>b.quantity-a.quantity)}
export function selectCopper(rows:CopperObservation[],state:MaterialState){return rows.filter(r=>r.reporter===state.country&&r.commodity===state.commodity&&r.reported_flow===state.direction&&(state.estimates||!r.is_net_weight_estimated)).sort((a,b)=>b.tonnes-a.tonnes)}
export const families=[{id:'all',name:'All products',chapters:[] as string[]},{id:'copper',name:'Copper',chapters:['74'],codes:['2603']},{id:'metals',name:'Other metals',chapters:['72','73','75','76','78','79','80','81']},{id:'forest',name:'Wood & paper',chapters:['44','45','46','47','48','49']},{id:'fuels',name:'Fuels',chapters:['27']},{id:'food',name:'Food & biomass',chapters:Array.from({length:24},(_,i)=>String(i+1).padStart(2,'0'))},{id:'plastics',name:'Plastics & rubber',chapters:['39','40']},{id:'minerals',name:'Minerals & stone',chapters:['25','26','68','69','70']},{id:'products',name:'Machines & vehicles',chapters:['84','85','86','87','88','89']}];
export function productMatches(p:Product,state:MaterialState){const family=families.find(f=>f.id===state.family)||families[0];return (family.id==='all'||family.chapters.includes(p.hs6.slice(0,2))||family.codes?.some(c=>p.hs6.startsWith(c)))&&`${p.hs6} ${p.commodity}`.toLowerCase().includes(state.search.toLowerCase())}
export function bcQuantity(p:Product,value:number){const tonnes=p.unit==='KGM';return {value:tonnes?value/1000:value,unit:tonnes?(p.quantityBasis.includes('contained metal')?'tonnes of contained metal':'tonnes · source quantity'):p.unitLabel,basis:p.quantityBasis}}
