'use client';
import {useState} from 'react';
import {ArrowUpRight,CornerDownLeft,Orbit} from 'lucide-react';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {getExtraction,formatMass} from '@/packages/overshoot-data/queries';
import {getMaterialFootprint,getBilateralFlow,getMetric} from '@/packages/overshoot-data/expanded-queries';
import {MATERIALS,type ExtractionData,type Material,type Scene} from '@/packages/overshoot-data/types';
import {fetchArtifact,metricLabel,type TradeData,type ResourceRow,type MetricRecord} from './data';
import {formatMetric} from './Records';
import {useAtlas,type AtlasState} from './state';
type Answer={text:string;source:string;state?:Partial<AtlasState>};
export default function Query({open,onClose,data,onSource}:{open:boolean;onClose:()=>void;data:ExtractionData|null;onSource:(id:string)=>void}){
 const state=useAtlas(),[question,setQuestion]=useState(''),[answer,setAnswer]=useState<Answer|null>(null),[busy,setBusy]=useState(false);
 async function ask(q:string){if(!data||busy)return;setQuestion(q);setBusy(true);setAnswer(null);const lower=q.toLowerCase();const matches=data.countries.filter(c=>new RegExp(`\\b${c.name.replace(/[.*+?^${}()|[\]\\]/g,'\\$&')}\\b`,'i').test(q)).sort((a,b)=>lower.indexOf(a.name.toLowerCase())-lower.indexOf(b.name.toLowerCase()));const aliases:Record<string,string>={'united states':'USA','usa':'USA','us':'USA','uk':'GBR','south korea':'KOR','world':'WORLD','global':'WORLD'};const code=matches[0]?.id||Object.entries(aliases).find(([name])=>new RegExp(`\\b${name}\\b`).test(lower))?.[1]||state.country;const explicitYear=q.match(/\b(?:19|20)\d{2}\b/)?.[0];const yr=Number(explicitYear||state.year);const name=(id:string)=>data.countries.find(c=>c.id===id)?.name||id;const material:Material=lower.includes('biomass')?'biomass':/fossil|coal|oil/.test(lower)?'fossil':/metal|copper|iron/.test(lower)?'metals':/mineral|sand|rock|stone/.test(lower)?'minerals':'all';
 try{
  if(/tailings/.test(lower)){setAnswer({text:'The Global Tailings Portal is catalogued, but its reuse terms are unresolved. Facility coordinates and capacities are not published in this atlas. River outfalls, US landfills, mining footprints and wastewater plants are available as distinct layers.',source:'grid-tailings-portal',state:{scene:'discard',wasteStream:'places'}});return}
  if(/footprint/.test(lower)){const d=await fetchArtifact<{rows:ResourceRow[]}>(`resources/${yr}.json`);const r=getMaterialFootprint(d.rows,code,material,yr);setAnswer(r.status==='available'?{text:`${name(code)}: ${formatMetric(r.data)} of ${material==='all'?'material':MATERIALS.find(m=>m.id===material)?.name.toLowerCase()} footprint in ${yr}. This modeled account assigns upstream extraction to final demand.`,source:r.source_ids[0],state:{scene:'flow',country:code,year:yr}}:{text:r.reason,source:'irp-resource-accounts-2026'});return}
  if(/trade|scrap|export|import|from.+to|moves? from/.test(lower)){
   const controlled=/basel|hazardous/.test(lower),scrap=/scrap|waste|worn/.test(lower),flow=controlled?'controlled':scrap?'discard':'raw';
   const commodity=controlled?'BASEL':/plastic/.test(lower)?'3915':/paper/.test(lower)?'4707':/alumin/.test(lower)?'7602':/copper/.test(lower)?(scrap?'7404':'2603'):/ferrous|steel|iron/.test(lower)?(scrap?'7204':'2601'):/clothing|textile/.test(lower)?'6309':/electronic|e-waste/.test(lower)?'8549':/coal/.test(lower)?'2701':/oil/.test(lower)?'2709':/wheat/.test(lower)?'1001':/wood|timber/.test(lower)?'4403':(state.flow===flow?state.commodity:flow==='raw'?'2603':'3915');
   const d=await fetchArtifact<TradeData>(controlled?'basel.json':'trade.json');const destination=matches[1]?.id||'WORLD';const r=getBilateralFlow(d.flows,code,destination,commodity,yr);
   if(r.status==='unavailable'){setAnswer({text:r.reason,source:controlled?'basel-national-reporting':'comtrade',state:{scene:'flow',country:code,destination,commodity,flow,year:yr}});return}
   const label=d.commodities?.find(c=>c.id===commodity)?.name||'Basel controlled waste';const lines=r.data.slice(0,5).map(f=>`${name(f.origin)} → ${name(f.destination)}: ${formatMass(f.tonnes).number} ${formatMass(f.tonnes).unit}.`);
   let text=`${label}, ${yr}, reported export weight. ${lines.join(' ')} This is the acquired subset, not a complete global trade total.`;
   if(commodity==='2603')text+=' Ore/concentrate mass is not contained copper.';
   const quality=await fetchArtifact<{notes:{origin:string;destination:string;commodity:string;year:number;message:string}[]}>('trade-quality.json');if(quality.notes.some(n=>r.data.some(f=>f.origin===n.origin&&f.destination===n.destination&&f.commodity===n.commodity&&f.year===n.year)))text+=' Chile and China report different weights for their copper-ore corridor; this answer keeps the exporter’s record.';
   setAnswer({text,source:r.source_ids[0],state:{scene:'flow',country:code,destination,commodity:controlled?'3915':commodity,flow,year:yr}});return
  }
  const metric=/e.?waste/.test(lower)?'ewaste_generated':/plastic.*waste|waste.*plastic/.test(lower)?'plastic_waste_generated':/food.*waste/.test(lower)?'food_waste':/hazardous/.test(lower)?'hazardous_waste_generated':/stock|in.use/.test(lower)&&code!=='WORLD'?'in_use_stock':/circular.*rate|circular material/.test(lower)?'circular_material_use_rate':/waste|throw.+away/.test(lower)?'municipal_waste_generated':null;
  if(metric==='municipal_waste_generated'){const d=await fetchArtifact<import('./SceneDetail').SceneData>('scenes.json');const row=code==='WORLD'?d.waste.global:d.waste.countries.find(r=>r.country===code);setAnswer(row?.tonnes!==null&&row?.tonnes!==undefined&&(!explicitYear||row.year===yr)?{text:`${name(code)} · municipal waste generated: ${formatMass(row.tonnes).number} ${formatMass(row.tonnes).unit}, reference year ${row.year}. National reporting years differ.`,source:row.source_id,state:{scene:'discard',country:code,wasteStream:'municipal'}}:{text:'No World Bank observation for this country and requested year. Other source series can be inspected in the country evidence browser.',source:'worldbank-waw3-2026'});return}
  if(metric){const d=await fetchArtifact<{records:MetricRecord[]}>(explicitYear?`metrics/${code}.json`:'metrics-latest.json');const preferred=d.records.filter(r=>metric!=='plastic_waste_generated'||r.source_id==='oecd-plastics-database-2022');const r=getMetric(preferred,code,metric,explicitYear?yr:undefined);const scene:Scene=metric==='in_use_stock'?'stock':metric==='circular_material_use_rate'?'return':'discard';const wasteStream=metric.startsWith('ewaste')?'ewaste':metric.startsWith('plastic')?'plastics':metric.startsWith('food')?'food':metric.startsWith('hazardous')?'hazardous':'municipal';setAnswer(r.status==='available'?{text:`${name(code)} · ${metricLabel(metric)}: ${formatMetric(r.data)}, reference year ${r.data.year}.${r.data.estimated?' This is a source estimate.':''}${r.data.method?' '+r.data.method+'.':''}`,source:r.source_ids[0],state:explicitYear?undefined:{scene,country:code,wasteStream,stockView:'country'}}:{text:r.reason,source:'all'});return}
  if(/built|hidden|garbage|stock/.test(lower)){setAnswer({text:'Much of the extracted material remains in roads, buildings and infrastructure. The Stock scene compares human-made mass with biomass and offers country material-stock estimates with their own reference years.',source:'elhacham-2020',state:{scene:'stock',stockView:'mass'}});return}
  if(/copper|aluminium|plastic/.test(lower)){setAnswer({text:'Extraction is available in four broad classes. For commodities, ask for a reported trade route—for example, copper ores from Chile to China in 2024.',source:'irp-2026'});return}
  if(!/extract|material|biomass|tonne|mineral|fossil|metal/.test(lower)){setAnswer({text:'Try a country extraction or footprint, a commodity trade route, or a country’s e-waste, food waste or material stock. Answers use finite source queries; an open-ended language model is not connected.',source:'all'});return}
  const metricMode=/per.person|per.capita/.test(lower)?'percapita':'absolute';const r=getExtraction(data,code,material,yr,metricMode);if(r.status==='unavailable'){setAnswer({text:r.reason,source:'irp-2026'});return}const formatted=formatMass(r.data.value,metricMode);setAnswer({text:`${name(code)}: ${formatted.number} ${formatted.unit} of ${material==='all'?'total material':MATERIALS.find(m=>m.id===material)?.name.toLowerCase()} extracted in ${yr}. An IRP material-flow estimate.`,source:r.source_ids[0],state:{scene:'extraction',country:code,material,year:yr,metric:metricMode}});
 }catch{setAnswer({text:'The required source snapshot could not be loaded. No quantity has been inferred.',source:'all'})}finally{setBusy(false)}
 }
 return <Dialog open={open} onOpenChange={o=>{if(!o)onClose()}}><DialogContent className="query-dialog"><div className="query-emblem"><Orbit size={28}/></div><DialogTitle>Ask the atlas</DialogTitle><DialogDescription>Explore acquired data. Every answer carries its source.</DialogDescription><form onSubmit={e=>{e.preventDefault();ask(question)}} className="query-form"><input value={question} onChange={e=>setQuestion(e.target.value)} aria-label="Question about material flows" placeholder="What is Japan’s material footprint?"/><button type="submit" aria-label="Ask question" disabled={busy}><CornerDownLeft size={18}/></button></form>{busy&&<p role="status">Looking up the source…</p>}{answer?<div className="query-answer" aria-live="polite"><p>{answer.text}</p><button className="source-link" onClick={()=>{onClose();onSource(answer.source)}}>Inspect source <ArrowUpRight size={14}/></button>{answer.state&&<button className="neu-button" onClick={()=>{const center=data?.countries.find(c=>c.id===answer.state?.country)?.center;state.set({...answer.state,...(center?{longitude:center[0],latitude:center[1],zoom:.9}:{})});onClose()}}>Show in atlas <ArrowUpRight size={14}/></button>}</div>:!busy&&<div className="query-suggestions">{['What is Japan’s material footprint in 2024?','Where does United States plastic scrap go in 2024?','How much e-waste does Canada generate?'].map(q=><button key={q} onClick={()=>ask(q)}>{q}<ArrowUpRight size={14}/></button>)}</div>}<p className="query-note">Typed source lookups · no connected language model</p></DialogContent></Dialog>;
}
