'use client';
import {useMemo,useState} from 'react';
import {ArrowUpRight,MapPin,ArrowRight} from 'lucide-react';
import {Select,SelectContent,SelectItem,SelectTrigger,SelectValue} from '@/components/ui/select';
import {useAtlas} from './state';
import {useArtifact,latestMetric,metricLabel,siteFiles,type MetricRecord,type SiteData} from './data';
import {formatMass} from '@/packages/overshoot-data/queries';
import type {Country} from '@/packages/overshoot-data/types';
import {SourceButton} from './SourceButton';

export function formatMetric(r:Pick<MetricRecord,'value'|'unit'>){if(r.unit==='percent'||r.unit==='%')return `${new Intl.NumberFormat('en',{maximumFractionDigits:1}).format(r.value)}%`;if(r.unit.includes('tonne')){if(r.unit.includes('person'))return r.value<1?`${(r.value*1000).toFixed(1)} kg / person`:`${r.value.toFixed(1)} tonnes / person`;const n=formatMass(r.value);return `${n.number} ${n.unit}${r.unit.includes('/year')?' / year':''}`}return `${new Intl.NumberFormat('en',{maximumFractionDigits:1}).format(r.value)} ${r.unit}`}
export function EvidenceExplorer({onSource}:{onSource:(id:string)=>void}){
 const s=useAtlas(),{data,error}=useArtifact<{records:MetricRecord[]}>(`metrics/${s.country}.json`),{data:countries}=useArtifact<Country[]>('countries.json');
 const [search,setSearch]=useState(''),[year,setYear]=useState('latest'),[limit,setLimit]=useState(24);
 const all=data?.records||[];
 const years=[...new Set(all.map(r=>r.year))].sort((a,b)=>b-a);
 const rows=useMemo(()=>{let selected=all.filter(r=>(year==='latest'||r.year===Number(year))&&[metricLabel(r.metric),r.source_id].join(' ').toLowerCase().includes(search.toLowerCase()));if(year==='latest'){const latest=new Map<string,MetricRecord>();for(const r of selected){const key=[r.metric,r.source_id,JSON.stringify(r.dimensions||{})].join(':');if(!latest.has(key)||latest.get(key)!.year<r.year)latest.set(key,r)}selected=[...latest.values()]}return selected.sort((a,b)=>metricLabel(a.metric).localeCompare(metricLabel(b.metric))||b.year-a.year)},[data,year,search]);
 return <div className="evidence-explorer"><div className="evidence-controls"><label className="field-label">Country<Select value={s.country} onValueChange={country=>{s.set({country});setLimit(24)}}><SelectTrigger aria-label="Evidence country" className="commodity-select"><SelectValue/></SelectTrigger><SelectContent><SelectItem value="WORLD">World</SelectItem>{countries?.filter(c=>c.id!=='WORLD').map(c=><SelectItem key={c.id} value={c.id}>{c.name}</SelectItem>)}</SelectContent></Select></label><label className="field-label">Year<Select value={year} onValueChange={v=>{setYear(v);setLimit(24)}}><SelectTrigger aria-label="Evidence year" className="commodity-select"><SelectValue/></SelectTrigger><SelectContent><SelectItem value="latest">Latest per series</SelectItem>{years.map(y=><SelectItem key={y} value={String(y)}>{y}</SelectItem>)}</SelectContent></Select></label></div><input className="source-search" aria-label="Search acquired metrics" placeholder="Search e-waste, food, packaging, stock…" value={search} onChange={e=>{setSearch(e.target.value);setLimit(24)}}/><p className="chart-method">{year==='latest'?'Latest available record for each series. Dates differ; estimates and projections keep their source notes.':'Only records for the selected year.'} These accounts overlap; do not add them together.</p>{error?<p className="data-gap">No acquired records for this country.</p>:!data?<p className="data-gap">Loading country records…</p>:<><div className="evidence-list">{rows.slice(0,limit).map((r,i)=><button key={i} onClick={()=>onSource(r.source_id)}><span><strong>{metricLabel(r.metric)}</strong><small>{r.year} · {r.source_id}{r.estimated?' · estimate':''}</small>{r.method&&<small>{r.method}</small>}{r.footnotes?.length? <small>{r.footnotes.join(' · ')}</small>:null}</span><span className="evidence-value">{formatMetric(r)}<ArrowUpRight size={14}/></span></button>)}</div>{!rows.length&&<p className="data-gap">No observations match this selection.</p>}{rows.length>limit&&<button className="neu-button" onClick={()=>setLimit(n=>n+24)}>Show more records</button>}</>}</div>
}
export function CountryStock({onSource,placement}:{onSource:(id:string)=>void;placement:'narrative'|'visual'}){
 const s=useAtlas(),{data}=useArtifact<{records:MetricRecord[]}>('metrics-latest.json'),{data:parts}=useArtifact<{records:{country:string;metric:string;dimension:string;category:string;value:number;year:number;source_id:string}[]}>('stock-components.json');
 const row=latestMetric(data?.records||[],s.country,'in_use_stock');const additions=latestMetric(data?.records||[],s.country,'stock_additions');const endOfLife=latestMetric(data?.records||[],s.country,'stock_end_of_life');
 if(placement==='narrative')return row?<><button className="main-measure" onClick={()=>onSource(row.source_id)}><span className="measure-number">{formatMass(row.value).number}</span><span className="measure-unit">{formatMass(row.value).unit}<small>In-use stock · {row.year} · model estimate</small></span></button><SourceButton onClick={()=>onSource(row.source_id)} label="MAT_STOCKS · MISO2"/><p className="scene-caveat">The mass already in use—not one year of extraction. Source coverage ends in {row.year}; the atlas does not project it forward.</p></>:<p className="scene-fact">Choose a country to explore its modeled material stock. No country value is replaced with a regional estimate.</p>;
 if(!row)return <div className="waste-empty"><h2>A country’s accumulated world.</h2><p>Select a country above to inspect the MAT_STOCKS account. The global comparison is available in the Mass comparison view.</p><SourceButton onClick={()=>onSource('mat-stocks-2024')} label="MAT_STOCKS coverage"/></div>;
 const components=parts?.records.filter(r=>r.country===s.country&&r.metric==='in_use_stock'&&r.dimension==='end_use')||[];const max=Math.max(1,...components.map(r=>r.value));
 return <section className="country-stock"><div className="visual-label"><span>IN-USE STOCK · {row.year}</span><SourceButton onClick={()=>onSource(row.source_id)} label="Model & units"/></div>{components.map((r,i)=><button className="account-bar" key={r.category} onClick={()=>onSource(r.source_id)}><span>{r.category}</span><strong>{formatMass(r.value).number} {formatMass(r.value).unit}</strong><i style={{width:`${r.value/max*100}%`,background:['#ffd16c','#91bfff','#ff927b','#8be5a5'][i%4]}}/></button>)}<div className="trade-account-pair">{[additions,endOfLife].map(r=>r&&<button key={r.metric} onClick={()=>onSource(r.source_id)}><span>{r.metric==='stock_additions'?'Added during year':'Left use during year'}</span><strong>{formatMetric(r)}</strong><small>{r.year} · modeled annual flow</small></button>)}</div><p className="chart-method">Four end uses and four material groups in the acquired model. Annual additions and retirements are shown separately from accumulated stock.</p></section>
}
export function AgricultureDetail({onSource}:{onSource:(id:string)=>void}){
 const s=useAtlas(),{data}=useArtifact<{year:number;rows:{country:string;item:string;tonnes:number;source_id:string;source_flag:string}[]}>(s.material==='biomass'?'agriculture.json':null);if(s.material!=='biomass'||!data)return null;const rows=data.rows.filter(r=>r.country===s.country).sort((a,b)=>b.tonnes-a.tonnes);return <section className="agriculture-detail"><div className="visual-label"><span>PRIMARY CROPS · {data.year}</span><SourceButton onClick={()=>onSource('faostat-qcl-2025')} label="FAOSTAT"/></div>{rows.slice(0,4).map(r=><button className="record-row" key={r.item} onClick={()=>onSource(r.source_id)}><span>{r.item}<small>{r.source_flag==='A'?'Reported':r.source_flag==='E'?'Estimated':r.source_flag==='I'?'Imputed by source':'Source flag '+r.source_flag}</small></span><strong>{formatMass(r.tonnes).number} {formatMass(r.tonnes).unit}</strong></button>)}<p className="chart-method">Eight selected primary crops are acquired. These are not total biomass extraction, and they are not added to IRP totals.</p></section>
}
const siteLabels:Record<string,string>={'river-plastic':'River plastic outfalls',landfill:'US landfills','mining-area':'Mapped mining areas','wastewater-treatment':'Wastewater treatment'};
export function CountryCircularity({onSource}:{onSource:(id:string)=>void}){
 const s=useAtlas(),{data}=useArtifact<{records:MetricRecord[]}>(s.country==='WORLD'?null:'metrics-latest.json');
 const row=latestMetric(data?.records||[],s.country,'circular_material_use_rate');
 if(s.country==='WORLD')return null;
 return <section className="country-circularity"><div className="visual-label"><span>YOUR COUNTRY</span></div>{row?<><button className="record-row" onClick={()=>onSource(row.source_id)}><span>Circular material use<small>{row.year}{row.estimated?' · source estimate':''}</small></span><strong>{formatMetric(row)}</strong></button><p className="chart-method">Eurostat’s national circular material use indicator. Its system boundary differs from the global Circularity Gap account.</p><SourceButton onClick={()=>onSource(row.source_id)} label="Eurostat · methodology"/></>:<p className="chart-method">No national circular material use record in the acquired Eurostat subset. The global rate is not substituted for your country.</p>}</section>
}
const siteNotes:Record<string,string>={'river-plastic':'Largest 1,000 of 31,819 modeled river outfalls, ranked by the study’s 2015 midpoint estimate. Macroplastic, not all plastic; model uncertainty is substantial.',landfill:'EPA LMOP: 2,323 geolocated US landfill records from September 2024. 318 records have no usable coordinates. Mass is reported annual waste acceptance, with each facility’s reporting year; this is not total national generation.','mining-area':'Largest 1,500 of 44,929 mapped mining polygons. Markers are representative points for mining areas, not tailings facilities. Area is not mass.','wastewater-treatment':'Largest 1,000 plants with reported treatment rates (quality flag 1) in HydroWASTE. Volume in m³/day is not material mass. Reporting years are unspecified.'};
export function SiteLayerSelect(){const s=useAtlas();return <label className="field-label">Geographic layer<Select value={s.siteType} onValueChange={siteType=>s.set({siteType,site:'',zoom:.55})}><SelectTrigger aria-label="Physical site layer" className="commodity-select"><SelectValue/></SelectTrigger><SelectContent>{Object.entries(siteLabels).map(([id,label])=><SelectItem key={id} value={id}>{label}</SelectItem>)}</SelectContent></Select></label>}
export function SitesPanel({onSource}:{onSource:(id:string)=>void}){
 const s=useAtlas(),{data,error}=useArtifact<SiteData>(siteFiles[s.siteType]);const[search,setSearch]=useState('');
 const all=data?.features.filter(f=>(s.country==='WORLD'||f.properties.country===s.country)&&f.properties.name.toLowerCase().includes(search.toLowerCase()))||[];
 const selected=data?.features.find(f=>f.properties.id===s.site);
 return <section className="sites-panel"><div className="visual-label"><span>PHYSICAL PLACES</span><MapPin size={19}/></div><p className="chart-method">{siteNotes[s.siteType]} Marker size is nonlinear. The geographic fallback limits the map to 500 markers; the list covers the loaded subset.</p><input className="source-search" aria-label="Find a physical site" placeholder="Find a river, landfill or mapped area…" value={search} onChange={e=>setSearch(e.target.value)}/>{selected&&<div className="selected-site"><span className="source-status available">SELECTED PLACE</span><h3>{selected.properties.name}</h3><p>{selected.properties.metric}</p><button onClick={()=>onSource(selected.properties.source_id)}><strong>{selected.properties.value===null?'Not reported':formatMetric({value:selected.properties.value,unit:selected.properties.unit})}</strong><span>{selected.properties.year??'Year unspecified'}{selected.properties.estimated?' · model estimate':''}</span></button><SourceButton onClick={()=>onSource(selected.properties.source_id)} label="Inspect place & methodology"/><p className="site-coordinates">{Math.abs(selected.geometry.coordinates[1]).toFixed(4)}° {selected.geometry.coordinates[1]>=0?'N':'S'} · {Math.abs(selected.geometry.coordinates[0]).toFixed(4)}° {selected.geometry.coordinates[0]>=0?'E':'W'}</p><a className="source-link" href={`https://www.openstreetmap.org/?mlat=${selected.geometry.coordinates[1]}&mlon=${selected.geometry.coordinates[0]}#map=13/${selected.geometry.coordinates[1]}/${selected.geometry.coordinates[0]}`} target="_blank" rel="noreferrer">Open exact location on OpenStreetMap <ArrowRight size={14}/></a></div>}{error?<p className="data-gap">Site snapshot unavailable.</p>:<div className="site-list">{all.slice(0,20).map(f=><button key={f.properties.id} onClick={()=>s.set({site:f.properties.id,longitude:f.geometry.coordinates[0],latitude:f.geometry.coordinates[1],zoom:2.1})}><MapPin size={17}/><span>{f.properties.name}<small>{f.properties.country||'Country not assigned'} · {f.properties.year??'Year unspecified'}</small></span><ArrowRight size={17}/></button>)}</div>}{!all.length&&data&&<p className="data-gap">No matching sites in this acquired subset. This is not evidence that none exist.</p>}</section>
}
