'use client';
import {Select,SelectContent,SelectItem,SelectTrigger,SelectValue} from '@/components/ui/select';
import {useAtlas} from './state';
import {useArtifact,latestMetric,type MetricRecord} from './data';
import {SourceButton} from './SourceButton';
import {formatMass} from '@/packages/overshoot-data/queries';
import {formatMetric,SiteLayerSelect,SitesPanel} from './Records';
import Destinations,{TreatmentView} from './Destinations';
import type {SceneData} from './SceneDetail';
const STREAMS=[['destinations','Where scrap goes'],['treatment','National waste treatment'],['ewaste-location','Where e-waste is treated'],['municipal','Municipal waste'],['ewaste','E-waste'],['plastics','Plastics'],['food','Food waste'],['hazardous','Hazardous waste'],['places','Physical places']];
const config:Record<string,{metric:string;source?:string;label:string;description:string;details:[string,string][]}>={
 ewaste:{metric:'ewaste_generated',label:'E-waste generated',description:'Electrical and electronic equipment leaving use. Generation is modeled; documented collection and recycling are separate records.',details:[['ewaste_recycled','Formally collected / recycled'],['ewaste_recycling_rate','Documented recycling rate'],['ewaste_per_capita','Generated per person']]},
 plastics:{metric:'plastic_waste_generated',source:'oecd-plastics-database-2022',label:'Plastic waste',description:'OECD’s modeled plastics account. Fate values retain the same year and source as generation. They are separate from municipal-waste accounts.',details:[['plastic_waste_recycled','Recycled'],['plastic_waste_incinerated','Incinerated'],['plastic_waste_sanitary_landfill','Sanitary landfill'],['plastic_waste_mismanaged','Mismanaged'],['plastic_waste_uncollected_litter','Uncollected litter']]},
 food:{metric:'food_waste',label:'Food waste',description:'Food Waste Index estimates cover household, food service and retail. Food lost before retail is a different FAO indicator, not added here.',details:[['household_food_waste','Households'],['food_service_food_waste','Food service'],['retail_food_waste','Retail']]},
 hazardous:{metric:'hazardous_waste_generated',label:'Hazardous waste generated',description:'National definitions and reporting coverage differ. Generation and treatment records can refer to different years; no universal fate split is inferred.',details:[['hazardous_waste_treated_recycl','Reported recycling'],['hazardous_waste_treated_landfil','Reported landfilling'],['hazardous_waste_treated_incinrt','Reported incineration'],['hazardous_waste_treated_incinrt_egy','Incineration with energy recovery']]}
};
export default function WasteDetail({data,placement,onSource}:{data:SceneData;placement:'narrative'|'visual';onSource:(id:string)=>void}){
 const s=useAtlas(),{data:metrics}=useArtifact<{records:MetricRecord[]}>(config[s.wasteStream]?'metrics-latest.json':null);const rows=metrics?.records||[],conf=config[s.wasteStream];
 const metric=conf?latestMetric(rows,s.country,conf.metric,conf.source):undefined;
 const msw=s.country==='WORLD'?data.waste.global:data.waste.countries.find(c=>c.country===s.country);
 const value=s.wasteStream==='municipal'?msw?.tonnes:metric?.value;
 const source=s.wasteStream==='municipal'?(msw?.source_id||data.waste.global.source_id):metric?.source_id||(s.wasteStream==='plastics'?'oecd-plastics-database-2022':s.wasteStream==='food'?'unsd-food-waste-2026':s.wasteStream==='hazardous'?'unsd-hazardous-2026':'unsd-ewaste-2026');
 if(placement==='narrative')return <>
  <label className="field-label waste-stream-select">Explore a waste stream<Select value={s.wasteStream} onValueChange={wasteStream=>s.set({wasteStream,site:'',destination:'WORLD',treatmentYear:0,...(wasteStream==='destinations'?{commodity:'3915',year:2024}:{})})}><SelectTrigger aria-label="Waste stream" className="commodity-select"><SelectValue/></SelectTrigger><SelectContent>{STREAMS.map(([id,label])=><SelectItem key={id} value={id}>{label}</SelectItem>)}</SelectContent></Select></label>
  {s.wasteStream==='destinations'?<Destinations placement="narrative" onSource={onSource}/>:['treatment','ewaste-location'].includes(s.wasteStream)?<p className="scene-caveat">{s.wasteStream==='treatment'?'The next life of discarded material: recycling, backfilling, energy recovery and disposal. Each country keeps its own reported account.':'Follow electronics leaving use to the location of reported treatment. Select a country to see where the record leads.'}</p>:s.wasteStream==='places'?<><SiteLayerSelect/><p className="scene-caveat">Choose a published geographic layer, then select a place on the map or in the list.</p></>:<>
   <button className="main-measure" onClick={()=>onSource(source)}><span className="measure-number">{value===null||value===undefined?'—':formatMass(value).number}</span><span className="measure-unit">{value===null||value===undefined?'No acquired value':formatMass(value).unit}<small>{s.wasteStream==='municipal'?`Municipal waste · ${msw?.year||'year unavailable'}`:`${conf?.label} · ${metric?.year||'year unavailable'}${metric?.estimated?' · estimate':''}`}</small></span></button>
   <SourceButton onClick={()=>onSource(source)} label={s.wasteStream==='municipal'?'World Bank · What a Waste 3.0':s.wasteStream==='plastics'?'OECD · Global Plastics Outlook':s.wasteStream==='food'?'UNEP / UNSD · Food Waste Index':s.wasteStream==='hazardous'?'UNSD · hazardous waste':'UNITAR / UNSD · e-waste'}/>
   <p className="scene-caveat">{s.wasteStream==='municipal'?'National reporting years differ. This is municipal waste, not all material leaving the economy.':conf?.description}</p>
  </>}
 </>;
 if(s.wasteStream==='destinations')return <div className="scene-visual discard-visual destinations-visual"><Destinations placement="visual" onSource={onSource}/></div>;
 if(['treatment','ewaste-location'].includes(s.wasteStream))return <TreatmentView weee={s.wasteStream==='ewaste-location'} onSource={onSource}/>;
 if(s.wasteStream==='places')return <div className="scene-visual discard-visual places-visual"><SitesPanel onSource={onSource}/></div>;
 if(s.wasteStream==='municipal'){
  const national=s.country!=='WORLD'?data.waste.countries.find(c=>c.country===s.country):{source_id:data.unep_waste_fate.source_id,fate:data.unep_waste_fate.categories};
  return <div className="scene-visual discard-visual"><div className="visual-label"><span>{s.country==='WORLD'?'GLOBAL DISPOSAL · 2020':'REPORTED TREATMENT SHARES'}</span><SourceButton onClick={()=>onSource(national?.source_id||source)} label={s.country==='WORLD'?'UNEP':'World Bank'}/></div>{national&&national.fate.length?<div className="waste-fates">{national.fate.map((f,i)=><button key={f.label} onClick={()=>onSource(national.source_id)}><span>{f.label}</span><strong>{f.share.toFixed(1)}%</strong><i style={{width:`${Math.min(100,f.share)}%`,background:['#6ae5c1','#91bfff','#ffd16c','#ff927b'][i%4]}}/></button>)}<p>{s.country==='WORLD'?'UNEP’s 2020 fate baseline, separate from the World Bank 2022 generation estimate. Uncontrolled includes dumping and open burning.':'Treatment dates are unspecified in this workbook. Source categories are preserved; no residual category or normalization is invented.'}</p></div>:<div className="waste-empty"><h2>No comparable fate record.</h2><p>This country’s acquired record does not include treatment shares.</p></div>}<button className="neu-button more-evidence" onClick={()=>onSource('records')}>Compare acquired country records</button><button className="source-link" onClick={()=>s.set({wasteStream:'destinations',commodity:'3915',year:2024,destination:'WORLD'})}>Follow scrap to its destination <ArrowIcon/></button></div>;
 }
 const details=(conf?.details||[]).map(([key,label])=>({row:latestMetric(rows,s.country,key,conf?.source),label}));
 const max=Math.max(1,...details.map(d=>d.row?.unit==='tonnes'?d.row.value:0));
 return <div className="scene-visual discard-visual"><div className="visual-label"><span>{conf?.label.toUpperCase()} · SOURCE RECORDS</span><SourceButton onClick={()=>onSource(source)} label="Methodology"/></div><div className="waste-fates">{details.map(({row,label})=><button key={label} onClick={()=>onSource(row?.source_id||source)}><span>{label}{row&&<small>{row.year}{row.estimated?' · estimate':''}</small>}</span><strong>{row?formatMetric(row):'Unavailable'}</strong>{row?.unit==='tonnes'&&<i style={{width:`${row.value/max*100}%`,background:'#91bfff'}}/>}</button>)}</div>{metric?.footnotes?.length?<p className="chart-method">{metric.footnotes.join(' · ')}</p>:null}<p className="chart-method">Every row keeps its own reference year. Missing national values remain unavailable. These records are not added to municipal waste totals.</p><button className="neu-button more-evidence" onClick={()=>onSource('records')}>Browse country evidence</button></div>;
}
function ArrowIcon(){return <span aria-hidden="true">↗</span>}
