import {z} from 'zod';
import {getExtraction,compareCountries} from '@/packages/overshoot-data/queries';
import {getBilateralFlow,getMaterialFootprint,getMetric,getSites,type AccountRecord,type FlowRecord,type QuantitativeRecord} from '@/packages/overshoot-data/expanded-queries';
import {type ExtractionData,SCENES} from '@/packages/overshoot-data/types';
import {useAtlas} from './state';
import type {SceneData} from './SceneDetail';
import {artifactUrl,type SiteData} from './data';
import {treatmentLeaves,type TreatmentData} from '@/packages/overshoot-data/destinations';
const country=z.string().regex(/^(WORLD|[A-Z]{3})$/),year=z.number().int().min(1900).max(2025);
const material=z.enum(['all','biomass','fossil','metals','minerals']);
const extraction=z.object({country,year:z.number().int().min(1970).max(2024),material:material.default('all')}).strict();
interface ModelContext{registerTool:(tool:{name:string;description:string;inputSchema:object;annotations:{readOnlyHint:boolean};execute:(input:unknown)=>unknown},options:{signal:AbortSignal})=>void|Promise<void>}
const cached=new Map<string,Promise<unknown>>();
function load<T>(file:string):Promise<T>{let p=cached.get(file);if(!p){p=fetch(artifactUrl(file)).then(r=>{if(!r.ok)throw Error('Required source snapshot is unavailable');return r.json()});cached.set(file,p)}return p as Promise<T>}
const countryYear={country:{type:'string'},year:{type:'integer',minimum:1900,maximum:2025}};
const schema=(properties:object,required:string[])=>({type:'object',properties,required,additionalProperties:false});
export function atlasTools(data:ExtractionData){return [
 {name:'getExtraction',description:'Read acquired domestic extraction in metric tonnes with provenance and estimate status.',inputSchema:schema({...countryYear,material:{type:'string',enum:['all','biomass','fossil','metals','minerals']}},['country','year']),annotations:{readOnlyHint:true},execute(input:unknown){const q=extraction.parse(input);return getExtraction(data,q.country,q.material,q.year)}},
 {name:'getMaterialFootprint',description:'Read native modeled material footprint. Never substitute regional values or rebalance the source account.',inputSchema:schema({...countryYear,material:{type:'string',enum:['all','biomass','fossil','metals','minerals']}},['country','year']),annotations:{readOnlyHint:true},async execute(input:unknown){const q=extraction.parse(input),d=await load<{rows:AccountRecord[]}>(`resources/${q.year}.json`);return getMaterialFootprint(d.rows,q.country,q.material,q.year)}},
 {name:'getBilateralFlow',description:'Read reported export weights from the acquired Comtrade subset. Net tonnes are not contained-metal mass. Missing routes are not zero.',inputSchema:schema({origin:{type:'string'},destination:{type:'string'},commodity:{type:'string'},year:{type:'integer'}},['origin','destination','commodity','year']),annotations:{readOnlyHint:true},async execute(input:unknown){const q=z.object({origin:country,destination:country,commodity:z.string().regex(/^(BASEL|[0-9]{4})$/),year}).strict().parse(input);if(q.commodity==='BASEL')return {status:'unavailable',reason:'Basel quantitative reuse is pending publisher permission.',source_id:'basel-national-reporting'};const d=await load<{flows:FlowRecord[]}>('trade.json');const result=getBilateralFlow(d.flows,q.origin,q.destination,q.commodity,q.year);const quality=await load<{notes:{origin:string;destination:string;commodity:string;year:number}[]}>('trade-quality.json');return {...result,quality_notes:quality.notes.filter(n=>n.year===q.year&&n.commodity===q.commodity&&(q.origin==='WORLD'||n.origin===q.origin)&&(q.destination==='WORLD'||n.destination===q.destination))}}},
 {name:'getTopFlowPartners',description:'Return ranked acquired trade records by reported tonnes, with explicit direction; this is a reporter/commodity subset, not global coverage.',inputSchema:schema({...countryYear,commodity:{type:'string'},direction:{type:'string',enum:['imports','exports']}},['country','commodity','direction','year']),annotations:{readOnlyHint:true},async execute(input:unknown){const q=z.object({country,commodity:z.string().regex(/^(BASEL|[0-9]{4})$/),direction:z.enum(['imports','exports']),year}).strict().parse(input);if(q.commodity==='BASEL')return {status:'unavailable',reason:'Basel quantitative reuse is pending publisher permission.',source_id:'basel-national-reporting'};const d=await load<{flows:FlowRecord[]}>('trade.json');return getBilateralFlow(d.flows,q.direction==='exports'?q.country:'WORLD',q.direction==='imports'?q.country:'WORLD',q.commodity,q.year)}},
 {name:'getWasteGeneration',description:'Read the World Bank municipal waste generation observation with its actual reference year. Other waste accounts use getCountryMetric.',inputSchema:schema(countryYear,['country']),annotations:{readOnlyHint:true},async execute(input:unknown){const q=z.object({country,year:year.optional()}).strict().parse(input),d=await load<SceneData>('scenes.json'),r=q.country==='WORLD'?d.waste.global:d.waste.countries.find(r=>r.country===q.country);return r&&r.tonnes!==null&&(!q.year||r.year===q.year)?{status:'available',data:r,unit:'tonnes/year',source_ids:[r.source_id]}:{status:'unavailable',reason:'No municipal observation for this country and year.',source_ids:['worldbank-waw3-2026']}}},
 {name:'getWasteFate',description:'Read source-native waste fate categories. Global UNEP fate is 2020; national World Bank treatment dates are unspecified. Do not assign generation years.',inputSchema:schema({country:{type:'string'}},['country']),annotations:{readOnlyHint:true},async execute(input:unknown){const q=z.object({country}).strict().parse(input),d=await load<SceneData>('scenes.json');if(q.country==='WORLD')return {status:'available',data:d.unep_waste_fate,source_ids:[d.unep_waste_fate.source_id]};const r=d.waste.countries.find(r=>r.country===q.country);return r?.fate.length?{status:'available',data:{categories:r.fate,year:null},source_ids:[r.source_id]}:{status:'unavailable',reason:'No acquired national fate record.',source_ids:['worldbank-waw3-2026']}}},
 {name:'getWasteTreatment',description:'Read native Eurostat treatment or WEEE location categories for one reporting country and year. Includes source cell IDs, missing cells and geographic exceptions. Does not establish the fate of a traded shipment.',inputSchema:schema({...countryYear,account:{type:'string',enum:['all-waste','ewaste']},scope:{type:'string',enum:['TOTAL','TOT_X_MIN']}},['country','year','account']),annotations:{readOnlyHint:true},async execute(input:unknown){const q=z.object({country,year,account:z.enum(['all-waste','ewaste']),scope:z.enum(['TOTAL','TOT_X_MIN']).default('TOT_X_MIN')}).strict().parse(input),d=await load<TreatmentData>(q.account==='ewaste'?'weee-treatment.json':'treatment.json'),row=d.records.find(r=>r.country===q.country&&r.year===q.year&&r.scope===(q.account==='ewaste'?'EE6':q.scope));return row?{status:'available',data:row,exclusive_categories:q.account==='all-waste'?treatmentLeaves(row):undefined,geography_exception:d.geography_exceptions?.[q.country]||null,country_note:d.country_notes?.[q.country]||null,source_ids:[d.source_id]}:{status:'unavailable',reason:'No acquired treatment account for this country, year and scope.',source_ids:[d.source_id]}}},
 {name:'getCountryMetric',description:'Read an acquired country metric and year: e-waste, food, plastics, hazardous waste, stock, circularity and packaging. Source methods and estimates are retained.',inputSchema:schema({...countryYear,metric:{type:'string'},source_id:{type:'string'}},['country','metric','year']),annotations:{readOnlyHint:true},async execute(input:unknown){const q=z.object({country,metric:z.string().min(1),year,source_id:z.string().optional()}).strict().parse(input),d=await load<{records:QuantitativeRecord[]}>(`metrics/${q.country}.json`);return getMetric(d.records.filter(r=>!q.source_id||r.source_id===q.source_id),q.country,q.metric,q.year)}},
 {name:'getSites',description:'Read the acquired geographic subset. River emissions, landfill annual waste acceptance, mining area and wastewater volume have distinct units. Returns source IDs and original properties.',inputSchema:schema({type:{type:'string',enum:['river-plastic','landfill','mining-area','wastewater-treatment']},country:{type:'string'},bounds:{type:'array',items:{type:'number'},minItems:4,maxItems:4}},['type']),annotations:{readOnlyHint:true},async execute(input:unknown){const q=z.object({type:z.enum(['river-plastic','landfill','mining-area','wastewater-treatment']),country:country.default('WORLD'),bounds:z.tuple([z.number(),z.number(),z.number(),z.number()]).optional()}).strict().parse(input);const files={'river-plastic':'river-sites.geojson',landfill:'landfill-sites.geojson','mining-area':'mining-sites.geojson','wastewater-treatment':'wastewater-sites.geojson'},d=await load<SiteData>(files[q.type]);return getSites(d.features,q.type,q.country,q.bounds)}},
 {name:'compareCountries',description:'Compare acquired extraction with provenance; missing values remain unavailable.',inputSchema:schema({countries:{type:'array',items:{type:'string'},maxItems:10},year:{type:'integer'},material:{type:'string'}},['countries','year']),annotations:{readOnlyHint:true},execute(input:unknown){const q=z.object({countries:z.array(country).min(1).max(10),year:z.number().int().min(1970).max(2024),material:material.default('all')}).strict().parse(input);return compareCountries(data,q.countries,q.material,q.year)}},
 {name:'navigateAtlas',description:'Change the visible atlas state and reproducible URL, including physical-site selection and camera.',inputSchema:schema({scene:{type:'string',enum:SCENES.map(s=>s.id)},...countryYear,material:{type:'string'},wasteStream:{type:'string'},siteType:{type:'string'},site:{type:'string'},stockView:{type:'string'},longitude:{type:'number'},latitude:{type:'number'},zoom:{type:'number'}},['scene']),annotations:{readOnlyHint:false},execute(input:unknown){const q=z.object({scene:z.enum(['extraction','flow','stock','discard','return']),country:country.optional(),year:z.number().int().min(1970).max(2024).optional(),material:material.optional(),wasteStream:z.enum(['destinations','treatment','ewaste-location','municipal','ewaste','plastics','food','hazardous','places']).optional(),siteType:z.enum(['river-plastic','landfill','mining-area','wastewater-treatment']).optional(),site:z.string().optional(),stockView:z.enum(['flows','mass','country']).optional(),longitude:z.number().min(-180).max(180).optional(),latitude:z.number().min(-85).max(85).optional(),zoom:z.number().min(-.5).max(4).optional()}).strict().parse(input);if(q.country&&q.country!=='WORLD'&&!data.countries.some(c=>c.id===q.country))throw Error('Unknown country code');useAtlas.getState().set(q);return {status:'updated',...q}}}
]}
export function registerAtlasTools(data:ExtractionData){const context=(document as Document & {modelContext?:ModelContext}).modelContext;if(!context?.registerTool)return;const lifecycle=new AbortController();for(const tool of atlasTools(data)){try{Promise.resolve(context.registerTool(tool,{signal:lifecycle.signal})).catch(()=>{})}catch{}}return()=>lifecycle.abort()}
export const queryArchitecture={getExtraction,compareCountries,getBilateralFlow,getMaterialFootprint,getMetric,getSites};
