import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import {gunzipSync} from 'node:zlib';
import {runQuery,type AssetReader} from '../../packages/material-world/query';
import {matchesFacility} from '../../packages/material-world/model';
const read:AssetReader=async<T,>(path:string)=>{const b=await readFile(new URL('../../public'+path,import.meta.url));return JSON.parse((b[0]===31&&b[1]===139?gunzipSync(b):b).toString()) as T};
const search=await runQuery('facilities',{kind:'landfill',country:'CAN',query:'Vancouver',region:'BC',limit:2},read);
assert.equal(search.matched,7);assert.equal(search.nextOffset,2);
const rows=search.records as Array<{id:string;value:number|null;country:string}>;
assert.equal(rows.length,2);assert(rows.every(r=>r.value===null&&r.country==='CAN'));
const page2=await runQuery('facilities',{kind:'landfill',country:'CAN',query:'Vancouver',region:'BC',limit:2,offset:2},read);
assert(!(page2.records as typeof rows).some(r=>r.id===rows[0].id));
const record=await runQuery('facility',{kind:'landfill',country:'CAN',id:rows[0].id},read);
assert.equal((record.record as typeof rows[number]).id,rows[0].id);assert(record.source);
const sau=await runQuery('facilities',{kind:'power',country:'SAU',source:'wri-power-plants',limit:100},read);
assert.equal(sau.matched,90);assert((sau.records as Array<{basis:string;unit:string}>).every(r=>r.basis==='capacity'&&r.unit==='MW'));
const trace=await runQuery('facilities',{kind:'energy',country:'SAU',basis:'estimated',limit:100},read);
assert(Number(trace.matched)>0);assert((trace.records as Array<{basis:string;unit:string;year:number}>).every(r=>r.basis==='estimated'&&r.unit==='tonnes CO₂e/year'&&r.year===2025));
const annual=await runQuery('energy',{country:'SAU',measure:'crude-production',from:'2024',to:'2025'},read);
assert.equal((annual.rows as unknown[]).length,2);assert.equal(annual.unit,'barrels / day');assert(annual.source);
const refuse=await runQuery('estimate_energy_gap',{country:'SAU',measure:'crude-production',year:2025},read);
assert.equal(refuse.estimate,null);assert(refuse.sourceObservation);
const noExtrapolate=await runQuery('estimate_energy_gap',{country:'SAU',measure:'crude-production',year:2099},read);assert.equal(noExtrapolate.estimate,null);
const gaps:AssetReader=async<T,>(path:string)=>path.endsWith('/crude-production.json')?{unit:'barrels / day',frequency:'annual',sourceId:'test',factor:1,description:'Test series',series:{TST:{id:'same-series'}},rows:[{country:'TST',period:'2000',value:10},{country:'TST',period:'2001',value:null},{country:'TST',period:'2002',value:30}]} as T:path.endsWith('/catalog.json')?{sources:{test:{url:'https://example.test'}},measures:[{id:'crude-production'}]} as T:read<T>(path);
const interpolated=await runQuery('estimate_energy_gap',{country:'TST',measure:'crude-production',year:2001},gaps);
assert.equal((interpolated.estimate as {value:number}).value,20);assert.equal((interpolated.estimate as {stored:boolean}).stored,false);
const waste=await runQuery('waste',{place:'CAN'},read);assert(waste.source);assert(waste.record);
const accounts=await runQuery('material_accounts',{country:'IND',from:2020,to:2024},read);assert.equal((accounts.rows as unknown[]).length,5);assert(accounts.source);
const ocean=await runQuery('environment',{layer:'ocean',bbox:[120,10,130,20]},read);assert(String(ocean.mapImageUrl).includes('MODIS_Aqua_L2_Chlorophyll_A'));assert(ocean.interpretation);
await assert.rejects(runQuery('environment',{layer:'satellite',date:'2099-01-01'},read));
await assert.rejects(runQuery('environment',{layer:'vegetation',date:'2025-04-01'},read));
await assert.rejects(runQuery('environment',{layer:'satellite',date:'2026-02-30'},read));
await assert.rejects(runQuery('facilities',{kind:'landfill',country:'../../x'},read));
await assert.rejects(runQuery('facilities',{kind:'landfill',country:'CAN',limit:100000},read));
await assert.rejects(runQuery('energy',{country:'CAN',measure:'../../x'},read));
const p={coordinates:[179,0],country:'FJI',region:'',type:'test',basis:'location',name:'Île',locality:'',id:'x'} as any;
assert(matchesFacility(p,{bbox:[170,-10,-170,10],query:'ile'}));assert(!matchesFacility({...p,coordinates:[0,0]},{bbox:[170,-10,-170,10]}));
console.log('PASS: Real source queries, province search, pagination, record evidence, Saudi power/energy, waste, material accounts, environmental URLs, explicit interpolation, no extrapolation, nulls and invalid-input rejection.');

const worldMines=await runQuery('facilities',{country:'WORLD',kind:'mining',type:'Copper mine',limit:3},read);
assert.equal(worldMines.matched,914);assert.equal((worldMines.records as unknown[]).length,3);
const chileMines=await runQuery('facilities',{country:'CHL',kind:'mining',type:'Copper mine',limit:100},read);
assert(Number(chileMines.matched)>20);assert((chileMines.records as Array<{country:string;type:string}>).every(r=>r.country==='CHL'&&r.type==='Copper mine'));
const worldRecord=await runQuery('facility',{country:'WORLD',kind:'mining',id:(worldMines.records as Array<{id:string}>)[0].id},read);assert(worldRecord.record);
const textileCatalog=await runQuery('production_catalog',{material:'textiles'},read);assert((textileCatalog.catalog as {products:Record<string,unknown>}).products['767']);
const cotton=await runQuery('production',{material:'textiles',country:'IND',item:'767',from:2020,to:2024},read);assert.equal((cotton.rows as unknown[]).length,4);assert(cotton.source);assert(!(cotton.rows as Array<{year:number}>).some(r=>r.year===2024),'Never invent a missing 2024 cotton-lint observation');
await assert.rejects(runQuery('production',{material:'textiles',country:'IND',item:'../../x'},read));
console.log('PASS: Worldwide facility search, named copper mines, source filtering, global record retrieval and natural-fibre production histories.');

const exports=await runQuery('trade',{country:'SAU',commodity:'2710',limit:2},read);
assert(Number(exports.matched)>2);assert.equal(exports.nextOffset,2);assert(exports.source);
const tradeRows=exports.records as Array<{origin:string;destination:string;source_url:string;reported_flow:string;tonnes:number;original_value:number}>;
assert(tradeRows.every(r=>r.origin==='SAU'&&r.reported_flow==='X'&&r.tonnes===r.original_value/1000));
const next=await runQuery('trade',{country:'SAU',commodity:'2710',limit:2,offset:2},read);
assert(!(next.records as typeof tradeRows).some(r=>r.destination===tradeRows[0].destination));
const incoming=await runQuery('trade',{country:tradeRows[0].destination,commodity:'2710',direction:'in',limit:100},read);
assert((incoming.records as typeof tradeRows).every(r=>r.destination===tradeRows[0].destination));
const bases=new Set((incoming.records as typeof tradeRows).map(r=>r.reported_flow));assert.equal(bases.size,1,'One reporting side per product-year group');
await assert.rejects(runQuery('trade',{country:'WORLD',commodity:'9999'},read));
console.log('PASS: New Saudi petroleum exports, bounded trade pagination, native weight conversion and separately labeled partner-export evidence.');
