import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import {gunzipSync} from 'node:zlib';
import {handleMcpRequest,preflightMcp} from '../../packages/material-world/mcp';
import {runQuery,type AssetReader} from '../../packages/material-world/query';
const read:AssetReader=async<T,>(path:string)=>{const b=await readFile(new URL('../../public'+path,import.meta.url));return JSON.parse((b[0]===31&&b[1]===139?gunzipSync(b):b).toString()) as T};
const headers={'Content-Type':'application/json','Accept':'application/json, text/event-stream','MCP-Protocol-Version':'2025-06-18'};
async function rpc(method:string,params?:unknown){const response=await handleMcpRequest(new Request('https://overshoot.gaiaai.xyz/mcp',{method:'POST',headers,body:JSON.stringify({jsonrpc:'2.0',id:1,method,params})}),read);assert.equal(response.status,200);const body=await response.json() as any;assert(!body.error,JSON.stringify(body.error));return body.result}
const init=await rpc('initialize',{protocolVersion:'2025-06-18',capabilities:{},clientInfo:{name:'release-check',version:'1'}});assert.equal(init.serverInfo.name,'overshoot-material-world');
const list=await rpc('tools/list');assert.equal(list.tools.length,25);assert(list.tools.every((t:any)=>t.annotations.readOnlyHint===true));
const path=await rpc('tools/call',{name:'research_path',arguments:{material:'glass',place:'BC'}});assert(!path.isError);assert.equal(path.structuredContent.facilityGeography,'CAN');assert.equal(path.structuredContent.bcGlass.origin.status,'unresolved');assert.equal(path.structuredContent.bcGlass.afterUse.value,100);assert.equal(path.structuredContent.stages.find((s:any)=>s.stage==='manufacturing').records,4);
assert.equal(path.structuredContent.bcGlass.depositGlass.containersRecovered,159640710);
const glass=await rpc('tools/call',{name:'glass_program',arguments:{program:'deposit',region:'Capital Regional District'}});assert(!glass.isError);assert.equal(glass.structuredContent.regions[0].glassTonnes,5159);assert.equal(glass.structuredContent.summary.estimatedTonnesRecovered,54542);
const dairy=await rpc('tools/call',{name:'glass_program',arguments:{program:'refillable'}});assert.equal(dairy.structuredContent.data.containersReturned,2666659);
const discovery=await rpc('tools/call',{name:'source_observatory',arguments:{material:'glass',status:'retained'}});assert.equal(discovery.structuredContent.matched,1);assert.equal(discovery.structuredContent.sources[0].localData,'/data/v29/bc-glass.json');
const fixture:AssetReader=async<T,>()=>({products:{'99':{name:'Illustrative product',unit:'tonnes',path:'/fixture/rows.json'}},defaultItem:'99',publisher:'Fixture',url:'https://example.org',edition:'fixture',license:'fixture'} as T);
const interpolatedReader:AssetReader=async<T,>(path:string)=>path==='/fixture/rows.json'?([{country:'CAN',year:2022,value:10,source_flag:'reported'},{country:'CAN',year:2024,value:30,source_flag:'reported'}] as T):fixture<T>(path);
const estimate=await runQuery('estimate_production_gap',{material:'food',country:'CAN',item:'99',year:2023},interpolatedReader);
assert.equal((estimate.estimate as {value:number}).value,20);assert.equal((estimate.estimate as {stored:boolean}).stored,false);
const noExtrapolation=await runQuery('estimate_production_gap',{material:'food',country:'CAN',item:'99',year:2021},interpolatedReader);assert.equal(noExtrapolation.estimate,null);
const local=await rpc('tools/call',{name:'local_context',arguments:{latitude:10.65,longitude:-71.6,radiusKm:100}});
assert(!local.isError);assert.equal(local.structuredContent.location.country,'VEN');
assert.equal(local.structuredContent.location.countryMethod,'Nearest source record within 25 km');
assert(local.structuredContent.records.some((r:any)=>r.kind==='energy'&&r.sourceUrl));
assert.equal(local.structuredContent.nationalExtraction.year,2024);
assert(local.structuredContent.definitions.extraction.includes('country total'));
const search=await rpc('tools/call',{name:'facilities',arguments:{country:'SAU',kind:'energy',limit:1}});assert(!search.isError);assert.equal(search.structuredContent.matched,24);assert.equal(search.structuredContent.records.length,1);assert.equal(search.structuredContent.records[0].basis,'estimated');assert(search.structuredContent.sources['climate-trace-2025'].licenseUrl);
const trade=await rpc('tools/call',{name:'trade',arguments:{country:'SAU',commodity:'2710',limit:3}});assert(!trade.isError);assert(trade.structuredContent.matched>0);assert(trade.structuredContent.records.every((r:any)=>r.reporter==='SAU'&&r.reported_flow==='X'&&r.is_net_weight_estimated===false&&r.source_url.startsWith('https://comtradeapi.un.org/')));
const connections=await rpc('tools/call',{name:'connections',arguments:{material:'copper',country:'CHL'}});assert(!connections.isError);assert.equal(connections.structuredContent.links,3);assert.equal(connections.structuredContent.mappedLinks,3);assert(connections.structuredContent.sources.some((s:any)=>s.id==='bhp-escondida-20f'));
const discoveryPaths=await rpc('tools/call',{name:'connections',arguments:{}});assert(!discoveryPaths.isError);assert.equal(discoveryPaths.structuredContent.matched,194);assert.equal(discoveryPaths.structuredContent.networks.length,12);assert.equal(discoveryPaths.structuredContent.nextOffset,12);assert.equal(discoveryPaths.structuredContent.index.length,194);
const coalPaths=await rpc('tools/call',{name:'connections',arguments:{material:'fuels',country:'USA',network:'coal-6002'}});assert(!coalPaths.isError);assert.equal(coalPaths.structuredContent.networks[0].generationMWh,18866382);assert(coalPaths.structuredContent.networks[0].links.every((l:any)=>l.quantity>0&&l.evidence==='government-reported'));
const receipts=await rpc('tools/call',{name:'coal_receipts',arguments:{plantId:6002,mineId:'4800977',month:1}});assert(!receipts.isError);assert(receipts.structuredContent.records.length>0);assert(receipts.structuredContent.records.every((r:any)=>r.plantId===6002&&r.mineId==='4800977'&&r.month===1));
const waste=await rpc('tools/call',{name:'waste_collection',arguments:{country:'IND',limit:2}});assert(!waste.isError);assert.equal(waste.structuredContent.records.length,2);assert(waste.structuredContent.source.sha256);
const invalid=await rpc('tools/call',{name:'facilities',arguments:{country:'../../secret',kind:'energy',limit:1}});assert.equal(invalid.isError,true);
const forbidden=await handleMcpRequest(new Request('https://overshoot.gaiaai.xyz/mcp',{method:'POST',headers:{...headers,Origin:'https://unrelated.example'},body:'{}'}),read);assert.equal(forbidden.status,403);
const browserPreflight=preflightMcp(new Request('https://overshoot.gaiaai.xyz/mcp',{method:'OPTIONS',headers:{Origin:'https://chatgpt.com','Access-Control-Request-Method':'POST'}}));assert.equal(browserPreflight.status,204);assert.equal(browserPreflight.headers.get('Access-Control-Allow-Origin'),'https://chatgpt.com');
const browserConnection=await handleMcpRequest(new Request('https://overshoot.gaiaai.xyz/mcp',{method:'POST',headers:{...headers,Origin:'https://chatgpt.com'},body:JSON.stringify({jsonrpc:'2.0',id:9,method:'tools/list'})}),read);assert.equal(browserConnection.status,200);assert.equal(browserConnection.headers.get('Access-Control-Allow-Origin'),'https://chatgpt.com');
const oversized=await handleMcpRequest(new Request('https://overshoot.gaiaai.xyz/mcp',{method:'POST',headers,body:' '.repeat(17000)}),read);assert.equal(oversized.status,413);
console.log('PASS: MCP initialization, 25 tools, measured coal paths and monthly receipts, legacy source scopes, trade evidence and input validation.');
