import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import {gunzipSync} from 'node:zlib';
import {createHash} from 'node:crypto';
import {runQuery,type AssetReader} from '../../packages/material-world/query';
import {latestCities,uniqueYearPoints,type WasteCatalog,type WasteObservation,type CityCollectionData,type WasteComparison} from '../../packages/material-world/wasteResearch';
import {atlasUrl,readAtlasState,defaultAtlasState} from '../../apps/overshoot/atlas-next/atlasState';
const read:AssetReader=async<T,>(path:string)=>{const b=await readFile(new URL('../../public'+path,import.meta.url));return JSON.parse((b[0]===31&&b[1]===139?gunzipSync(b):b).toString()) as T};
const manifest=JSON.parse(await readFile(new URL('../../packages/overshoot-data/release18/manifest.json',import.meta.url),'utf8'));
for(const m of manifest){const raw=gunzipSync(await readFile(new URL('../../packages/overshoot-data/release18/'+m.file,import.meta.url)));assert.equal(createHash('sha256').update(raw).digest('hex'),m.sha256)}
const catalog=await read<WasteCatalog>('/data/v18/waste/catalog.json');let count=0,zeros=0,breaks=0;
for(const s of catalog.series){const rows=await read<WasteObservation[]>(s.path);assert.equal(rows.length,s.count);assert.equal(new Set(rows.map(r=>r.id)).size,rows.length);assert(catalog.sources[s.sourceId].metadataUrl);assert.equal(new Set(rows.map(r=>r.country+':'+r.year)).size,rows.length,'Unexpected country/year ambiguity');for(const r of rows){assert(Number.isFinite(r.value));assert(/^[A-Z]{3}$/.test(r.country));if(s.sourceId.startsWith('eurostat-'))assert.notEqual(r.country,'XKX','Eurostat Kosovo cells must remain withheld');assert.equal(r.unit,s.unit);assert.equal(r.value,Number(r.rawValue)*r.factor);if(r.value===0)zeros++;if(r.flags.includes('b'))breaks++;if(r.basis==='Model projection')assert(r.year>2022&&r.source.toUpperCase().includes('UNITAR'))}count+=rows.length}
assert.equal(count,catalog.counts.historyRecords);assert(zeros>0&&breaks>0);assert.equal(catalog.series.length,123);
const cities=await read<CityCollectionData>('/data/v18/waste/city-collection.json');assert.equal(cities.records.length,5170);assert.equal(new Set(cities.records.map(r=>r.cityId)).size,4452);assert.equal(new Set(cities.records.map(r=>r.country)).size,152);assert.equal((await read<unknown[]>('/data/v18/waste/collection-regional-aggregates.json')).length,9);
const city=await runQuery('waste_collection',{country:'IND',limit:3},read) as any;assert.equal(city.records.length,3);assert(city.records.every((r:any)=>r.country==='IND'&&r.footnotes.length&&r.source));const next=await runQuery('waste_collection',{country:'IND',limit:3,offset:3},read) as any;assert(next.records.every((r:any)=>!city.records.some((x:any)=>x.id===r.id)));
const multi=await runQuery('waste_history',{series:'eu-municipal-gen-kg-hab',countries:['DEU','FRA'],from:2020,to:2024},read) as any;assert(multi.records.length>=8);assert(multi.records.every((r:any)=>r.year>=2020&&r.year<=2024&&r.rawUnit==='KG_HAB'));assert(multi.source.sha256);
await assert.rejects(()=>runQuery('waste_history',{series:'../private',countries:['DEU']},read));await assert.rejects(()=>runQuery('waste_history',{series:'missing',countries:['DEU']},read));await assert.rejects(()=>runQuery('waste_history',{series:'eu-municipal-gen-kg-hab',countries:['DEU'],from:2024,to:2020},read));await assert.rejects(()=>runQuery('waste_collection',{limit:1000},read));
const comparison=await runQuery('waste_compare',{places:['CAN','JPN'],measure:'perPerson'},read) as any;assert.equal(comparison.records.length,2);assert.equal(comparison.records[0].sourceDate,'2018');assert.equal(comparison.measure.unit,'kg/person/day');const matrix=await read<WasteComparison>('/data/v18/waste/comparison.json');assert.equal(matrix.records.length,479);assert(matrix.records.some(r=>r.observations.tonnes?.value===null||!r.observations.tonnes));
const projection=await runQuery('waste_compare',{places:['CAN'],measure:'projection_2050'},read) as any;assert.equal(projection.records[0].sourceDate,'2050 · model');
const fixture=cities.records[0];assert.equal(latestCities([{...fixture,year:2010,id:'a'},{...fixture,year:2020,id:'b'},{...fixture,year:2020,id:'c'}]).length,2);assert.equal(uniqueYearPoints([{...multi.records[0],year:2000},{...multi.records[0],year:2000},{...multi.records[0],year:2001}]).length,1);
const state={...defaultAtlasState,view:'waste' as const,wasteTab:'trends' as const,wasteSeries:'eu-packaging-w150102-rcy-neu-t',compare:'DEU,FRA',wasteQuery:'São Paulo',wasteLevel:'city' as const,wasteYear:'2022',wasteFrom:'2000',wasteTo:'2020'};const url=new URL(atlasUrl(state),'https://overshoot.gaiaai.xyz');const restored=readAtlasState(url);for(const key of ['view','wasteTab','wasteSeries','compare','wasteQuery','wasteLevel','wasteYear','wasteFrom','wasteTo'] as const)assert.equal(restored[key],state[key]);assert(catalog.series.some(s=>s.id===state.wasteSeries));
console.log(`PASS: raw-source hashes; ${count} historical observations; ${zeros} genuine zeroes; ${breaks} break flags; city/aggregate separation; pagination; units and conversions; nulls; projections; API validation; share-link round trip.`);
